### ISSUE TITLE
Brutefir and a HifiBerryDAC Plus Volumio2 v2.001 rpi 2/3

### ISSUE THREAD

**Issue by Alphascrypt** [balbuze/volumio-plugins#1]
I cant get an output to an HifibBerry DAC Plus.  And i cant activate the advanced settings.

**Comment by balbuze** [comment]
Have you installed the last version ? Did you select Loopback as output in volumio/playback ?
When you say you can't activate advanced setting, you mean that nothing happen when clicking ?

**Comment by Alphascrypt** [comment]
I followed your instruction. Yes when i hitting the SAVE button nothing happen so i cant save the output device. Ithink thats the problem. I downloaded YOUR latest .zip version

**Comment by balbuze** [comment]
do you use a dev version of volumio ?

**Comment by Alphascrypt** [comment]
Nope its the original version for the raspberry pi /Volumio2 v2.001

**Comment by balbuze** [comment]
ok. I'm doing a install with the file on the repo (I use to use my local). Wait a little....

**Comment by Alphascrypt** [comment]
Np nice to see a that u will help 👍

**Comment by balbuze** [comment]
Is your DAC working (before the plugin) with a mixer (Digital) or no mixer or something else ?

**Comment by Alphascrypt** [comment]
Yes before installing the plugin all works fine. After installing and activating the plugin no output.

**Comment by balbuze** [comment]
what is the value in output device in the plugin advanced settings ? (if you can see it..) It should the value returned by aplay -l for your DAC (card number)

**Comment by Alphascrypt** [comment]
My card number is 0 i and i did the output = 0

**Comment by balbuze** [comment]
huumm. Can paste your aplay -l please ?

**Comment by Alphascrypt** [comment]
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by balbuze** [comment]
your hifiberry is card 1

**Comment by balbuze** [comment]
and I can't see Loopback device. Have you reboot after installation ?

**Comment by Alphascrypt** [comment]
I have done a fresh install bcs i need the amp for people actually. i can made a test tomorrow

**Comment by balbuze** [comment]
ok. I have to reflash a official version to test. But I think problem comes from output setting. You can check if brutfir is working by typing "systemctl status brutefir" Keep me in touch.

**Comment by Alphascrypt** [comment]
That i already checked. Brutefir was active

**Comment by balbuze** [comment]
So in this case I think  it just because output was not sent to the right output.
But you didn't answers about Loopback ?

**Comment by Alphascrypt** [comment]
Oh i missed. Loopback was displayed after installing the plugin.

**Comment by balbuze** [comment]
So I tested with a fresh 2.001 install. It works but you have to select "none" as mixer....Don't forget than bauer binaural and equalizer are disabled...

**Comment by Alphascrypt** [comment]
And whats with the I2S DAC? Must turned off and choosed Loopback right?

**Comment by balbuze** [comment]
No your dac must be activated. Once it works as output (play something), change for Loopback and save. Do not desactivate it. In the plugin setting set the right value (aplay -l) in output device and save.
If you want to test a filter, enter anothertest2.wav in left and right filter and save. You can do it while playing. The available filters can be seen in /INTERNAL/brutefirfilters on your network. Bad quality but just to help testing.

**Comment by Alphascrypt** [comment]
Good evening, so it wont work. Did u have installed the display touch plugin before?

**Comment by balbuze** [comment]
hello
no... display touch
We can recheck different point if you want...
- you have working system rpi 2/3 with hifiberry dac pro configured
- you installed the plugin
- after reboot, you select Loopback as output in Volumio and you save.
- you select "none" as mixer and you save
- you enable the plugin and in advanced settings, you change if needed the output according to "aplay -l" and you save.
- at this point you should have sound ! (try to play something)
if not check if brutefir is running

**Comment by Alphascrypt** [comment]
When i want to select output device Loopback it automaticly jumps back to Hifiberry DAC Plus so i cant change it

**Comment by balbuze** [comment]
I saw this... Unfortunatly the problem does not come from the plugin. You can try to disable I2C dac select jack save reboot and select I2C again and save....

**Comment by marcelek** [comment]
I've still this problem. Pi3 + Hifiberry DAC Plus + volumio v2.129 in normal mode (no-dev)
1. fresh install + lastest plugin (7.04.2017) + reboot
2. can't save loopback. Every time I've selected it, goes back to Hifiberry.
3. If I turn off I2C, Hifiberry is gone from plugin settings and mixer goes to none.

Any ideas?

**Comment by Alphascrypt** [comment]
https://www.computerhilfe-wagner.de/volumio-2-audio-output-spring-auf-audio-jack/



Ein Problem welches nerven kosten kann.

Man hat sich einen DAC/DAC+ gekauft alles soweit eingerichtet und stellt fest das die Audio Ausgabe nicht richtig stabil läuft.

Als erstes schaut man natürlich wieder in die Wiedergabe option und stellt fest das der Audio output wieder auf Audio Jack steht und nicht auf dem DAC.

 

Das Problem ist der Kernel.

 

Abhilfe ist ganz einfach:

 

Wir öffnen einfach /etc/modules


sudo nano /etc/modules
1
sudo nano /etc/modules
und fügen einfach diesen Treiber ein


snd_bcm2835
1
snd_bcm2835
danach speichern und neustarten.

 

Fertig! Die Audio Ausgabe bleibt nun stabil auf dem Ausgewählten DAC/DAC+ stehen.

**Comment by balbuze** [comment]
Sorry but I can't understand you... Write in English please.

**Comment by marcelek** [comment]
Thanx Alphascrypt, but this is not my case. :)

**Comment by balbuze** [comment]
the problem comes from the way volumio manages i2s dac. Michelangelo knows about that and maybe a fix will arrive. By waiting, I have a workaround that requires to modify a file in volumio:
in /volumio/app/plugins/audio_interface/alsa_controller/index.js , you have to comment 2 lines near number 520 (by adding //)  
// this.config.set('outputdevicename', data.i2sid.label);
      //   OutputDeviceNumber = I2SNumber;
save and restart volumio : killall volumio
now you setting is kept.
let me know

**Comment by marcelek** [comment]
Nothing's change. Commenting this lines is not a solution. 

In addition:
- brutefir is working, settings in plugin are saved (bug with showing device name - got device number "2", but it's working)
- I've got a sound. (not sure if from brutefir or directly)
- cannot control mixer and change the volume.

**Comment by balbuze** [comment]
commenting line is a solution to be able to use i2s dac and Loopback as output.
As this point, you can't control the volume because volumio does not allow to use a mixer different from the output device. With alsamixer if you select the good device, you should be able to set the volume.
If brutefir is running you can set a filter to check if the sound come from it. Just enter anothertest.wav for left and right filter. Even without filter, you can change attenuation and save. The sound stop and restart with a level different.

**Comment by marcelek** [comment]
If I can set volume by alsamixer, I should be able to set it with amixer from code.
Do you know, where (in with file) volumio sets volume/send command thru amixer? I can hardcode my device_number ('2') until volumio fix the code.

BTW Do you think it is good idea to fix the volumio/brutefir code to set loopback/brutefix parameters automatic from previews settings? All information are in there, so installing plugin should be transparent for user.

**Comment by balbuze** [comment]
I agree with you that plugin install should set to Loopback by default. I'll see later...
For the mixer, it's not easy, but I would try to modify line 825 (may change between version) in /volumio/app/plugins/audio_interface/alsa_controller/index.js
	var array = execSync('amixer -c '+device+' scontents', { encoding: 'utf8' })
by 
	var array = execSync('amixer -c2+scontents', { encoding: 'utf8' })
but not tested !!!

**Comment by balbuze** [comment]
and same thing line 764
I tested and now I can select the mixer of my dac eben with Loopback as output... But when changing volume, UI not updated...

**Comment by balbuze** [comment]
no sure it is the good way..

**Comment by marcelek** [comment]
I’m looking near +120 /volumio/app/volumecontrol.js but I’m not JS master.

testing in progress… ;)
