### ISSUE TITLE
volspotconnect2: Shuffle is not working

### ISSUE THREAD

**Issue by fbontin** [balbuze/volumio-plugins#100]
Was trying to turn on shuffle via spotify connect (on mobile or computer) but it does not work. This is also referenced in the official repository in [this issue](https://github.com/volumio/volumio-plugins/issues/90).

I am using volumio 2.295 (newest version as of today).

By the way, thanks for a great plug-in :-)

**Comment by balbuze** [comment]
This is not implemented yet in librespot used in the plugin. Maybe one day.   If you can't wait, use volspotconnect instead.
