### ISSUE TITLE
volspotconnect: crash on next start if you don't pause before going inactive

### ISSUE THREAD

**Issue by markubiak** [balbuze/volumio-plugins#102]
Heya,

The latest commit on the volspotconnect branch is stellar, love the metadata info and can't wait for those buttons to start working!

However, I'm encountering a bug.  If I am playing music and disconnect from spotify-connect-web entirely (going inactive) without pausing, the webUI doesn't clear itself.  Additionally, and more annoyingly, the next time i try to reconnect to spotify-connect-web, it'll connect (become active), but the second I try to play music the thing crashes.  I have to restart my entire Pi, not just the plugin, to fix it.  The Volumio log complains that a port is being used or something.  I've got more debug info at home so I'll shoot you a commented log if you can't reproduce.

Cheers

**Comment by balbuze** [comment]
Hi,
yes I met the problem. It seems to be the same than when changing user, it crashes. But I haven't had time to have a deep look on that. I suspect a "device busy" for the output but not sure...

**Comment by markubiak** [comment]
It's pretty clear that it's simply not stopping when the user disconnects.  Maybe the original contributor of this knows?  I'll do some digging if he doesn't.

**Comment by ashthespy** [comment]
Greetz,

I'm travelling currently, but the relevant function is [`ControllerVolspotconnect.prototype.DeactivatedState`](https://github.com/balbuze/volumio-plugins/blob/master/plugins/music_service/volspotconnect/index.js#L208)
The events that trigger this are:
1. `DInactive` 
     Device ends playback mode i.e on hitting pause in Spotify
1.  `SInactive` 
     Spotifiy session has ended

Could you dig up some logs to see if it's these events are actually getting triggered - can then rule out the player, and focus on telling the Volumio state machine that we have finished playback.

**Comment by markubiak** [comment]
Found it.  The case statement in ParseData was:
````
  parseData(data) {
    // Quick and dirty JSON check
    try {
      const metadata = JSON.parse(data);
      this.emit('metadata', metadata);
    } catch (e) {
      switch (data) {
        case 'kSpPlaybackNotifyBecameActive':
          this.emit('SActive', '')
          break;

        case 'kSpDeviveActive':
          this.emit('DActive', '')
          break;

        case 'kSpDeviveInactive':
          this.emit('DInactive', '')
          break;

        case 'SInactive':
          this.emit('kSpPlaybackNotifyBecameInactive')
          break;

        default:
          this.emit('unknown', data)
      };
    }
}
````
The last case statement was backwards.  Changing it back around fixes it:
````
  parseData(data) {
    // Quick and dirty JSON check
    try {
      const metadata = JSON.parse(data);
      this.emit('metadata', metadata);
    } catch (e) {
      switch (data) {
        case 'kSpPlaybackNotifyBecameActive':
          this.emit('SActive', '')
          break;

        case 'kSpDeviveActive':
          this.emit('DActive', '')
          break;

        case 'kSpDeviveInactive':
          this.emit('DInactive', '')
          break;

        case 'kSpPlaybackNotifyBecameInactive':
          this.emit('SInactive')
          break;

        default:
          this.emit('unknown', data)
      };
    }
}
````
I'd make a PR but I have my own volumio-plugins branch and don't feel like screwing with Git for a half hour to make a 2 line change.

@balbuze any chance you can mainline this?

Mark

**Comment by balbuze** [comment]
well done! You are faster than me ! I'm going to change it now!

**Comment by balbuze** [comment]
It is done now !  It also solve the problem when switching form a user to an other ! Very well done !

**Comment by markubiak** [comment]
Awesome, I'm gonna close this. Thanks!

**Comment by ashthespy** [comment]
Oh ouch, sorry everyone - looks like I copy pasted an old version in my PR. Was wondering why I never had this issue. 
@markubiak thanks for tracking this down!
