### ISSUE TITLE
wifireconnect: wget rather than ping

### ISSUE THREAD

**Issue by macmpi** [balbuze/volumio-plugins#103]
You may want to consider using something like below instead of `ping` [here](https://github.com/balbuze/volumio-plugins/blob/master/plugins/system_controller/wifireconnect/wifireconnect.sh.tmpl#L7):
`wget -q --tries=10 --timeout=20 --spider http://google.com > /dev/null 2>&1`.

Indeed in some case `ping` may have [execute rights issues](https://volumio.org/forum/volumio-often-disconnected-from-wifi-t6697-20.html#p40383) or even be blocked by some ISPs.
It's a fairly commonly used method to check internet availability and proper name resolution; `wget` is available for any user.

**Comment by balbuze** [comment]
I upload a new version using wget. But not tested...

**Comment by macmpi** [comment]
Can't test either (hence I did not originally submit a PR), but confident it should work as I'm using similar thing [here](https://github.com/macmpi/berryboot-scripts/blob/master/Volumio2/installVolumio2#L50).
Hope it helped.
