### ISSUE TITLE
volspotconnect is not avalible (:4000 with no answer too)

### ISSUE THREAD

**Issue by exetico** [balbuze/volumio-plugins#104]
Hi.

In the past i used Volumio + volspotconnect2 - but now that volspotconnect supports album info in Volumio, i'm using that one. In the last couple of months i used this, with no issues at all - My Pi was turned off and on each time, i should use it (I have an SonOff in front of it).

But now i changed the setup so my Pi is turned on 24/7 and i'm facing problems with an very unstable volspotconnect-experience (Spotify Connect).

I can't find the device after some hours in idle-state. My hotfix is to disable and enable the plugin - but i'm thinking about if you could use some logs or anything else to figure out, what's going on. When i'm trying  to reach out my Volumio Spotify Connect, i can't even access the interface at `myvolumioip:4000`.

**Comment by lgroeb** [comment]
Hi, 
Same problem here. Using volumio on Raspberry Pi3. Because power consumption is very low and in order to avoid bootup times, I am running it 24/7. I switched to volspotconnect because I am using the AmpSwitch plugin. Roughly after one day volspotconect is gone -- not showing up any more in Spotify. Restart solves the issue.
It would be great to solve that stability problem. The combination of volumio, volspotconnect, and AmpSwitch is absolutely great.
If I can support somehow (e.g. sending traces) please let me know.

**Comment by balbuze** [comment]
Hi
I understand Spotify connect is no more reachable. But is your device still online ? I mean VolumioUI, or even ssh ? Because ISP refresh there DNS lease every night, the device lose connection and never reconnect. This a know problem.. I wrote a plugin that may help : wifireconnect. I alsa work for ethernet connection. Search the repo.

**Comment by exetico** [comment]
My Volumio GUI is still working fine. It's just the Spotify Connect-feature. I can't find it on my Spotify-apps, and there is no respons on {Volumioip}:4000. SSH is also working fine.

But i must admit that it actually had work out just fine, the last 10 days (my Volumio device is still on 24/7).

Will i be able to somehow confirm, the things you are mentioning about my ISP's DNS leases? It would be nice to confirm, whether it's the reason or not.

**Comment by lgroeb** [comment]
I can also confirm that webGui still works. Playing Webradio or Airplay is still working fine. Only volumio does not show up in the Spotify App any more. What I will do today: I check, if spotify connect still works before I go to bed and tomorrow morning. Then the ISP refresh happened over night.
By the way is there a problem with your plugin wifireconnect if wifi is not used at all? May Raspberry Pi is connected via lan.
Thanks for your help!

**Comment by balbuze** [comment]
I just uploaded a new version of wifireconnect that works with eth...

**Comment by lgroeb** [comment]
Thank you very much balbuze. I will try to run into the problem first before using your plugin. I think that makes sense to see whether this is the problem. Just had a strange issue: we were playing via spotify connect from our iPad the whole day. Then we stopped it like 5 hours ago. Now I tried to connect spotify from my mobile (android). Volumio showed up. It connected, started playing and then it was gone. Unfortunately restarted the rapsberry. Next time I try to restart the plugin only. Lets see whether the plugin is still running tomorrow.

**Comment by lgroeb** [comment]
Update: after restarting RaspberryPi yesterday, volspotconnect was still working fine today morning. (Did not install wifireconnect yet; ISP refresh should have happened). I also could switch between two different devices without problems. So obviously everything was fine. Will be back home tomorrow evening. Let's see whether it still works.

**Comment by lgroeb** [comment]
Hi, I cannot reproduce the problem. I have two raspberries running without any problems since days. Did not install the wifereconnect plugin. So somehow the problem seems to have disappeard...

**Comment by exetico** [comment]
I still facing the same problem.

Normally i just disable and enable the plugin — but i was hoping for a solution. And i help somehow, by lookig into specific logs, or something simular?

**Comment by lgroeb** [comment]
It would be really great if there is the possibility to analyze the issue once it occurs. I would also like to support it but also need to know how to do it. It is an absolutely great plugin but it is annoying if it sometimes dies. So, balbuze it would be great if you would let us know how we can support.

**Comment by ashthespy** [comment]
Greetings! 
The plugin as default logs activities to the volumio log (accessible via `sudo journalctl -f` for eg). 
Could either of you post these when it goes unresponsive, I could have a look.

**Comment by balbuze** [comment]
Hi,
what you can do is via ssh:
disable the service : systemctl stop volspotconnect
then launch the start script:
cd /data/plugins/music_service/volspotconnect/spotify-connect-web/
and:
sh startconnect.sh
or if you use rpi b or zero
sudo sh startconnect.sh
And play what you want and wait for the problem...

**Comment by lgroeb** [comment]
Just wanted to say that I did not have too much time to play around. But I could not reproduce the problem so far. Two Raspberries (2 and 3) are running for days without loosing connection. Thanks for your help ashthespy and balbuze. If the problem occurs, I will try to provide logs. Thanks for this great plugin!

**Comment by exetico** [comment]
Same here - but i got another crash today, but if was after i started a track. I can't find anything in `/var/log`, and `sudo journalctl -f` doesn't list anything about this.

I'm not sure, where i should look for crash-info for this kind of thing - and no log-dir is defind in `startconnect.sh`:
```
d /data/plugins/music_service/volspotconnect/spotify-connect-web
./spotify-connect-web  --username 'FANCYUSERNAME' --password 'FANCYPASSWORD' --bitrate 320 --name 'Volumio' --playback_device softvolume --mixer 'SoftMaster'  --mixer_device_index 5 --dbrange 45  &
avahi-publish-service -s 'Volumio' _spotify-connect._tcp 4000 VERSION=1.0 CPath=/login/_zeroconf
```
But i think it's more likely to be a problem with `spotify-connect-web`, and not this solution. But i can only find a single way to get som debug info with that, and it's:
```
--debug, -d           enable libspotify_embedded/flask debug output
```
