### ISSUE TITLE
Unable to find mixer control SoftMaster,0 [default]

### ISSUE THREAD

**Issue by nklmilojevic** [balbuze/volumio-plugins#107]
Hi, 

I'm using volspotconnect with Volumio 2 on my rPi 3 with pHAT  DAC, and I have softmixer as a default. I'm getting this error:

> Nov 25 11:54:39 volumio volumio[700]: File "runpy.py", line 180, in run_module
Nov 25 11:54:39 volumio volumio[700]: File "runpy.py", line 72, in _run_code
Nov 25 11:54:39 volumio volumio[700]: File "/data/plugins/music_service/volspotconnect/spotify-connect-web/main.py", line 14, in <module>
Nov 25 11:54:39 volumio volumio[700]: from connect import Connect
Nov 25 11:54:39 volumio volumio[700]: File "/data/plugins/music_service/volspotconnect/spotify-connect-web/connect.py", line 9, in <module>
Nov 25 11:54:39 volumio volumio[700]: from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
Nov 25 11:54:39 volumio volumio[700]: File "/data/plugins/music_service/volspotconnect/spotify-connect-web/console_callbacks.py", line 157, in <module>
Nov 25 11:54:39 volumio volumio[700]: mixer = alsa.Mixer(args.mixer, **mixer_card_arg)
Nov 25 11:54:39 volumio volumio[700]: alsaaudio.ALSAAudioError: Unable to find mixer control SoftMaster,0 [default]

**Comment by nklmilojevic** [comment]
Disergard this, I was using the plugin for Volumio and not for Volumio2...

**Comment by balbuze** [comment]
Hi!
volspotconnect is designed for volumio2 too ! It just not use the same library. But it provides UI metadata!
And I see where the problem comes from. I'll try to fix and publish a new version soon !

**Comment by nklmilojevic** [comment]
Awesome :) patiently waiting for it

**Comment by balbuze** [comment]
Done !
You can test now. Let me know as I can't fully test...

**Comment by nklmilojevic** [comment]
@balbuze I'm having the same error again.
