### ISSUE TITLE
volspotconnect1/2 is blocking any other playback

### ISSUE THREAD

**Issue by dmnc-net** [balbuze/volumio-plugins#109]
Hi,
I'm trying Volumio2 on HifiBerry AMP2 and in my project I'd like to use Spotify, Spotify Connect, internet radios and MP3 from network share.

volspotconnect and volspotconnect2 is working well but when song is playing I can't switch/play anything else from Volumio UI.  For example clicking on some internet radio or local media (mp3) will produce:
 `Failed to open "alsa" [alsa]; Failed to open ALSA device "hw:1,0": Device or resource busy`

I have to stop music from the Spotify (i.e. mobile or web player) and then I can use Volumio regularly.

Is is possible to receive some "hey, user is going to switch the music, please sh*t up" from Volumio in volspotconnect1/2 and stop the playback?

_volspotconnect 1.7.4
volspotconnect2 0.4.6
Volumio 2.348_

**Comment by dmnc-net** [comment]
And vice versa, when local media is playing and I choose Volumio from my mobile Spotify app, plugin receives the command from Spotify Connect but I have to stop previous playback manually because plugin can't do that. UI is showing volspotconect source, I can see correct song poster from the Spotify but still listening to mp3 which I started before.

**Comment by balbuze** [comment]
solved with update 0.7.0
