### ISSUE TITLE
Laggy sound with new Volumio v.2.041 and volspotconnect v.1.4.8

### ISSUE THREAD

**Issue by szelek** [balbuze/volumio-plugins#11]
Hi,

I am experiencing a problem with laggy sound whenever i start playing music using volspotconnect plugin.
Song plays for 3-5 seconds and then it gets choppy, and there are just random sounds every few seconds.
I'm not quite sure how I can extract any logs directly from plugin?
The same thing happens when I change plugin settings to low bitrate.
I have Volumio with Hifiberry DAC Pro.

I've performed clean installation of Volumio and volspotconnect plugin yesterday.
Everything was working fine with version from the end of November.

Please let me know if You need any more info.

**Comment by balbuze** [comment]
I experienced the same thing yesterday. It last few minutes and became normal. Nothing in the plugin can explain that. Please reboot if needed and try again... What is your device ?

**Comment by szelek** [comment]
I have RPi2 model B.
I've restarted volumio multiple times. Unfortunately even after few hours, the problem still persists.

**Comment by balbuze** [comment]
Ok I'll try to have a look tonight.

**Comment by balbuze** [comment]
I uploaded a 1.5.1 version. Hope it solves your problem.... let me know

**Comment by balbuze** [comment]
Solved
