### ISSUE TITLE
ifi nano idsd issue?

### ISSUE THREAD

**Issue by mgocl** [balbuze/volumio-plugins#112]
Hi! I am running volumio 2.323 with raspberry pi 3 and ifi nano idsd usb dac. I am planning to have a 2.1 setup soon (with multichannel usb soundcard) and would like to do a sub integration and room correction further down the road. In order to achieve that I installed brutefir plugin. It seems to work (status)
<img width="1272" alt="screen shot 2017-12-15 at 14 12 46 1" src="https://user-images.githubusercontent.com/34574738/34044107-05530df8-e1a4-11e7-8ddd-244e272039f6.png">
<img width="554" alt="screen shot 2017-12-15 at 14 16 29" src="https://user-images.githubusercontent.com/34574738/34044118-120d3fc8-e1a4-11e7-84ca-6d4808a74d61.png">
<img width="905" alt="screen shot 2017-12-15 at 14 14 48" src="https://user-images.githubusercontent.com/34574738/34044122-14067ec0-e1a4-11e7-8a4e-29f1aa50b3b9.png">
However changing the eq settings doesn't produce any audible difference. Plus in advanced plugin settings I do not have input/output devices, as is in case of some of users.
<img width="708" alt="screen shot 2017-12-15 at 14 13 36" src="https://user-images.githubusercontent.com/34574738/34044163-3cfe82dc-e1a4-11e7-96e8-423af0a4f7bb.png">

Kind regards

Michal

**Comment by balbuze** [comment]
Hi!
If I understand, plugin is activated and seems to work... Have you changed something in volumio playback option? (you shouldn't). So you get sound when playing a track. Try to enter rephase.raw as left and right filter? The sound should change... As for the equalizer...

**Comment by balbuze** [comment]
The output/input option in advanced were in old version. Now it is "autoconfigured" in the plugin.
