### ISSUE TITLE
[volstereo2mono] - issues with other plugins

### ISSUE THREAD

**Issue by dmnc-net** [balbuze/volumio-plugins#115]
If volstereo2mono is enabled and whatever is played by the official Volumio Youtube plugin sounds goes off. Even other sources which was working just before YT is now silent. Solving by reboot :(

Config: RPi3 + HiFiBerry AMP2 (DAC+) + latest Volumio

**Comment by balbuze** [comment]
Just after enabling the plugin have try to reboot ?
Do you use a volume mixer ?
In play back option of volumio what is the name of the output ?

**Comment by dmnc-net** [comment]
No, with volstereo2mono I can play just local library (mp3 from USB/NAS). When I play something on YT, sound is off and when I came back to local mp3s sound was still off (so I've restarted).

Now I found issue with your volspotconnect plugin - again no sound (but I can play local media without problem)

**Comment by balbuze** [comment]
not sure but it could be due to a sampling problem... Can you paste 

pcm.monooutf {
    type route
    slave.pcm "plughw:${hwout},0"
    ttable {
        0.0 0.7	# in-channel 0, out-channel 0, 70% volume
        1.0 0.7	# in-channel 1, out-channel 0, 70% volume
	0.1 0.7	# in-channel 0, out-channel 1, 70% volume
	1.1 0.7	# in-channel 0, out-channel 1, 70% volume
    }
}

pcm.monoout {
	type plug
	slave.pcm "monooutf"
}
to replace the content of /data/plugins/audio_interface/volstereo2mono/asound.tmpl please and let me know ?
thanks!
