### ISSUE TITLE
Incompatibility problem with AirPlay

### ISSUE THREAD

**Issue by raptor-f** [balbuze/volumio-plugins#116]
There seems to be a strange incompatibility problem with Apple AirPlay possibly caused by modification of the mpd.conf when using this plugin.

Sometime when exiting AirPlay mode something goes wrong and all Audio output stops.

I'm using an I2C dac (IQ Audio DAC Plus)

**Comment by balbuze** [comment]
what plugin are you talking about?
none of my plugins change mpd.conf.
Volumio does it as a new output is configured

**Comment by raptor-f** [comment]
Sorry Its the volsimpleequal plugin I was talking about.  Maybe its not the mpd.conf that's being modified, could it be asound.conf ?

I find the first time I use Airplay after installing the volsimpleequal plugin it works OK but then when I switch back to playing MP3 files or Webradio streams, sometimes something doesn't exit cleanly and all Audio stops and doesn't come back even after a reboot. I haven't found the exact sequence that causes this yet.  Sometimes it takes a few switches between Airplay usage and MP3 for Webradio streams usage before it happens.  

If I don't install the volsimpleequal plugin then I never encounter a problem using AirPlay.

**Comment by balbuze** [comment]
should be ok 2.378
