### ISSUE TITLE
Rpi Zero with Hifiberry Dac

### ISSUE THREAD

**Issue by mredone** [balbuze/volumio-plugins#118]
Hello.
I have problem with volspotconnect ver 1.7.4.
When i change in playback options mixer type to none i hear sound.
But i don't have volume control.
But when i change to software nothing play.
Track work, i see cover and time running but no sound.

Ok in logs is small problem
Unable to acquire device:  No such file or directory [softvolume]

**Comment by ashthespy** [comment]
@balbuze 
I am also having the same issue with the same setup - no hardware volume control with the Hifiberry dac.
I recall sometime back you got the softvol to work by some `asound.conf` within the chroot. 

If you have some time soon, I would be willing to test!

**Comment by balbuze** [comment]
It was supposed to be be solved... I'm going to check today...
