### ISSUE TITLE
[volspotconnect-futurdev]  adding ReplayGain Support

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#119]
Hi Balbuze, 

did you notice Herrernst implemented ReplayGain support.

https://github.com/herrernst/librespot/tree/volume-normalization/src

This would truly be an addition to volspotconnect2

**Comment by balbuze** [comment]
Hi!
thanks, I'll have a look and if possible add it in the plugin.

**Comment by balbuze** [comment]
I'm compiling now a version of librespot with ReplayGain... It fails... Retry tomorrow..
But do you think I should add a switch in the webUI to enable/disable it ?

**Comment by cortegedusage** [comment]
I think people should have a choice so a switch would be nice.

cheers!

2018-01-15 21:23 GMT+01:00 balbuze <notifications@github.com>:

**Comment by balbuze** [comment]
ok I have a working version for x64...
Tomorrow I'll try to compil for amrv6 and add the switch !

**Comment by balbuze** [comment]
guess what ? 
https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect-futurdev
;-)

**Comment by cortegedusage** [comment]
Wow, that's great. 

cheers!

**Comment by cortegedusage** [comment]
I've been using it today, and it sounds very nice.
but, it seems to crash whenever I stop a song.
It looks active in the app but when i resume
librespot restarts.

play the song:
Jan 17 20:33:21 woonkamer volumio[10197]: INFO:librespot::player: Loading track "Too Late"
Jan 17 20:33:21 woonkamer volumio[10197]: INFO:librespot::player: Track gain: -3.2399979db
Jan 17 20:33:21 woonkamer volumio[10197]: INFO:librespot::player: Track peak: 0.86110026
Jan 17 20:33:21 woonkamer volumio[10197]: INFO:librespot::player: Album gain: -5.0699997db
Jan 17 20:33:21 woonkamer volumio[10197]: INFO:librespot::player: Album peak: 1.0085515
Jan 17 20:33:21 woonkamer volumio[10197]: INFO:librespot::player: Track "Too Late" loaded
Jan 17 20:33:21 woonkamer volumio[10197]: INFO:librespot::player: metadata:{"ARTIST":"Augustus Pablo","TITLE":"Too Late"}

Push pause
Jan 17 20:33:26 woonkamer volumio[10197]: thread '<unnamed>' panicked at 'invalid state', src/player.rs:178
Jan 17 20:33:26 woonkamer volumio[10197]: note: Run with `RUST_BACKTRACE=1` for a backtrace.

try to resume

Jan 17 20:33:32 woonkamer volumio[10197]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /checkout/src/libcore/result.rs:859
Jan 17 20:33:32 woonkamer systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Jan 17 20:33:32 woonkamer systemd[1]: Unit volspotconnect2.service entered failed state.
Jan 17 20:33:34 woonkamer systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Jan 17 20:33:34 woonkamer systemd[1]: Stopping Volspotconnect2 Daemon...
Jan 17 20:33:34 woonkamer systemd[1]: Starting Volspotconnect2 Daemon...
Jan 17 20:33:34 woonkamer systemd[1]: Started Volspotconnect2 Daemon.
Jan 17 20:33:34 woonkamer volumio[12740]: INFO:librespot: librespot de2b4cc (2017-12-07). Built on 2018-01-15. Build ID: JxrhZJUc
Jan 17 20:33:34 woonkamer volumio[12740]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
Jan 17 20:33:34 woonkamer volumio[12740]: INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-k4kn.ap.spotify.com:4070"
Jan 17 20:33:35 woonkamer volumio[12740]: INFO:librespot_core::session: Authenticated as "*********" !
Jan 17 20:33:35 woonkamer volumio[12740]: INFO:librespot::audio_backend::alsa: Using alsa sink
Jan 17 20:33:35 woonkamer volumio[12740]: INFO:librespot_core::session: Country: "NL"

do you know how to run with backtrace?

**Comment by balbuze** [comment]
Hi,
Sorry for this late answers...I've got some  problem with my home network...
for backtrace, just enter "export RUST_BACKTRACE=1" via ssh and restart librespot. But not sure it will help...

**Comment by balbuze** [comment]
I found something maybe wrong in the code... I'm recompiling librespot to see if better...

**Comment by balbuze** [comment]
outch ! After a long fight my network problem is solved... So I uploaded a "regular" version of volspotconnect2 including all last changes/improvements. Hope it will be fine....

**Comment by cortegedusage** [comment]
did you manage to get the stop error out of it, or is it still present?

I've also encountered some issues with the implementation it seems to clip with very quiet tracks.
I gave this back to herrernst, maybe he can fix this...

happy listening!

**Comment by balbuze** [comment]
Yes it seems to be fixed.by the code I modified.. I'm using it for several days and didn't experienced any problems....

**Comment by cortegedusage** [comment]
hmmm I've uninstalled rebooted and installed, but I encounter the same
problem,
librespot panic's when pausing the music.

are you sure you've uploaded the right binairy?




2018-01-24 22:00 GMT+01:00 balbuze <notifications@github.com>:

**Comment by cortegedusage** [comment]
ah you didn't change install.sh it is still downloading from
futeredev....thus the old librespot file is downloaded :)

2018-01-24 22:09 GMT+01:00 Dennis van Paassen <dvpaassen@gmail.com>:

**Comment by cortegedusage** [comment]
yeah you made a mistake in the install script,
it still points at the futeredev repo on github, so it downloads the old binary.

the new binairy works perfectly, thank you again!!!

you know people get paid to do this sort of things :)

good night

**Comment by balbuze** [comment]
Damn!
Stupid error... 
I can't change it before tonight...

**Comment by balbuze** [comment]
done!

**Comment by cortegedusage** [comment]
Thank you!

BTW did you notice the movement on the librespot front?

Seems like finally all forks Will come together..

Op 25 jan. 2018 6:50 p.m. schreef "balbuze" <notifications@github.com>:

**Comment by cortegedusage** [comment]
Closing this, thank you for your work...
adding metadata to the ui is the sugar on the cream.

cheers!
