### ISSUE TITLE
Volspotconnect inactive on pi0 and phat dac

### ISSUE THREAD

**Issue by Dustee** [balbuze/volumio-plugins#12]
Model : Raspberry pi Zero
Sound card : pimoroni phat dac (should be similar to setup to hifiberry dac)
Os: Volumio  2.041
Plugin: volspotconnect.zip December 19th 
Spotify account is premium, and not made through Facebook.

Hi, first of all thanks for making this plugin, I tested it on a raspberry 2 with hdmi and it works fine.
I’m trying to make it work with my rpi0 and the phat dac soundcard but no luck.

The plugin stays inactive no matter what I've tried. It only worked once when I disabled the I2S dac, but I couldn’t make it work again. Here is some info you might find useful :

aplay -l

> **** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sndrpihifiberry [snd_rpi_hifiberry_dac], device 0: HifiBerry DAC HiFi pcm5102a-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

startconnect.sh

> cd /data/plugins/music_service/volspotconnect/spotify-connect-web
./spotify-connect-web  --username 'xxx' --password 'xxx' --bitrate 320 --name 'Volumio' --playback_device plughw:1 --mixer ''  --mixer_device_ind$
avahi-publish-service -s 'Volumio' _spotify-connect._tcp 4000 VERSION=1.0 CPath=/login/_zeroconf

Any help would be much appreciated.

**Comment by balbuze** [comment]
Do you use version 1.5.1 of the plugin?I see something wrong in your config about mixer. But this does not come from the plugin. Try to disable i2s dac choose jack save reboot enable your dac save. Save the mixer. You need a working volumio before using the plugin. But there is a bug if mixer "none" is selected. I think fixing it tonight

**Comment by Dustee** [comment]
Yes it is version 1.5.1 . When i revert back to jack output the plugin works, and it selects --mixer 'PCM'  --mixer_device_index 0.
Audio with the dac works fine on volumio, i played some tracks using upnp.

I found out that the pimoroni phat dac does not support hardware mixing. Would that be the problem? Can we get the plugin to work without setting the mixer parameter?

**Comment by balbuze** [comment]
It should work with softvol. When mixer is set to none a bug prevents the plugin to start. As I wrote, I'll try to fix it in some hours now

**Comment by Dustee** [comment]
Hi, i tried the 1.5.2 version of the plugin but i still have trouble making it work.
In order to troubleshoot i made startconnect.sh executable, and tried to manually run the script.
This version of the scipt : 

> cd /data/plugins/music_service/volspotconnect/spotify-connect-web
./spotify-connect-web  --username 'xxx' --password 'xxx' --bitrate 320 --name 'Volumio' --playback_device plughw:1 --mixer ''  --mixer_device_index 1 --dbrange 45

Returns this error:

> Loading Spotify library...
usage: main.py [--device DEVICE | --playback_device PLAYBACK_DEVICE]
               [--mixer_device_index MIXER_DEVICE_INDEX] [--mixer MIXER]
               [--dbrange DBRANGE]
main.py: error: argument --mixer/-m: expected one argument

I tried putting "SoftMaster" in the --mixer parameter of the script, but i got this error:

> Loading Spotify library...
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from connect import Connect
  File "/usr/src/app/connect.py", line 9, in <module>
    from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
  File "/usr/src/app/console_callbacks.py", line 104, in <module>
    mixer = alsa.Mixer(args.mixer, **mixer_card_arg)
alsaaudio.ALSAAudioError: Unable to find mixer control SoftMaster,0 [hw:1]

Also i modified /data/plugins/music_service/volspotconnect/spotify-connect-web/etc/asound.conf 
because it was pointing to wrong device names. Since hdmi is plughw:0,1 and my dac is plughw:1,0 i made it like so:
`pcm.softvolume {
    type             plug
    slave.pcm       "softvol"
}

pcm.softvol {
    type            softvol
    slave {
        pcm         "plughw:1,0"
    }
    control {
        name        "SoftMaster"
        card        0
        device      1
    }
max_dB 0.0
min_dB -50.0
resolution 100
}`

Do you think there is something wrong in the configs?
Sorry for the long post.

**Comment by balbuze** [comment]
Does your device work with volumio? I mean with local tracks ? Because the value in start connect.sh is wrong. Around.conf is a copy of /etc/asound.conf when you save the config in plugin. Try with none as mixer. You can erase /data and restart volumio. But you 'll loose your config.

**Comment by balbuze** [comment]
It is very important to have a working config especially with Software volume before trying to get the plugin working

**Comment by balbuze** [comment]
I tested with a fresh install (volumio 2.041) and version 1.5.2 of the plugin with a hifiberry like dac. And I there is a problem with softvol... I really don't understand why because I tested the same plugin several times on the previous SD card with success..I have to investigate

**Comment by Dustee** [comment]
I 'm having trouble with volumio now. Even though i was able to use the dac with upnp and play music a few days ago, i can't get it working anymore no matter how many clean installs i do.
I will use the volumio forums for this issue though as this is not the place for general volumio help.

Bear in mind that i'm not at all experienced with alsa, and i have limited experience in linux, but if you want me to test something, let me know.

**Comment by balbuze** [comment]
ok. But your feeback is useful, as I saw a case not managed correctly by the plugin with a hifberry dac... I'm working on it. keep in touch !

**Comment by balbuze** [comment]
I uploaded a new version 1.5.3 that should work better for you if you don't use softvol. Let me know

**Comment by cortegedusage** [comment]
Hi I was trying to install volspotconnect on volumio 2.041 on rpi2 with
hifimediy usb dac.
on and previously i could get it to work with mixer set to none, but with
new installation
it doesn't work with softvol or none.

running startconnect.sh gives:

Established under name 'grotezaal'
Loading Spotify library...
Traceback (most recent call last):
  File "loader.py", line 3, in <module>
  File "runpy.py", line 180, in run_module
  File "runpy.py", line 72, in _run_code
  File
"/data/plugins/music_service/volspotconnect/spotify-connect-web/main.py",
line 14, in <module>
    from connect import Connect
  File
"/data/plugins/music_service/volspotconnect/spotify-connect-web/connect.py",
line 9, in <module>
    from console_callbacks import audio_arg_parser, mixer, error_callback,
connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
  File
"/data/plugins/music_service/volspotconnect/spotify-connect-web/console_callbacks.py",
line 104, in <module>
    mixer = alsa.Mixer(args.mixer, **mixer_card_arg)
alsaaudio.ALSAAudioError: No such file or directory [hw:1]
Failed to execute script loader

any ideas?

btw I got it working with rpi3 with i2s dac and softvol so I know it can
work..

thanks

2016-12-23 21:41 GMT+01:00 balbuze <notifications@github.com>:

**Comment by balbuze** [comment]
I can't have a look now. Sorry. Maybe tomorrow but not sure... Xmas time...

**Comment by balbuze** [comment]
But post the content of startconnect.sh (remove credentials)

**Comment by Dustee** [comment]
Good news everyone!
I just installed 1.5.4 and it works. I immediately powered off the pi and took a backup of the image, just to be safe. :D
In the playback settings, i have mixer type set to "none", i get no sound with mixer type set to "software", even though the service remains active either way.
I didn't get to try 1.5.3, if you want me to test it so that you can pinpoint exactly what was the issue, let me know. I'll be available after monday.

Thanks for making this happen and have a merry christmas!

**Comment by macmpi** [comment]
@Dustee 
Same setup (PiZero, pHat DAC, Volumio 2.041), and [similar issue under 1.5.6](https://volumio.org/forum/spotify-connect-plugin-old-volumio-login-with-winscp-t4524-300.html#p=26882).
Did not have the issue with some earlier version (can't remember which): have you tried 1.5.6?

**Comment by Dustee** [comment]
@macmpi 
I'm using 1.5.6 since balbuze released it.
The plugin had some trouble working a few days ago. It  appeared as enabled in the volumio ui, but i couldn't actually connect from a spotify app. I had this kind of error in "/var/log/volumio.log"

> Volspotcoonect status error: Error: connect ECONNREFUSED 127.0.0.1:4000

But today, i tried toggling it on and off in the volumio ui, and it is working again like before.
