### ISSUE TITLE
Simple equalizer desactivate I2S Dac

### ISSUE THREAD

**Issue by jbonlinea** [balbuze/volumio-plugins#121]
Hi, 

I'm not sure I'm facing a real bug, but it's neither an expexted behaviour, so I'll post my experience as feedback.

___ My set up ___
Raspberry 3 , Hifiberry Dac+Standard; Volumio 2.348 rev 22 December 2017

Installed plug in (in case of) :  youtube, spotify, snapcast and of course simple equalizer

___ Install ___
the advancement bar stayed stuck at 70% for a while untill I clicked around and the modal desapeared.

Yet, the plug-in was installed

___ First use ___
on plug-in activation, I was redirected to the "lecture" setting (I already changed the local but must be "play or "playback in english, anyway, the second one on the list).

At the same time the sound had drastically changed

On the "lecture settings" page, 

- the output is not "Hifiberry dac plus" anymore but  "hifiberry dac plus trought ecqualizer" 
- the IS2 DAC option is now set to OFF, while it was on, and set with the approrpriate driver.

I can't say if any other changes have been applied.

___ re-activating I2S dac ___
If I re-activate I2S DAC, the music stops, and volumio become buggy. 
Clicking play return a notification in the upper right conner, however no music is played and the count stay where it was.

I can't acces to my music library tab neither, the loading logo apears for a while untill I'm redirected to the central play tab. 

Desactivating I2S do not solved the issue, I had to disactivate the simple equalizer pluggin, reboot, reactivate the equlizer plug in.
On plug-in activation, I observed the same as before, but I haven't change the I2S setting again. 

___ End of the feedback ___

Hope this might help

Cheers

**Comment by balbuze** [comment]
The plugin use the current settings of volumio and redirect the sound to the equalizer. Even if i2s appears deactivated, it is not. Don't change this once the plugin is enable.

**Comment by jbonlinea** [comment]
ok
yes that what i did the second time, 
I was surprised of the behaviour and reported it in case it was usefull.

Thank's for your answer

**Comment by balbuze** [comment]
I know it's a bit confusing... But I don't know how to workaround this.. 
Does the equalizer works for you?

**Comment by jbonlinea** [comment]
Humm,

the plugin run, and affect the sound.

However I can't get (a stable) Shaireport connexion when the plug-in is running.

When I disable the plug-in, I can't  play music anymore.
In the play setting tab, "hifiberry dac plus pro through equalizer" remains, and I2S still appears disabled.
If I change the audio output to hifiberry, I still can't enable I2S.
After reboot everything is back in order, the plug-in is desactivated, music plays nicely, and shaireport is stable
