### ISSUE TITLE
[volstereo2mono] - issues with AirPlay

### ISSUE THREAD

**Issue by sacca1986** [balbuze/volumio-plugins#122]
Hi,
the volstereo2mono plugin not work with Airplay
When i try to stream audio with Airplay Volumio is reboot. 

Below the log of volumio:

------------------------------------------------------------------------------------
Volumio.service: main process exited, code=exited, status=1/FAILURE
Unit volumio.service entered failed state.
Starting dynamicswap service...
Started dynamicswap service.
Unable to set hw params for playback monoout: Device or resource busy
Unable to set sw parameters for playback monoout stream: Device or resource busy
pcmjob failed.
volstereo2mono.service: main process exited, code=exited, status=1/FAILURE
Unit volstereo2mono.service entered failed state.
bcm2835-i2s 3f203000.i2s: ASoC: can't set 3f203000.i2s hw params: -16
------------------------------------------------------------------------------------

Thanks
PS: I have IQuadioDAC plus and Volumio 2.348

**Comment by balbuze** [comment]
does it work with other source ?

**Comment by sacca1986** [comment]
Yes !!
I tried with with WebRadio and MP3 on NAS and the plugin work.
The problem do only with AirPlay.

**Comment by ttaylor** [comment]
I can confirm this same problem with a RPi3 and HiFiBerry AMP2 (running as DAC Plus) and Volumio 2.362. Once Airplay is connected from iPhone, audio will play for a couple seconds before service restarts. WebRadio plays just fine.

**Comment by balbuze** [comment]
should be ok with volumio 2.378
