### ISSUE TITLE
[volspotconnect 2] service name not given to volumio

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#125]
in line 92
  //   service: self.servicename, 

should be without the  "//"
 is there any reason they are there?

I'm using a python script to display info on a lcd screen.
removing them doesn't change anything in how the plugin works
and my display displays the right  information :)

btw
Volumio hasn't updated it's repository installing from there results in crashing UI...

cheers!

**Comment by balbuze** [comment]
Oops! It should not...
As the pr is not merged, I'm going to remove it until I correct that. But I am not at home now. So not sure to be able to do it before tonight.

**Comment by cortegedusage** [comment]
thanks!

**Comment by balbuze** [comment]
It should be ok with the last official version of the plugin available in volumio
