### ISSUE TITLE
[volspotconnect1/2] volume issues

### ISSUE THREAD

**Issue by dmnc-net** [balbuze/volumio-plugins#127]
**volspotconnect** 
Changing volume from the Spotify (remote device, i.e. cellphone) controls master Volumio volume level but didn't update the UI. After pause, UI is updated with correct volume level.

**volspotconnect2** 
Changing volume from the Spotify (remote device, i.e. cellphone) doesn't control master Volumio volume, so user has to set higher Volumio volume level and then control within remote but after switching to another music source, user has to remember to lower master volume.

**Comment by balbuze** [comment]
yes this is normal behaviour. It should change in the future...

**Comment by ashthespy** [comment]
@tzapu with volspotconnect2 changes from the client (0 -- 100) are mapped to 0 -- current Volumio system volume.

**Comment by tzapu** [comment]
i find that behaviour quite confusing... it pretty much means you have two sets of volumes (in my case, also a third from the avr)

would there be an option at some point to disable volume changes?

thanks @ashthespy
