### ISSUE TITLE
softvol fix

### ISSUE THREAD

**Issue by balbuze** [balbuze/volumio-plugins#13]
in order of having it working, mixer_device_index must be the number of the output device.
First test to make it work this way. (plugin and softvol works with this value)

**Comment by balbuze** [comment]
should be fixed in ver 1.5.6
but volumio sometime retruns a wrong value for number

**Comment by Dustee** [comment]
I just tried v1.5.6.
It works with software mixer. At first no sound was coming out of the speakers, but as soon as i tried to change the volume from the spotify app on my phone, it got unstuck and it started working.
Setting mixer to none also still works as previously.

**Comment by balbuze** [comment]
Good! Thanks you for testing.

**Comment by ashthespy** [comment]
Would like to also update that softvol is working fine for me (rpi0+PCM5102) with ver 1.5.6!

**Comment by balbuze** [comment]
great! happy new year !
