### ISSUE TITLE
Volspotconnect2 x86

### ISSUE THREAD

**Issue by mredone** [balbuze/volumio-plugins#132]
Is any chance to get x86 dev version to test?

**Comment by balbuze** [comment]
X86 is ready. You can install it via ssh. Just download volspotconnect2.zip, unzip in folder and run volumio plugin install.

**Comment by mredone** [comment]
Hmm how long it takes 
`Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin`

It takes now 10minutes.
Something wrong.

**Comment by mredone** [comment]
Ok after all day fight plugin is installed... and not work...
I see it in list of devices but not playing, no gui change

**Comment by codewarriorFX** [comment]
Im having the same issue on x86.

**Comment by codewarriorFX** [comment]
Hi, I just downloaded the last build and is working now on X86.
