### ISSUE TITLE
[volspotconnect2] librespot crashing with invalid enum value

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#133]
Hey Balbuze, 

after my android spotify app updated
i cannot connect to librespot anymore
running it from cli gives me
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:906:4

might be related to
https://github.com/librespot-org/librespot/pull/167

I noticed you changed the binairy did pulled the code from github or did you just recompiled it with the new desired port nr?

cheers
Dennis

**Comment by balbuze** [comment]
Hi,
This is the same librespot than previous version. Just a change for the port. 
Do you use x86 or arm?

**Comment by ashthespy** [comment]
@cortegedusage I built a version with the patches merged - would you be willing to test?

**Comment by cortegedusage** [comment]
Yeah sure, where van i find IT?

Op 28 feb. 2018 10:11 a.m. schreef "Ash" <notifications@github.com>:

**Comment by ashthespy** [comment]
Sorry  - work called  :-)
If you have an arm device try with this!

```
wget https://git.io/vAXK0 -O volspotconnect2.zip
unzip volspotconnect2.zip -d volspotconnect2
cd ./volspotconnect2
volumio plugin install
```

**Comment by cortegedusage** [comment]
@ash

hmm still same error occurs.


2018-02-28 16:17 GMT+01:00 Ash <notifications@github.com>:

**Comment by balbuze** [comment]
using previous cmd still download the same librespot. I have to compile and upload a new version before use.

**Comment by cortegedusage** [comment]
Ah that explains

Op 28 feb. 2018 6:19 p.m. schreef "balbuze" <notifications@github.com>:

**Comment by ashthespy** [comment]
Ah - this new plugin system - it still uses the `install.sh` file? 
Here is the new binary file 
[librespot.zip](https://github.com/balbuze/volumio-plugins/files/1768167/librespot.zip)

**Comment by balbuze** [comment]
sure it is the same. But it downloads 	wget https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/arch/armhf/librespot-armhf5030.tar.xz at install time. So I'm going to upload your version of librespot

**Comment by cortegedusage** [comment]
new binary works!

thank you guys!


2018-02-28 18:45 GMT+01:00 balbuze <notifications@github.com>:

**Comment by krisss85** [comment]
Yay it works. Thx for fixing this.

**Comment by WalterBorgstein** [comment]
Does this have an impact on the working via the IOS app of Spotify? Since a couple of days connect stopped working for me.

**Comment by ashthespy** [comment]
Yep - it should fix that.

**Comment by WalterBorgstein** [comment]
Great! I will wait for the plugin update ;)

**Comment by ashthespy** [comment]
Dunno how long until it's pushed to the official plugin manager - but until then can get it with
```
wget https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/volspotconnect2.zip
mkdir ./volspotconnect2
miniunzip volspotconnect2.zip -d ./volspotconnect2
cd ./volspotconnect2
volumio plugin refresh
```

**Comment by balbuze** [comment]
If no problem, I'll push to volumio saturday. But don't know when itwill be available in volumio!

**Comment by messismore** [comment]
Do plugins installed via the manager update automatically?

**Comment by balbuze** [comment]
You can install it "by hand" f you can't wait....
I just send a PR to volumio in order to update the official plugin. But can't tell you when it will be updated

**Comment by messismore** [comment]
Waiting is no problem 😄 
I was just wondering whether there is something I have to do when the update becomes available in the manager.

**Comment by balbuze** [comment]
When the update will be available, you'll see an "update" button in the plugin list. But it will not be updated automatically.

**Comment by Levdbas** [comment]
Ey there, after manually updating to 0.6.2 I still run into errors.

`Mar 03 12:49:45 volumio volumio[13577]: INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-r4r7.ap.spotify.com:4070"
Mar 03 12:49:51 volumio volumio[13577]: INFO:librespot_core::session: Authenticated as "levdbas" !
Mar 03 12:49:51 volumio volumio[13577]: INFO:librespot_core::session: Country: "NL"
Mar 03 12:49:51 volumio volumio[13577]: INFO:librespot::audio_backend::alsa: Using alsa sink
Mar 03 12:49:51 volumio volumio[13577]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(13))', /checkout/src/libcore/result.rs:906:4
Mar 03 12:49:51 volumio volumio[13577]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Mar 03 12:49:51 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Mar 03 12:49:51 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
Mar 03 12:49:53 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Mar 03 12:49:53 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Mar 03 12:49:53 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Mar 03 12:49:53 volumio systemd[1]: Started Volspotconnect2 Daemon.
Mar 03 12:49:53 volumio volumio[13671]: INFO:librespot: librespot d9deef8 (2018-02-06). Built on 2018-02-06. Build ID: BKb2hWLu
Mar 03 12:49:53 volumio volumio[13671]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
`

**Comment by balbuze** [comment]
how did you install ? you are still using a old version of librespot : librespot d9deef8 (2018-02-06). Built on 2018-02-06. Build ID should be INFO:librespot: librespot c1128f9 (2018-02-28). Built on 2018-02-28. Build ID: B698bwAU
please remove previous version and install the new using ssh (waiting the official)

**Comment by Levdbas** [comment]
Removing the plugin entirely before installing it again via SSH did the trick. Thanks!

**Comment by cortegedusage** [comment]
Original problem resolved

closing
