### ISSUE TITLE
[volspotconnect 2] password not escaped before shell execution

### ISSUE THREAD

**Issue by DBMandrake** [balbuze/volumio-plugins#134]
After changing my spotify password I noticed that a password with an ampersand was causing the volspotconnect2 service to crash and realised that a password entered in the web interface for this plugin is placed straight into startconnect.sh without any form of shell code escaping.

This means that the part of my password after the ampersand was being executed as shell code...

Not only does this cause the service to crash and fail to work, anyone with access to edit plugins in the web interface can execute arbitrary shell code as the volumio user by including characters such as ampersand or semi-colon.

It also means passwords with single or double quotes as part of the password itself cannot be used.

Further details here:

https://volumio.org/forum/spotify-connect-plugin-passwords-not-escaped-properly-t9207.html

**Comment by ashthespy** [comment]
@DBMandrake This is a rather silly oversight and an easy fix - thanks for bringing it our attention!

**Comment by balbuze** [comment]
should be fixed with last version (0.6.2)
