### ISSUE TITLE
[volspotconnect2] volspotconnect2.tmpl onstart1.sh not enabled

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#136]
as it is now in volspotconnect2.tmpl --onstart is disabled.
you should remove the # 

cheers

**Comment by balbuze** [comment]
done in last version 0.6.3

**Comment by cortegedusage** [comment]
Seems like you've added a # in onstart1.sh itself, shouldn't this be remover?

**Comment by balbuze** [comment]
Do you need it ?

**Comment by cortegedusage** [comment]
Ah wait, is the volumio stop command not needed anymore?


Op 5 mrt. 2018 10:40 a.m. schreef "balbuze" <notifications@github.com>:
