### ISSUE TITLE
volspotconnect2 log?

### ISSUE THREAD

**Issue by voltcode** [balbuze/volumio-plugins#138]
Hi, 
I'd like to see what is going on with volspotconnect2 and librespot under the hood, to debug recent issues.

I seem to be intermittently pestered by https://github.com/balbuze/volumio-plugins/issues/133 and some wifi problems. I flashed by volumio image, installed the latest volspotconnect2 and want to make sure librespot is working fine and it's the network, or vice versa. What's the best way to see what is going on?
/var/log/volumio.log shows nothing (many info level messages, some related to volspotconnect2, but nothing relevant).

**Comment by ashthespy** [comment]
Hi!
If you pulled the latest plugin from this repo, it should be all good. 
You can confirm by looking at active log info with `sudo journalctl -f | grep 'librespot\|SpCon'` and then initiating a Spotify Connect session. 

PS:  `librespot c1128f9 (2018-02-28). Built on 2018-02-28. Build ID: B698bwAU` is the current patched version.
