### ISSUE TITLE
Error Installing Plugin 

### ISSUE THREAD

**Issue by 4of3** [balbuze/volumio-plugins#14]
Hey, 

first of all thanks to your work! :-)

But i have some problems, hopefully you can help me?!
i installed today the latest version of volumio on my raspberry 1 Model B. i download your .zip  file hear
by push to view raw
![image](https://cloud.githubusercontent.com/assets/5593856/21962846/4d6963a2-db2f-11e6-829c-3770339d232d.png)

after that i connect to the volumio GUI and go to plugin, choose the zip file...after a while a error comes up:
Cpu is Armv6l, downloading required package. Be patient, it could take up to 5min...
Installing spotify-connect-web dependencies
Failed to download. Stopping installation now
The following error occurred when installing the plugin: Error

can you help me, did i something wrong?

cheers

**Comment by balbuze** [comment]
Hi,
This error is due to a network issue. Maybe the repo was down or your connection failed ? Your device must be connected to internet. Have you tried again ? I'll check later if it works.

**Comment by 4of3** [comment]
During my try und had auf stable Internet connection. I will try it
tomorrow again...and right back
