### ISSUE TITLE
[volspotconnect2] Volumio plugin manager update

### ISSUE THREAD

**Issue by dmnc-net** [balbuze/volumio-plugins#140]
Hi @ashthespy, I just found that volspotconnect2 plugin here has been updated on March 4 but that one in the Plugin manager is still from Feb 18. I don't know the background and obstacles with putting the plugin to the Volumio's plugin manager (repo) but is there any chance to have fresh releases there in the future?

**Comment by ashthespy** [comment]
This is something that Volumio team knows best ;-) but , the [recommended path](https://volumio.org/forum/require-plugins-uploaded-plugins-repo-t8116.html) to officially publish the plugin is to submit a pull request as https://github.com/volumio/volumio-plugins/pull/154
Normally the PR is merged quite quickly,  but Michelangelo is a bit held up currently - so it's taking a tad longer. 
There is always the method to manually install the plugin via ssh, so no worries! :-)
