### ISSUE TITLE
Display plugin version number and ZIP upload capability

### ISSUE THREAD

**Issue by Streep** [balbuze/volumio-plugins#143]
I cannot see in the interface what the current version is of the installed plugins. Can you please add this somewhere? It's very inconvenient when having to attend to multiple systems. Also the functionality of being able to upload a zip file to install a plugin is not possible anymore (I thought there was a button for that before the latest update -- if it has been removed since, please update the help file to reflect that, i.e. https://volumio.github.io/docs/Plugin_System/Plugin_System_Overview).

**Comment by kayue** [comment]
@Streep Yes the upload plugin capability has been removed by Volumio upstream.

I have updated the README file in the repo already: https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect2#to-install
