### ISSUE TITLE
[volspotconnect2] audible click between tracks when using USB-DAC

### ISSUE THREAD

**Issue by MennoH** [balbuze/volumio-plugins#148]
I'm using the latest version of librespot on Volumio 2.368 (installed via wget because of problem with not playing the next track automatically). During switch to next track an audible click can be heard when I use my USB-DAC. Also, the first tones of the new song do not appear (due to resync of DAC?)

**Comment by martinbalint** [comment]
It should have been fixed in kernel 4.10. Volumio is running 4.9.
See https://patchwork.kernel.org/patch/9470981/
