### ISSUE TITLE
Where is my Spotify playlists

### ISSUE THREAD

**Issue by trycoon** [balbuze/volumio-plugins#155]
I have successfully installed the https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect2-plugin according to the description on this page. But where is my Spotify playlists? How do I browse my music? I can't find where to browse Spotify and select playlists to play.
Thanks!

**Comment by ashthespy** [comment]
@trycoon  This plugin is for **Spotify Connect** and not Spotify :-)

**Comment by trycoon** [comment]
Ah sorry, I did’nt know the difference. I thought the support would show up in the UI and the API, but it was only available in the API. I can play music from my automation dashboard now, nice!
Closing the issue...

Thanks!
