### ISSUE TITLE
Plugin doesn't appear on Volumio

### ISSUE THREAD

**Issue by dccarm** [balbuze/volumio-plugins#157]
I've installed volspotconnect2 on to three different raspberry pi's by SSH. The first was a few days ago dev ver 0.7.0 on to a pi zero and it worked perfectly. The second two, on to another pi zero and a Pi A seem to install perfectly but do not appear in the list of plugins in Volumio.

**Comment by balbuze** [comment]
You don't need to install via ssh. Use the version available in.Ui.
Are all your devices on the same network?

**Comment by dccarm** [comment]
I did originally install via the UI, but Spotify kept stopping at the end of the first track. That's why I tried the SSH install. I've tried the UI route again and it's working now. Thanks.
