### ISSUE TITLE
Not working at all for me. Messing my DAC configuration

### ISSUE THREAD

**Issue by LeVolatile** [balbuze/volumio-plugins#159]
Hi,

I have tried your Simple Equalizer.  Installed normally without errors but no more sound.  It changed my DAC setup by disabling I2S and changing my DAC for Allo.  I got an Hifiberry DAC+.  Even If I reconfigure it, nothing is playing.  It also prevents me from accessing my music Library. Nor turning it Off nor uninstalling the plugin solve the issue. Fortunately it didn't messed up my system. Uninstalling the plugin, rebooting the RPi and properly setting for my DAC solved the issue.

**Comment by balbuze** [comment]
humm... What is your device (rpi b+,2,3..)?
Steps that should work : 
- having a working well configured system (tested with a track)
- install the plugin
- enable the plugin. It takes about 10 seconds.
- play a track.
In playback setting of volumio, you should have something like "hifiberry dac through equalizer plugin".
I2s appears disable but it is not! DO NOT change any settings, output, i2s, volume mixer or it will corrupt the configuration. If no sound, just reboot. 
let me know

**Comment by LeVolatile** [comment]
I retried but without any success. I just seen that if I don't touch playback setting after I installed the plugin, I can recover normal operation just by disabling the Equalizer and rebooting.  I don't  need to uninstall it.

BTW, you should specify that this is a Beta version to reduce irritants from the users.  If some cautions must be taken to avoid installation corruption, it should also be specified in the installation notice.

My setup is as follow:  RPi 3+ with Hifiberry DAC+ and a "beefy" power supply.

**Comment by SlowmoDK** [comment]
I was having the same issues ....

solution for me ... 

install plugin while not playing.  After 10 sec player restarted message (no sound at this point)
reboot and then aprox 10 sec after restart another restarted player message 

then it works ;)

**Comment by LeVolatile** [comment]
I still waiting for a solution! What's new? Still stays ABSOLUTELY SILENT! Worst: Volumio "says" it's playing.
