### ISSUE TITLE
volstereo2mono volume 100% on startup

### ISSUE THREAD

**Issue by dccarm** [balbuze/volumio-plugins#160]
I have at last got volstereo2mono working with my pi zero and justboom amp. When I start up, the default volume is 100% - it's marked as disabled in the settings and if I change it, it still goes back to 100%.

**Comment by balbuze** [comment]
is the volume 100% or just the display? does the volume change (sound level) when changing in Ui?

**Comment by dccarm** [comment]
Volume changes in the UI. It's just the startup volume.

**Comment by dccarm** [comment]
Actually, after rebooting a few times, it seems to me that it's just the display that shows 100% - the actual volume is much lower than that.
