### ISSUE TITLE
Unable to install Spotify Connect 0.7 plugin

### ISSUE THREAD

**Issue by hebert99** [balbuze/volumio-plugins#163]
Hi everybody,

I own 2 Pi3 with Volumio. Very good value and performance for the money. DACs are both Hifiberry DAC+.
I was using volspotconnect2 0.3 until last week. Volumio version was 2.310. It stopped working but the devices were visible from the Spotify Windows and Android apps. After 30 seconds the Spotify app returned audio to the phone or desktop failing to connect to the Pi3.

I started reading and found the new plugin version. I upgraded one Pi3 to 2.389 and did the complete procedure through SSH but I cannot make it work. Download, unzip and directory creation do work, but the volumio plugin install command does nothing after the following response:

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin

Volumio GUI keeps working but volspotconnect2 does not install properly, nor makes the device visible from Spotify apps. I tried plugin installation as a normal and root user. I made also a factory reset and Volumio upgrade with no success.

Any help would be kindly appreciated.

**Comment by balbuze** [comment]
Hi,
Volspotconnect2 ils available as an official plugin. Just search it in the webUi. :wink:

**Comment by hebert99** [comment]
Thanks for the info. Now working very well :smiley:
