### ISSUE TITLE
--onstart not working

### ISSUE THREAD

**Issue by richpuch** [balbuze/volumio-plugins#164]
Did you rework the way spotify connect2 is run...you helped me in the past with getting things reported into home assistant with the use of the onstart1.sh and onstop1.sh files.  I recently upgraded the plugin, created the files and edited volspotconnect2.tmpl but it doesn't seem like that file gets called anymore.  trying to execute this line when starting and a similar line when stopping:

/usr/bin/curl -X POST  -H "x-ha-access: mocha211" -H "Content-Type: application/json" -d '{"state": "on"}' http://192.168.2.25:8123/api/states/input_boolean.volumio_spotify_status

Also...can't seem to get the volume set...I set it in the plug in section but it never changes when I start using the plugin.

**Comment by ashthespy** [comment]
Hi,
`--onstart` and `--onstop` should still work, are you sure your `onstart1.sh` is executable?

The inital volume setting from the UI is Spotify Connect deamon's inital volume. The catch here is that this considers the current Volumio alsa volume as it's reference 100%.  
I started implementing the Alsa mixer, but I was having issues developing - all my devices have only software mixers, need to look at it soon!

**Comment by richpuch** [comment]
Thanks for helping....
I chmod 777 to both my onstart1.sh and onstop1.sh.  If I try to run the onstart1.sh from command line it executes my file.  But as I switch to spotify connect from my iphone, the  volspotconnect2.tmpl doesn't call the onstart.    I see a startconnect.sh and I tinkered with that file too, but no luck.
here is what my  volspotconnect2.tmpl looks like:
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detectedcd /data/plugins/music_service/volspotconnect2./librespot -b 320  -c /tmp ${shared} ${normalvolume} --name '${devicename}' --backend alsa --device ${outdev} --disable-audio-cache --initial-volume ${initvol}  --onstart ./onstart1.sh --onstop ./onstop1.sh
According to the readme file and Volumio I'm on verison 18th march 2018.
Thanks for looking into this.Rich


    On Wednesday, April 25, 2018, 5:28:22 PM EDT, Ash <notifications@github.com> wrote:  
 
 
Hi,
--onstart and --onstop should still work, are you sure your onstart1.sh is executable?

The inital volume setting from the UI is Spotify Connect deamon's inital volume. The catch here is that this considers the current Volumio alsa volume as it's reference 100%.
I started implementing the Alsa mixer, but I was having issues developing - all my devices have only software mixers, need to look at it soon!

**Comment by balbuze** [comment]
As far as I know, on start on stop were removed in the last librespot, replaced by onevent. I didn't test it deeply. seems to crash librespot . see what is returned when launching librespot with no other option. You'll see all switches available.

**Comment by ashthespy** [comment]
@richpuch 
Sorry for the delay -  I just tested this out maybe this helps you get your setup working?

```bash
#startconnect.sh
 ./librespot -b 320  -c /tmp -n 'Volumio' --onevent ./onstart.sh
```

```bash
#onevent.sh
echo "$PLAYER_EVENT $TRACK_ID"  >> onevent.log
```

```
#onevent.log
start 5ef9bfb004d4415bae220c0a79da3fa3
change 04f235e2ce6c4c5ba189e327dbbe620c
change 945f800b0ed64cd087d5ce624ffeebfc
stop 945f800b0ed64cd087d5ce624ffeebfc
```
