### ISSUE TITLE
Installer is stuck at Status:Downloading

### ISSUE THREAD

**Issue by niels-anders** [balbuze/volumio-plugins#166]
I'd like to try this plugin as I hope to use my Android Spotify app to stream music to my setup with Volumio via Spotify Connect. 

I followed the install instructions but the:

`$ volumio plugin install`

returns:
```
This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
```
and gets stuck at Downloading plugin. The wget command to fetch the zip file is working correctly so outside connections are possible. Is there a service down? 

I am not sure if the problem is with the plugin, Volumio servers, or my own.

**Comment by niels-anders** [comment]
Sorry, I thought I wrote on a special volspotconnect2 issue board, yes I mean volspotconnect2. And thanks for the super-quick reply!

I didn't use the inbuilt plugin manager as the [instructions](https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect2) mentions:
 
> Due to a Volumio decision, now third party or dev plugin can only be install through SSH. Here is how:

**Comment by xrischan** [comment]
I guess its just lazy coding. Not checking if a dir exits within the script. Especially not a a full "whatif" clean uninstall. 
So, if it went wrong on the first attempt, then there's no hope. Gets stuck at 30%. So as the programmer you should know what 30% represents. 
 I had to do a whole img re-press. to fix this.  
Gotta check your IF's, BUT's, and Whatevers. esp when there's a no escape plan.  
Love the player. Works great with my JUSTOOM DAC. But there's a many few GUI or 'sh' problems that still need attention. :)
