### ISSUE TITLE
Changing bit depth to 32 bits, Volumio Spotify connect 1.7.4

### ISSUE THREAD

**Issue by nagogam** [balbuze/volumio-plugins#167]
Hi,

Is it possible to change the bit depth to 32 bits with your plug-in? I modified the shairpoint-sync configuration file so all the "airplay" audio is converted to 32 bits, but it doesn't affect the audio coming through the Spotify connect plug-in, for some reason.

Thank you,
Michael

**Comment by balbuze** [comment]
when you use spotify connect, it Does not use shairplay... data comes directly from Spotify. My advice is that changing each plugs output is not the solution. It should all output to a virtual device define in asound.conf and conversion is done here.

**Comment by nagogam** [comment]
Thanks.

When you are talking about a virtual device, you mean, instead of using "hw:1" I should define a new virtual one? Right?

pcm.spotoutf
{
type dmix
slave {
pcm hw:1
rate 44100
        }
ipc_key 1024
}
pcm.spotout
{
type plug
slave.pcm spotoutf
}
