### ISSUE TITLE
[volspotconnect2] prev/next/stop from web interface doesn't work anymore.

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#168]
came back from holliday today
and noticed I couldn't control volspotconnect2 from the volumio gui anymore.

when checking in the cli, I get
May 05 21:12:08 woonkamer volumio[974]: info: CoreCommandRouter::volumioGetState
May 05 21:12:08 woonkamer volumio[974]: info: CoreStateMachine::getState
May 05 21:12:19 woonkamer volumio[974]: info: CoreCommandRouter::volumioNext
May 05 21:12:19 woonkamer volumio[974]: info: CoreStateMachine::next
May 05 21:12:19 woonkamer volumio[974]: info: [SpConDebug] Received next
May 05 21:12:19 woonkamer volumio[974]: (node:974) UnhandledPromiseRejectionWarning: Unhandle                                                                                                d promise rejection (rejection id: 33): WebapiError: Unauthorized
May 05 21:12:28 woonkamer volumio[974]: info: CoreCommandRouter::volumioGetQueue
May 05 21:12:28 woonkamer volumio[974]: info: CoreStateMachine::getQueue
May 05 21:12:28 woonkamer volumio[974]: info: CorePlayQueue::getQueue
May 05 21:12:28 woonkamer volumio[974]: info: CoreCommandRouter::volumioGetState
May 05 21:12:28 woonkamer volumio[974]: info: CoreStateMachine::getState
May 05 21:12:48 woonkamer volumio[974]: info: CoreCommandRouter::volumioGetQueue
May 05 21:12:48 woonkamer volumio[974]: info: CoreStateMachine::getQueue
May 05 21:12:48 woonkamer volumio[974]: info: CorePlayQueue::getQueue
May 05 21:12:48 woonkamer volumio[974]: info: CoreCommandRouter::volumioGetState
May 05 21:12:48 woonkamer volumio[974]: info: CoreStateMachine::getState
May 05 21:12:49 woonkamer volumio[974]: info: CoreCommandRouter::volumioPause
May 05 21:12:49 woonkamer volumio[974]: info: CoreStateMachine::pause
May 05 21:12:49 woonkamer volumio[974]: info: CoreStateMachine::stPlaybackTimer
May 05 21:12:49 woonkamer volumio[974]: info: CoreStateMachine::servicePause
May 05 21:12:49 woonkamer volumio[974]: info: CoreCommandRouter::servicePause
May 05 21:12:49 woonkamer volumio[974]: info: [SpConDebug] Received pause
May 05 21:12:49 woonkamer volumio[974]: (node:974) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): WebapiError: Unauthorized
May 05 21:13:08 woonkamer volumio[974]: info: CoreCommandRouter::volumioGetQueue
May 05 21:13:08 woonkamer volumio[974]: info: CoreStateMachine::getQueue
May 05 21:13:08 woonkamer volumio[974]: info: CorePlayQueue::getQueue
May 05 21:13:08 woonkamer volumio[974]: info: CoreCommandRouter::volumioGetState
May 05 21:13:08 woonkamer volumio[974]: info: CoreStateMachine::getState

there seems to be a webapi Error...
I'm sure this worked a week ago as I could control volspotconnect with my remote...

I will try a fresh install of the plugin...

**Comment by cortegedusage** [comment]
hmm installing a fresh pull from github doesn't give me the ability to push next or prev.
so this must be intended....?

**Comment by cortegedusage** [comment]
I've installed 0.7.1 
but somewhere I believe I saw 0.7.4?

**Comment by cortegedusage** [comment]
reinstalling 0.7.0 gave me the disired next/prev/stop ...

**Comment by ashthespy** [comment]
@cortegedusage  unfortunately, this is due to changes not from us https://github.com/volumio/volumio-plugins/issues/185

That being said, the dev version should not have this "feature".

**Comment by ashthespy** [comment]
I stand corrected -- https://github.com/balbuze/volumio-plugins/commit/3c96ff549dbcc7ab1f8a8656fb689aa9aafc9029 enables it for some reason.
@balbuze is this intentional?

**Comment by cortegedusage** [comment]
Probably some unintenden pull from volumio,
anyway the problem I first encountered was with an earlier version that worked a week
ago. and then it returned an error on the spotify side, see error log in the first commit.
maybe something to do with: 
https://github.com/spotify/web-api/issues/859#issuecomment-386214823

That said, at this moment I can't use volspotconnect2 at all, because it is crashing 
randomly but quite frequently, which seems to be a new problem, probably also to the above problem.
plietar commented on this in:
https://github.com/librespot-org/librespot/issues/215

anyhow.
That's all I found...

**Comment by cortegedusage** [comment]
To continue with the original problemen IT seems my remote control ( which was lost a couple of days) does work... Zo volumio controleingen with the web commands does work only the web gui doesn't.. strange

**Comment by ashthespy** [comment]
@cortegedusage It's not that strange, https://github.com/volumio/volumio-plugins/commit/1bddf32f238215bb2a884ff200db5580290ed16e adds a new `disableUi`  disabling the buttons from the webuI. Volumio decided to enable it by default for volspotconnect2. I requested that it be reset (https://github.com/volumio/volumio-plugins/issues/185#issuecomment-379464387) but it doesn't seem to have happened. I'd guess @balbuze copied it over and hence it's also set to `true` in the 'dev' version here.

I am aware of the upstream Spotify CDN issues, but thanks, will keep an eye on developments.

**Comment by cortegedusage** [comment]
Ah thanks die the reply that's makes sence. It doesn't explain my first
issue though... Annyway I know where to look now tot enable it again..

Cheers,
Dennis

Op 13 mei 2018 14:05 schreef "Ash" <notifications@github.com>:

@cortegedusage <https://github.com/cortegedusage> It's not that strange,
volumio/volumio-plugins@1bddf32
<https://github.com/volumio/volumio-plugins/commit/1bddf32f238215bb2a884ff200db5580290ed16e>
adds a new disableUi disabling the buttons from the webuI. Volumio decided
to enable it by default for volspotconnect2. I requested that it be
reset (volumio#185
(comment)
<https://github.com/volumio/volumio-plugins/issues/185#issuecomment-379464387>)
but it doesn't seem to have happened. I'd guess @balbuze
<https://github.com/balbuze> copied it over and hence it's also set to true
in the 'dev' version here.

I am aware of the upstream Spotify CDN issues, but thanks, will keep an eye
on developments.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/balbuze/volumio-plugins/issues/168#issuecomment-388621949>,
or mute the thread

**Comment by ashthespy** [comment]
Set https://github.com/balbuze/volumio-plugins/blob/3c96ff549dbcc7ab1f8a8656fb689aa9aafc9029/plugins/music_service/volspotconnect2/index.js#L116 
to false

**Comment by balbuze** [comment]
sorry lads! I'm not a home now. I'll upload a new version asap. Don't forget to save plugin setting with this dev version, even if you don't change anything.

**Comment by cortegedusage** [comment]
cheers!
