### ISSUE TITLE
ODROID C2

### ISSUE THREAD

**Issue by chsims1** [balbuze/volumio-plugins#17]
Hi Balbuze,

no idea what's involved here, but what would need modifying to make your excellent plugin work on an ODROID ?

Regards

**Comment by balbuze** [comment]
hi!
I suppose that if you ask, it's because it doesn't work.... In fact I don't know the C2. But I suppose this due to cpu problem ? What have you tried?
And a "flash info" : I'm working on new plugin (volspotconnect2) that use a different lib (librespot). Search my repo, I just post a early dev version.... not finished yet of course - appears as incative and just test on one device. But it works !

**Comment by chsims1** [comment]
Well, I half expectd it just to work (same processor as Pi3 I thought??).  I'll have a closer look at the errors, and get back to you.

**Comment by balbuze** [comment]
Maybe it could works. But the value detected by the install script does not match with what is expected. You can try to disable detection in install or change the name so that it works... Sorry I can't have a look now. I'm not at home until several hours.

**Comment by chsims1** [comment]
Most of those 404 errors are because the redirect mirror is not working for some reason.  The Odroid uses Debian sources rather than Raspbian.

Reported architecture is 'aarch64' rather than 'armv7l' as given by the Pi 3 (don't know why it does this if it is the same set of CPU cores), and if I change the install script accordingly, then it does it's thing and reports that the plugin is successfully installed. However, plugin remains inactive, even after a reboot, and I can't see the device from Spotify on my phone.  Does the plugin produce error logs anywhere?

**Comment by balbuze** [comment]
Due to problems with dependencies try to disable. Shared device and save.

**Comment by chsims1** [comment]
volspotconnects works! Much faster installation. Well done Balbuze. As you say, the inactive label is shown.

**Comment by balbuze** [comment]
Yes I know for the error message. I'm going to correct it.
Librespot is Open source. It works on miscellaneous device (as you saw).
The downloaded file is rather small. 3Mo. No other dependecies needed..
No Spotify_app_key needed
And in discovery mode, no credentials needed.
But I didn't test with several account. And I will add a setting to use it with a single user ( some user don't want to share the device)
more info : https://github.com/plietar/librespot
The previous version of volspotconnect uses a full system, with web server etc (reachable on port 4000). It works well but a big part is not use in the plugin. It uses a close lib from Spotify and for amrv6 it require a chroot version with vm (qemu).
I'm really interested by the test you have done. What is your dac ? What is your mixer setting inVolumio? etc and any info that may help to debug.

**Comment by chsims1** [comment]
DAC: Odroid hifi shield+
Output Device: Odroiddac
Mixer type: software
Mixer Control Name: Software Volume Control

I have some Pis around with various DACs .... I'll try them tomorrow

**Comment by balbuze** [comment]
great thank you. I suspect a problem in volume setting with hardware volume...

**Comment by balbuze** [comment]
I uploaded a new version that appears activated. And it stop when desactivated!

**Comment by balbuze** [comment]
@chsims1 
I have added support aarch64 in install script. But I don't own a odroid C2... I can't test it, but maybe could you ? thanks !
