### ISSUE TITLE
Multiple Sliders per Frequency Range

### ISSUE THREAD

**Issue by k-lidh** [balbuze/volumio-plugins#170]
Hi,
I have just started using the paramtetric equalizer plugin and it is working fine. Thank You!
It would be nice if:
- multiple adjustments (i.e. 3) would be possible per frequency range
or
- the 4 sliders would provide a fully adjustable (30Hz-20000Hz) range

I tried to reconfigure this myself in the config.json file and I failed. 
Any hints on how to do that ?

Jörg

**Comment by balbuze** [comment]
Sorry, but what plugin?
I don't understand what you want. Can you explain please?

**Comment by k-lidh** [comment]
Hi,
Sorry for being unprecise. 
Plugin:volparametriceq
Issue: Each of the 4 slider groups in the user interface is limited to a specific frequency range. As I would primarly like to do a precise adjustment in the low frequency region (30Hz to 400Hz) using sharp (low q) filters to fight room modes, I would appreciate  multiple slider groups in that frequency region.
What I did and didnt work: I tried to alter the frequencys in the configuration file for the user interface (UIConfig.json). After I saved the changed file, volumio di not start.

Regards
Joerg

**Comment by balbuze** [comment]
You have to alter UIConfig.json and change the text in i18n/strings_*.json to match with it

**Comment by k-lidh** [comment]
That was quick! Thank you! I will give it atry tomorrow and report back.

**Comment by balbuze** [comment]
just be aware to change only the min max values of Hz for the 4 equalizer

**Comment by balbuze** [comment]
Just for info, following your comments, I'm working on a version with customisable range and step for each band :-)

**Comment by balbuze** [comment]
done!
