### ISSUE TITLE
wifireconnect not working

### ISSUE THREAD

**Issue by hairer** [balbuze/volumio-plugins#173]
Just tried to install wifireconnect, I get the following:

[...]
Status :Copying Plugin into location
Progress: 70
Status :Installing dependencies
Progress: 0
Status :The following error occurred when installing the plugin: Error

At this stage the installation freezes and I have to manually abort... Is this a known problem? Any fix?

**Comment by hairer** [comment]
You're right, the exact same error also shows up when I try to install volspotconnect2 which suggests that it's a problem on my end. This time, I precisely followed the instructions given at the link you just mentioned... For what it's worth, I also double-checked that I am running the latest version of Volumio. Any idea of what could cause this?

**Comment by balbuze** [comment]
does wget retrun a error?

**Comment by hairer** [comment]
No, wget works fine. I also get the same error if I download the zip file to my Mac, unzip it there, copy it over to the RPI3 and then type volumio plugin install...

**Comment by balbuze** [comment]
do you use a dev version of volumio? What is your device (rpi?)

**Comment by hairer** [comment]
My device is a Raspberry Pi 3 model B with an I2S DAC connected to it. The version of volumio is a normal one but I installed a few extra Linux packages myself. Could this be the problem? Maybe I'll try a clean reinstall of Volumio to see if this helps...

**Comment by hairer** [comment]
OK, I did a factory reset and was able to install the plugin after that, so it looks like my installation was just messed up. Thanks for your help and sorry for the false alert.
