### ISSUE TITLE
[Volspotconnect2] give Librespot realtime priority 

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#179]
In my quest for good sound I came up with an idea,
would it be possible to run librespot with real time priority. 
So other scripts wouldn't interfere with it. 
I believe volumio does something simular with MPD.

I tried to figure it out and ran librespot with:
 sudo taskset 0x00000004 ./librespot -b 320  -c /tmp   --enable-volume-normalisation --name 'woonkamer' --backend alsa --device softvolume --disable-audio-cache --initial-volume 100
this should run librespot on one core only...

but changing this in tmpl file didn't work at all, the plugin wouldn't start at all..

running it from command line did work for me... Didn't have time for extensive listening so
that'l have to wait.

**Comment by ashthespy** [comment]
Interesting idea, I am no expert with this.  
but `taskset -c 2 ./librespot -b 320  -c /tmp` in my `startconnect.sh` (and tmpl file) works here.

**Comment by balbuze** [comment]
I'm very septic on what improvement it could be. The main reason is that Spotify is far from being HQ stream. And Even with a local HQ file, not sure there is a difference. When you use a bit perfect system, it just send bit per bit data, buffered but unaltered. But I'm not specialist...

**Comment by ashthespy** [comment]
I gotta agree - right now I highly doubt there will be any noticeable difference. 
Maybe [someday](https://www.theverge.com/2017/3/1/14776780/spotify-hi-fi-preparing-launch-lossless-audio-tier) it might - but again not the expert here! ;-)

**Comment by cortegedusage** [comment]
closing, not a real life priority anyway :)
