### ISSUE TITLE
RPi 3, IQaudio digiamp+, volspotconnect 2

### ISSUE THREAD

**Issue by chsims1** [balbuze/volumio-plugins#18]
Tried on my standard RPi3 player with IQaudio digiamp+.  Appears to install ok, I can connect to the device with my phone, but no audio.  System log:

`Jan 21 19:31:03 volumiokitchen volumio[1136]: TRACE:librespot::stream: allocated stream 27
Jan 21 19:31:03 volumiokitchen volumio[1136]: DEBUG:librespot::audio_file2: Got channel 27
Jan 21 19:31:03 volumiokitchen volumio[945]: src/mpdcli.cxx:127::MPDCli::showError: bad state
Jan 21 19:31:03 volumiokitchen volumio[945]: src/main.cxx:476::MPD connection failed
Jan 21 19:31:03 volumiokitchen volumio[1136]: TRACE:librespot::stream: allocated stream 28
Jan 21 19:31:03 volumiokitchen volumio[1136]: DEBUG:librespot::audio_file2: Got channel 28
Jan 21 19:31:03 volumiokitchen volumio[1136]: DEBUG:librespot::spirc: kMessageTypePlay "LG-D855" dee64f45d09deeb4477dbe7d7a85641d222871a5 3 0
Jan 21 19:31:03 volumiokitchen volumio[1136]: ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM 1
Jan 21 19:31:03 volumiokitchen volumio[1136]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/option.rs:323
Jan 21 19:31:03 volumiokitchen volumio[1136]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jan 21 19:31:03 volumiokitchen volumio[1136]: DEBUG:librespot::spirc: kMessageTypeNotify "Volumiokitchen" 3731a6dbee325571437188a20b4392879d23a824 8 1485027063625
Jan 21 19:31:22 volumiokitchen volumio[1136]: DEBUG:librespot::spirc: kMessageTypePause "LG-D855" dee64f45d09deeb4477dbe7d7a85641d222871a5 4 0
Jan 21 19:31:22 volumiokitchen volumio[1136]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
Jan 21 19:31:34 volumiokitchen volumio[1136]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
Jan 21 19:31:34 volumiokitchen systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Jan 21 19:31:34 volumiokitchen systemd[1]: Unit volspotconnect2.service entered failed state.
`

**Comment by balbuze** [comment]
ok I think I see where does the problem comes from. I try to correct iit now.

**Comment by balbuze** [comment]
It's done ! new version to test ver 0.0.4 . It should solve the output device problem. Let me know if you test

**Comment by chsims1** [comment]
It worked for a very brief period before the sound cut out, Log info:

`Jan 21 21:05:01 volumiokitchen volumio[925]: DEBUG:librespot::audio_file2: Got channel 91
Jan 21 21:05:06 volumiokitchen volumio[925]: DEBUG:librespot::spirc: kMessageTypePlay "LG-D855" dee64f45d09deeb4477dbe7d7a85641d222871a5 3 0
Jan 21 21:05:06 volumiokitchen kernel: pcm512x 1-004c: No SCLK, using BCLK: -2
Jan 21 21:05:06 volumiokitchen volumio[925]: DEBUG:librespot::spirc: kMessageTypeNotify "Volumiokitchen" 3731a6dbee325571437188a20b4392879d23a824 4 1485032706703
Jan 21 21:05:09 volumiokitchen volumio[918]: 2017-01-21 21:05:09 [SPTF] 21:05:09.063 E [ap:4210] ChannelError(0, 0, playlist)
Jan 21 21:05:14 volumiokitchen volumio[925]: DEBUG:librespot::spirc: kMessageTypePause "LG-D855" dee64f45d09deeb4477dbe7d7a85641d222871a5 4 0
Jan 21 21:05:14 volumiokitchen volumio[925]: INFO:librespot::util: Running onstop.sh
Jan 21 21:05:14 volumiokitchen volumio[925]: thread '<unnamed>' panicked at 'program failed to start: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
Jan 21 21:05:14 volumiokitchen volumio[925]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jan 21 21:05:14 volumiokitchen volumio[925]: DEBUG:librespot::spirc: kMessageTypeNotify "Volumiokitchen" 3731a6dbee325571437188a20b4392879d23a824 5 1485032714048
Jan 21 21:05:19 volumiokitchen volumio[925]: DEBUG:librespot::spirc: kMessageTypePlay "LG-D855" dee64f45d09deeb4477dbe7d7a85641d222871a5 5 0
Jan 21 21:05:19 volumiokitchen volumio[925]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
Jan 21 21:05:25 volumiokitchen volumio[925]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
Jan 21 21:05:25 volumiokitchen systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Jan 21 21:05:25 volumiokitchen systemd[1]: Unit volspotconnect2.service entered failed state.
`

It works, but it is not stable ;)

**Comment by balbuze** [comment]
Thanks for the feedback. I'll have a look tomorrow. Don't know where are you from but here it's time to go to bed....

**Comment by chsims1** [comment]
Here too (UK)balbuze, sleep well. Rather strange it works on the Odroid but not the RPi.  Trying it on a RPi0 in the morning 0:D

**Comment by balbuze** [comment]
hello, new version! It works on my rpi B (same cpu than rpi zero). I added a script that remove credentials when play stops. With that the device is available for a other user on the same network. I need to work on some other point, stream quality setting with a three value selector, and I made a first (unsuccessful) test to stop volumio if playing when start to play spotify...

**Comment by chsims1** [comment]
Yep, that now works great on the RPi 3.  I tried yesterday's version on a RPi0 and it worked initially, but failed when I paused the song playback .. it wouldn't play when I tried to start it again, and then the device disappeared from Spotify.  I'll try your latest version this afternoon.

**Comment by chsims1** [comment]
Ok, so as you say it works fine on a RPi B with hifiberry DAC.

RPi2 B with IQaudio DAC+ (Mixer type: Hardware, Control name: digital): starts playing on the device, but not shown playing on phone. I couldn't stop the play from the phone.  When I repeated this later in the day, it did show the file playing on the phone (and was playing on device), but when I pressed pause the playback stopped but it also dumped the device.

`an 22 16:18:34 volumiobookroom systemd[1]: Stopping Volspotconnect2 Daemon...
Jan 22 16:18:34 volumiobookroom volumio[1716]: Signal received: [Term]. Say goodbye and exit.
Jan 22 16:18:34 volumiobookroom volumio[1716]: INFO:librespot::util: Exit status: signal: 15`

RPi0 with IQaudio DAC (Hardware, digital): same behaviour as RPi 2 ie. plays but device dropped on pause

**Comment by chsims1** [comment]
It's not a problem atm balbuze.  The RPi 3 is my main music player, which works fine.  Let me know if you want any more testing done.

What is the status with stream quality with Volumio. I read somewhere else that the higher rate (320 kbps is it?) wasn't actually achievable.

**Comment by balbuze** [comment]
It seems 320kps does nothing with the previous volspotconnect. With the new version, some measurement could gives information, comparing the amount of data used by the official app...I'll do it later, when some other problems will be solved... Anayway, thank you for your help!
