### ISSUE TITLE
volspotconnect2 low sound

### ISSUE THREAD

**Issue by VincentBoots** [balbuze/volumio-plugins#180]
Hi,

When I use the Volspotconnect2 plugin the sound is much lower then when using a the Spotify plugin or radio.

I already installed Dev 0.7.5 but this makes no difference.

**Comment by orderoftheflame** [comment]
Is this because of the what the volume is set to in the spotify client itself?

I think by default the plugin sets it to 33% when you connect to volumio, you can change this in settings.

**Comment by ashthespy** [comment]
https://github.com/balbuze/volumio-plugins/issues/127

**Comment by ashthespy** [comment]
@VincentBoots  Sorry was on the road.

Hmm - I started working on adding [ALSA mixer support](https://github.com/ashthespy/librespot/tree/alsamixer) - but don't have a DAC with hardware control and put it on pause.
 So sorry, not ETA's!

**Comment by VincentBoots** [comment]
Hi, my Pi doesn't  have a hardware control dac at the moment. But  i also will look into that :)

**Comment by kayue** [comment]
There is a volume normalization option in the settings screen, make sure it is off if you want max volume.

**Comment by balbuze** [comment]
This is not a bug or issue... As explained, librespot used in the plugin use its own volume mixer. It means you have to set volume at 100% in Spotify app to get the max volume set in volumio. Ex if volumio is set at 40% then max volume in Spotify will be this 40%.

**Comment by VincentBoots** [comment]
Yes, im am looking how others like mopidy solved this. Because they also work with the new librespot. But there it's working as expected.

**Comment by balbuze** [comment]
I haven't check, but it should work only if a software mixer is used on the system. It is not whisable by default on a bit perfect player, or simply to keep the best sound quality.

**Comment by sm3rt** [comment]
It would be good to resolve this in some way as I thought (as others will) that the sounds wasn't actually working.  If I put the volume to full on the spotify client and then wind the Volumio volume up it works.  Shouldn't the client volume be coupled to the backend?

**Comment by balbuze** [comment]
Set the volume to max in the plugin and save.

**Comment by balbuze** [comment]
done in the next dev version
