### ISSUE TITLE
works on android 7, not works with android 8

### ISSUE THREAD

**Issue by twproject** [balbuze/volumio-plugins#186]
Hi all,
  i'm able to use volspotconnect with my wife phone (android 6) but my android 8 don't see volumio. I make a test with raspotify and i had the same result.

Do you have some ideas about?
Thanks

**Comment by feddevanderlist** [comment]
Do you have more details?
I can tell you that it works on my oneplus 6 with android 8.1.
Are you sure that you are connected to the same network?
