### ISSUE TITLE
[volparametriceq] Advanced Settings not Working

### ISSUE THREAD

**Issue by ereturn** [balbuze/volumio-plugins#188]
Advanced Settings slider is returning to "off" after saving and reloading, with no changes occurring.  Fresh install of the plugin does not fix the issue, nor does restarting Volumio after saving settings.

Running on Pi 3B+ with the latest version of volparametriceq (0.1.8, Aug 3rd) and version 2.389 of Volumio.

**Comment by ereturn** [comment]
Updating to the latest version of Volumio fixed the problem.

**Comment by balbuze** [comment]
The was probably due to the fact you have installed a previous version of the plugin.
