### ISSUE TITLE
spotconnect2 keeps crashing on one song

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#189]
I have one song on which librespot always crashes.

running volumio 2.444 I think with the lates spotconnect2 from the repo.
computer tells me this:
Sep 16 14:12:15 woonkamer volumio[963]: info: [SpConDebug] Token: BQBnwQJ6uWdkVZHQeHUpbg0PQgWLcJjcHOEKmmA4ietnG7U169iQw16ehqia3sFCqFvomAW50_r-7P0ghB9JVNzGqpYwguY5OGaI1c-9SnmOZCkH6C-S4sP-JT1fvXeluaeLgq_pxtg6LeMbX2M4V3fp5WsiDQsIjQX4o-jct4zm
Sep 16 14:12:15 woonkamer volumio[963]: info: [SpConDebug] Sink released
Sep 16 14:12:15 woonkamer volumio[27991]: INFO:librespot_playback::player: SpCon::metadata
Sep 16 14:12:15 woonkamer volumio[963]: info: [SpConDebug] Pushing metadata::Vollibrespot:true
Sep 16 14:12:15 woonkamer volumio[27991]: INFO:librespot_playback::player: Loading track "Sito To" with Spotify URI "spotify:track:4NYe98w8kYWN2BMhiUIuzq"
Sep 16 14:12:15 woonkamer volumio[27991]: INFO:librespot_playback::player: Normalisation Data: NormalisationData { track_gain_db: -8.540001, track_peak: 1.0076668, album_gain_db: -8.57, album_peak: 1.0315007 }
Sep 16 14:12:15 woonkamer volumio[27991]: INFO:librespot_playback::player: Applied normalisation factor: 0.37411055
Sep 16 14:12:16 woonkamer volumio[27991]: 6:   0x639aa3 - librespot_audio::fetch::AudioFileFetch::download::h06048639f5a47bfb
Sep 16 14:12:16 woonkamer volumio[27991]: 7:   0x639c1b - <librespot_audio::fetch::AudioFileFetch as futures::future::Future>::poll::h69775e117a951b61
Sep 16 14:12:16 woonkamer volumio[27991]: 17:   0x532c8b - librespot::main::h4fc393d3895496fd
Sep 16 14:12:16 woonkamer volumio[27991]: INFO:librespot_playback::player: Shutting down player thread ...

not sure if I should issue it here or at librespot repo itself..

thanks anyway...

Dennis

**Comment by balbuze** [comment]
I have to test this song... For info, we are working on a new version of the plugin, with a new version of librespot. The main new feature will be the  hardware mixer management.

**Comment by cortegedusage** [comment]
Ah new version, very interesting.
Is that only Hardware mixer or would There be any chance on software mixer
too?


Op zo 16 sep. 2018 16:41 schreef balbuze <notifications@github.com>:

**Comment by balbuze** [comment]
Yes, softvolume too!

**Comment by ashthespy** [comment]
Is this a repeatable error @cortegedusage ? Could you launch it with `--verbose` and obtain more detailed logs?

**Comment by cortegedusage** [comment]
@ashthespy 
if I run librespot on it's own from the command line it just runs and plays.
If I add -v to the volspotconnec2.tmpl and restart volspotconnect it crashes with this:
Sep 16 19:50:56 woonkamer volumio[963]: info: [SpConDebug] Session is active!
Sep 16 19:50:56 woonkamer volumio[963]: info: [SpConDebug] Currently active:webradio
Sep 16 19:50:56 woonkamer volumio[963]: info: [SpConDebug] Stopping currently active service
Sep 16 19:50:56 woonkamer volumio[963]: info: [SpConDebug] SpotConn Active
Sep 16 19:50:56 woonkamer volumio[963]: info: [SpConDebug] Currently active:webradio
Sep 16 19:50:56 woonkamer volumio[15299]: INFO:librespot_playback::player: SpCon::metadata
Sep 16 19:50:56 woonkamer volumio[15299]: DEBUG:librespot_connect::spirc: kMessageTypeNotify "Wileyfox Swift" 0c4de5a55b528f247a9caf7301931d617051d20a 1676649224 1537127456829
Sep 16 19:50:56 woonkamer volumio[963]: info: [SpConDebug] Token: BQAibcRLav4vP-ZXQeyaSjfZ2Z0mtHqp9jI7WLoasad3DPHkV_V6o9po-WRppwUKLz5wLYyxi0CV6KLSYbCsxuuyCfrKOImSUiWhIFdXJJQQFxbUFjaZW2ctiSMbcsXUekFnRBXt_3b4m1uozu70ZUMz7p3d01f0FcR8Xm29EOcV
Sep 16 19:50:56 woonkamer volumio[963]: info: [SpConDebug] Pushing metadata::Vollibrespot:true
Sep 16 19:50:56 woonkamer volumio[15299]: INFO:librespot_playback::player: Loading track "Sito To" with Spotify URI "spotify:track:4NYe98w8kYWN2BMhiUIuzq"
Sep 16 19:50:56 woonkamer volumio[15299]: DEBUG:librespot_core::audio_key: new AudioKeyManager
Sep 16 19:50:56 woonkamer volumio[15299]: DEBUG:librespot_audio::fetch: Downloading file 4310bb8d969082b6c2f64fb59de5d1871086a536
Sep 16 19:50:56 woonkamer volumio[15299]: TRACE:librespot_audio::fetch: requesting chunk 0
Sep 16 19:50:56 woonkamer volumio[15299]: DEBUG:librespot_core::channel: new ChannelManager
Sep 16 19:50:57 woonkamer volumio[15299]: TRACE:librespot_audio::fetch: chunk 0 / 74 complete
Sep 16 19:50:57 woonkamer volumio[15299]: TRACE:librespot_audio::fetch: requesting chunk 1
Sep 16 19:50:57 woonkamer volumio[15299]: INFO:librespot_playback::player: Normalisation Data: NormalisationData { track_gain_db: -8.540001, track_peak: 1.0076668, album_gain_db: -8.57, album_peak: 1.0315007 }
Sep 16 19:50:57 woonkamer volumio[15299]: INFO:librespot_playback::player: Applied normalisation factor: 0.37411055
Sep 16 19:50:57 woonkamer volumio[15299]: 6:   0x582aa3 - librespot_audio::fetch::AudioFileFetch::download::h06048639f5a47bfb
Sep 16 19:50:57 woonkamer volumio[15299]: 7:   0x582c1b - <librespot_audio::fetch::AudioFileFetch as futures::future::Future>::poll::h69775e117a951b61
Sep 16 19:50:57 woonkamer volumio[15299]: 17:   0x47bc8b - librespot::main::h4fc393d3895496fd
Sep 16 19:50:57 woonkamer volumio[15299]: DEBUG:librespot_connect::spirc: drop Spirc[0]
Sep 16 19:50:57 woonkamer volumio[15299]: INFO:librespot_playback::player: Shutting down player thread ...

Don't know what it says, but when i run it stand alone I get this
DEBUG:librespot_connect::spirc: kMessageTypeLoad "Wileyfox Swift" 0c4de5a55b528f247a9caf7301931d617051d20a 2 0
DEBUG:librespot_playback::player: command=Load(SpotifyId(u128!(209898050021955585563708664604202960940)), false, 42354)
INFO:librespot_playback::player: SpCon::kSpPlaybackNotifyBecameActive
INFO:librespot_playback::player: SpCon::token
INFO:librespot_playback::player: SpCon::metadata
INFO:librespot_playback::player: Loading track "Sito To" with Spotify URI "spotify:track:4NYe98w8kYWN2BMhiUIuzq"
DEBUG:librespot_core::audio_key: new AudioKeyManager
DEBUG:librespot_audio::fetch: Downloading file c77d06b2d0eac3effe582c0693413307efe6d2c9
TRACE:librespot_audio::fetch: requesting chunk 0
DEBUG:librespot_core::channel: new ChannelManager
TRACE:librespot_audio::fetch: chunk 0 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 1
TRACE:librespot_audio::fetch: chunk 1 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 2
TRACE:librespot_audio::fetch: requesting chunk 32
TRACE:librespot_audio::fetch: requesting chunk 31
TRACE:librespot_audio::fetch: chunk 31 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 32
TRACE:librespot_audio::fetch: requesting chunk 15
TRACE:librespot_audio::fetch: chunk 15 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 16
TRACE:librespot_audio::fetch: requesting chunk 7
TRACE:librespot_audio::fetch: chunk 7 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 8
TRACE:librespot_audio::fetch: requesting chunk 3
TRACE:librespot_audio::fetch: chunk 3 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 4
TRACE:librespot_audio::fetch: requesting chunk 5
TRACE:librespot_audio::fetch: chunk 5 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 6
TRACE:librespot_audio::fetch: requesting chunk 4
TRACE:librespot_audio::fetch: chunk 4 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 6
INFO:librespot_playback::player: Track "Sito To" loaded
INFO:librespot_playback::player: SpCon::EnteredStop
TRACE:librespot_audio::fetch: chunk 6 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 8
TRACE:librespot_audio::fetch: chunk 8 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 9
TRACE:librespot_audio::fetch: chunk 9 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 10
TRACE:librespot_audio::fetch: chunk 10 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 11
TRACE:librespot_audio::fetch: chunk 11 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 12
TRACE:librespot_audio::fetch: chunk 12 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 13
DEBUG:librespot_connect::spirc: kMessageTypePause "webapi-f5b77cf902904d008cf32c898bb0a707" webapi-f5b77cf902904d008cf32c898bb0a707 1676901125 0
TRACE:librespot_audio::fetch: chunk 13 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 14
TRACE:librespot_audio::fetch: chunk 14 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 16
TRACE:librespot_audio::fetch: chunk 16 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 17
TRACE:librespot_audio::fetch: chunk 17 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 18
TRACE:librespot_audio::fetch: chunk 18 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 19
TRACE:librespot_audio::fetch: chunk 19 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 20
TRACE:librespot_audio::fetch: chunk 20 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 21
TRACE:librespot_audio::fetch: chunk 21 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 22
TRACE:librespot_audio::fetch: chunk 22 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 23
TRACE:librespot_audio::fetch: chunk 23 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 24
TRACE:librespot_audio::fetch: chunk 24 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 25
TRACE:librespot_audio::fetch: chunk 25 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 26
TRACE:librespot_audio::fetch: chunk 26 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 27
TRACE:librespot_audio::fetch: chunk 27 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 28
TRACE:librespot_audio::fetch: chunk 28 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 29
TRACE:librespot_audio::fetch: chunk 29 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 30
TRACE:librespot_audio::fetch: chunk 30 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 32
TRACE:librespot_audio::fetch: chunk 32 / 33 complete
TRACE:librespot_audio::fetch: requesting chunk 2
TRACE:librespot_audio::fetch: chunk 2 / 33 complete
DEBUG:librespot_audio::fetch: File c77d06b2d0eac3effe582c0693413307efe6d2c9 complete
DEBUG:librespot_connect::spirc: kMessageTypePlay "Wileyfox Swift" 0c4de5a55b528f247a9caf7301931d617051d20a 3 0
DEBUG:librespot_playback::player: command=Play
INFO:librespot_playback::player: SpCon::kSpDeviceActive
INFO:librespot_playback::player: SpCon::kSpSinkActive
DEBUG:librespot_connect::spirc: kMessageTypePause "Wileyfox Swift" 0c4de5a55b528f247a9caf7301931d617051d20a 4 0
DEBUG:librespot_playback::player: command=Pause
INFO:librespot_playback::player: SpCon::kSpDeviceInactive
INFO:librespot_playback::player: SpCon::kSpSinkInactive
DEBUG:librespot_connect::spirc: kMessageTypePause "webapi-f5b77cf902904d008cf32c898bb0a707" webapi-f5b77cf902904d008cf32c898bb0a707 1676927054 0

which is what you'd expect I guess...

cheers!

**Comment by ashthespy** [comment]
From what I understood - that same binary, when launched from `startconnect.sh` panics,  but when started directly from the command line is fine?  But then that would mean that your not running it with the same flags as in the `startconnect.sh` script correct?

**Comment by cortegedusage** [comment]
you are right.
starting it with that flags makes it crash..
DEBUG:librespot_connect::spirc: kMessageTypeLoad "Wileyfox Swift" 0c4de5a55b528f247a9caf7301931d617051d20a 2 0
DEBUG:librespot_playback::player: command=Load(SpotifyId(u128!(209898050021955585563708664604202960940)), false, 1977)
INFO:librespot_playback::player: SpCon::kSpPlaybackNotifyBecameActive
INFO:librespot_playback::player: SpCon::token
DEBUG:librespot_connect::spirc: kMessageTypeNotify "Wileyfox Swift" 0c4de5a55b528f247a9caf7301931d617051d20a 1765387066 1537216194671
INFO:librespot_playback::player: SpCon::metadata
INFO:librespot_playback::player: Loading track "Sito To" with Spotify URI "spotify:track:4NYe98w8kYWN2BMhiUIuzq"
DEBUG:librespot_core::audio_key: new AudioKeyManager
DEBUG:librespot_audio::fetch: Downloading file 4310bb8d969082b6c2f64fb59de5d1871086a536
TRACE:librespot_audio::fetch: requesting chunk 0
DEBUG:librespot_core::channel: new ChannelManager
DEBUG:librespot_connect::spirc: kMessageTypeNotify "Wileyfox Swift" 0c4de5a55b528f247a9caf7301931d617051d20a 1765387191 1537216194796
TRACE:librespot_audio::fetch: chunk 0 / 74 complete
TRACE:librespot_audio::fetch: requesting chunk 1
INFO:librespot_playback::player: Normalisation Data: NormalisationData { track_gain_db: -8.540001, track_peak: 1.0076668, album_gain_db: -8.57, album_peak: 1.0315007 }
INFO:librespot_playback::player: Applied normalisation factor: 0.37411055
TRACE:librespot_audio::fetch: chunk 1 / 74 complete
TRACE:librespot_audio::fetch: requesting chunk 2
thread 'main' panicked at 'assertion failed: new_index < self.shared.chunk_count', audio/src/fetch.rs:232:9
stack backtrace:
   0:   0x9bb13f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h280c621ec0336843
                       at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:   0x9c549f - std::sys_common::backtrace::print::h5bb167d48668dac9
                       at /checkout/src/libstd/sys_common/backtrace.rs:68
                       at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:   0x9b39c7 - std::panicking::default_hook::{{closure}}::hccf3b2e1cc48596f
                       at /checkout/src/libstd/panicking.rs:381
   3:   0x9b34a3 - std::panicking::default_hook::h338b1189515ccc69
                       at /checkout/src/libstd/panicking.rs:397
   4:   0x9b3e73 - std::panicking::rust_panic_with_hook::h5d950fb4a856fba5
                       at /checkout/src/libstd/panicking.rs:577
   5:   0x60875b - std::panicking::begin_panic::ha26d1eaefd276c66
   6:   0x606aa3 - librespot_audio::fetch::AudioFileFetch::download::h06048639f5a47bfb
   7:   0x606c1b - <librespot_audio::fetch::AudioFileFetch as futures::future::Future>::poll::h69775e117a951b61
   8:   0x9682b3 - <futures::task_impl::Spawn<T>>::poll_future_notify::h6fe3530f2f67f8a5
   9:   0x9673ef - <std::thread::local::LocalKey<T>>::with::h5df8b425f55682a1
  10:   0x96313f - <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::h499bca6cd3e132fa
  11:   0x96cc77 - <scoped_tls::ScopedKey<T>>::set::hbb222b4ab40fc883
  12:   0x967a37 - <std::thread::local::LocalKey<T>>::with::hb27572acc20ed0d2
  13:   0x967f6b - <std::thread::local::LocalKey<T>>::with::hb4bb07cc84c796b9
  14:   0x96762b - <std::thread::local::LocalKey<T>>::with::h81fb88fea251b38c
  15:   0x963c83 - tokio_core::reactor::Core::poll::hd1ae9ec193b91eae
  16:   0x4e7a9f - tokio_core::reactor::Core::run::h63abb1361e8308ab
  17:   0x4ffc8b - librespot::main::h4fc393d3895496fd
  18:   0x4e8def - std::rt::lang_start::{{closure}}::h10d05b1747dc8be9
  19:   0x9b3b1b - std::panicking::try::do_call::h9cb586bd57bb9d3d
                       at /checkout/src/libstd/rt.rs:59
                       at /checkout/src/libstd/panicking.rs:480
  20:   0x9da99b - __rust_maybe_catch_panic
                       at /checkout/src/libpanic_unwind/lib.rs:101
  21:   0x9badcb - std::rt::lang_start_internal::h104139376fdb9ead
                       at /checkout/src/libstd/panicking.rs:459
                       at /checkout/src/libstd/panic.rs:365
                       at /checkout/src/libstd/rt.rs:58
  22:   0x500733 - main
  23: 0x76cea293 - __libc_start_main
DEBUG:librespot_connect::spirc: drop Spirc[0]
INFO:librespot_playback::player: Shutting down player thread ...

**Comment by cortegedusage** [comment]
you are right sir.. I didn't use the same flags, my fault...
I removed them one by one. and guess what, when I remove the -b 320 flag there is no problem and it plays.... so apparently there is no 320 available. and it crashes librespot. 
Unfortunately Librespot doesn't crash, but hangs....

What is the default quality when -b flag is not passed on?

**Comment by ashthespy** [comment]
160 is the default when no bitrate is passed. 

It looks like even though the servers indicate that the appropriate fileID exists: 
`spotify:track:4NYe98w8kYWN2BMhiUIuzq`
`FileFormat::OGG_VORBIS_320` -- `FileId("4310bb8d969082b6c2f64fb59de5d1871086a536")`

There seems to be some issue with downloading the file chunks - the [`assert!(new_index < self.shared.chunk_count);`](https://github.com/librespot-org/librespot/blob/431be9e847a584d374ec44e7c138525dd8fbb9d6/audio/src/fetch.rs#L232) panics and exits. 

I will have to investigate further.

**Comment by paulohoppe** [comment]
,.

Em sex, 1 de mar de 2019 17:47, balbuze <notifications@github.com> escreveu:
