### ISSUE TITLE
RPi 3, IQAudioDAC

### ISSUE THREAD

**Issue by bartberden** [balbuze/volumio-plugins#19]
Hey there!

First of all, awesome plugin! It seems I'm having some issues with volume scaling.. If i put the slider  at 50% or below, I hear almost nothing. 

See some volume comparisons:
Spotify volume: 50%, Alsamixer volume:14%
Spotify volume: 75%, Alsamixer: 35%

Any idea how to solve this?

**Comment by balbuze** [comment]
It's right volumes are not aligned. The only thing you can do is to remove --dbrange 45 from volspotconnect.tmpl and save the setting of the plugin. You can also change the value "45" by a other and made test to see if it's better for you. Let me know.

**Comment by bartberden** [comment]
I assume this file is located in the v2 version? If so, there isn't a reference of --dbrange in the file..

**Comment by balbuze** [comment]
Sorry I was not clear. This is for volspotconnect 1. It  is located in /data/plugins/music_service/volspotconnect/volspotconnect.tmpl . Volspotconnect 2 is not ready...I'm just trying to make a other plugin using a open source lib.

**Comment by bartberden** [comment]
I removed the dbrange from the template file, but the scaling still doesnt seem to work properly. I found this topic which has the same issue, and a fix by setting amixer with the parameter -M. (https://volumio.org/forum/hardware-volume-control-iqaudio-dac-t1642.html) Is there any way to include this fix?
