### ISSUE TITLE
combine equaliser and stereo2mono plugins

### ISSUE THREAD

**Issue by cgtobi** [balbuze/volumio-plugins#190]
Hi, 

apparently they can't be used together. Is it planned to integrate the stereo2mono feature into one of the equalizers?

Cheers,
cgtobi

**Comment by balbuze** [comment]
are you familiar with shh? If yes I can provide a asound.conf file that will add mono output to the equalizer...

**Comment by cgtobi** [comment]
Sure, ssh is not a problem.
balbuze <notifications@github.com> schrieb am Di. 18. Sep. 2018 um 18:46:

**Comment by hacs-atome** [comment]
Hi,

Would you mind to share the configuration ? I've been trying to get stereo2mono and volsimpleequal to work together for days now and it's driving me crazy.

**Comment by balbuze** [comment]
Jump to volumio3 and install FusionDsp ;-)
