### ISSUE TITLE
"More songs load as you listen" not loading more songs

### ISSUE THREAD

**Issue by willthomson** [balbuze/volumio-plugins#192]
The following post suggests it's a problem with the way Spotify Connect is implemented.

https://community.spotify.com/t5/Android/Artist-Radio-More-Songs-DON-T-Load-as-You-Listen/m-p/1476640#M68103

To load more songs I need to disconnect from Spotify Connect, play the last track in the list and then connect to Spotify Connect again.

**Comment by ashthespy** [comment]
Yep, we haven't implemented context in `librespot` yet. You can track the progress at https://github.com/librespot-org/librespot/issues/57

**Comment by ashthespy** [comment]
@willthomson was on the other thread and was reminded of this one.
Headsup - the version of the plugin based on `vollibrespot` has support for this (aka dynamic playlists) implemented :-)
