### ISSUE TITLE
[brutefir3] Presets

### ISSUE THREAD

**Issue by fumok** [balbuze/volumio-plugins#195]
Thanks alot for this awesome plugin.
I think it would be very useful use of presets to quickly change the filters.

**Comment by balbuze** [comment]
Thanks! Are you talking about volparametrieq?

**Comment by fumok** [comment]
My fault, I'm talking about brutefir3 (v 0.6.5).
I'm very new to drc, and would be very useful switch from different filters sets (including freqs and filters lenght).

**Comment by balbuze** [comment]
It's a idea.
Btw, how do you use the plugin? What hardware? How did you make measures? I'm interested in your feedback. Thanks.

**Comment by fumok** [comment]
I'm very new to drc, so I think I've little to say.

I use a PI3 B with a Topping D50 DAC. For measurements I connect direct to my laptop the D50 and UMIK-1, then with REW I do an RTA analisys in different zones. Now I'm trying different house curves (B&K,  EBU-Tech 3276, Olive). 

I've tryed some sweep measurement, but what a mess with delays and reverbarations, my listening room (living area) is terrible. Maybe better not to know :-). Anyway for now RTA analisys gave me betters results.

If you want other details please ask.

**Comment by balbuze** [comment]
We are working to propose tools and methods to make mmm "moving microphone measurement". We'll add some tools in the plugin and a wiki to explain. What do you think of the last version of the online help? Is it clear enough? Helpful? Or not useful for you?

**Comment by merlin2222** [comment]
> My fault, I'm talking about brutefir3 (v 0.6.5).
> I'm very new to drc, and would be very useful switch from different filters sets (including freqs and filters lenght).

I don't really think it is necessary. Once you choose sample rate you are not likely to change it. For sample rate 96000 it is recommended you use 65536 taps in rePhase. With sample rate 44100 it is sufficient you use 16384  taps. In BruteFIR set filter size to the same value as number of taps you're using. With RPI 3B you might want to set sample rate to 44100 to reduce the chances to get clicking sounds, which is a common problem when using RPI with USB DAC.

Regarding the measurement method - you don't need to connect D50 directly to your laptop. You can have it connected to Volumio and use sweep files with embedded timing reference signal with REW. It is described in the help section.

Read more about moving microphone method (implemented via RTA in REW) here: http://www.ohl.to/audio/downloads/MMM-moving-mic-measurement.pdf
When moving mic try to cover area around your head (in all 3 directions) starting at your listening position. Set smoothing to 1/12 and export measurement as text so you can work with it in rePhase.

MMM (or RTA as called in REW) is reliable up to app 600Hz, and that is anywway the area where most of the problems are. For the freqs above 600Hz you should use single point time (at your listening position) time gated sweep measurement.

**Comment by merlin2222** [comment]
> I've tryed some sweep measurement, but what a mess with delays and reverbarations, my listening room (living area) is terrible. Maybe better not to know :-). Anyway for now RTA analisys gave me betters results.

Try to make at least 5 sweep measurement around your head at your listening position with REW. Average those responses under All SPL tab and apply 1/12 smoothing on the averaged response. If you do everything right you should get a response that is very similar to RTA response.

**Comment by fumok** [comment]
@merlin2222 thanks a lot for good suggestions. I already saw the pdf you linked, but it will take me some time to fully understand most of the information.

By the way, are these settings right for MMM in REW?

![mmm-rec](https://user-images.githubusercontent.com/20909133/48401742-1e6e7c00-e72a-11e8-96f3-af4eede50d1e.jpeg)

**Comment by merlin2222** [comment]
Yes, these settings are fine.

[Dirac Live measurement positions.docx](https://github.com/balbuze/volumio-plugins/files/2575898/Dirac.Live.measurement.positions.docx)

These are measurement points as suggested by DiracLive. You can use them as your MMM points - start from central position, move slowly with constant speed (app 20cm/sec) toward next positions as if you were to draw a line between them. Finish at central position.

You can also sue them as your sweep measruement points. After making measurements average them and apply 1/12 smoothing. Export that file as text so you can use it in rePhase.

**Comment by merlin2222** [comment]
I must say clearly here that I didnn't find RPI to be reliable HW platform with USB DACs. RPI has some issue with the way USB is connected to the networking controller which will cause occasional clicking noises when BruteFIR is used. Those clicking noises will be more frequent with higher sampling rate and when you listen music from NAS vs when you listen Internet radio (as there is more network traffic in that case).

For best results with Volumio and BruteFIR I recommend sampling rate of 96000 and 65536 filtersize/taps.

When doing EQ in rePhase try to follow these simple guidelines:

- avoid high Q corrections as much as you can
- remember that dips are not as hearable as rises, so flatten the rise points but avoid to flatten dips unless they are deeper than -try to dB
- avoid high gains as much as you can. Don't go over +18dB, even better if you can stay bellow +12dB
- there is an initial 6dB attenuation in BruteFIR. If your max filter is (for example) set to +16dB then set additional 10dB of attenuation in BruteFIR settings to avoid clipping
- measure carefully! your correction will only be good as was your measurement. Repat measurements unless you have good correlation between MMM (RTA) and sweep measurements (make at least 5 of them and average them).
- remember that Room EQ is not an exact science, so may the Force be with you. ;)

**Comment by merlin2222** [comment]
When using these sweep files set REW to "Use acoustic timing reference" and check "Wait for timing reference" box. Then press Start measureing and wait until you see "Waiting for timing reference" message. At that moment start playing the file via Kinsky, BubbleUPnP or BruteFIR interface. The measurement will begin after the timing reference signal is played by the speakers.

Sweep files:
https://www.dropbox.com/preview/Public/000/LogSweep_LEFT_16_48.wav?role=personal
https://www.dropbox.com/preview/Public/000/LogSweep_RIGHT_16_48.wav?role=personal
https://www.dropbox.com/preview/Public/000/LogSweep_BOTH_16_48.wav?role=personal

When doing RTA (MMM), start playing these files, press record in RTA window and start slowly moving your mic.

Pink noise files for RTA (MMM):
https://www.dropbox.com/preview/Public/000/PinkNoise_48k_16-bit_L.wav?role=personal
https://www.dropbox.com/preview/Public/000/PinkNoise_48k_16-bit_R.wav?role=personal
https://www.dropbox.com/preview/Public/000/PinkNoise_48k_16-bit_BOTH.wav?role=personal

**Comment by balbuze** [comment]
For info, sweep files and pink noise files file available and playable directly in the plugin. Just press 'install tools, wait until the webUi is refreshed and you'll find them in the new webUi of the plugin.

**Comment by merlin2222** [comment]
Oh, nice! I'll add a post on Github.

**Comment by merlin2222** [comment]
Nice! :)

**Comment by merlin2222** [comment]
This mic is cheaper alternative to UMIK-1. It works equally well and comes with calibration file. As it is small it is well suited for MMM but be sure to buy a 4-pole extension cable like this one:
https://www.ebay.co.uk/itm/3M-WHITE-Slim-4-Pole-Pin-3-5mm-Headphone-Mic-EXTENSION-Stereo-Phone-Cable/362164951906?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649
