### ISSUE TITLE
Autoswitching brutefir config files according to current track sampling rate

### ISSUE THREAD

**Issue by klapaciuss** [balbuze/volumio-plugins#196]
Hello.

I am using DRC filters according to my own meassurement. I am used to using brutefir with filters defined via raw PCM files filter definition on standard Linux Debian with MPD. 

Has your plugin for Volumio possibility to autoswitch brutefir config file according to current track sampling rate? For different sampling rates is needes special brutefir config files with right filter definition and it is annoying to switch it manually.

Thanks for answer in advanced.

Regards.

Marek

**Comment by klapaciuss** [comment]
Hello.

Thanks for reply. I tried brutefir3. It seems that pcm raw files are not supported for filter definition in your plugin (standard brutefir supports it). Is it true? It would be bad news for me as rephase limits filters to 17 bands max. My filters are more complex.

Regards.

Marek

**Comment by balbuze** [comment]
yes, the plugin only supports .txt filter (32/64 bits floats lines).
But you can set in the file called brutefir.conf.tmpl an other format (line 22 and 36). 
You find it : /data/plugins/audio_interface/brutefir
Save the file. Of course, select a format supported by brutefir (https://www.ludd.ltu.se/~torger/brutefir.html#config_4)
Now choose your filter in the plugin.
let me know.

**Comment by balbuze** [comment]
But rephase is not limited to 17 bands! it can handles 17*16 bands. Just use bank selector(left of the equalizer)

**Comment by balbuze** [comment]
The output is misconfiguration. Disable the plugin, and set the correct output and mixer in volumio. Reboot. Enable the Plugin. Don't try to change anything in volumio playback!. Try to play a track.
What is your hardware?

**Comment by klapaciuss** [comment]
Hello. After steps according to your recommendation brutefir is working on selected sample rate (currently 44.1kHz). I tried to enable resampling on Volumio after that (conversion to brutefir target sample rate) but after enabling sample rate conversion nothing was played despite of source track sampling frequency.  After sample rate conversion switching off all is working OK with brutefir (with 44.1kHz sampling rate tracks).

**Comment by balbuze** [comment]
Don't enable Resampling in volumio. Just set in brutefir the same sample rate than your filters. If you want to output at 96khz set it in brutefir with the appropriate filter. Everything played in volumio will be resampled according to that

**Comment by balbuze** [comment]
Hi, no way to autoswitch filters. 88.2khz is a available sample rate in the plugin.
