### ISSUE TITLE
Volumio does not play

### ISSUE THREAD

**Issue by AirTobe91** [balbuze/volumio-plugins#198]
Hey,
I got the problem, that Spotify Connect isn't working well.
I got a Raspberry PI 3B+ with a Hifiberry AMP2.
Internet Radio and everything else works nicely.
I installed the VolSpotConnect2 plugin, take my Samsung Galaxy S7, starting a Song on my phone and then switch it to my Volumio Device, like I normally doing it with Spotify Connect devices.
So I find the Volumio device in my Spotify App on the phone, and the display which is connected to my Volumio device shows that it is playing the song, but it doesn't play the song. One other thing I found is, that the time line is not in sync. So my phone shows 0:15min and when I switch the song to Volumio, it starts at 0:00min.
Do you maybe have a explanation or solution for that?
Thanks.

**Comment by AirTobe91** [comment]
The Volumio Simple Equalizer is installed.

**Comment by balbuze** [comment]
Ok. Do you use the official volspotconnect2 plugin or the device version from my repo?
