### ISSUE TITLE
Not possible to activate plugin 

### ISSUE THREAD

**Issue by Istvan1976** [balbuze/volumio-plugins#199]
Installation is ok. But pressing switch button at Installed Plugins >> Brutefir for Volumio: ON/OFF displays the following red message; "this plugin is failing to start, please install updated version or contact developer" plus no settings page to modify settings.

It is the today, latest version installed with instructions written here (installation was ok, no error message). Volumio version is the latest 2.513

**Comment by balbuze** [comment]
sorry... It should be solved now. Let  me know ;-)

**Comment by Istvan1976** [comment]
Hello Balbuze,

Many thanks to take care on this over the weekend... now activate button works well, thank you.
