### ISSUE TITLE
Installation Error RPi 2. Volumio 2.016

### ISSUE THREAD

**Issue by chsims1** [balbuze/volumio-plugins#2]
Installed without problems on earlier volumio/spotifyconnect versions. Fails with:

`Installing dependencies
The folowing error occurred when installing the plugin: Error`

Multiple installation attempts and reboots has no effect.

Also, on a very minor note, check the spelling error in the error message ("folowing" should be "following."

**Comment by balbuze** [comment]
Don't know for 2.016 but I just test it with 2.018 and no problem. You can update.
For the typo error, it does not come from plugin but from volumio itself! but thank you reporting it!
A other point, you to be connected to internet to install this plugin as a file is downloaded from Volumio server.
Let me know

**Comment by chsims1** [comment]
Same problem with 2.018. From the journalctl log it appears that there is a permissions problem when your install script runs.  Changing the root and user password back to the default 'volumio' ones, the plugin installs fine.

**Comment by balbuze** [comment]
Good ! So you had changed default password value ?

**Comment by chsims1** [comment]
Yes, that was what was causing the problem.
