### ISSUE TITLE
volspotconnect - startup fails when using special chars in password 

### ISSUE THREAD

**Issue by petternorman** [balbuze/volumio-plugins#20]
I couldn't get volspotconnect to start so I debugged the device through ssh and it turned out that some special chars I use in my spotify password causes the error. 
Examples in this case < and >.

**Comment by balbuze** [comment]
Thanks for the PR. Could please give me a sample of problematic password? .I have no doubt of what you wrote but I need to understand.

**Comment by petternorman** [comment]
Yes of course. 
Example password: Spotify>|<password
_It's a made up password so dont even try, future internet user._
The problem was either the >, | or <. All of them have special usages in a command shell as i understand it. 
Note that the "|" isn't an uppercase i but a vertical bar.

**Comment by balbuze** [comment]
PR merged
