### ISSUE TITLE
Connect for free account

### ISSUE THREAD

**Issue by cjvanzwol** [balbuze/volumio-plugins#202]
Spotify released  new SDK (so the news told me). In this new SDK it is possible te give connect functionality to free accounts. Is there an update planned in which this is being implemented?

**Comment by ashthespy** [comment]
Nope - the SDK isn't open-source from what I understood.
And our current backend doesn't implement playback for ads - which would be required and is quite low in my priority list to be honest.

**Comment by cjvanzwol** [comment]
Ok, that is clear. Thanks for the update.
