### ISSUE TITLE
[brutefir3] Timing reference signal should play on same speaker

### ISSUE THREAD

**Issue by bjornarsu** [balbuze/volumio-plugins#203]
Make acoustic timing reference sound  in same speaker during sweep playback regardless of which channel is being tested. In the current version it's sounded in the same speaker as the sweep is being played back on, AFAIK making it impossible to measure the impulse response delay between speakers.

E.g. the timing reference part preceding the sweep should always play in the left speaker regardless if it's the left or right speaker playing back the sweep.

Does that make sense? :)

**Comment by balbuze** [comment]
Delay is managed by the room settings option in the plugin. To make it easyer to use, instead of giving a time value, a distance in cm is given, and then a delay is calculated. It should be enough, no?

**Comment by merlin2222** [comment]
> Make acoustic timing reference sound in same speaker during sweep playback regardless of which channel is being tested. In the current version it's sounded in the same speaker as the sweep is being played back on, AFAIK making it impossible to measure the impulse response delay between speakers.
> 
> E.g. the timing reference part preceding the sweep should always play in the left speaker regardless if it's the left or right speaker playing back the sweep.
> 
> Does that make sense? :)

Yes, it does make sense. Measurement log sweep files with timing reference signal coming from right speaker will be included in the next release. In the meantime, you can generate such sweep files with REW by yourself. ;)

**Comment by balbuze** [comment]
The new version 0.7.7 includes now sweep files with time reference on right channel. Hope it will fine for you. Thanks you merlin2222 ;-)

**Comment by merlin2222** [comment]
My pleasure, Sir! :)

**Comment by merlin2222** [comment]
Btw, have you considered implementing automatic update procedure, like the one Volumio has? :)

**Comment by balbuze** [comment]
Automatic updates will work when the plugin will be "official". But as long it is a dev version, update is made by hand.

**Comment by merlin2222** [comment]
Aaa, ok! :)
