### ISSUE TITLE
Initial volume setting not stored

### ISSUE THREAD

**Issue by fuzzybear62** [balbuze/volumio-plugins#204]
Hi, It seems that the initial volume value is not stored after save

**Comment by ashthespy** [comment]
If this if about volspotconnect2, then yes - it will use the last volume of the system when it starts playing via a connect session.

**Comment by fuzzybear62** [comment]
Sorry for not specify that is related to volspotconnect 2 last version on github. 
When you go to the plugin settings and choose the initial volume with the slider and than save, no errors, but if you exit and entry again in the plugin setting it retains the old value.
I'm using the latest version of volumio 2.522 on a RPI 3 with HIFYBERRY DAC Plus and hardware as mixer. Switching plugin to the one available with volumio plugins interface it works well

**Comment by ashthespy** [comment]
This `initial volume` setting in the menu is now redundant (except in the case of no mixer I'd reckon). With the latest version, you no longer need the `initial volume` setting - the daemon directly interfaces with `alsa` and will use the last volume from Volumio when starting a Spotify Connect session.
The `initial volume` flag can still be used - but it will just change the volume of Volumio (similar to the default startup volume) when the plugin initialises on boot. 

If I am not mistaken, this already happens - on bootup, the default volume of the entire system will reset to 30%.

**Comment by ashthespy** [comment]
Yep, so now if you change volume from the Spotify App, you are directly changing the Volumio volume.
To get rid of the old 33%, initial volume, you can always edit `--initial-volume ${initvol}` in the `volspotconnect2.tmpl` file and remove or change it to 80% in your case.

**Comment by fuzzybear62** [comment]
Got it. Thank you for the precise and quick answer
