### ISSUE TITLE
[volspotconnect2] Address already in use

### ISSUE THREAD

**Issue by bartcho** [balbuze/volumio-plugins#205]
RP 2

After few hours of idle, when trying to connect:

> Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_connect::discovery: Post "/" {}
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_connect::spirc: drop Spirc[2]
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_playback::player: Shutting down player thread ...
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_playback::player: drop Player[2]
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] : Connecting to AP "gew1-accesspoint-b-fl0z.ap.spotify.com:4070"
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] : Authenticated as "loginName" !
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_core::session: new Session[3]
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] : Setting up new mixer: card:hw:1 mixer:Digital index:0
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] : Alsa min: 0 (MilliBel(-9999999)[dB]) -- max: 207 (MilliBel(0)[dB]) HW: true
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_connect::spirc: new Spirc[3]
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_core::mercury: new MercuryManager
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_playback::player: new Player[3]
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] : Using alsa sink
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] librespot_connect::spirc: linear volume: 65535
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] : Current alsa volume: 207[i64] MilliBel(0)
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] : Mapping volume [100.000%] 65535 [u16] ->> Alsa [0.000%] 0 [dB]
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] vollibrespot::meta_pipe: Shutting down MetaPipe thread ...
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] vollibrespot::meta_pipe: Starting new MetaPipe[3]
Jan 09 09:25:47 volumio volumio[16083]: thread '<unnamed>' panicked at 'Error starting Metadata pipe: : Os { code: 98, kind: AddrInUse, message: "Address already in use" }', libcore/result.rs:1009:5
Jan 09 09:25:47 volumio volumio[16083]: stack backtrace:
Jan 09 09:25:47 volumio volumio[16083]: 0:   0x9adf97 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h3608b871673a8803
Jan 09 09:25:47 volumio volumio[16083]: at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Jan 09 09:25:47 volumio volumio[16083]: 1:   0x99d88f - std::sys_common::backtrace::print::hef947be8cf8e8f55
Jan 09 09:25:47 volumio volumio[16083]: at libstd/sys_common/backtrace.rs:71
Jan 09 09:25:47 volumio volumio[16083]: at libstd/sys_common/backtrace.rs:59
Jan 09 09:25:47 volumio volumio[16083]: 2:   0x99b3cb - std::panicking::default_hook::{{closure}}::haac47ed356699ffe
Jan 09 09:25:47 volumio volumio[16083]: at libstd/panicking.rs:211
Jan 09 09:25:47 volumio volumio[16083]: 3:   0x99b043 - std::panicking::default_hook::h95ba73384225983b
Jan 09 09:25:47 volumio volumio[16083]: at libstd/panicking.rs:227
Jan 09 09:25:47 volumio volumio[16083]: 4:   0x99baf3 - std::panicking::rust_panic_with_hook::ha1106c0ce43cea72
Jan 09 09:25:47 volumio volumio[16083]: at libstd/panicking.rs:477
Jan 09 09:25:47 volumio volumio[16083]: 5:   0x99b6b7 - std::panicking::continue_panic_fmt::h875c7946721c05c9
Jan 09 09:25:47 volumio volumio[16083]: at libstd/panicking.rs:391
Jan 09 09:25:47 volumio volumio[16083]: 6:   0x99b59f - rust_begin_unwind
Jan 09 09:25:47 volumio volumio[16083]: at libstd/panicking.rs:326
Jan 09 09:25:47 volumio volumio[16083]: 7:   0x9ebe8b - core::panicking::panic_fmt::h429a06507aba9228
Jan 09 09:25:47 volumio volumio[16083]: at libcore/panicking.rs:77
Jan 09 09:25:47 volumio volumio[16083]: 8:   0x4fa6e3 - core::result::unwrap_failed::hf50c9885e9663b30
Jan 09 09:25:47 volumio volumio[16083]: 9:   0x4e1437 - vollibrespot::meta_pipe::MetaPipeThread::run::h3128b8650559db06
Jan 09 09:25:47 volumio volumio[16083]: 10:   0x4f5d83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h912d4703b4899cb9
Jan 09 09:25:47 volumio volumio[16083]: 11:   0x4ee73f - std::panicking::try::do_call::h982a3bb7e26ea884
Jan 09 09:25:47 volumio volumio[16083]: 12:   0x9b6f57 - __rust_maybe_catch_panic
Jan 09 09:25:47 volumio volumio[16083]: at libpanic_unwind/lib.rs:103
Jan 09 09:25:47 volumio volumio[16083]: 13:   0x50152f - <F as alloc::boxed::FnBox<A>>::call_box::h58cacb42b6374723
Jan 09 09:25:47 volumio volumio[16083]: 14:   0x99a687 - std::sys_common::thread::start_thread::hd1b180dd2fa4010c
Jan 09 09:25:47 volumio volumio[16083]: at liballoc/boxed.rs:656
Jan 09 09:25:47 volumio volumio[16083]: at libstd/sys_common/thread.rs:24
Jan 09 09:25:47 volumio volumio[16083]: 15:   0x99d223 - std::sys::unix::thread::Thread::new::thread_start::h63a610b507ecb711
Jan 09 09:25:47 volumio volumio[16083]: at libstd/sys/unix/thread.rs:90
Jan 09 09:25:47 volumio volumio[16083]: [Vollibrespot] vollibrespot::meta_pipe: drop MetaPipeThread[3]

It keeps repeating, service restart is needed, any suggestions?

**Comment by ashthespy** [comment]
Hmm this happens when a session is dropped, and is reconnected. I need to make it handle session reconnects more gracefully. Have some rough drafts, will polish it up and fix it soon.
