### ISSUE TITLE
Plugin broken on 10th January 2019?

### ISSUE THREAD

**Issue by by81** [balbuze/volumio-plugins#206]
Hi there,

is the plugin broken due to Spotify changes today?

I get an "Cannot play at the moment" ("Kann zurzeit nicht abgespielt werden" in my german version).

I have the 0.8.2 installed!

Can you help?

Thank you

Greets
Daniel

**Comment by balbuze** [comment]
Humm... No problem for me (from France). Maybe a temporary issue from Spotify server? Does it work with the official client? Have you tried other tracks?

**Comment by by81** [comment]
No, xBox One Spotify Connect seams also broken here. And (also it's not a common way to do that) I cannot do Spotify Connect from one mobile phone to the other.

**Comment by by81** [comment]
Absolutely NOTHING! Spotify connects with some luck to Volumio but no sound at all!

**Comment by ashthespy** [comment]
@by81 Can you share some logs?
```
# Daemon logs
sudo journalctl -u volspotconnect2.service
```

**Comment by by81** [comment]
`-- Logs begin at Thu 2019-01-10 21:05:23 UTC, end at Thu 2019-01-10 21:07:18 UTC
Jan 10 21:06:14 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Jan 10 21:06:14 volumio systemd[1]: Started Volspotconnect2 Daemon.
Jan 10 21:06:14 volumio volumio[1162]: vollibrespot v0.1.2 edd446b 2018-11-24 (l
Jan 10 21:06:14 volumio volumio[1162]: [Vollibrespot] : Failed to register IPv6 
Jan 10 21:06:29 volumio volumio[1162]: [Vollibrespot] : Connecting to AP "gew1-a
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Authenticated as "112188
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Using alsa sink
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Country: "DE"
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Metadata pipe establishe
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : SessionActive!
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Loading track "Una Matti
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Track "Una Mattina" load
Jan 10 21:06:30 volumio volumio[1162]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdat
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Alsa error PCM open ALSA
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Could not start audio: A
Jan 10 21:06:30 volumio volumio[1162]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdat
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Alsa error PCM open ALSA
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Could not start audio: A
Jan 10 21:06:35 volumio volumio[1162]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdat
Jan 10 21:06:35 volumio volumio[1162]: [Vollibrespot] : Alsa error PCM open ALSA
Jan 10 21:06:35 volumio volumio[1162]: [Vollibrespot] : Could not start audio: A
Jan 10 21:06:40 volumio volumio[1162]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdat
lines 1-23...skipping...
-- Logs begin at Thu 2019-01-10 21:05:23 UTC, end at Thu 2019-01-10 21:07:18 UTC. 
Jan 10 21:06:14 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Jan 10 21:06:14 volumio systemd[1]: Started Volspotconnect2 Daemon.
Jan 10 21:06:14 volumio volumio[1162]: vollibrespot v0.1.2 edd446b 2018-11-24 (lib
Jan 10 21:06:14 volumio volumio[1162]: [Vollibrespot] : Failed to register IPv6 re
Jan 10 21:06:29 volumio volumio[1162]: [Vollibrespot] : Connecting to AP "gew1-acc
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Authenticated as "11218844
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Using alsa sink
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Country: "DE"
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Metadata pipe established
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : SessionActive!
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Loading track "Una Mattina
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Track "Una Mattina" loaded
Jan 10 21:06:30 volumio volumio[1162]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdate)
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Alsa error PCM open ALSA f
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Could not start audio: Als
Jan 10 21:06:30 volumio volumio[1162]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdate)
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Alsa error PCM open ALSA f
Jan 10 21:06:30 volumio volumio[1162]: [Vollibrespot] : Could not start audio: Als
Jan 10 21:06:35 volumio volumio[1162]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdate)
Jan 10 21:06:35 volumio volumio[1162]: [Vollibrespot] : Alsa error PCM open ALSA f
Jan 10 21:06:35 volumio volumio[1162]: [Vollibrespot] : Could not start audio: Als
Jan 10 21:06:40 volumio volumio[1162]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdate)
Jan 10 21:06:40 volumio volumio[1162]: [Vollibrespot] : Alsa error PCM open ALSA f`

**Comment by ashthespy** [comment]
From your logs - something else on Volumio is already playing -  not letting the plugin play. 

Maybe easier to hop on to [gitter](https://gitter.im/balbuze/volumio-plugins) ?
