### ISSUE TITLE
[brutefir3] config fails silently for interfaces with >2 channels

### ISSUE THREAD

**Issue by alastair-dm** [balbuze/volumio-plugins#208]
brutefir.conf.tmpl specifies 2 channels in the output section. For cards with >2 channels BruteFIR fails to start as can be seen monitoring the log, but there is no clear indication of this in the web gui. In my case the audio interface is a Focusrite Forte with 4 output channels. With brutefir3 disabled it plays correctly, but with brutefir3 enabled there is only silence. Changing the brutefir.conf.tmpl output channel definition from 2 to 4/0,1 works for this interface, but isn't a general solution.

**Comment by balbuze** [comment]
sorry for this late answer. I have no hardware in this case. So I can't test.  But I'll do some tests to see how it can be managed.

**Comment by alastair-dm** [comment]
no worries, it's probably an unusual situation. Some indication in the web interface that brutefir has failed to start should probably be the priority, along with a brief troubleshooting doc.

I don't know if volumio has an easy way to find the channel counts the hardware supports, but I couldn't find it under /proc/asound. [hw_config.c](https://www.spinics.net/linux/fedora/alsa-user/msg07230.html) will list the supported channel counts. My UCA202 supports 1 or 2 channels, the nvidia card 2, 4, 6 or 8, and the Forte only 4. Since the nvidia does support 2 channels despite having more I guess the config would work, but I've not tried volumio on that machine.
