### ISSUE TITLE
Allo DigiOne : Only S16_LE output working

### ISSUE THREAD

**Issue by ogroot** [balbuze/volumio-plugins#210]
I have a digione but cannot get audio/sound with the S24_LE and S32_LE output settings.
Only the S16_LE setting is working.  
The digione  is connected to a DAC that is 32k-192k  and 16-24 bits capable (see alsacap output below).
So I can understand that the S32_LE is not working, but S24_LE should.

alsacap -d hw:1,0 -c 2 -f S24_LE

*** Exploring configuration space of device `hw:1,0' for playback ***
Set number of channels to 2.
Set sample format to S24_LE.
Parameter ranges remaining after these settings:
2 channels
Sampling rate 32000..192000 Hz
Sample formats: S24_LE
Significant bits: 32

**Comment by ogroot** [comment]
Ok. I did some further investigation and found that the DigiOne plays 24-bit if I set the output format to S24_**4**LE.

**Comment by ogroot** [comment]
I edited the UIConfig.json file of the plugin and added the S24_4LE option to the list.
Now I can select and save this option via the plugin GUI.

Can we add this to future versions of the Plugin? Thanks!

**Comment by balbuze** [comment]
Hello ! I'm working on a new version with hw capabilities detection. In the scrolling list, it will be displayed only usable format. But I need to solve some small details...

**Comment by ogroot** [comment]
Hi Balbuze, thanks. good to hear.
I'm curious how you make the mapping from S24_LE --> S24_4LE.  
Because when I query the capabilities (e.g. with alsacap) it only returns S16_LE + S24_LE.
But I need to change this to S24_4LE to make it work.

**Comment by balbuze** [comment]
To be honest, I didn't make deep test ... Let's see how it works when realised..

**Comment by ogroot** [comment]
Just let me know if I can test something for you.

**Comment by balbuze** [comment]
Hi!
I upload a new version with hw detection. It seems to work... If no correct format detected, reboot and retry. If nothing detected, it shhould fallback with S16_LE.
I also added a filter format selector
Remove previous install.
If no filter, use "dirac pulse" (named "none" in previous version)
Let me know.

**Comment by ogroot** [comment]
Hi, 
Will try to find some time this weekend to test and let you know.

**Comment by ogroot** [comment]
Hi Balbuze,
Tested this morning 0.8.4. But unfortunately this is - in my case with the Allo Digione - not an improvement. The plugin identified 2 options S16_LE and S24_LE.   

But still S24_LE is not working. Probably because the Allo Digione requires S24_4LE and not S24_LE.

In the previous version I could fix this by adding S24_4LE manually to the option list in UIConfig.json.
But in this 0.8.4. that trick does not work anymore.

So I had to revert to the previous version :-(

Could it be possible to add the opportunity to 'overrule' this automatic filled output listbox? E.g. by entering the format manually in a textbox

**Comment by balbuze** [comment]
Damn! Ok I'll add options in the list

**Comment by balbuze** [comment]
By waiting, you can comment line 56 and uncomment line 57 in brutefir.conf.tmpl

**Comment by balbuze** [comment]
in last version 0.8.5, I have added factory values for the output format + hw detected. Let me know how it works for you  and  if  others values are needed.

**Comment by ogroot** [comment]
Hi Balbuze, tested it succesfully on 2 systems.
For the Allo Digione it detected only one format: "HW-detected-S16_LE.
Now I can also select "Factory_S24_4LE", which also works.
Thanks for supporting this great plugin!

**Comment by balbuze** [comment]
glad to read that!
pleas share your experience when you use your filters
