### ISSUE TITLE
[volspotconnect2 0.8.5] Unable to connect

### ISSUE THREAD

**Issue by paradoxxl** [balbuze/volumio-plugins#212]
RPI2, hifiberry DAC+ plugin version  0.8.5, premium account

I just updated to 0.8.5. I am unable to connect and listen to music. The behavior is the following: Sometimes, I can see the connector in the spotify app (Android/Windows). But when I try to connect, it does not do anything and the connector disappears eventually.
It is the same with multi device option disabled and configured account.
I already re-installed the plugin without success.

**aplay -l:**
`**** List of PLAYBACK Hardware Devices ****`
`card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]`
`  Subdevices: 7/7`
`  Subdevice #0: subdevice #0`
`  Subdevice #1: subdevice #1`
`  Subdevice #2: subdevice #2`
`  Subdevice #3: subdevice #3`
`  Subdevice #4: subdevice #4`
`  Subdevice #5: subdevice #5`
`  Subdevice #6: subdevice #6`
`card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]`
`  Subdevices: 1/1`
`  Subdevice #0: subdevice #0`
`card 1: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []`
`  Subdevices: 1/1`
`  Subdevice #0: subdevice #0 `

**startconnect.sh:**
`cd /data/plugins/music_service/volspotconnect2`
`./vollibrespot -b 320  -c /tmp  \`
`                  --disable-audio-cache \`
`                  --name 'parafi' --initial-volume 0\`
`                  --device plughw:1   \`
`                  --mixer alsa \`
`                  --mixer-name '' --mixer-card 'hw:1'  \`
`#                  --verbose`

**excuting startconnect.sh:**
`vollibrespot v0.1.3 48346b7 2019-02-25 (librespot 57c9ab5 2019-02-22) -- Built On 2019-02-25`
`[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }`
`[Vollibrespot] : Connecting to AP "gew1-accesspoint-b-pk51.ap.spotify.com:4070"`
`[Vollibrespot] : Authenticated as "xxxxxxxxxxxxxx" !`
`[Vollibrespot] : Setting up new mixer: card:hw:1 mixer: index:0`
`thread 'main' panicked at 'Couldn't find SelemId', libcore/option.rs:1000:5`
`stack backtrace:`
`   0:   0x966c4f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h3608b871673a8803`
`                       at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49`
`   1:   0x956547 - std::sys_common::backtrace::print::hef947be8cf8e8f55`
`                       at libstd/sys_common/backtrace.rs:71`
`                       at libstd/sys_common/backtrace.rs:59`
`   2:   0x954083 - std::panicking::default_hook::{{closure}}::haac47ed356699ffe`
`                       at libstd/panicking.rs:211`
`   3:   0x953cfb - std::panicking::default_hook::h95ba73384225983b`
`                       at libstd/panicking.rs:227`
`   4:   0x9547ab - std::panicking::rust_panic_with_hook::ha1106c0ce43cea72`
`                       at libstd/panicking.rs:477`
`   5:   0x95436f - std::panicking::continue_panic_fmt::h875c7946721c05c9`
`                       at libstd/panicking.rs:391`
`   6:   0x954257 - rust_begin_unwind`
`                       at libstd/panicking.rs:326`
`   7:   0x9a4b43 - core::panicking::panic_fmt::h429a06507aba9228`
`                       at libcore/panicking.rs:77`
`   8:   0x9a4bb3 - core::option::expect_failed::h4c79c3aae6612643`
`                       at libcore/option.rs:1000`
`   9:   0x531987 - <librespot_playback::mixer::alsamixer::AlsaMixer as librespot_playback::mixer::Mixer>::open::h319574e505014b71`
`  10:   0x4a6ffb - librespot_playback::mixer::mk_sink::h161596f8e091e127`
`  11:   0x4a2bf7 - <vollibrespot::Main as futures::future::Future>::poll::h8de885f8b6bf28df`
`  12:   0x4c54fb - futures::task_impl::std::set::h3a231d6da27c56c1`
`  13:   0x4adb1b - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::hc0350974eb54f7ad`
`  14:   0x4c5057 - futures::task_impl::std::set::h0db44df5c700aa4f`
`  15:   0x4afed7 - <std::thread::local::LocalKey<T>>::with::ha1273ecb6d30dba0`
`  16:   0x49b6d7 - <tokio::executor::current_thread::Entered<'a, P>>::block_on::hf53fa7227aee9d56`
`  17:   0x4b05d7 - <std::thread::local::LocalKey<T>>::with::hf91e923a09439449`
`  18:   0x4af3df - <std::thread::local::LocalKey<T>>::with::h3da296c6003abc58`
`  19:   0x4afd3f - <std::thread::local::LocalKey<T>>::with::h9880996ad7a77c2d`
`  20:   0x4bd94b - <scoped_tls::ScopedKey<T>>::set::h60c9c58b92fafac6`
`  21:   0x4b50b3 - tokio_core::reactor::Core::run::hdd5b409087e686c0`
`  22:   0x4a561b - vollibrespot::main::hff5c7bba125530f5`
`  23:   0x4b6147 - std::rt::lang_start::{{closure}}::h209c228e7daff9ce`
`  24:   0x9541cf - std::panicking::try::do_call::haa4d884de44899fd`
`                       at libstd/rt.rs:59`
`                       at libstd/panicking.rs:310`
`  25:   0x96fc0f - __rust_maybe_catch_panic`
`                       at libpanic_unwind/lib.rs:103`
`  26:   0x953217 - std::panic::catch_unwind::h90512a021818b18b`
`                       at libstd/panicking.rs:289`
`                       at libstd/panic.rs:392`
`  27:   0x951bd3 - std::rt::lang_start_internal::h2c5a86fd7f2a32eb`
`                       at libstd/rt.rs:58`
`  28:   0x4a646f - main`
`  29: 0x76ceb293 - __libc_start_main`

**Comment by ashthespy** [comment]
@paradoxxl What is your Mixer type in the playback options menu?

**Comment by aceholgi** [comment]
@ashthespy Your hint solved that issue for me. Initially, in the playback options "none" was set for the mixer, what seemed the right choice for me, but wasn't working as described above. Setting the mixer to "Software" and saving made volspot2 working. After that, it was possible to change the mixer back to "none" and have volspot still working!

**Comment by NIwaAJP** [comment]
I had the same connection issues and could resolve that issue by following aceholgi's instructions.
1) Install volspotconnect2 Version 0.85
2) Switch mixer from None to Software. volspotconnect2 works. No connection issues.
3) Switching mixer back from Software to None. volspotconnect2 still works.
Thanks a lot for the advice.

**Comment by ashthespy** [comment]
What version of Volumio are you guys on?

**Comment by paradoxxl** [comment]
Thanks for the immediate help @ashthespy, @aceholgi and @NIwaAJP 

I just tried the same - switching the mixer. For my installation from `hardware` to `software`.  Volspotconnect immediately connected and was able to play music. And it continued working when I changed the mixer back to the `hardware` option. I'm so happy to use the audio setup again :)

The connect script now has the attribute **mixer-name** set automatically. This seems to have been the issue as @ashthespy suggested. The Volumio version I use is `2.555`.

`**startconnect.sh**`
`cd /data/plugins/music_service/volspotconnect2`
`./vollibrespot -b 320  -c /tmp --disable-discovery `
`                  --disable-audio-cache \`
`                  --name 'parafi' --initial-volume 5\`
`                  --device plughw:1   \`
  `                --mixer alsa \`
  `                --mixer-name 'Digital' --mixer-card 'hw:1'  \`
`#                  --verbose`

**Comment by balbuze** [comment]
should be fixed with 0.8.6

**Comment by gizmobinky** [comment]
thanks the problem with the mixer type on none is gone.

thanks :-)

**Comment by NIwaAJP** [comment]
> What version of Volumio are you guys on?

Latest version. 2.555
