### ISSUE TITLE
Can't play from "My playlists"

### ISSUE THREAD

**Issue by imitto** [balbuze/volumio-plugins#213]
Hi
Two days ago something went wrong with Spotify. In "My Playlists" I see my saved playlists, but can not play them. If I click on a playlist, nothing happens, even it's not listing the content of the list. All other stuff works ("My top artists", "My albums" etc.)
I tried a full reinstall of Volumio, but still don't work. I generated a new refresh token and updated my index.js with it, still not working.

**Comment by balbuze** [comment]
hi!
sorry but it seems you are talking about the Spotify plugin. Here it is Spotify connect (volspotconnect2).
You should post here : https://github.com/volumio/volumio-plugins
