### ISSUE TITLE
[volspotconnect2] Volume change not working properly

### ISSUE THREAD

**Issue by barisari** [balbuze/volumio-plugins#214]
First of all, thanks for the great plugin. I wasn't able change current track via Spotify as mentioned in previous issues. Yesterday I updated plugin from Git via SSH. The change track problem is fixed (thank you) but now I am unable to change the volume as I want to. For example; when I set the volume to zero (mute), I think it goes all the way up to 100%. When the volume is around 5 - 10 percent it's pretty loud, I think there is no difference in volume between 99% and 1%, all same level. However 100% and 0% play at full volume.

I am using an Allo miniBoss I2C Dac with a Raspberry Pi Zero/W.

Any help would be appreciated very much, thank you.

**Comment by balbuze** [comment]
What kind of volume mixer with this dac? Software, hardware or none ?

**Comment by barisari** [comment]
I am using hardware mixer.

**Comment by ashthespy** [comment]
@barisari Can you post some logs with the `--verbose` option set? You would have to edit `startconnect.sh` and launch the service manually. The logs should then show you the volume mapping b/w alsa and Spotify. If you are on gitter in a bit, I can walk you through the process.

**Comment by barisari** [comment]
Sorry for the late answer. I am not experienced with linux, so I don't know how to get logs and set the verbose option. :/ Today I updated to the version 0.8.8, the problem still continues. And also now I can not connect to Volumio via spotify connect when mixer is set to software. :/

**Comment by balbuze** [comment]
I think I found the problem for software mixer... I'm testing a fix right now

**Comment by balbuze** [comment]
it seems your device is muted. Can you check using alsamixer ?

**Comment by balbuze** [comment]
please test with 0.8.9

**Comment by barisari** [comment]
Updated to 0.8.9. Software mixer is working now.

But when I set to hardware mixer, even though it is muted, it is playing at 100% volume.

Here is the logs of HW Mixer Analogue:
```
[Vollibrespot] librespot_core::session: new Session[0]
[Vollibrespot] : Setting up new mixer: card:hw:1 mixer:Analogue index:0
[Vollibrespot] : Alsa min: 0 (MilliBel(-600)[dB]) -- max: 1 (MilliBel(0)[dB]) HW: true
[Vollibrespot] : Alsa min-db is not SND_CTL_TLV_DB_GAIN_MUTE!!
[Vollibrespot] librespot_connect::spirc: new Spirc[0]
[Vollibrespot] librespot_core::mercury: new MercuryManager
[Vollibrespot] librespot_connect::spirc: linear volume: 65535
[Vollibrespot] : Current alsa volume: 1[i64] MilliBel(0)
[Vollibrespot] : Mapping volume [100.000%] 65535 [u16] ->> Alsa [0.000%] 0 [dB] - 0 [i64]
```

When I change mixer control name analogue to digital, it seems to work fine. I don't know what's the difference between analogue and digital in mixer control name section. And also hardware mixer in digital mode plays loudest, like hardware mixer in analogue mode in version 0.7.4 . 

Here is the logs of HW Mixer Digital:

```
[Vollibrespot] : Setting up new mixer: card:hw:1 mixer:Digital index:0
[Vollibrespot] : Alsa min: 0 (MilliBel(-9999999)[dB]) -- max: 207 (MilliBel(0)[dB]) HW: true
[Vollibrespot] : Current alsa volume: 189[i64] MilliBel(-900)
[Vollibrespot] : Using alsa sink
[Vollibrespot] : Mapping volume [100.000%] 65535 [u16] ->> Alsa [0.000%] 0 [dB] - 0 [i64]
```

**Comment by balbuze** [comment]
Allô mini boss use pcm5122. This chip provides a lot of function, not
 used in most cases. In your case, you have to use digital as mixer. I own some dac with this chip and the only way setting volume is this.

**Comment by barisari** [comment]
Thank you very much for your support.
