### ISSUE TITLE
uninstall throught GUI not working

### ISSUE THREAD

**Issue by benuron** [balbuze/volumio-plugins#215]
Great job with the plugin!

Just noticed the unistall through the web gui isn't really working and then the permisson to install new versions is denied.

Works by ssh though using 
```
sudo rm -Rf /data/configuration/music_service/volspotconnect2/
sudo rm -Rf /data/plugins/music_service/volspotconnect2/
```

**Comment by ashthespy** [comment]
Do you know if https://github.com/volumio/Volumio2/commit/3eded89f8ebe8ff5e8f4fb66c1443167728c1b4d fixes this issue?

**Comment by balbuze** [comment]
Yes it is supposed

**Comment by benuron** [comment]
Fixed!

**Comment by benuron** [comment]
From the web GUI the plugnin dissapears but the folders and files continue to exist and need to be removed manually

**Comment by benuron** [comment]
Fixed!

**Comment by ogroot** [comment]
I remember the BruteFIR plugin had similar issue.

**Comment by ashthespy** [comment]
@ogroot the issue (and fix) isn't specific to a particular plugin - it's to do with the way Volumio's plugin manager uninstalls *any* plugin
