### ISSUE TITLE
Latest version of volspotconnect2 crashing with Invalid bitrate: ()

### ISSUE THREAD

**Issue by DBMandrake** [balbuze/volumio-plugins#219]
I can't see any other reports of this problem yet (sorry if I missed them) but I just tried to update from a version a couple of months old to the latest and it is crashing for me on start. I've tried both manually downloading and installing with wget and installing via GUI - same result.

The previous version I was running that dates back about 2 months was working OK but suffering from the problem reported in another issue where it disappears from the list of available devices after a few hours (usually overnight) so I thought I would try the latest version. Here is the system journal for the error - it seems to relate to the new bitrate setting:

```
Mar 24 16:19:55 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Mar 24 16:19:55 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Mar 24 16:19:55 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Mar 24 16:19:55 volumio systemd[1]: Started Volspotconnect2 Daemon.
Mar 24 16:19:55 volumio volumio[8136]: vollibrespot v0.1.3 48346b7 2019-02-25 (librespot 57c9ab5 2019-02-22) -- Built On 2019-02-25
Mar 24 16:19:55 volumio volumio[8136]: thread 'main' panicked at 'Invalid bitrate: ()', libcore/result.rs:1009:5
Mar 24 16:19:55 volumio volumio[8136]: stack backtrace:
Mar 24 16:19:55 volumio volumio[8136]: 0:   0x93ac4f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h3608b871673a8803
Mar 24 16:19:55 volumio volumio[8136]: at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Mar 24 16:19:55 volumio volumio[8136]: 1:   0x92a547 - std::sys_common::backtrace::print::hef947be8cf8e8f55
Mar 24 16:19:55 volumio volumio[8136]: at libstd/sys_common/backtrace.rs:71
Mar 24 16:19:55 volumio volumio[8136]: at libstd/sys_common/backtrace.rs:59
Mar 24 16:19:55 volumio volumio[8136]: 2:   0x928083 - std::panicking::default_hook::{{closure}}::haac47ed356699ffe
Mar 24 16:19:55 volumio volumio[8136]: at libstd/panicking.rs:211
Mar 24 16:19:55 volumio volumio[8136]: 3:   0x927cfb - std::panicking::default_hook::h95ba73384225983b
Mar 24 16:19:55 volumio volumio[8136]: at libstd/panicking.rs:227
Mar 24 16:19:55 volumio volumio[8136]: 4:   0x9287ab - std::panicking::rust_panic_with_hook::ha1106c0ce43cea72
Mar 24 16:19:55 volumio volumio[8136]: at libstd/panicking.rs:477
Mar 24 16:19:55 volumio volumio[8136]: 5:   0x92836f - std::panicking::continue_panic_fmt::h875c7946721c05c9
Mar 24 16:19:55 volumio volumio[8136]: at libstd/panicking.rs:391
Mar 24 16:19:55 volumio volumio[8136]: 6:   0x928257 - rust_begin_unwind
Mar 24 16:19:55 volumio volumio[8136]: at libstd/panicking.rs:326
Mar 24 16:19:55 volumio volumio[8136]: 7:   0x978b43 - core::panicking::panic_fmt::h429a06507aba9228
Mar 24 16:19:55 volumio volumio[8136]: at libcore/panicking.rs:77
Mar 24 16:19:55 volumio volumio[8136]: 8:   0x48750f - core::result::unwrap_failed::hf6293151d0e2fda6
Mar 24 16:19:55 volumio volumio[8136]: 9:   0x478b07 - vollibrespot::main::hff5c7bba125530f5
Mar 24 16:19:55 volumio volumio[8136]: 10:   0x48a147 - std::rt::lang_start::{{closure}}::h209c228e7daff9ce
Mar 24 16:19:55 volumio volumio[8136]: 11:   0x9281cf - std::panicking::try::do_call::haa4d884de44899fd
Mar 24 16:19:55 volumio volumio[8136]: at libstd/rt.rs:59
Mar 24 16:19:55 volumio volumio[8136]: at libstd/panicking.rs:310
Mar 24 16:19:55 volumio volumio[8136]: 12:   0x943c0f - __rust_maybe_catch_panic
Mar 24 16:19:55 volumio volumio[8136]: at libpanic_unwind/lib.rs:103
Mar 24 16:19:55 volumio volumio[8136]: 13:   0x927217 - std::panic::catch_unwind::h90512a021818b18b
Mar 24 16:19:55 volumio volumio[8136]: at libstd/panicking.rs:289
Mar 24 16:19:55 volumio volumio[8136]: at libstd/panic.rs:392
Mar 24 16:19:55 volumio volumio[8136]: 14:   0x925bd3 - std::rt::lang_start_internal::h2c5a86fd7f2a32eb
Mar 24 16:19:55 volumio volumio[8136]: at libstd/rt.rs:58
Mar 24 16:19:55 volumio volumio[8136]: 15:   0x47a46f - main
Mar 24 16:19:55 volumio volumio[8136]: 16: 0x76d65631 - __libc_start_main
Mar 24 16:19:55 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Mar 24 16:19:55 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
```
It doesn't matter what bitrate I select in the GUI I get the same problem.

Happy to help test and debug this but can anybody suggest a previous commit that is known working that I can revert to in the meantime ?

**Comment by DBMandrake** [comment]
Just wanted to add that I've reverted to commit a55fc1440e6463bd3378d70170171e738600b658 and everything is working again.

**Comment by balbuze** [comment]
Sorry but you mix volspotconnect 2 and brutefir... Not easy to get what is the problem

**Comment by DBMandrake** [comment]
> Sorry but you mix volspotconnect 2 and brutefir... Not easy to get what is the problem

Huh ? I'm not mixing up anything. The different plugins are all in the same git repo so there is only one commit timeline....

I was simply selecting a point in time soon after the Next track fix.

**Comment by balbuze** [comment]
I think the problem is rather due to the update of the plugin. Previous settings seems to be not removed. A uninstall the previous and the install should solve it. let me know if you try. TY

**Comment by DBMandrake** [comment]
If by uninstall you mean just uninstalling via the Plugins GUI, then I've tried that already before initially posting here. Is there some other way to remove lingering configuration files or should a normal uninstall of the plugin remove all related files ?

**Comment by balbuze** [comment]
it is supposed to bee removed when uninstalling... and when installing...

**Comment by ashthespy** [comment]
Your `startconnect.sh` probably looks like:
```bash
./vollibrespot -b ${bitrate} -c /tmp  \
                  --disable-audio-cache \
```
Try deleting `/data/configuration/music_service/volspotconnect2/config.json` and along with the plugin folder in `/data/plugins/music_service/` and reinstalling the plugin.

**Comment by TimHausmann** [comment]
I had the same issue and tried as you suggested. The output is now:
`volumio@wohnzimmer:~$ sudo journalctl -f -o cat -u volspotconnect2.service Started Volspotconnect2 Daemon.
vollibrespot v0.1.4 d207974 2019-03-26 (librespot 57a6586 2019-03-26) -- Built On 2019-03-26
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
Started Volspotconnect2 Daemon.
Stopping Volspotconnect2 Daemon...
Stopped Volspotconnect2 Daemon.
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.1.4 d207974 2019-03-26 (librespot 57a6586 2019-03-26) -- Built On 2019-03-26
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
`
I cant't see a Spotify Connect target in the App, but this could be due to my VPN connection.

**Comment by DBMandrake** [comment]
> Your `startconnect.sh` probably looks like:
> 
> ```shell
> ./vollibrespot -b ${bitrate} -c /tmp  \
>                   --disable-audio-cache \
> ```
> 
> Try deleting `/data/configuration/music_service/volspotconnect2/config.json` and along with the plugin folder in `/data/plugins/music_service/` and reinstalling the plugin.

Will give that a try this weekend.

**Comment by ashthespy** [comment]
@TimHausmann Yours looks like a different issue - the daemon is launching and waiting for connections as expected.

**Comment by TimHausmann** [comment]
@ashthespy I had the same output as DBMandrake before. After I followed your instructions to delete and install the plug-in, everything works fine now.

**Comment by balbuze** [comment]
In fact it seems that when you update the plugin, or even remove and reinstall it, some file are kept in ram and a sort of mix between old and new version is done... A killall node or a reboot fix it...

**Comment by TimHausmann** [comment]
I restarted Volumio via console command, this didn't help. It seems like a Volumio issue to me.

**Comment by DBMandrake** [comment]
> In fact it seems that when you update the plugin, or even remove and reinstall it, some file are kept in ram and a sort of mix between old and new version is done... A killall node or a reboot fix it...

Not for me it didn't. I tried rebooting between uninstalling the previous plugin and installing the new one. It seems more like a left over configuration file that the new version of the plugin chokes on.

I see there have been more commits since I last tested so I'll first try a straight uninstall and then install of the latest version without attempting to manually delete any configuration files.

If the new version of the plugin crashes due to old configuration files and uninstalling the old plugin doesn't remove them, that's a bug.

**Comment by ashthespy** [comment]
> If the new version of the plugin crashes due to old configuration files and uninstalling the old plugin doesn't remove them, that's a bug.

True, the plugin install script does some basic clean up already, but it doesn't seem to help here? https://github.com/balbuze/volumio-plugins/blob/4d75ac7a959338a68bc795f06caf11e8d228a566/plugins/music_service/volspotconnect2/install.sh#L12

But then again, plugin installation/config clean shouldn't be required on a per plugin basis, but at the Volumio system level. I recall seeing a commit (https://github.com/balbuze/volumio-plugins/issues/215#issuecomment-472099745) that should have fixed this from the Volumio side.

**Comment by TimHausmann** [comment]
I don't have the latest Volumio version installed, which should have a fixed uninstall feature. Maybe that's why it didn't work. My current version is 2.555.

**Comment by DBMandrake** [comment]
Still no luck here. First I uninstalled the old working version through the GUI. I then checked both `/data/configuration/music_service/volspotconnect2/` and `/data/plugins/music_service/volspotconnect2/` and in both cases both these directories were removed by the GUI uninstaller, so removal of old files doesn't seem to be the issue.

I then tried to install the latest version from master by git pulling it and installing from the command line.

As soon as I try to enable the new service in the GUI it tries to launch the service before I have had a chance to configure it and it keeps crashing in a loop complaining about the bitrate as before.

I then try to configure it via the GUI with the options:

Initial volume 100
Normalisation Volume Off
Bitrate 320
Multi-user Device On
Debug Off (I see the debug option is new since last time I tried to install)

When I hit save and check `/data/configuration/music_service/volspotconnect2/config.json` I see:

```
{
  "initvol": {
    "type": "string",
    "value": "33"
  },
  "normalvolume": {
    "type": "boolean",
    "value": false
  },
  "bitrate": {
    "type": "number",
    "value": 320
  },
  "shareddevice": {
    "type": "boolean",
    "value": true
  },
  "username": {
    "type": "string",
    "value": ""
  },
  "password": {
    "type": "string",
    "value": ""
  },
  "debug": {
    "type": "boolean",
    "value": false
  }
}
```
Considering I'm setting initial volume to 100 it seems the GUI is not saving my requested settings properly. On further checking by watching config.json and changing different settings I find the following settings are not being updated in the file after gui changes:

initvolume (always 33 no matter the slider setting)
bitrate (always 320 no matter the drop down setting)
debug (always false)

The following settings are saved properly:

normalvolume
shareddevice
username
password.

So there seems to be problems with reading GUI settings and saving them in the config file.

If I manually edit the config.json to change initvol to 100 and bitrate to 160 then restart the service and go back into the GUI it still reports initial volume as 30 and bitrate is shown as blank, so the GUI is not reading those settings from the config file either.

I still get invalid bitrate when starting the service.

Next thing I tried is stopping the plugin and manually launching it from the command line with the same parameters as startconnect.sh but values substituting $bitrate with 320:

```
volumio@volumio:/data/plugins/music_service/volspotconnect2$ ./vollibrespot -b 320 -c /tmp  \
>                   --disable-audio-cache \
>                   --name 'Volumio' 100\
>                   --device plughw:2   \
>                   alsa \
>                   --mixer-name 'UMC204HD 192k Output' --mixer-card 'hw:2'  \
>
vollibrespot v0.1.4 d207974 2019-03-26 (librespot 57a6586 2019-03-26) -- Built On 2019-03-26
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
[Vollibrespot] : Connecting to AP "gew1-accesspoint-b-8vvh.ap.spotify.com:4070"
[Vollibrespot] : Authenticated as "dbmandrake" !
[Vollibrespot] : Using alsa sink
[Vollibrespot] : Country: "GB"
[Vollibrespot] : Metadata pipe established
[Vollibrespot] : SessionActive!
[Vollibrespot] : Loading track "Surface" with Spotify URI "spotify:track:5ERWSokrBWx8sUwHV6QN93"
[Vollibrespot] : Track "Surface" loaded
```
As can be seen this works, and I was able to play music. :)

So there seems to be a problem with the handling of configuration variables - both in reading and writing them to config.json, and for some reason even when bitrate is set correctly in config.json it is not being passed to startconnect.sh, as clearly when I substitute 320 for $bitrate it then works.

I don't know enough about volumio to know how the variables in the config file are passed to the service.

By the way because I am running on a Cubox-i I am not running the very latest version of Volumio - Cubox-i builds are very infrequent so when I find one that works well I stick with it. I am currently running version System Version 2.425 built July 20, 2018. I don't think there is a later build.

**Comment by ashthespy** [comment]
@DBMandrake  First lets get the music up and running, edit `startconnect.tmpl` and set your bitrate to survive plugin restarts. 

I am curious - why only the bitrate config option. Do you have similar issues with the debug toggle? Then it would point towards Volumio not purging the old configuration from memory.

**Comment by DBMandrake** [comment]
> @DBMandrake First lets get the music up and running, edit `startconnect.tmpl` and set your bitrate to survive plugin restarts.

Ah, great tip, I didn't know what startconnect.tmpl was for. I've put 320 in there and now it works after stopping starting the service, so at least I can use it while further testing is done. :)

> IIRC Volumio uses [`v-conf`](https://www.npmjs.com/package/v-conf) to cache the config in memory to save writes to the SD card.
> 
> I am curious - why only the bitrate config option. Do you have similar issues with the debug toggle? Then it would point towards Volumio not purging the old configuration from memory.

As I described above, it's not just bitrate, many of the settings are not written to config.json and some are. When I hit save 
normalvolume
shareddevice
username
password

Are written to config.json immediately, however none of the other settings including debug are ever updated. When opening the plug settings in the GUI none of the settings from the file are displayed correctly.

> I don't know if you have tried this yet - but does a `killall node` after first installation help?

No I haven't, but would a reboot have the same effect ?

**Comment by DBMandrake** [comment]
Ok I tried killall node and the effect was interesting.

The settings like bitrate which were not saving in config.json started to save correctly, also the UI was now also reporting those settings properly. However the initial volume slider has now disappeared from the UI completely and that settings has gone back to 33 in config.json.

And then after a while, it seems to have stopped updating again. So I'm at a bit of a loss to understand how this configuration caching is supposed to work...

**Comment by ashthespy** [comment]
Restarting the Volumio  app (`killall node` or `volumio vresart` `systemctl restart volumio.service`) seems force `v-conf` to read the new configuration instead of the cached copy it uses now. But this is something that should be reported in the main Volumio bug tracker to investigate further!
