### ISSUE TITLE
Not an Issue ;) volspotconnect2

### ISSUE THREAD

**Issue by chsims1** [balbuze/volumio-plugins#22]
Hi balbuze,

just interested, but does the fact that you are using the librespot mean that this plugin will be able to use snapcast?  Badaix mentions it on his Github

**Comment by balbuze** [comment]
I don't know in fact. Even if it works with librespot, there is still missing features, and it is slow to start playing, and any command. Not sure of the future... One thing I started to work with volspotocnnect (1) is to display album art in volumio and having working buttons... but far from being finished.

**Comment by balbuze** [comment]
I had a look here https://github.com/badaix/librespot/releases and maybe just by using this lib in volspotconnect2 + configured snapcast would be enough ?

**Comment by chsims1** [comment]
Well I have no complaints against volspotconnect1; it's performed reliably for me.  I really would like snapcast multiroom synching though.

You sound as though you're unhappy with librespot.  Is this something that can be worked on, or is it just a case of letting go?

**Comment by cortegedusage** [comment]
although I'm not sure where I remember seeing it somewhere I think on RuneAudio forum that it can work with spotify-connect-web.
quick search reveals something like this:
https://github.com/badaix/snapcast/issues/45

maybe this wil get you in the right direction.

**Comment by balbuze** [comment]
Yes thanks.. but for some personal reasons it will be difficult for me to work on this and the plugin... I'll do my best.

**Comment by balbuze** [comment]
😁. I agree with the fact snapcast should be configured system wide, using alsa output. Maybe Michelangelo is working on this?
