### ISSUE TITLE
Settings are missing

### ISSUE THREAD

**Issue by rs689** [balbuze/volumio-plugins#222]
Latest version of Volumio on Rpi 3 B+ with HiFiBerry Digi+ Pro.
After successful installation of BruteFIR3, I enable it under installed plugins. But when I click on the settings, the page stays empty with no sliders or anything showing, just a blank page with Volumio background.

I have tried uninstalling and reinstalling several times. I even did a fresh dump of the Volumio image, to no avail.

**Comment by balbuze** [comment]
If you use last commit from yesterday, you may encounter problems as I stated to implement new features, but I didn't check if installation is still fine... Try to install a previous version.

**Comment by rs689** [comment]
8.5 did it, I think that's from a month or so ago (for anyone else that might wander here).

Thank you :)
