### ISSUE TITLE
Sweep tools and pink noise tools don't work

### ISSUE THREAD

**Issue by Kandyis** [balbuze/volumio-plugins#223]
Hi
I use brutefir3 on rpi3b+  with an USB DAC (Audioquest Dragonfly 1.2) and it seems to work without problems. However I downloaded the sweep and pink noise tools and I cannot play them. When I try to play it I get the black loading screen and after that I get the popup message "Configuration update player successfully restarted" but I don't get any sound. Sometimes the screen refreshes to "Playback options". Sometimes I need to turn the plugin off and restart the rpi to make volumio work again. 
This is my configuration:
![Untitled1111](https://user-images.githubusercontent.com/49247220/55498461-fd101d00-5643-11e9-9835-0bb7af26edb2.png)

**Comment by balbuze** [comment]
Yes you're right. There's a problem with last version. I have to fix it. But in few days... sorry

**Comment by Kandyis** [comment]
Thanks for the info and the hard work!

**Comment by balbuze** [comment]
it is fixed now.
let me know!

**Comment by Kandyis** [comment]
It works now! But I think there is an issue with the sweep tools. For all the channels that I choose (Left or Right or Both) it always starts to play with a short high frequency sound from the right channel and after that the sweep sound starts from the channel which I selected.

**Comment by balbuze** [comment]
This not a issue but rather a feature.. it allows to have the time reference always the same. And in the case you want to know the delay between both channels, rew display this info.

**Comment by balbuze** [comment]
The short signal is the time reference to automatically start the record in rew.

**Comment by Kandyis** [comment]
Ok so it works. Thanks a lot!

**Comment by balbuze** [comment]
How do you plan to create your filters ?

**Comment by Kandyis** [comment]
I want to measure my room and use REW and rephase to create the filters. But I don't have a measurement microphone yet. And I don't really know how do I put them to Raspberry Pi Volumio folder, because I'm planning to create the filters with my PC.

**Comment by balbuze** [comment]
From your PC, you can access the share folder of volumio. In file explorer type "file://Ipadressofv olumio". In the last version of the plugin, you can generate filter in few click without using rephase. Just export the impulse from rew as 32b pcm, put it in filter-sources. In plugin, click on generate filter, and use it as filter. This not fully documented.

**Comment by Kandyis** [comment]
Ok nice to know about the new feature. Also I tried "file://Ip adress of volumio" and it works. I also tried WINSCP and connected via ssh.
