### ISSUE TITLE
USB Dac not working but IS2 and audio jack do.  

### ISSUE THREAD

**Issue by illtrick** [balbuze/volumio-plugins#224]
I posted this over at the volumio forums as well but thought it more appropriate here.  

It took a good bit of troubleshooting to isolate it to this but I'm pretty confident that the problem stems from the USB Dac as a selected output. I see the latest build of Spotify Connect 0.9.3 has verbose logging but I'll need someone to point out where I can find the logs so I can post them. 

Issue: No devices running Spotify (iPhone, Android, windows, osx ) are able to connect to the pi. They all see the device but time out when connecting. Zero successful connections made.

What works: iOS and OSX devices connect and play fine with Airplay using USB dac. Spotify Connect works when playback is switched to the audio jack on the pi. I have another pi with an Allo Boss that works every time with every device when using Spotify Connect using most current version of plugin and volumio. 

What I've tried: oodles of reboots, March and February releases of volumio, factory resetting, 0.9.1 and 0.9.3 Spotify plugin, multiple uninstall/reinstall of plugin, changing mixer from hardware to none, changing playback device to audio jack (only thing that worked). 

Device Details:
pi 3+ running March 12 release of volumio and 0.9.3 of Spotify Connect. 
Schiit Modi Multibit USB dac

**Comment by ashthespy** [comment]
Greets, 
Looks like there is hiccups when configuring the outputs for your USB DAC.

>  but I'll need someone to point out where I can find the logs so I can post them.

```
sudo journalctl -f -o cat -u volspotconnect2.service
```

**Comment by illtrick** [comment]
Awesome.  Thanks @ashthespy for the fast response.  Here's the logs from an attempted connection.


`
volumio@office:~$ sudo journalctl -f -o cat -u volspotconnect2.service
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.1.4 d207974 2019-03-26 (librespot 57a6586 2019-03-26) -- Built O                                                            n 2019-03-26
[Vollibrespot] librespot_connect::discovery: Zeroconf server listening on 0.0.0.                                                            0:37051
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, m                                                            essage: "No such device" }
[Vollibrespot] mdns::fsm: received question: IN _Volumio._tcp.local
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
[Vollibrespot] mdns::fsm: received question: IN office.local
[Vollibrespot] mdns::fsm: received question: IN _Volumio._tcp.local
[Vollibrespot] mdns::fsm: received question: IN office.local
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
[Vollibrespot] librespot_connect::discovery: Post "/" {}
[Vollibrespot] : Connecting to AP "guc3-accesspoint-b-t4f9.ap.spotify.com:4070"
[Vollibrespot] : Authenticated as "smaerdmuipo" !
[Vollibrespot] librespot_core::session: new Session[0]
[Vollibrespot] : Setting up new mixer: card:hw:5 mixer:PCM index:0
[Vollibrespot] : Alsa min: 0 (MilliBel(0)[dB]) -- max: 0 (MilliBel(0)[dB]) HW: false
[Vollibrespot] : Switching to linear volume mapping, control range: MilliBel(0)
[Vollibrespot] : Alsa min-db is not SND_CTL_TLV_DB_GAIN_MUTE!!
[Vollibrespot] librespot_connect::spirc: new Spirc[0]
[Vollibrespot] librespot_core::mercury: new MercuryManager
[Vollibrespot] librespot_connect::spirc: linear volume: 19660
thread 'main' panicked at 'Couldn't get current volume: Error("snd_mixer_selem_get_playback_volume",                                         Sys(EINVAL))', src/libcore/result.rs:997:5
stack backtrace:
[Vollibrespot] librespot_playback::player: new Player[0]
[Vollibrespot] : Using alsa sink
0:   0x9422c7 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hdf951eb9f43ea27e
at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
1:   0x93dd3f - std::sys_common::backtrace::_print::h2b5fdbbb5020ccf8
at src/libstd/sys_common/backtrace.rs:70
2:   0x94037f - std::panicking::default_hook::{{closure}}::h18d8c59665918d69
at src/libstd/sys_common/backtrace.rs:58
at src/libstd/panicking.rs:200
3:   0x93ffe7 - std::panicking::default_hook::h1fd1ad969274543a
at src/libstd/panicking.rs:215
4:   0x940aef - std::panicking::rust_panic_with_hook::h40a77253872948e8
at src/libstd/panicking.rs:478
5:   0x94066f - std::panicking::continue_panic_fmt::hec94fc8e5daf641b
at src/libstd/panicking.rs:385
6:   0x94055b - rust_begin_unwind
at src/libstd/panicking.rs:312
7:   0x95345b - core::panicking::panic_fmt::h74ee8034b317ceed
at src/libcore/panicking.rs:85
8:   0x4fc277 - core::result::unwrap_failed::h3820fedf691dab68
9:   0x4faeb7 - librespot_playback::mixer::alsamixer::AlsaMixer::map_volume::hcf1bc755ea1546db
10:   0x4fb7c3 - <librespot_playback::mixer::alsamixer::AlsaMixer as librespot_playback::mixer::Mixe                                        r>::set_volume::hb2bb2ff98e12994b
11:   0x4cdef3 - librespot_connect::spirc::SpircTask::set_volume::hae6337ac82867b6d
12:   0x4c943f - librespot_connect::spirc::Spirc::new::h6a96f65176ba53b7
13:   0x453f23 - <vollibrespot::Main as futures::future::Future>::poll::hac634acab561e301
14:   0x47229f - futures::task_impl::std::set::h8f43bf460171e6dd
15:   0x45eafb - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::hf53dae6c69b9                                        47dd
16:   0x4725ab - futures::task_impl::std::set::hca81eb426e337ec0
17:   0x45fc07 - <std::thread::local::LocalKey<T>>::with::h16c90b4f172abf2e
18:   0x471b77 - <tokio_current_thread::Entered<'a, P>>::block_on::he71db7d6e5ff877f
19:   0x45fd7f - <std::thread::local::LocalKey<T>>::with::h1f3014f00cfcd6db
20:   0x460ab3 - <std::thread::local::LocalKey<T>>::with::hfbf76d11899a3b58
21:   0x460647 - <std::thread::local::LocalKey<T>>::with::h911bf35cf05c03f7
22:   0x47ee43 - <scoped_tls::ScopedKey<T>>::set::h91b17ad9302ffe42
23:   0x469627 - tokio_core::reactor::Core::run::hb8e8c62c83ec5d82
24:   0x454beb - vollibrespot::main::h4f545e75eb48df12
25:   0x45f34f - std::rt::lang_start::{{closure}}::hc0fa9231237dfeef
26:   0x9404d3 - std::panicking::try::do_call::h287c6909aadcc5f1
at src/libstd/rt.rs:49
at src/libstd/panicking.rs:297
27:   0x9450f7 - __rust_maybe_catch_panic
at src/libpanic_unwind/lib.rs:92
volspotconnect2.service: main process exited, code=exited, status=101/n/a
Unit volspotconnect2.service entered failed state.
28:   0x940f53 - std::rt::lang_start_internal::h747c58e2c78f4f4f
at src/libstd/panicking.rs:276
at src/libstd/panic.rs:388
at src/libstd/rt.rs:48
29:   0x454f1b - main
30: 0x76c87293 - __libc_start_main
[Vollibrespot] librespot_connect::spirc: drop Spirc[0]
[Vollibrespot] librespot_playback::player: Shutting down player thread ...
[Vollibrespot] librespot_playback::player: drop Player[0]
[Vollibrespot] librespot_core::session: drop Session[0]
[Vollibrespot] librespot_core::mercury: drop MercuryManager
[Vollibrespot] librespot_core::session: drop Dispatch
volspotconnect2.service holdoff time over, scheduling restart.
Stopping Volspotconnect2 Daemon...
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.1.4 d207974 2019-03-26 (librespot 57a6586 2019-03-26) -- Built On 2019-03-26
[Vollibrespot] librespot_connect::discovery: Zeroconf server listening on 0.0.0.0:43275
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such dev                                        ice" }
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
`

**Comment by ashthespy** [comment]
I wonder what makes these devices special - second time [I see this error](https://forum.volumio.org/spotify-connect-disconnects-when-changing-volume-t12104.html):
`'Couldn't get current volume: Error("snd_mixer_selem_get_playback_volume", Sys(EINVAL))`

PS: You can exit the log with a `Ctrl-c` 
PSS: use ` ``` ` around your logs to get [a code block](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Comment by illtrick** [comment]
Thanks.  Just a bit of background, this DAC was working with the plugin on previous versions (0.8.9 and earlier).  I have noticed changes in volume control (as a user) in the past few versions so there might be some relation there.

**Comment by ashthespy** [comment]
@illtrick Are you willing to help me debug a little - would need some copy pasting into the console!
if so - hop onto gitter, I will be there for about half an hour

**Comment by illtrick** [comment]
I'm away from the device right now but hell yes I'm willing to do some live debugging.  What timezone are you on?  I'm pacific time 11 AM right now and can be available after 8 PM my time.

**Comment by ashthespy** [comment]
I recently changed the `libasound` version while building the binaries, wonder if that could be the issue. I am on CET. So I will probably just list out the some things to check here (soonish!)

**Comment by illtrick** [comment]
Doesn't look like either did the trick.  Also tried going back to 0.1.2 to no effect.   I still see the same ```Couldn't get current volume: Error```

 Here's the logs:

```[Vollibrespot] : Setting up new mixer: card:hw:5 mixer:PCM index:0
[Vollibrespot] : Alsa min: 0 (MilliBel(0)[dB]) -- max: 0 (MilliBel(0)[dB]) HW: f                                                            alse
[Vollibrespot] : Switching to linear volume mapping, control range: MilliBel(0)
[Vollibrespot] : Alsa min-db is not SND_CTL_TLV_DB_GAIN_MUTE!!
[Vollibrespot] : Using alsa sink
thread 'main' panicked at 'Couldn't get current volume: Error("snd_mixer_selem_g                                                            et_playback_volume", Sys(EINVAL))', libcore/result.rs:1009:5
stack backtrace:
0:   0x9aec4f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h3608                                                            b871673a8803
at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1:   0x99e547 - std::sys_common::backtrace::print::hef947be8cf8e8f55
at libstd/sys_common/backtrace.rs:71
at libstd/sys_common/backtrace.rs:59
2:   0x99c083 - std::panicking::default_hook::{{closure}}::haac47ed356699ffe
at libstd/panicking.rs:211
3:   0x99bcfb - std::panicking::default_hook::h95ba73384225983b
at libstd/panicking.rs:227
4:   0x99c7ab - std::panicking::rust_panic_with_hook::ha1106c0ce43cea72
at libstd/panicking.rs:477
5:   0x99c36f - std::panicking::continue_panic_fmt::h875c7946721c05c9
at libstd/panicking.rs:391
6:   0x99c257 - rust_begin_unwind
at libstd/panicking.rs:326
7:   0x9ecb43 - core::panicking::panic_fmt::h429a06507aba9228
at libcore/panicking.rs:77
8:   0x5a3c4f - core::result::unwrap_failed::h57469fb2d38b01b9
9:   0x57931f - librespot_playback::mixer::alsamixer::AlsaMixer::map_volume::h49                                                            3299dacfa4bd72
10:   0x579c8f - <librespot_playback::mixer::alsamixer::AlsaMixer as librespot_p                                                            layback::mixer::Mixer>::set_volume::hfb3dda43b22ec3a9
11:   0x554ba3 - librespot_connect::spirc::SpircTask::set_volume::h0a694701541c0                                                            155
12:   0x550cc3 - librespot_connect::spirc::Spirc::new::h7a04817e15060e21
13:   0x4eae3b - <vollibrespot::Main as futures::future::Future>::poll::h8de885f                                                            8b6bf28df
14:   0x50d4fb - futures::task_impl::std::set::h3a231d6da27c56c1
15:   0x4f5b1b - <futures::future::lazy::Lazy<F, R> as futures::future::Future>:                                                            :poll::hc0350974eb54f7ad
16:   0x50d057 - futures::task_impl::std::set::h0db44df5c700aa4f
17:   0x4f7ed7 - <std::thread::local::LocalKey<T>>::with::ha1273ecb6d30dba0
18:   0x4e36d7 - <tokio::executor::current_thread::Entered<'a, P>>::block_on::hf                                                            53fa7227aee9d56
19:   0x4f85d7 - <std::thread::local::LocalKey<T>>::with::hf91e923a09439449
20:   0x4f73df - <std::thread::local::LocalKey<T>>::with::h3da296c6003abc58
21:   0x4f7d3f - <std::thread::local::LocalKey<T>>::with::h9880996ad7a77c2d
22:   0x50594b - <scoped_tls::ScopedKey<T>>::set::h60c9c58b92fafac6
23:   0x4fd0b3 - tokio_core::reactor::Core::run::hdd5b409087e686c0
24:   0x4ed61b - vollibrespot::main::hff5c7bba125530f5
25:   0x4fe147 - std::rt::lang_start::{{closure}}::h209c228e7daff9ce
26:   0x99c1cf - std::panicking::try::do_call::haa4d884de44899fd
at libstd/rt.rs:59
at libstd/panicking.rs:310
27:   0x9b7c0f - __rust_maybe_catch_panic
at libpanic_unwind/lib.rs:103
28:   0x99b217 - std::panic::catch_unwind::h90512a021818b18b
at libstd/panicking.rs:289
at libstd/panic.rs:392
29:   0x999bd3 - std::rt::lang_start_internal::h2c5a86fd7f2a32eb
volspotconnect2.service: main process exited, code=exited, status=101/n/a
Unit volspotconnect2.service entered failed state.
at libstd/rt.rs:58
30:   0x4ee46f - main
31: 0x76dae293 - __libc_start_main
volspotconnect2.service holdoff time over, scheduling restart.
Stopping Volspotconnect2 Daemon...
```

**Comment by illtrick** [comment]
Here's what happens when I switch playback devices.  Starting with HDMI out then switching back to the Modi Multibit

```
[Vollibrespot] : Connecting to AP "guc3-accesspoint-b-rrl6.ap.spotify.com:4070"
[Vollibrespot] : Authenticated as "smaerdmuipo" !
[Vollibrespot] : Setting up new mixer: card:hw:0 mixer:PCM index:0
[Vollibrespot] : Alsa min: -10239 (MilliBel(-9999999)[dB]) -- max: 400 (MilliBel(400)[dB]) HW: true
[Vollibrespot] : Using alsa sink
[Vollibrespot] : Current alsa volume: -2735[i64] MilliBel(-2735)
[Vollibrespot] : Mapping volume [29.999%] 19660 [u16] ->> Alsa [70.505%] -27.38 [dB]
[Vollibrespot] : Country: "US"
[Vollibrespot] : Metadata pipe established
Stopping Volspotconnect2 Daemon...
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.1.2 edd446b 2018-11-24 (librespot e386736 2018-10-16) -- Built On 2018-11-24
Stopping Volspotconnect2 Daemon...
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.1.2 edd446b 2018-11-24 (librespot e386736 2018-10-16) -- Built On 2018-11-24
Started Volspotconnect2 Daemon.
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
Started Volspotconnect2 Daemon.
Started Volspotconnect2 Daemon.
Started Volspotconnect2 Daemon.
[Vollibrespot] : Connecting to AP "guc3-accesspoint-b-nn2n.ap.spotify.com:4070"
[Vollibrespot] : Authenticated as "smaerdmuipo" !
[Vollibrespot] : Setting up new mixer: card:hw:5 mixer:PCM index:0
[Vollibrespot] : Alsa min: 0 (MilliBel(0)[dB]) -- max: 0 (MilliBel(0)[dB]) HW: false
[Vollibrespot] : Switching to linear volume mapping, control range: MilliBel(0)
[Vollibrespot] : Alsa min-db is not SND_CTL_TLV_DB_GAIN_MUTE!!
[Vollibrespot] : Using alsa sink
thread 'main' panicked at 'Couldn't get current volume: Error("snd_mixer_selem_get_playback_volume", Sys(EINVAL))', libcore/result.rs:1009:5
stack backtrace:
```

**Comment by illtrick** [comment]
So some more trial and error and I got it working.  Here's the steps I took:
Changed Mixer Type to None and was able to get playback!  BUT no volume control via Spotify.  
Cycled through v0.1.2 , .3 and .4 still: Playback, but no volume control.
Ran the commands to setup new mixer: Playback, but no volume control.
Changed Mixer Type to Software and now I have both Playback and Volume Control!

logs from successful connect and play
```
Started Volspotconnect2 Daemon.
vollibrespot v0.1.4 d207974 2019-03-26 (librespot 57a6586 2019-03-26) -- Built On 2019-03-26
Started Volspotconnect2 Daemon.
[Vollibrespot] librespot_connect::discovery: Zeroconf server listening on 0.0.0.0:33447
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
[Vollibrespot] librespot_connect::discovery: Post "/" {}
[Vollibrespot] : Connecting to AP "guc3-accesspoint-b-dmj6.ap.spotify.com:4070"
[Vollibrespot] : Authenticated as "smaerdmuipo" !
[Vollibrespot] librespot_core::session: new Session[0]
[Vollibrespot] : Setting up new mixer: card:hw:5 mixer:SoftMaster index:0
[Vollibrespot] : Alsa min: 0 (MilliBel(0)[dB]) -- max: 99 (MilliBel(0)[dB]) HW: false
[Vollibrespot] : Using Alsa linear volume
[Vollibrespot] : Alsa min-db is not SND_CTL_TLV_DB_GAIN_MUTE!!
[Vollibrespot] librespot_connect::spirc: new Spirc[0]
[Vollibrespot] librespot_core::mercury: new MercuryManager
[Vollibrespot] librespot_playback::player: new Player[0]
[Vollibrespot] : Using alsa sink
[Vollibrespot] librespot_connect::spirc: linear volume: 19660
[Vollibrespot] : Current alsa volume: 63[i64] MilliBel(9999999)
[Vollibrespot] : Mapping (lin) volume [29.999%] 19660 [u16] ->> Alsa [29.293%] 29 [i64]
[Vollibrespot] librespot_core::session: Session[0] strong=5 weak=2
[Vollibrespot] : Country: "US"
[Vollibrespot] vollibrespot::meta_pipe: Starting new MetaPipe[0]
[Vollibrespot] : Metadata pipe established
[Vollibrespot] vollibrespot::meta_pipe: Volume { volume_to_mixer: 19660 }
[Vollibrespot] vollibrespot::meta_pipe: Event::Volume(29.999237048905165)
[Vollibrespot] librespot_core::mercury: subscribed uri=hm://remote/user/smaerdmuipo/ count=0
[Vollibrespot] librespot_connect::spirc: kMessageTypeNotify "NCASE" 62d0d0527bbc7c11455829269137e01d686fdc65 1894787164 1554525463945
[Vollibrespot] librespot_connect::spirc: kMessageTypeNotify "stereo" a8cf079c641dc556ac20ac1d7c6b9cd140a59598 1894787164 1554525463945
[Vollibrespot] librespot_connect::spirc: kMessageTypeLoad "NCASE" 62d0d0527bbc7c11455829269137e01d686fdc65 2 1554525463945
[Vollibrespot] librespot_connect::spirc: Requesting API access token
[Vollibrespot] vollibrespot::meta_pipe: SessionActive { became_active_at: 1554525464155 }
[Vollibrespot] : SessionActive!
[Vollibrespot] librespot_connect::spirc: Frame has 40 tracks
[Vollibrespot] vollibrespot::meta_pipe: Load { track_id: SpotifyId(u128!(39326327933985369058526703245583919820)) }
[Vollibrespot] librespot_playback::player: command=Load(SpotifyId(u128!(39326327933985369058526703245583919820)), false, 352274)
[Vollibrespot] : Loading track "Stil" with Spotify URI "spotify:track:0TPjC727vSIuS8a0npQcHy"
[Vollibrespot] librespot_core::audio_key: new AudioKeyManager
[Vollibrespot] librespot_audio::fetch: Downloading file 262b4f5b2979257a32f9d3c5c23535f630b61c58
[Vollibrespot] librespot_core::channel: new ChannelManager
[Vollibrespot] librespot_audio::fetch: AudioFileOpen::len 51150760[u64] 390.249[chunks] => 391[chunks]
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
[Vollibrespot] librespot_playback::player: Normalisation Data: NormalisationData { track_gain_db: -3.5100021, track_peak: 0.959459, album_gain_db: -1.9400024, album_peak: 0.97083676 }
[Vollibrespot] librespot_playback::player: Applied normalisation factor: 0.66757476
[Vollibrespot] vollibrespot::meta_pipe: GotToken { token: Token { access_token: "BQDlXjfw3obHUviRFiejjozHYnfZSzSW7U3qFml4okxaf2xJwmu9cg96PQKyPomkfdSBPXN00ugkpKvrzRVUy8t48KFIc06CVXhYtaTArNbYgB3hGTt6S8bNLLa3pS18pqzcVGWyxZmz8EQyn65PDN9zAh63dF_7EmT-8LM", expires_in: 3600, token_type: "Bearer", scope: ["streaming", "user-read-playback-state", "user-modify-playback-state", "user-read-currently-playing", "user-read-private"] } }
[Vollibrespot] vollibrespot::meta_pipe: ApiToken::<Token { access_token: "BQDlXjfw3obHUviRFiejjozHYnfZSzSW7U3qFml4okxaf2xJwmu9cg96PQKyPomkfdSBPXN00ugkpKvrzRVUy8t48KFIc06CVXhYtaTArNbYgB3hGTt6S8bNLLa3pS18pqzcVGWyxZmz8EQyn65PDN9zAh63dF_7EmT-8LM", expires_in: 3600, token_type: "Bearer", scope: ["streaming", "user-read-playback-state", "user-modify-playback-state", "user-read-currently-playing", "user-read-private"] }>
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
[Vollibrespot] : Track "Stil" loaded
[Vollibrespot] vollibrespot::meta_pipe: PlaybackStopped { track_id: SpotifyId(u128!(39326327933985369058526703245583919820)) }
[Vollibrespot] mdns::fsm: received question: IN _spotify-connect._tcp.local
[Vollibrespot] librespot_connect::spirc: kMessageTypePlay "NCASE" 62d0d0527bbc7c11455829269137e01d686fdc65 3 1554525464188
[Vollibrespot] librespot_playback::player: command=Play
[Vollibrespot] vollibrespot::meta_pipe: Play { track_id: SpotifyId(u128!(39326327933985369058526703245583919820)), position_ms: 352274 }
[Vollibrespot] vollibrespot::meta_pipe: PlaybackStarted { track_id: SpotifyId(u128!(39326327933985369058526703245583919820)) }
[Vollibrespot] vollibrespot::meta_pipe: SinkActive
[Vollibrespot] librespot_connect::spirc: kMessageTypePause "NCASE" 62d0d0527bbc7c11455829269137e01d686fdc65 4 1554525470894
[Vollibrespot] vollibrespot::meta_pipe: Pause { track_id: SpotifyId(u128!(39326327933985369058526703245583919820)), position_ms: 352274 }
[Vollibrespot] librespot_playback::player: command=Pause
[Vollibrespot] vollibrespot::meta_pipe: SinkInactive
[Vollibrespot] vollibrespot::meta_pipe: PlaybackStopped { track_id: SpotifyId(u128!(39326327933985369058526703245583919820)) }
[Vollibrespot] librespot_connect::spirc: kMessageTypePause "" webapi-4ced2e7c73484127be5d36015752eb43 1894800064 1554525476202
[Vollibrespot] : volStop
```

**Comment by ashthespy** [comment]
> 
> 
> So some more trial and error and I got it working.
> 
> Here's the steps I took:
> 
>     1. Changed Mixer Type to None and was able to get playback!  BUT no volume control via Spotify.
>     2. Cycled through v0.1.2 , .3 and .4 still: Playback, but no volume control.

You should have gotten internal software volume control with this setup - i.e 0-100% where 100% is the current Volumio volume.
 
>     3. Ran the commands to setup new mixer: Playback, but no volume control.

1. What version of Volumio are you running?
1. Could you try the steps under `Check card/mixer` steps a few posts back when you go through the above steps (Mixer None and Hardware). This is only required for .4 and latest plugin version.
1. Also the output of `startconnect.sh` would be helpful for each of those Mixers (minus login info of course ;-))
