### ISSUE TITLE
Volspotconnect2 broken by latest Spotify ?

### ISSUE THREAD

**Issue by DBMandrake** [balbuze/volumio-plugins#225]
Spotify on my iPhone updated itself 3 days ago, today was the first time I've tried to send to volspotconnect2 since then, and it looks like the Spotify update may have broken things again ?

The symptoms are different to what I have ever seen before after a Spotify update - Volumio still appears in the Bonjour generated list of available devices in the Spotify app, however attempting to connect to it does absolutely nothing.

No "conecting...." then giving up a few seconds later. Just no response at all, and no errors. Worse still, even with debug mode enabled in the plugin there is absolutely nothing in the system journal on the volumio box when attempting to connect, suggesting that the client isn't even trying to connect, so I have no clue what is happening and can't offer any debug logs since nothing is logged.

If I try to send the Spotify stream to Spotify connect on my Xbox One it works perfectly, which rules out network issues etc... I've tried rebooting both phone and volumio, etc.

Anyone else having an issue in the last few days ? Pretty sure it was working for me last weekend prior to the Spotify app update.

**Comment by ashthespy** [comment]
Does it work if you use your credentials to login?

**Comment by DBMandrake** [comment]
Ah, good spot! I didn't think to try that.

Yes, if I disable Multi-user mode and enter my Spotify credentials it works again. :)

Although I have tried using credentials a long time ago (maybe a year ago ?) since then I've been using Multi-User mode without credentials up until about as recently as last weekend.

Can I assume that since you were so quick to pick a workaround that worked you already have suspicions about the cause ?

**Comment by ashthespy** [comment]
@DBMandrake Not really - I was recently facing issues with the zeroconf/mdns login on my Windoze client, while things worked flawlessly with my Android client. I went digging a little but all fingers pointed to issues from Spotify's side. I pulled some logs off the official client:
```shell
21:10:53.486 E [mdns_discovery.cpp:201  ] The I/O operation has been aborted because of either a thread exit or an application request
21:10:58.726 D [gaia_manager.cpp:1146   ] GAIA: TIMING(350742484) GaiaManager::sendHelloHelper
21:11:01.746 D [gaia_manager.cpp:1160   ] GAIA: GaiaManager::hermesDeviceCheck
21:11:03.749 E [mdns_discovery.cpp:201  ] The I/O operation has been aborted because of either a thread exit or an application request
21:11:09.754 E [mdns_discovery.cpp:201  ] The I/O operation has been aborted because of either a thread exit or an application request
``` 

But yeah, they should fix it soon hopefully!

**Comment by lycha** [comment]
Hi, i have a similar issue. I've updated the plugin to 0.9.1 version and Spotify does not recognize volumio. I was using multi user mode but even when I've switched to single it doesn't work. 
I'm using Spotify on Android

**Comment by ashthespy** [comment]
@lycha Logs please!

**Comment by lycha** [comment]
Here's the link to generated logs: http://logs.volumio.org/volumio/Qtg480o.html

**Comment by ashthespy** [comment]
There is something wrong with your `startconnect.sh`. And the daemon
doesn't start.

**Comment by lycha** [comment]
Thanks for quick reply. How can I fix it? I didn't do any code modifications in volumio instance and I have only 2 plugins installed. The issue was probably triggered by the update. 
My first idea to fix it is to reinstall volumio and I'm not a fan of this solution. 
I've already tried to reinstall the plugin, reinstallation process went well but I can see in logs that after starting the deamon it constantly fails with the same error http://logs.volumio.org/volumio/jtNMxqv.html

Do you have any idea how I can fix it?

**Comment by ashthespy** [comment]
Enable ssh, open up a prompt and then you should be able to view the file with 
```shell
cat /data/plugins/music_services/volspotconnect2/startconnect.sh
```

**Comment by PabloCasson** [comment]
Hi my Spotify stopped connecting with the plugin last night. If I turn off multiroom in the plugin GUI and input my spotfiy username and password then the problem is sorted and I can connect. 

I'm just wondering if this is the only fix as it was quite handy when any one in the family could play on the speaker using their own account, which I don't think will work with multiroom switched off.

**Comment by ashthespy** [comment]
@PabloCasson you probably meant multiuser correct?
What Spotify client are you on? As posted in https://github.com/balbuze/volumio-plugins/issues/225#issuecomment-481766826, I was having issues with the official client on windows, but not with the android client. I don't really think they have changed how the multiuser is implemented, but will test when I get back to my device.

**Comment by DBMandrake** [comment]
Just wanted to let you know that I've just updated to the 0.9.3 / April 30th release and the problem with multi-user mode seems to be fixed - I've gone back to using multi-user mode without credentials.
