### ISSUE TITLE
spotifyconnect2 crashes when trying to stop volumio

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#23]
Hi Balbuze

I installed your plugin but it keeps crashing (randomly).
it works when i stop volumio myself, but when there is music playing
it crashes.

when i run ./startconnect.sh by hand I get this

volumio@woonkamer:/data/plugins/music_service/volspotconnect2$ sudo ./startconnect.sh
INFO:librespot::main_helper: librespot 3331338 (2016-12-30). Built on 2016-12-30.
INFO:librespot::session: Connecting to AP sto3-accesspoint-a66.ap.spotify.com:4070
INFO:librespot::session: Authenticated !
Using alsa sink
DEBUG:librespot::spirc: kMessageTypeHello "woonkamer1" fde5c8b55b80c1285408fe6afe4ce0647c5cc4d9 1 1485725474090
DEBUG:librespot::spirc: kMessageTypeNotify "BRANKO" cf27014524cb8d7a99544d69e06cac826ccacbd6 2 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamer" 56aff1562d26b8ac066582f2faaac0055d603bd9 190 1485721929816
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamert" acf84e51aae6cddf3b2ff713052a65e3d2a0af8c 168 1485722350726
DEBUG:librespot::spirc: kMessageTypeNotify "BRANKO" cf27014524cb8d7a99544d69e06cac826ccacbd6 271 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 10 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "Volumio" 5ea9b5fd-6fff-4a3c-9ae8-1ad709a12406 479 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 212 1485725406241
DEBUG:librespot::spirc: kMessageTypeHello "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 213 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "woonkamer1" fde5c8b55b80c1285408fe6afe4ce0647c5cc4d9 2 1485725474090
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamert" acf84e51aae6cddf3b2ff713052a65e3d2a0af8c 169 1485722350726
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamer" 56aff1562d26b8ac066582f2faaac0055d603bd9 191 1485721929816
DEBUG:librespot::spirc: kMessageTypeNotify "Volumio" 5ea9b5fd-6fff-4a3c-9ae8-1ad709a12406 480 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "BRANKO" cf27014524cb8d7a99544d69e06cac826ccacbd6 124 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 115 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 115 1485725406241
DEBUG:librespot::spirc: kMessageTypeLoad "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 11 0
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 214 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "woonkamer1" fde5c8b55b80c1285408fe6afe4ce0647c5cc4d9 3 1485725488923
DEBUG:librespot::spirc: kMessageTypeHello "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 215 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "BRANKO" cf27014524cb8d7a99544d69e06cac826ccacbd6 125 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "woonkamer1" fde5c8b55b80c1285408fe6afe4ce0647c5cc4d9 4 1485725488923
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamer" 56aff1562d26b8ac066582f2faaac0055d603bd9 192 1485721929816
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamert" acf84e51aae6cddf3b2ff713052a65e3d2a0af8c 170 1485722350726
DEBUG:librespot::spirc: kMessageTypeNotify "Volumio" 5ea9b5fd-6fff-4a3c-9ae8-1ad709a12406 481 1485725488923
INFO:librespot::player: Load Done
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 116 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 116 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 216 1485725406241
DEBUG:librespot::spirc: kMessageTypeNotify "woonkamer1" fde5c8b55b80c1285408fe6afe4ce0647c5cc4d9 5 1485725489212
DEBUG:librespot::spirc: kMessageTypePlay "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 12 0
INFO:librespot::util: Running ./onstart1.sh
Sending stop
INFO:librespot::util: Exit status: exit code: 0
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
DEBUG:librespot::spirc: kMessageTypeNotify "woonkamer1" fde5c8b55b80c1285408fe6afe4ce0647c5cc4d9 6 1485725494161
{ status: 'stop',
  position: 1,
  title: 'Unknown - Arabix By Twilight Circus Dub Soundsystems',
  artist: '',
  album: null,
  albumart: '/albumart',
  uri: 'http://192.240.97.69:8909/stream',
  trackType: 'webradio',
  seek: 0,
  duration: 0,
  samplerate: '',
  bitdepth: '',
  channels: 0,
  random: null,
  repeat: null,
  consume: false,
  volume: 50,
  mute: false,
  stream: 'webradio',
  updatedb: false,
  volatile: false,
  service: 'webradio' }

DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 217 1485725494161
DEBUG:librespot::spirc: kMessageTypeHello "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 218 1485725494161
DEBUG:librespot::spirc: kMessageTypeHello "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 219 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 220 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "BRANKO" cf27014524cb8d7a99544d69e06cac826ccacbd6 126 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "BRANKO" cf27014524cb8d7a99544d69e06cac826ccacbd6 127 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamer" 56aff1562d26b8ac066582f2faaac0055d603bd9 194 1485721929816
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamer" 56aff1562d26b8ac066582f2faaac0055d603bd9 193 1485721929816
DEBUG:librespot::spirc: kMessageTypeNotify "woonkamer1" fde5c8b55b80c1285408fe6afe4ce0647c5cc4d9 7 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "woonkamer1" fde5c8b55b80c1285408fe6afe4ce0647c5cc4d9 8 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamert" acf84e51aae6cddf3b2ff713052a65e3d2a0af8c 172 1485722350726
DEBUG:librespot::spirc: kMessageTypeNotify "Slaapkamert" acf84e51aae6cddf3b2ff713052a65e3d2a0af8c 171 1485722350726
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 117 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 118 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "Volumio" 5ea9b5fd-6fff-4a3c-9ae8-1ad709a12406 482 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "Volumio" 5ea9b5fd-6fff-4a3c-9ae8-1ad709a12406 483 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 117 1485725494161
DEBUG:librespot::spirc: kMessageTypeNotify "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 118 1485725494161
DEBUG:librespot::spirc: kMessageTypePause "Wileyfox Swift" e69f00bf8833dd5e2e4b03ac9ad76b00586ab1ef 13 0
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837

the last error comes when i stop spotify in the app.

Hope you can fix it. for now stucking on #1 

thanks

**Comment by balbuze** [comment]
this feature has been removed.....
