### ISSUE TITLE
Worst plugin I've ever seen

### ISSUE THREAD

**Issue by by81** [balbuze/volumio-plugins#231]
DELETED because it was just insults from a poor guy...

**Comment by balbuze** [comment]
Poor guy you are....

**Comment by by81** [comment]
I always wanted to get that working but no chance! Who is poor at that time?

**Comment by balbuze** [comment]
Don't expect any help anymore

**Comment by by81** [comment]
With or without you that will not work so it doesn't matter! Thanks for nothing! I had the dream of showing people the difference of DACs with the help of Volumio but unfortunately the Spotify plugin do not work at all. I am a great Open Source Lover but Volumio and Spotify do not work at all for daily use. Not your fault at all but you got it! Sorry for that! I don't think you will get that working I think! But thank you for your help as I thought I needed it. The platform and your plugin is obviously not what I expect for daily use! Thank you nevertheless and keep working!
