### ISSUE TITLE
Headphone equalization 

### ISSUE THREAD

**Issue by Kandyis** [balbuze/volumio-plugins#233]
Hi,

There is a database with equalization settings for lots of headphones:
https://github.com/jaakkopasanen/AutoEq

I was wondering if I could use Volumio brutefir plugin to use these filters? Or do I need to change them somehow? 
For example settings for Sennheiser HD 650: 
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Sennheiser%20HD%20650

**Comment by balbuze** [comment]
thank you for the tip! I tested it and yes, wav file given works with the plugin! I can't say now if it sounds better, but it works!

**Comment by balbuze** [comment]
![image](https://user-images.githubusercontent.com/12850139/57986751-404e1000-7a79-11e9-8698-5144550bc8e7.png)

**Comment by Kandyis** [comment]
It works for me as well. There are preamp values you need to set for parametric filters. If I need -6 db should I choose Input Attenuation 6 in Volumio?

**Comment by merlin2222** [comment]
> It works for me as well. There are preamp values you need to set for parametric filters. If I need -6 db should I choose Input Attenuation 6 in Volumio?

Yes, you should.

**Comment by Kandyis** [comment]
> But as it says you need -6.8dB on the link you provided you should actually set Input Attenuation to 8dB

Did you meant 7 db? Because this would be the next integer. 
The filter size is set to 65536 and the filters seem to work correctly, I cannot yet tell the difference from my windows pc with equalizer apo + peace.

**Comment by merlin2222** [comment]
> > But as it says you need -6.8dB on the link you provided you should actually set Input Attenuation to 8dB
> 
> Did you mean 7 db? Because this would be the next integer.

No, I meant 8 db. Currently BruteFIR accepts only even values for input attenuation so next even integer is 8.

> The filter size is set to 65536 and the filters seem to work correctly, I cannot yet tell the difference from my windows pc with equalizer apo + peace.

In that case 65536 is the correct filter size.

**Comment by balbuze** [comment]
One more thing. When you do 'sudo journalctl -f' while playing, you'll see if clipping occurs. A message like 'peak 2/1.25' appears in that case. If so, increase attenuation.

**Comment by Kandyis** [comment]
Thanks guys! I tested it without attenuation and it indeed showed lots of peaks. With 8db attenuation there is no clipping.

**Comment by nicosea** [comment]
I am using Volumio Simple Equalizer and I would like to use these settings:
https://github.com/jaakkopasanen/AutoEq/blob/master/results/innerfidelity/sbaf-serious/Sennheiser%20HD%20660%20S/Sennheiser%20HD%20660%20S%20FixedBandEQ.txt

Each point in a bar is equal to 1db? I mean if I want to get:
Filter 1: ON PK Fc 31 Hz Gain 6.7 dB Q 1.41
Should I slide up the first plugin column 31Hz to +6.5?
