### ISSUE TITLE
Installer stuck at 'Downloading plugin'

### ISSUE THREAD

**Issue by kls0e** [balbuze/volumio-plugins#234]
Hi,

since April 31st release, when installing, the installer is stuck: 
`$ volumio plugin install

returns:

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin`

**Comment by balbuze** [comment]
Hi,
What plugin are you talking about?

**Comment by matthias-klose** [comment]
pardon, that is volspotconnect2.

**Comment by ashthespy** [comment]
Have you changed the default password of Volumio - the plugin installer won't work in that case.

**Comment by 01findus** [comment]
I have the same issue, with Volumio 2.657 and Volspotconnect 0.9.7.

And yes I can confirm that I changed the volumio user password, but after changing the password back the issue that the installation of the plugin via the gui stops at the download remains!

Best Regards
Alexander
