### ISSUE TITLE
using wrong playback device.

### ISSUE THREAD

**Issue by CodingGhost** [balbuze/volumio-plugins#236]
it uses the wrong playback device, but how do I force it to use the correct one? If I set it in the startconnect.sh it will get overwritten..
Edit: I created a workaround by chowning the startconnect.sh to root and doing a chmod 755.
but still, this is a bug.

**Comment by balbuze** [comment]
what is your device, mixer? tthe plugin use the same output than volumio. So disable and re enable the plugin if this is not the correct output

**Comment by CodingGhost** [comment]
My alsa device name would be plughw:0, but the plugin wants to use plughw:5. Enable/disable or even reinstall did not help.
Where exactly does the llugin source this information? Then I can go look here if it really is ..:5

**Comment by balbuze** [comment]
Do you have sound with the plugin?

**Comment by CodingGhost** [comment]
No, only after my little mod in the start script. Without it I can see the errors in journalctl, cannot open alsa device, no such file or directory.

**Comment by ashthespy** [comment]
>My alsa device name would be plughw:0, but the plugin wants to use plughw:5. Enable/disable or even reinstall did not help.
> Where exactly does the llugin source this information? Then I can go look here if it really is ..:5

Try re-doing the playback device setup instead as this information is obtained via the Volumio exposed api - so unless you have another plugin configuring the audio output, something might have been broken in the Audio device setup in Volumio.
