### ISSUE TITLE
Suggestion: optional bypass for software volume control.

### ISSUE THREAD

**Issue by KTZ228** [balbuze/volumio-plugins#239]
For some of us who use an I2S transport hat (like the Digione from Allo), having the best possible audio quality is key. So that is why I think many of us would appreciate it if there was a setting to bypass the software audio mixer, and thus disable software volume control.

**Comment by balbuze** [comment]
are you talking about volspotconnect2?

**Comment by KTZ228** [comment]
I think so, your plugin is the one that you can also download as a plugin through the Volumio interface right?

**Comment by balbuze** [comment]
spotify connect, right?
I could add a switch to choose to use or not internal librespot mixer. But you'll probaly get the same sound than setting it to 100%

**Comment by KTZ228** [comment]
It would be really great if you could add such a switch!! Does the plugin automatically update or would I have to download it manually?

**Comment by balbuze** [comment]
If I do it, there will be two steps : the first, a dev version to check if it work as expected... need a manual installation.
If everything is fine, it will be published as a "standard' plugin :-)

**Comment by KTZ228** [comment]
Nice!! Thanks for the help and keep up the good work!

**Comment by KTZ228** [comment]
Is there any way I could help adding this feature?

**Comment by JesperJust** [comment]
I second this proposal. Besides from the audio quality issue it would also prevent the situation where several people are using the same volspotconnect2/volumio and some are controlling the sound volume on the amplifier and some in the spotify app. This may lead to a situation where the amplifier is turned up to a level that is okay when volume is set to 30% in one users spotify app, but far to loud when the next user is coming along and playing with volume set to 100% in his spotify app. I hope you get my meaning :)

**Comment by ashthespy** [comment]
I've managed to implement this - https://github.com/ashthespy/librespot/commit/6e369f079000f6f13af3f53d37aff432e3ab02a3. This adds an option to disable the volume control on the Spotify Client. 

I haven't had much time to make a new release, but until then you could play around with this [vollibrespot.zip](https://github.com/ashthespy/Vollibrespot/files/3370580/vollibrespot.zip) to test. 
The new control flag to set (via `startconnect.sh` would be `volume-ctrl`:
```
"volume-ctrl",
 "Volume control type - [linear, log, fixed]. Default is logarithmic",
```

**Comment by balbuze** [comment]
Thanks! I'm going to try it and update the plugin.

**Comment by ashthespy** [comment]
@balbuze I have already made the updates to the plugin, will make a PR for it this evening..
