### ISSUE TITLE
Odroid C2

### ISSUE THREAD

**Issue by chsims1** [balbuze/volumio-plugins#24]
volspotconnect.service - Volspotconnect Daemon
   Loaded: loaded (/etc/systemd/system/volspotconnect.service; disabled)
   Active: active (running) since Wed 2017-02-08 10:39:26 UTC; 2min 34s ago
 Main PID: 936 (bash)
   CGroup: /system.slice/volspotconnect.service
           ├─936 /bin/bash /data/plugins/music_service/volspotconnect/spotify-connect-web/startconnect.sh
           └─938 avahi-publish-service -s Volumio _spotify-connect._tcp 4000 VERSION=1.0 CPath=/login/_zeroconf

Feb 08 10:39:27 volumio volumio[936]: File "runpy.py", line 180, in run_module
Feb 08 10:39:27 volumio volumio[936]: File "runpy.py", line 72, in _run_code
Feb 08 10:39:27 volumio volumio[936]: File "/data/plugins/music_service/volspotconnect/spotify-connect-web/main.py", line 14, in <module>
Feb 08 10:39:27 volumio volumio[936]: from connect import Connect
Feb 08 10:39:27 volumio volumio[936]: File "/data/plugins/music_service/volspotconnect/spotify-connect-web/connect.py", line 9, in <module>
Feb 08 10:39:27 volumio volumio[936]: from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callback...ck_setup
Feb 08 10:39:27 volumio volumio[936]: File "/data/plugins/music_service/volspotconnect/spotify-connect-web/console_callbacks.py"...<module>
Feb 08 10:39:27 volumio volumio[936]: audio_arg_parser.add_argument('--mixer', '-m', help='alsa mixer name for volume control', ...rs()[0])
Feb 08 10:39:27 volumio volumio[936]: IndexError: list index out of range
Feb 08 10:39:27 volumio volumio[936]: Failed to execute script loader
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by chsims1** [comment]
Quite a complex output..hope it means more to you than me ;)

**Comment by balbuze** [comment]
Thanks I'll have a look later. Could paste startconnect.sh please after removing credentials and aplay -l

**Comment by chsims1** [comment]
sorry can you just point me at the location of startconnect.sh before I start searching?

**Comment by chsims1** [comment]
aplay -l 

`**** List of PLAYBACK Hardware Devices ****
card 0: ODROIDHDMI [ODROID-HDMI], device 0: I2S dit-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: ODROIDDAC [ODROID-DAC], device 0: I2S pcm5102-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`

**Comment by chsims1** [comment]
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect/spotify-connect-web
./spotify-connect-web  --username '' --password '' --bitrate 320 --name 'Volumio' --playback_device softvolume --mixer 'SoftMaster'  --mixer_device_index softvolume --dbrange 45  &
avahi-publish-service -s 'Volumio' _spotify-connect._tcp 4000 VERSION=1.0 CPath=/login/_zeroconf

**Comment by balbuze** [comment]
Hummm. Seems your are victim of something I reported in volumio issues. The value returned by the system is not what expected. For the mixer index. Don't know why. But you can change the last softvolume by 1 . And restart. But any change in config will replace it. The only way I found was to reflash.

**Comment by balbuze** [comment]
https://github.com/volumio/Volumio2/issues/935
