### ISSUE TITLE
VOLUMIO BAUER FILTER PLUGIN: Installation fails

### ISSUE THREAD

**Issue by mbrennwa** [balbuze/volumio-plugins#240]
I followed the instructions to download and install the volumiobauerfilter at https://github.com/balbuze/volumio-plugins/tree/master/plugins/audio_interface/volumiobauerfilter .

The install command failed:
----------------------------------------------------------------------------------------
volumio@volumiomb:~/volbinauralfilter$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating folder on disk
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying Plugin into location
Progress: 70
Status :Installing dependencies
Progress: 0
Status :The following error occurred when installing the plugin: Error
----------------------------------------------------------------------------------------

What can I do to make this work?

**Comment by ashthespy** [comment]
Have you changed the password for the default volumio user account? The plugin installer unfortunately doesn't work in that case.

**Comment by mbrennwa** [comment]
Yes, first thing I did was to change the password for the volumio account. Leaving it as at the default setting would be a security issue. I have a hard time to believe the plugin installer needs the volumio password at the default setting. Really?

**Comment by ashthespy** [comment]
Oh, your preaching to the choir here, but it's not specific to this plugin, but is a limitation of the Volumio.  https://github.com/volumio/Volumio2/issues/1192

**Comment by AlleyCat2017** [comment]
1) does this plugin designed to work on the Raspberry Pi version of Volumio?
2) Why the install failed? Any logs are generated?
3) The Volumio rev is Volumio-2.632-2019-10-03-pi. The plugin rev is Oct. 6th. Volumio settings and user password are default. Has this configuration been tested?
4) If the problem with Volumio, any older revision I should test?
5) The plugin install via SSH also fails for the Volumio example found at https://?volumio.github.io/docs/Plugin_System/Plugin_System_Overview.html
6) Any instructions to install the plugin manually? 
7) How to uninstall manually the plugin? The UI uninstall is not responsive and doesn't work.

Thank you.

**Comment by balbuze** [comment]
>     1. does this plugin designed to work on the Raspberry Pi version of Volumio?
> 
>     2. Why the install failed? Any logs are generated?
> 
>     3. The Volumio rev is Volumio-2.632-2019-10-03-pi. The plugin rev is Oct. 6th. Volumio settings and user password are default. Has this configuration been tested?
> 
>     4. If the problem with Volumio, any older revision I should test?
> 
>     5. The plugin install via SSH by Volumio example works.  found at https://volumio.github.io/docs/Plugin_System/Plugin_System_Overview.html
> 
>     6. Any instructions to install the plugin manually?
> 
>     7. How to uninstall manually the plugin? The UI uninstall is not responsive and doesn't work.
> 
> 
> Thank you.

1 yes
2 Install work fine on my system. But it may seem stuck at 70%, just be patient
3 The plugin in this repo is from December 22th 2018... Where did you get your version?
4 It works with last version of volumio
5-6 Simply read Readme.md in the folder of the plugin....
7 No problem removing it from UI. But if you are stuck, remove the folder /data/plugins/audio_interface/volbinauralfilter/
And if not better, reflash your SD card
