### ISSUE TITLE
Spotify - Next track via volume buttons

### ISSUE THREAD

**Issue by autur** [balbuze/volumio-plugins#244]
Hi Balbuze, 
I use android apps that allow you to control tracks via the smartphone volume buttons when the screen is off (it's annoying to always turn on the screen to change tracks), but they don't work with Spotify Connect, i.e., when screen is off and it's streaming to Volumio, the volume buttons don't do anything. Any chance that you will support such functionality in future versions? Or is there some setting/plugin in Volumio that can do what I'm describing?

My setup is LG V30 --> RPI2 (Volumio) --> DAC/AMP

I'm listing some apps that do what I'm describing:
https://play.google.com/store/apps/details?id=frinky.volumeKeys.music.controller
https://play.google.com/store/apps/details?id=com.flar2.volumeskip

**Comment by ashthespy** [comment]
If the native Spotify app on Android doesn't support it, there is nothing the plugin can do to support it. It just listens to commands, and it is up the to the clients to implement such features. 

It does however seem that few people want this feature: [Android-Music-Use-Volume-Buttons-to-Pause-or-Skip-Songs](https://community.spotify.com/t5/Live-Ideas/Android-Music-Use-Volume-Buttons-to-Pause-or-Skip-Songs/idi-p/4623004), you could vote for it there and hope Spotify does something about it :-)

**Comment by autur** [comment]
Forgot to reply to this. The main issue is not that the Spotify does not support this, because the apps I listed do permit switching Spotify tracks with volume buttons. However, this appears to work only when the music is playing on the Android device, not when it's streaming to another device, so in the end, I believe it's a limitation of the third-party apps mentioned, and I probably should be appealing to the app developers.
