### ISSUE TITLE
latest brutefir3 - installation error

### ISSUE THREAD

**Issue by mike38b** [balbuze/volumio-plugins#245]
It seems like the latest version fails to install.
Tried clean volumio install as well as different volumio versions and always get the same error:

Status :Installing dependencies
Progress: 0
Status :The following error occurred when installing the plugin: Error

**Comment by NeilBrwk** [comment]
Same here. 
....
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 70
Status :Installing dependencies
Progress: 0
Status :The following error occurred when installing the plugin: Error

Which logs can I post?

**Comment by balbuze** [comment]
yep you are right. let me check what happens...

**Comment by wildekek** [comment]
Same here. Any hints on how to force an uninstall? I tried the UI and the ./uninstall.sh script, but I still see it in the plugin manager. If I can wipe it properly then I can test some older versions and let you know from which commit the problem started.

**Comment by balbuze** [comment]
please before you install the new version I just published, remove previous files : rm -Rf brutefir*
and do as explain in readme. It should be ok now. Let me know

**Comment by wildekek** [comment]
> It should be ok now. Let me know
Confirmed, works. Thanks man!

**Comment by NeilBrwk** [comment]
Perfect, thank you.

**Comment by balbuze** [comment]
Could you tell what DAC you are using, and how you generate your filters ? Thanks!

**Comment by wildekek** [comment]
I use an Arcam irDac (v1) over USB. Install went fine with your latest fix, but have not been able to output any audio with brutefir enabled though. I'll create a new issue for that once I have some debug output.

**Comment by balbuze** [comment]
have you an hw volume mixer?

**Comment by wildekek** [comment]
yep, (tested and seems to work fine with brutefir disabled)

**Comment by balbuze** [comment]
most of the time, it is due to a wrong output format, or sample rate. And very important is to follow that 
- a working volumio setup
- enable the plugin, wait a least 20 sec
- try to play something
- if no sound, change output format ( should be detected)
- try 48000 as sample rate
but 'sudo journalctl -f' gives info about the problem

**Comment by wildekek** [comment]
Yep, works with 32bit and a little patience :) Thanks!

**Comment by balbuze** [comment]
I improve the hw detection, and now it (should) set automatically a correct value.
Many other improvements...

**Comment by mike38b** [comment]
Thank you for quick fix.

Next question is irrelevant to the topic:
I noticed that there is a out of sync when streaming to volumio with enabled brutefir3 via shairport sync. 
I.e. when the plugin is enabled the audio is ~1sec behind the video. 
I presume there is no way to avoid it?

**Comment by pirun** [comment]
Hi balbuze,

Got error when install 2020/03/20 version.
It turned out that "install.sh" and "uninstall.sh" lack of execution permission.
Need to fix by chmod +x.

**Comment by balbuze** [comment]
@pirun , to install, just follow instructions in readme.md

**Comment by pirun** [comment]
@balbuze 
Yes, I was following the instructions.

In this step : volumio plugin install
There was some error.
_Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Progress: 30
Status :Creating install location
Progress: 40
Status :Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Progress: 60
Status :Copying plugin to location
Progress: 70
Status :Installing necessary utilities
Progress: 0
Status :An error occurred while installing the plugin Error_

The journalctl showed .
Mar 22 13:16:59 volumio volumio[1050]: info: Downloading plugin at http://127.0.0.1:3000/plugin-serve/brutefir.zip
Mar 22 13:16:59 volumio volumio[1050]: info: END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/brutefir.zip
Mar 22 13:16:59 volumio volumio[1050]: info: Folder /tmp/plugins removed
Mar 22 13:16:59 volumio volumio[1050]: info: Checking if plugin already exists
Mar 22 13:16:59 volumio volumio[1050]: info: Rename folder
Mar 22 13:16:59 volumio volumio[1050]: info: Folder /tmp/downloaded_plugin.zip removed
Mar 22 13:16:59 volumio volumio[1050]: info: Move to category
Mar 22 13:17:08 volumio volumio[1050]: info: Checking if install.sh is present
Mar 22 13:17:08 volumio volumio[1050]: info: Executing install.sh
**Mar 22 13:17:08 volumio sudo[3154]: pam_unix(sudo:auth): authentication failure; logname= uid=1000 euid=0 tty= ruser=volumio rhost= user=volumio
Mar 22 13:17:10 volumio sudo[3154]: pam_unix(sudo:auth): conversation failed
Mar 22 13:17:10 volumio sudo[3154]: pam_unix(sudo:auth): auth could not identify password for [volumio]
Mar 22 13:17:10 volumio sudo[3154]: volumio : 1 incorrect password attempt ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/sh /data/plugins/audio_interface/brutefir/install.sh**

And I found out that /data/plugins/audio_interface/brutefir/install.sh does not have permission to execute.
After chmod +x install.sh in unzip folder one. 
I can install the plugin.
Just curious if it only occurs on me?.

**Comment by balbuze** [comment]
very weird as this part is unchanged for years... I just re tested it and no problem.
How do you unzip the plugin?

**Comment by pirun** [comment]
Exactly the command in readme.md
"miniunzip brutefir.zip -d ./brutefir"

My volumio version VERSION: 2.729

RELEASE DATE: 18-03-2020

**Comment by balbuze** [comment]
are you logged with volumio as user?

**Comment by balbuze** [comment]
or have you changed the default password?

**Comment by pirun** [comment]
> or have you changed the default password?
I do change the password of user "volumio".
I think that you had figured out the problem.

**Comment by balbuze** [comment]
ah, this is an old 'bug' in Volumio...
can you tell me more about your use of the plugin?
device
dac
how you generate filters
more info
thanks!

**Comment by pirun** [comment]
Just got my plugin installed.
Haven't generate filter, plan to do with REW and minidsp umik-1.
RPi3 + audiolab M-DAC.

**Comment by balbuze** [comment]
Do you know that the plugin can generate filter CV with a measure from Rew?
