### ISSUE TITLE
Error Installing - TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by asrinivas** [balbuze/volumio-plugins#25]
Hi, I'm trying to install volspotconnect2 plugin via the web UI, and running into this error:

Downloading plugin at http://127.0.0.1:3000/plugin-serve/volspotconnect2.zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/volspotconnect2.zip
Creating folder on disk
Unpacking plugin
The following error occurred when installing the plugin: TypeError: Cannot read property 'name' of undefined

Do I need to configure something before installing the plugin?

**Comment by balbuze** [comment]
no. Have you downloaded the raw file ? https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/volspotconnect2.zip 
Have you set a new password in volumio?

**Comment by asrinivas** [comment]
I got it to work! I did a factory reset and re-installed the Spotify plugin, then uploaded the zip file you linked to. I was previously browsing to the file here: https://github.com/balbuze/volumio-plugins/blob/master/plugins/music_service/volspotconnect2/volspotconnect2.zip, then clicking "download", which gave me the folder, which I then had to recompress and upload to Volumio. Using your link worked perfectly.

**Comment by balbuze** [comment]
I have to precise one thing. Volspotconnect 2 is just a prototype. I'm working on it. You will face a problem. : No cache size limit...The cache increase and fill the SD card if you never reboot your device or never change Spotify user. I'm writing a script to solve this. I going to push it on the next few days

**Comment by paytufo** [comment]
Can you send me the raw of spotify?
