### ISSUE TITLE
Playback interruptions

### ISSUE THREAD

**Issue by ogroot** [balbuze/volumio-plugins#254]
Running 9 months with Volumio  2.598 and DRC 1.1.5, without problems.
Recently I upgrading to 2.699 and DRC 1.4.2. Since that moment i encounter  frequent playback interruptions. See below the output fromsudo journalctl -f. 

I notice that the interruptions are related to the used bitrate of DRC. The higher the bitrate the worse the interruptions get. 44.1 plays ok. but 96khz is not usable anymore.
The strange thing is that with the old version of Volumio/DRC I could play at 96khz! 
I'm running on a Pi2B could it be that newer versions are compiled differently?

Feb 21 20:36:35  volumio[22232]: BruteFIR v1.0m (November 2013)                                (c) Anders Torger
Feb 21 20:36:35  volumio[22232]: Internal resolution is 64 bit floating point.
Feb 21 20:36:35  volumio[22232]: Creating 4 FFTW plans of size 4096...finished.
Feb 21 20:36:35  volumio[22232]: Loading 16 coefficient sets...finished.
Feb 21 20:36:35  volumio[22232]: Realtime priorities are min = 2, usermax = 1, mid = 3 and max = 4.
Feb 21 20:36:35  volumio[22232]: Warning: no support for clock cycle counter on this platform.
Feb 21 20:36:35  volumio[22232]: Timers for benchmarking may be unreliable.
Feb 21 20:36:36  volumio[22232]: Realtime priority 1 set for cli process (pid 22238)
Feb 21 20:36:36  volumio[22232]: Realtime priority 3 set for input process (pid 22233)
Feb 21 20:36:36  volumio[22232]: Realtime priority 4 set for filter process (pid 22237)
Feb 21 20:36:36  volumio[22232]: Realtime priority 4 set for filter process (pid 22236)
Feb 21 20:36:36  volumio[22232]: Realtime priority 3 set for output process (pid 22239)
Feb 21 20:36:36  volumio[22232]: Fixed I/O-delay is 4096 samples
Feb 21 20:36:36  volumio[22232]: Audio processing starts now
Feb 21 20:37:03  volumio[22232]: ALSA I/O: Could not read audio: Broken pipe.
Feb 21 20:37:03  volumio[22232]: I/O module failed to read (probably) due to buffer underflow on output, aborting.
Feb 21 20:37:03  systemd[1]: brutefir.service: main process exited, code=exited, status=5/NOTINSSTALLED
Feb 21 20:37:03  systemd[1]: Unit brutefir.service entered failed state.
Feb 21 20:37:03  systemd[1]: brutefir.service holdoff time over, scheduling restart.
Feb 21 20:37:03  systemd[1]: Stopping brutefir Daemon...
Feb 21 20:37:03  systemd[1]: Starting brutefir Daemon...
Feb 21 20:37:03  systemd[1]: Started brutefir Daemon.

**Comment by ogroot** [comment]
Ok. tested a bit further in order to narrow down the issue.
I installed the latest version of the DRC plugin on my 'previous' volumio install on a P2B+. 
Results are:

Volumio 2.598 + DRC 1.1.5 :     44.1khz --> OK    48khz --> OK    96khz --> OK 
Volumio 2.598 + DRC 1.4.2 :     44.1khz --> occasional drop   48khz --> NOT OK    96khz --> NOT OK  
Volumio 2.699 + DRC 1.4.2:      44.1khz --> occasional drop   48khz --> NOT OK    96khz --> NOT OK  
So it looks like something happened between 1.1.5 and 1.4.2. 
Are newer version of DRC more system/resource dependent? 
Have some compile options/optimizations changed?

**Comment by ogroot** [comment]
@balbuze : Just let me know if I can help with additional testing / logging, etc.!

**Comment by balbuze** [comment]
humm, I think the problem comes from gere : https://github.com/balbuze/volumio-plugins/commit/3395aad70da3e26fd70b74e6c917eb3a370e1a62#diff-edb2c18f9f2b8f77d1c0374e280d1635 I  changed the number of partition and the priority for process.

**Comment by balbuze** [comment]
it works fine with a RPI >3 but not tested with RPI2.

**Comment by ogroot** [comment]
Thanks for your quick analysis.  I was already afraid that the RPI2 was reaching it limits. 
Although CPU load is never above 26%!?!?
Guess I need to upgrade to a 3 or 4 ?

**Comment by balbuze** [comment]
If you had a working version with a rpi2, by reverting change it should work again. I could prepare a"special"  version to test. I'll try to do that today if you are interested

**Comment by ogroot** [comment]
Thanks for your suggestion. But, I have a backup image of my 'working' installation (Volumio 2.598 + DRC 1.1.5).  So, for the short term I'm fine. 
But if I want to keep up with future new releases/features, I probably have to upgrade to a 3 or 4.

**Comment by ogroot** [comment]
Hi Balbuze,..... unfortunately no good news.
Now running new RP4 and still having these problems!!
Volumio 2.598 + DRC 1.4.2 --> 44.1khz = occasional drop, 48khz = NOT OK, 96khz = NOT OK
Volumio 2.699 + DRC 1.4.2 --> 44.1khz = occasional drop, 48khz = NOT OK, 96khz = NOT OK

Similar output on sudo journalctl -f

Feb 27 15:51:53 volumio[3217]: [40B blob data]
Feb 27 15:51:53 systemd[1]: brutefir.service: main process exited, code=exited, status=5/NOTINSSTALLED
Feb 27 15:51:53 volumio[3217]: ALSA I/O: Could not read audio: Broken pipe.
Feb 27 15:51:53 volumio[3217]: I/O module failed to read (probably) due to buffer underflow on output, aborting.
Feb 27 15:51:53 systemd[1]: Unit brutefir.service entered failed state.
Feb 27 15:51:53 systemd[1]: brutefir.service holdoff time over, scheduling restart.
Feb 27 15:51:53 systemd[1]: Stopping brutefir Daemon...
Feb 27 15:51:53 systemd[1]: Starting brutefir Daemon...
Feb 27 15:51:53 systemd[1]: Started brutefir Daemon.
Feb 27 15:51:53 volumio[3228]: BruteFIR v1.0m (November 2013)                                (c) Anders Torger
Feb 27 15:51:53 volumio[3228]: Internal resolution is 64 bit floating point.
Feb 27 15:51:53 volumio[3228]: Creating 4 FFTW plans of size 4096...finished.
Feb 27 15:51:53 volumio[3228]: Loading 16 coefficient sets...finished.
Feb 27 15:51:53 volumio[3228]: Realtime priorities are min = 2, usermax = 1, mid = 3 and max = 4.
Feb 27 15:51:53 volumio[3228]: Warning: no support for clock cycle counter on this platform.
Feb 27 15:51:53 volumio[3228]: Timers for benchmarking may be unreliable.
Feb 27 15:51:53 volumio[3228]: Realtime priority 1 set for cli process (pid 3232)
Feb 27 15:51:53 volumio[3228]: Realtime priority 3 set for input process (pid 3229)
Feb 27 15:51:53 volumio[3228]: Realtime priority 4 set for filter process (pid 3231)
Feb 27 15:51:53 volumio[3228]: Realtime priority 4 set for filter process (pid 3230)
Feb 27 15:51:53 volumio[3228]: Realtime priority 3 set for output process (pid 3233)
Feb 27 15:51:53 volumio[3228]: Fixed I/O-delay is 4096 samples
Feb 27 15:51:53 volumio[3228]: Audio processing starts now

**Comment by balbuze** [comment]
hello!
sorry for that...
what is your dac?
I'll try to make a new version reversing some change...
I use it for month on a rpi3/I2C allo boss and rpi4/usb DAC without problem though

**Comment by balbuze** [comment]
can you try to drop these 2 files in the plugin folder and save the config in the plugin please?
let's see if better


[brutefir.zip](https://github.com/balbuze/volumio-plugins/files/4263133/brutefir.zip)

**Comment by ogroot** [comment]
It is an Allo DigiOne.  Using Factory_S24_4LE  format
I put the 2 files in the plugin folder, but no difference/improvement.
Not even after restarting the RPI.

**Comment by ogroot** [comment]
you mean the following directory: /data/plugins/audio_interface/brutefir?

**Comment by ogroot** [comment]
Because I stored the new config.json and brutefir.conf.tmpl in this directory......but I do not see the config.json getting updated when I save the configuration?!

**Comment by ogroot** [comment]
Ok. Digging a bit further......  

I changed manually "numb_part" to "8" in /data/configuration/audio_interface/brutefir/config.json

And now it plays correct at 96khz!!!!

**Comment by balbuze** [comment]
oh yes I see the problem when saving values! but you did the good thing!
test deeply and if ok I will release a new version

**Comment by ogroot** [comment]
FYI....... Allo DigiOne using Factory_S24_4LE format:  
numb_part" = "8"  --> OK
numb_part" = "16"  --> OK
numb_part" = "32"  --> NOT OK

**Comment by ogroot** [comment]
One other 'minor' issue I discovered: the format value "Factory_S24_4LE" is not kept after disabling/enabling plugin. Use case:
1. Set config format to "Factory_S24_4LE"
2. Save config
3. Disable plugin
4. Re enable  plugin
5. go to config
6. format is now showing "Factory_S24_LE"  (without the 4)
7. need to correct format setting and save the config again. In order to make it work.

**Comment by ogroot** [comment]
Ok. Working flawless now!!
I played several albums, without any 'interruption'.

Would appreciate if you could release a new version.
Just let me know if I could help with some testing.

**Comment by balbuze** [comment]
Can you check what is in the file hwparam in /data/configuration/audio_interface/brutefir.
There is a routine to detect he capabilities (sample rate and output format) to set the plugin. But in your case it seems the value selected is not correct...

**Comment by ogroot** [comment]
There is no "hwparam" file there...but there is a "hwinfo.json"
Is that what you mean?
This hwinfo.json contains:

_{
"formats":{"value":" S16_LE S24_LE"},
"channels":{"value":"2"},
"samplerates":{"value":" 44100 48000 88200 96000 176400 192000"}
}_

**Comment by balbuze** [comment]
Yes this file. So the value used by the plugin is S24_LE. This value is not good in your case, right?

**Comment by ogroot** [comment]
Indeed. The Allo DigiOne requires "**Factory_S24_4LE**" in order to play.

**Comment by ogroot** [comment]
But the main problem is that in DRC 1.4.2. the format setting will be reset after restart.....
1. After reboot:  config.json contains "output_format": "value": "S24_LE"
2. Change the output format in the plugin UI to : Factory_S24_4LE
3. Save
4. config.json contains now "output_format": "value": "Factory_S24_4LE"
5. Reboot the system (or disable/enable plugin)
6. After reboot/restart 
7. Plugin UI shows again incorrect "S24_LE"
8. Also config.json contains again incorrect "output_format": "value": "S24_LE"

So the setting is updated/changed after reboot or disable/enable plugin

**Comment by balbuze** [comment]
It due to the autoconfig... I should disable it as in some case (yours) the value returned by the Dac cannot be used

**Comment by ogroot** [comment]
Have you changed this autoconfig behaviour recently?
Because I did not have this problem in DRC 1.1.5!

**Comment by balbuze** [comment]
Yes... It was supposed to be an improvement...:grin:

**Comment by ogroot** [comment]
Balbuze
How / where can I download 'old' versions of Brutefir?
I need to fallback to a previous version.

**Comment by balbuze** [comment]
Try this https://github.com/balbuze/volumio-plugins/commit/3395aad70da3e26fd70b74e6c917eb3a370e1a62#diff-edb2c18f9f2b8f77d1c0374e280d1635

**Comment by balbuze** [comment]
Download the zip go in folder and install by using "volumio plugin install"

**Comment by balbuze** [comment]
Wait. This the version just before you need

**Comment by balbuze** [comment]
https://github.com/balbuze/volumio-plugins/blob/1eba24b78f0a1cdbc9016a47a56c8487f31644f7/plugins/audio_interface/brutefir3/brutefir.zip

**Comment by ogroot** [comment]
No. Unfortunately, not an usable version. 
This version is also changing/resetting the  "output_format" after reboot 
"value": "Factory_S24_4LE" -->   "value": "S24_LE"

**Comment by ogroot** [comment]
1.2.4 is not working on 2.703......
DRC plugin config screen is showing errors in fields ([object Object] and VALUE NOT FOUND BETWEEN SELECT OPTIONS)

I'm kind of stuck now.

**Comment by balbuze** [comment]
no, just delete files in /data/configuration/audio_interface/brutefir

**Comment by ogroot** [comment]
Yes. That solved this. But .......
Now - after a reboot - my mounted NAS is not shown anymore under Music Library and all the number of track is 0 in the sources screen...

If I disable the DRC plugin....the NAS and tracks are shown again!

**Comment by balbuze** [comment]
oh....
reboot 
btw,  I'm try a new version right now, if ok I will publish asap

**Comment by ogroot** [comment]
Strange....Rebooting does not always solve the missing NAS
Tried it many time, but rebooting helps in about 50%.  
Sometimes the NAS is visible......sometimes not.

**Comment by ogroot** [comment]
This exception is thrown in /var/log/volumio.log: 

2020-02-28T16:33:42.424Z - info: CoreCommandRouter::executeOnPlugin: mpd , handleBrowseUri
2020-02-28T16:33:42.425Z - info: CURURI: music-library
2020-02-28T16:33:42.426Z - info:  message= [50@0] {} No database, stack=Error:  [50@0] {} No database
    at MpdClient.receive (/volumio/app/plugins/music_service/mpd/lib/mpd.js:63:14)
    at Socket.<anonymous> (/volumio/app/plugins/music_service/mpd/lib/mpd.js:43:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)

**Comment by ogroot** [comment]
This is not thrown when I disable the DRC plugin

**Comment by balbuze** [comment]
version 1.4.3 is out... let me know
- fix fot output format
- fix to 8 partitions for filters
- process management set to auto in brutefir
- remove normalization for drc generation (clipping may occurs if no attenuation set)

**Comment by ogroot** [comment]
Thanks Balbuze!!!
First initial test results and feedback:

Setup:  Volumio 2.703 + DRC 1.4.3.

1. Playback interruption --> solved!
2.  Factory_S24_4LE format  --> solved!
3.  Loosing NAS Music Libary after reboot with DRC enabled --> **NOT solved!**

**Comment by ogroot** [comment]
Tried to reboot several times. Every time the NAS is not shown. 
As soon as I disable DRC. The NAS immediately appears

Shall I create new issue for this? (since it is not related to playback interruption)

**Comment by balbuze** [comment]
Do you use last update of Volumio?

**Comment by balbuze** [comment]
Yes please, open a new issue.

**Comment by ogroot** [comment]
Just created new issue for the disappearing NAS.

Thanks for fixing the Playback interruptions!!!
