### ISSUE TITLE
No DRC playback via RPi Audio Jack

### ISSUE THREAD

**Issue by ogroot** [balbuze/volumio-plugins#256]
DRC is not playing via RPi audio jack.

restarting Brutefir (systemctl restart brutefir) gives the following error:

Mar 19 17:13:24 volumio: BruteFIR v1.0m (November 2013)                                (c) Anders Torger
Mar 19 17:13:24 volumio: Internal resolution is 64 bit floating point.
Mar 19 17:13:24 volumio: Creating 4 FFTW plans of size 16384...finished.
Mar 19 17:13:25 volumio: Loading 16 coefficient sets...finished.
Mar 19 17:13:25 volumio: Realtime priorities are min = 2, usermax = 1, mid = 3 and max = 4.
Mar 19 17:13:25 volumio: Warning: no support for clock cycle counter on this platform.
Mar 19 17:13:25 volumio: Timers for benchmarking may be unreliable.
Mar 19 17:13:25 volumio: Filters in process 0: 0 2
Mar 19 17:13:25 volumio: Filters in process 1: 1 3
Mar 19 17:13:25 volumio: **ALSA I/O: Could not link alsa devices: File descriptor in bad state.**
Mar 19 17:13:25 volumio: Failed to init output device.
Mar 19 17:13:25 volumio: Failed to initialise digital audio interfaces.

Output section of volumio-brutefir-config is:
#-----------------
#Output configuration
#-----------------
output "l_out","r_out"{
device: "alsa" {device: **"hw:0";** ignore_xrun: true; };
sample: "S16_LE";   # sample format
channels: 2;       # number of open channels / which to use
delay:0,0; #delay for each channel if set in the plugin
dither: false;
};

speaker-test -D hw:0   works OK!

What am I doing wrong?

**Comment by balbuze** [comment]
Hi! I saw this in the past... let me remember... Did you install an other plugin such as equalizer?

**Comment by balbuze** [comment]
44.1kHz?

**Comment by ogroot** [comment]
I tried: 44100 and 48000. Both give the same problem.

**Comment by ogroot** [comment]
No other plugin installed.  Bare RPi2 without cards or DAC

**Comment by balbuze** [comment]
I'm testing with rpi4... same problem
