### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by CodingGhost** [balbuze/volumio-plugins#257]
Mar 24 11:14:54 volumio volumio[2428]: [Vollibrespot] : ConnectRequest: "Spotify/112800721 Win32/0 (PC desktop)"
Mar 24 11:15:04 volumio volumio[2428]: [Vollibrespot] : ConnectRequest: "Spotify/112800721 Win32/0 (PC desktop)"
Mar 24 11:15:08 volumio volumio[2428]: [Vollibrespot] : ConnectRequest: "Spotify/112800721 Win32/0 (PC desktop)"
Mar 24 11:15:12 volumio volumio[2428]: [Vollibrespot] : Connecting to AP "gew1-accesspoint-b-btcn.ap.spotify.com:4070"
Mar 24 11:15:12 volumio volumio[2428]: [Vollibrespot] : SessionError: Connection reset by peer (os error 104)
Mar 24 11:15:14 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Mar 24 11:15:14 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Mar 24 11:15:14 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Mar 24 11:15:14 volumio systemd[1]: Started Volspotconnect2 Daemon.
Mar 24 11:15:14 volumio volumio[2914]: vollibrespot v0.1.9 c98fd5d 2019-11-08 (librespot 4674946 2019-11-08) -- Built On 2019-11-08
Mar 24 11:15:14 volumio volumio[2914]: [Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
Mar 24 11:15:14 volumio volumio[2914]: [Vollibrespot] : ConnectRequest: "Spotify/8.5.49 Android/28 (COL-L29)"
Mar 24 11:15:25 volumio volumio[2914]: [Vollibrespot] : ConnectRequest: "Spotify/112800721 Win32/0 (PC desktop)"
Mar 24 11:15:25 volumio volumio[2914]: [Vollibrespot] : Login error for user "vi37elpfrltaj8hldw2k6n4yq": MAC mismatch

**Comment by ashthespy** [comment]
`SessionError: Connection reset by peer (os error 104)` and `MAC mismatch` looks like your having net issues, try reconnecting by restarting the plugin again?

**Comment by CodingGhost** [comment]
I tried everything, from reinstalling the plugin to reinstalling volumio. Also this is not the only problem, most of the time if it does connect I cannot pause or do anything. but you are right, it sounds like a net problem. But everything else works normal..?

**Comment by ashthespy** [comment]
To rule out mdns and other network issues, try logging in with your credentials and confirm everything is working as expected..

**Comment by robfrye** [comment]
I also can't connect now.  This might be helpful:

`xxxxxxx@xxxxxxxxxxxxx:~$ sudo journalctl -f -o cat -u volspotconnect2.service
33:   0x9e03c0 - std::rt::lang_start_internal::h87508684140f3dc4
at src/libstd/rt.rs:48
34:   0x4643f8 - main
35: 0xb6cd4294 - __libc_start_main
volspotconnect2.service holdoff time over, scheduling restart.
Stopping Volspotconnect2 Daemon...
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.1.9 c98fd5d 2019-11-08 (librespot 4674946 2019-11-08) -- Built On 2019-11-08
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
[Vollibrespot] : ConnectRequest: "Spotify/112900592 OSX/0 (MacBookPro12,1)"
[Vollibrespot] : ConnectRequest: "Spotify/112900592 OSX/0 (MacBookPro12,1)"`

**Comment by ashthespy** [comment]
@robfrye still having the issue? Unfortunately the whole stack trace isn't captured, thus can't make out if it's same issue..

**Comment by robfrye** [comment]
Never got it to connect.  Happy to send you better logs if you tell me how.

I ended up installing the old Spotify Connect plugin in the meantime

**Comment by CodingGhost** [comment]
what old plugin do you mean?

**Comment by ashthespy** [comment]
>I ended up installing the old Spotify Connect plugin in the meantime 

i.e [`volsptoconnect`](https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect)?

Could you try out a new beta - https://github.com/balbuze/volumio-plugins/issues/259#issuecomment-607156749 that should help in most scenarios?

**Comment by robfrye** [comment]
yes volspotconnect

**Comment by ashthespy** [comment]
Okay, let me know if you still have issues when switch back to this one, and for future ref, full logs (from boot) are found with: 
```bash
journalctl -b -u volspotconnect2.service
```

**Comment by robfrye** [comment]
> Okay, let me know if you still have issues when switch back to this one, and for future ref, full logs (from boot) are found with:
> 
> ```shell
> journalctl -b -u volspotconnect2.service
> ```

I switched it back on, still won't connect and that command results in this:

`xxxxxxx@xxxxxxxx:~$ journalctl -b -u volspotconnect2.service
No journal files were found.`

**Comment by ashthespy** [comment]
You probably need a `sudo` before the command..

**Comment by robfrye** [comment]
So it is working now

**Comment by CodingGhost** [comment]
I will reinstall volumio and report back. It behaves very strange lately, then im gonna try the new version

**Comment by robfrye** [comment]
Back to not connecting:

`volumio@berrypie:~$ sudo journalctl -b -u volspotconnect2.service
-- Logs begin at Fri 2020-04-03 01:34:59 UTC, end at Fri 2020-04-03 01:36:23 UTC. --
Apr 03 01:35:19 berrypie systemd[1]: Starting Volspotconnect2 Daemon...
Apr 03 01:35:19 berrypie systemd[1]: Started Volspotconnect2 Daemon.
Apr 03 01:35:19 berrypie volumio[1132]: vollibrespot v0.1.9 c98fd5d 2019-11-08 (librespot 4674946 2019-11-08) -- Built On 2019-11-08
Apr 03 01:35:19 berrypie volumio[1132]: [Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
Apr 03 01:35:58 berrypie volumio[1132]: [Vollibrespot] : ConnectRequest: "Spotify/8.5.51 iOS/13.3.1 (iPhone11,8)"
Apr 03 01:36:00 berrypie volumio[1132]: [Vollibrespot] : ConnectRequest: "Spotify/8.5.51 iOS/13.3.1 (iPhone11,8)"
Apr 03 01:36:02 berrypie volumio[1132]: [Vollibrespot] : ConnectRequest: "Spotify/8.5.51 iOS/13.3.1 (iPhone11,8)"
Apr 03 01:36:02 berrypie volumio[1132]: [Vollibrespot] : Connecting to AP "guc3-accesspoint-b-1l92.ap.spotify.com:4070"
Apr 03 01:36:03 berrypie volumio[1132]: [Vollibrespot] : Authenticated as "1po6sov54dp0ed0b4wecu67tk" !
Apr 03 01:36:03 berrypie volumio[1132]: [Vollibrespot] : Setting up new mixer: card:hw:5 mixer:PCM index:0
Apr 03 01:36:03 berrypie volumio[1132]: [Vollibrespot] : Alsa min: 0 (MilliBel(0)[dB]) -- max: 0 (MilliBel(0)[dB]) HW: false
Apr 03 01:36:03 berrypie volumio[1132]: [Vollibrespot] : Switching to linear volume mapping, control range: MilliBel(0)
Apr 03 01:36:03 berrypie volumio[1132]: [Vollibrespot] : Alsa min-db is not SND_CTL_TLV_DB_GAIN_MUTE!!
Apr 03 01:36:03 berrypie volumio[1132]: [Vollibrespot] : Using alsa sink
Apr 03 01:36:03 berrypie volumio[1132]: thread 'main' panicked at 'Couldn't get current volume: Error("snd_mixer_selem_get_playback_volume", Sys(EINVAL))', src/libcore/re
Apr 03 01:36:03 berrypie volumio[1132]: stack backtrace:
Apr 03 01:36:03 berrypie volumio[1132]: 0:   0xa2c788 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
Apr 03 01:36:03 berrypie volumio[1132]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
Apr 03 01:36:03 berrypie volumio[1132]: 1:   0xa2c788 - backtrace::backtrace::trace_unsynchronized::h244e30b4d61a86e0
Apr 03 01:36:03 berrypie volumio[1132]: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
Apr 03 01:36:03 berrypie volumio[1132]: 2:   0xa2c788 - std::sys_common::backtrace::_print::h978df54e55c6209d
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/sys_common/backtrace.rs:47
Apr 03 01:36:03 berrypie volumio[1132]: 3:   0xa2c788 - std::sys_common::backtrace::print::ha75ae47f14b8f7f3
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/sys_common/backtrace.rs:36
Apr 03 01:36:03 berrypie volumio[1132]: 4:   0xa2c788 - std::panicking::default_hook::{{closure}}::h004e1d529e652ede
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/panicking.rs:200
Apr 03 01:36:03 berrypie volumio[1132]: 5:   0xa2c380 - std::panicking::default_hook::h185ef7ff1eea4221
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/panicking.rs:214
Apr 03 01:36:03 berrypie volumio[1132]: 6:   0xa2cf44 - std::panicking::rust_panic_with_hook::hfe0a86ed15580d4a
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/panicking.rs:477
Apr 03 01:36:03 berrypie volumio[1132]: 7:   0xa2cb10 - std::panicking::continue_panic_fmt::h182e68ecbb1c932b
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/panicking.rs:384
Apr 03 01:36:03 berrypie volumio[1132]: 8:   0xa2c9fc - rust_begin_unwind
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/panicking.rs:311
Apr 03 01:36:03 berrypie volumio[1132]: 9:   0xa43444 - core::panicking::panic_fmt::h7e9f94035af782b3
Apr 03 01:36:03 berrypie volumio[1132]: at src/libcore/panicking.rs:85
Apr 03 01:36:03 berrypie volumio[1132]: 10:   0xa43534 - core::result::unwrap_failed::hf7591c1dd9412006
Apr 03 01:36:03 berrypie volumio[1132]: at src/libcore/result.rs:1084
Apr 03 01:36:03 berrypie volumio[1132]: 11:   0x5737d8 - librespot_playback::mixer::alsamixer::AlsaMixer::map_volume::hc3941422653c99d0
Apr 03 01:36:03 berrypie volumio[1132]: 12:   0x574194 - <librespot_playback::mixer::alsamixer::AlsaMixer as librespot_playback::mixer::Mixer>::set_volume::hb83ffa4c77bee
Apr 03 01:36:03 berrypie volumio[1132]: 13:   0x4dcf70 - librespot_connect::spirc::SpircTask::set_volume::h377a17551ebc8992
Apr 03 01:36:03 berrypie volumio[1132]: 14:   0x4d7e08 - librespot_connect::spirc::Spirc::new::h321dd080a56e195c
Apr 03 01:36:03 berrypie volumio[1132]: 15:   0x4adb70 - <vollibrespot::Main as futures::future::Future>::poll::hb49550d8e3f467fa
Apr 03 01:36:03 berrypie volumio[1132]: 16:   0x4d39b4 - futures::task_impl::std::set::hb572c3af727256ac
Apr 03 01:36:03 berrypie volumio[1132]: 17:   0x4abe2c - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::hc872efa618c45de3
Apr 03 01:36:03 berrypie volumio[1132]: 18:   0x4d383c - futures::task_impl::std::set::ha1da852080a54e89
Apr 03 01:36:03 berrypie volumio[1132]: 19:   0x498894 - std::thread::local::LocalKey<T>::with::hb33a14aa0d64830e
Apr 03 01:36:03 berrypie volumio[1132]: 20:   0x48ec1c - tokio_current_thread::Entered<P>::block_on::h6c7f92e99b77886b
Apr 03 01:36:03 berrypie volumio[1132]: 21:   0x4986b4 - std::thread::local::LocalKey<T>::with::h9ec9ec76b26e7edf
Apr 03 01:36:03 berrypie volumio[1132]: 22:   0x49830c - std::thread::local::LocalKey<T>::with::h26f52d592cd722ab
Apr 03 01:36:03 berrypie volumio[1132]: 23:   0x49816c - std::thread::local::LocalKey<T>::with::h22d8fcf69243240c
Apr 03 01:36:03 berrypie volumio[1132]: 24:   0x48e1e0 - scoped_tls::ScopedKey<T>::set::h3380ded7e37a7882
Apr 03 01:36:03 berrypie volumio[1132]: 25:   0x4c7ee4 - tokio_core::reactor::Core::run::h9c6fa799f1a72320
Apr 03 01:36:03 berrypie volumio[1132]: 26:   0x4b03ec - vollibrespot::main::h551d8fa54606fabf
Apr 03 01:36:03 berrypie volumio[1132]: 27:   0x4b70ac - std::rt::lang_start::{{closure}}::hdc0b123e45936b4e
Apr 03 01:36:03 berrypie volumio[1132]: 28:   0xa2c974 - std::rt::lang_start_internal::{{closure}}::h923917fc45a67b03
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/rt.rs:49
Apr 03 01:36:03 berrypie volumio[1132]: 29:   0xa2c974 - std::panicking::try::do_call::he118fbfc301d3e1a
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/panicking.rs:296
Apr 03 01:36:03 berrypie volumio[1132]: 30:   0xa30e54 - __rust_maybe_catch_panic
Apr 03 01:36:03 berrypie volumio[1132]: at src/libpanic_unwind/lib.rs:80
Apr 03 01:36:03 berrypie volumio[1132]: 31:   0xa2d3c0 - std::panicking::try::hcc03ea850c2702cb
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/panicking.rs:275
Apr 03 01:36:03 berrypie volumio[1132]: 32:   0xa2d3c0 - std::panic::catch_unwind::hf09eaf9043e449c8
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/panic.rs:394
Apr 03 01:36:03 berrypie volumio[1132]: 33:   0xa2d3c0 - std::rt::lang_start_internal::h87508684140f3dc4
Apr 03 01:36:03 berrypie volumio[1132]: at src/libstd/rt.rs:48
Apr 03 01:36:03 berrypie volumio[1132]: 34:   0x4b13f8 - main
Apr 03 01:36:03 berrypie volumio[1132]: 35: 0xb6c5a294 - __libc_start_main
Apr 03 01:36:03 berrypie systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Apr 03 01:36:03 berrypie systemd[1]: Unit volspotconnect2.service entered failed state.
Apr 03 01:36:05 berrypie systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Apr 03 01:36:05 berrypie systemd[1]: Stopping Volspotconnect2 Daemon...
Apr 03 01:36:05 berrypie systemd[1]: Starting Volspotconnect2 Daemon...
Apr 03 01:36:05 berrypie systemd[1]: Started Volspotconnect2 Daemon.
Apr 03 01:36:05 berrypie volumio[1346]: vollibrespot v0.1.9 c98fd5d 2019-11-08 (librespot 4674946 2019-11-08) -- Built On 2019-11-08
Apr 03 01:36:05 berrypie volumio[1346]: [Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }`

**Comment by ashthespy** [comment]
@robfrye You seem to have a different issue - what is your USB DAC? It doesn't seem to support a mono/front left channel. And probably needs to set each channel separately. 

PS: use ` ``` ``` ` wrap up code blacks..

**Comment by robfrye** [comment]
The dac is a Schiit Modi3

**Comment by ashthespy** [comment]
That sounds familiar, is this you? https://forum.volumio.org/spotify-connect2-not-connecting-via-usb-dac-t14304.html

**Comment by robfrye** [comment]
Nope that was someone else. Maybe the same issue? The dac works fine with other sources

**Comment by ashthespy** [comment]
If you are willing to debug, hop on to gitter, and I can guide you towards the information I would need to fix it..

**Comment by ashthespy** [comment]
Forgot to mention, that @robfrye managed to [solve this](https://gitter.im/balbuze/volumio-plugins?at=5e8776a426dafb366520b222)
>BTW, I also finally got the SpotifyConnect2 plugin working by using the following settings in playback options in the Web UI:
Playback Mode: DoP
Mixer Type: Software
Followed by saving the options for the plugin
