### ISSUE TITLE
Plugin crashing when switching song on spotify, and general performance slowdown

### ISSUE THREAD

**Issue by Birdroun** [balbuze/volumio-plugins#26]
Hi, first I want to thank you for your amazing work, the plugin works almost flawlessly, the revision 2 has a better sound management imo than the first version.

I installed the plugin on a fresh volumio 2 install, and I get two problems, sometimes when I manually switch songs the music stops directly on spotify, and the spotify connect output disappears on spotify.
Sometimes spotify takes like 10 to 15 seconds to change songs, and when that appens actually my rpi is actually really slow, even to get a ssh response.

If you could tell me how to get the logs and everything that I can get to help you.
I'm using a raspberry pi 2 B, with a Iqaudio pidac+.

**Comment by balbuze** [comment]
Yes I know for these problems and some others...I'm going to upload a new version soon...

**Comment by balbuze** [comment]
I uploaded a new version that should solve previous problem. But I remove volumio play stop when starting spotify as it takes a lot of time. I'll see later.
Feel free to test!!!

**Comment by Birdroun** [comment]
Tested last version, 0.20, it's working really great right now, switching volume and songs in spotify is really fast almost no latency and it's really stable right now already. Is there any way to support you ?
