### ISSUE TITLE
Lost support for my .wav filters?

### ISSUE THREAD

**Issue by janhenhan** [balbuze/volumio-plugins#260]
Hi,

First of all thank you so so much for this plugin! It's amazing and exactly what I need in Volumio to have a room corrected Airplay receiver!

I installed it last week and everything was fine right out of the box: I uploaded my 24bit/44.1kHz .wav filters, selected them in your plugin chose 44.1 and 32bit as an output for my i2s DAC and everything sounded awesome.

Unfortunately, for unrelated reasons, I had to redo the install today. And something must have changed in the meantime. My filters suddenly sound like s***, I would describe it as 'next door sound' + high distortion. The filter files are exactly the same though. I see in the change log that you did some work in the meantime. Maybe something broke?

Is there an easy way for me to roll back to last weeks version?

Thanks!!

**Comment by balbuze** [comment]
hello!
I made some work on the plugin, but not supposed to gives the result you are describing... Can you join a filter so that I can test ?

**Comment by janhenhan** [comment]
[test.wav.zip](https://github.com/balbuze/volumio-plugins/files/4399600/test.wav.zip)

**Comment by balbuze** [comment]
are you sure of your filter? clipping is at least 15db above the maxi we can set in the plugin. And file is small. What is the filter length?

**Comment by janhenhan** [comment]
Well my confidence in the filter comes from the fact that it was working last week ;) I just downgraded to the older version of the plugin from mid March. Everything works again. I'll stick with this older version for now since it does everything I need it to. I can try to help debug next weekend.

**Comment by balbuze** [comment]
Ok thanks for the inquiry. I have a small of what happens. I'll check tomorrow.

**Comment by balbuze** [comment]
Ni! I just pushed a new version that fix the problem.
