### ISSUE TITLE
dbl filters not processed - no sound

### ISSUE THREAD

**Issue by hoernix** [balbuze/volumio-plugins#262]
Hi,
thank you very much for providing the brutefir plugin for volumio. It's the main reason why I chose volumio.
I create filters using Acourate and the dbl format.
While dbl files worked fine since I started using volumio and drc in december 2019 after upgrading to the latest version of volumio and brutefir-plugin (April 5th) the dbl filters do not work anymore. 
I created 64bit mono wav files using Acourate and the filters work fine again, so I use those for the time being.
But I don't get the dbl files working.

Kind Regards
Marc

**Comment by balbuze** [comment]
ho, please send me a file so that I could test. What was the last working version of plugin?

**Comment by hoernix** [comment]
Hi, apologies for my late reply. I just saw, you provided a new version of the plugin today. Thank you, I will give it a try. I attached the files anyway.


[filters_dbl.zip](https://github.com/balbuze/volumio-plugins/files/4535976/filters_dbl.zip)

**Comment by balbuze** [comment]
ok, I tested your files with the version, it works fine ;-)
