### ISSUE TITLE
volspotconnect2 - Activation of “Gapless Playback”, “Autoplay” or “Debug Mode” is not stored

### ISSUE THREAD

**Issue by pachulo** [balbuze/volumio-plugins#264]
Hi! First of all thanks a lot for this plugin!

Since the update to 1.0.0 I'm having this issue: I activate **Gapless Playback** and click on the save, everything seems right, but if I go out of the plugin configuration page and then back, the option is deactivated again.

I have also tried with **Autoplay** & **Debug Mode** options, and the same problem arises.

By the way, when I install the plugin both **Gapless Playback** & **Autoplay** are activated, but I don't want the **Autoplay** and I want the **Initial Volume** to be 100, so when I make the changes **Gapless Playback** stays on **Off**.

In the volumio.log I can see this when I click on **Save**:
```
2020-04-22T20:02:47.597Z - info: CALLMETHOD: music_service volspotconnect2 saveVolspotconnectAccount [object Object]
2020-04-22T20:02:47.602Z - info: CoreCommandRouter::executeOnPlugin: volspotconnect2 , saveVolspotconnectAccount
```
I've tried modifying the config manually on `/data/configuration/music_service/volspotconnect2/config.json` and after disabling and enabling the plugin, the **On** for **Gapless Playback** option is persisted.

P.D.
I'm running Volumio version 2.729, if that matters.

**Comment by balbuze** [comment]
Thanks! I'm going to fix it! (but  this is not this file to be modified)

**Comment by pachulo** [comment]
OK, after the last update this is working now! Thanks a lot!

By the way, is there anyway to contribute to your work?
