### ISSUE TITLE
Can't connect to spotify with volspotconnect2

### ISSUE THREAD

**Issue by benuron** [balbuze/volumio-plugins#265]
since I updated to the volspotconnect2 1.0.1, the volumio stopped appearing in the Spotify devices list.

in the logs appears this error several times:

> Apr 30 13:10:27 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=1/FAILURE
> Apr 30 13:10:27 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
> Apr 30 13:10:30 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
> Apr 30 13:10:30 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
> Apr 30 13:10:30 volumio systemd[1]: Starting Volspotconnect2 Daemon...
> Apr 30 13:10:30 volumio systemd[1]: Started Volspotconnect2 Daemon.

Using the Volumio 2.729 in the rasp Zero W

**Comment by ashthespy** [comment]
Can you provide the output of  `journalctl  -u volspotconnect2.service`

**Comment by benuron** [comment]
> Apr 30 14:26:22 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=1/FAILURE
> Apr 30 14:26:22 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
> Apr 30 14:26:24 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
> Apr 30 14:26:24 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
> Apr 30 14:26:24 volumio systemd[1]: Starting Volspotconnect2 Daemon...
> Apr 30 14:26:24 volumio systemd[1]: Started Volspotconnect2 Daemon.
> Apr 30 14:26:24 volumio volumio[1254]: error: UnrecognizedOption("b")
> Apr 30 14:26:24 volumio volumio[1254]: Usage: ./vollibrespot [options]
> Apr 30 14:26:24 volumio volumio[1254]: Options:
> Apr 30 14:26:24 volumio volumio[1254]: -c, --config CACHE  Path to config file to read. Defaults to 'config.toml'
> Apr 30 14:26:24 volumio volumio[1254]: --backend BACKEND
> Apr 30 14:26:24 volumio volumio[1254]: Audio backend to use. Use '?' to list options
> Apr 30 14:26:24 volumio volumio[1254]: --verbose       Enable verbose output
> Apr 30 14:26:24 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=1/FAILURE
> Apr 30 14:26:24 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
> Apr 30 14:26:26 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
> Apr 30 14:26:26 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
> Apr 30 14:26:26 volumio systemd[1]: Starting Volspotconnect2 Daemon...
> Apr 30 14:26:26 volumio systemd[1]: Started Volspotconnect2 Daemon.
> Apr 30 14:26:26 volumio volumio[1261]: error: UnrecognizedOption("b")
> Apr 30 14:26:26 volumio volumio[1261]: Usage: ./vollibrespot [options]
> Apr 30 14:26:26 volumio volumio[1261]: Options:
> Apr 30 14:26:26 volumio volumio[1261]: -c, --config CACHE  Path to config file to read. Defaults to 'config.toml'
> Apr 30 14:26:26 volumio volumio[1261]: --backend BACKEND
> Apr 30 14:26:26 volumio volumio[1261]: Audio backend to use. Use '?' to list options
> Apr 30 14:26:26 volumio volumio[1261]: --verbose       Enable verbose output
> Apr 30 14:26:26 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=1/FAILURE
> Apr 30 14:26:26 volumio systemd[1]: Unit volspotconnect2.service entered failed state.

**Comment by ashthespy** [comment]
As suspected, someone issues in the flags passed the binary.
```
Apr 30 14:26:24 volumio volumio[1254]: error: UnrecognizedOption("b")
```

What's the output of `cat /data/plugins/music_service/volspotconnect2/startconnect.sh`

**Comment by benuron** [comment]
> cd /data/plugins/music_service/volspotconnect2
> ./vollibrespot -b 320 -c /tmp  \
>                   --disable-audio-cache \
>                   --name 'Volumio' --initial-volume 80\
>                   --device softvolume   \
>                   --mixer alsa \
>                   --mixer-name 'SoftMaster' --mixer-card 'hw:1' --mixer-linear-volume \
>

**Comment by ashthespy** [comment]
Umm, what version of the plugin are you using? You seem to have an outdated version of the plugin, with the newest version of the daemon. Something that shouldn't happen? 🧐🤔

**Comment by balbuze** [comment]
have you rebooted after install?

**Comment by benuron** [comment]
I had rebooted several times.
After unistalling and reinstalling throught the webUI is working :smiley: 

Device is raspi zero W.

I tried installing manually but I am experiencing some latency through ssh :worried:  maybe some faulty sd card.

Anyways thanks for the help :+1:  and for the plugin

**Comment by berrywhite96** [comment]
Have the same problem, updated from an very old version. The vollibrespot does not know the -b flag, also if I run it manually it does not work.

**Comment by ashthespy** [comment]
Please uninstall the plugin via the UI, then restart Volumio (or `volumio vrestart` from the console) and try installing it again from the UI.

**Comment by arjenpdevries** [comment]
It does indeed look like the problem I reported at #269; apologies for not checking longer, given the behaviour was identical and the report very recent, I assumed I had that problem.

So I updated, and rebooted, and rebooted again including unplugging power :-) Will take a look through uninstall ; install procedure and report back here.

**Comment by arjenpdevries** [comment]
That worked, thanks for the advice!

**Comment by ashthespy** [comment]
> 
> 
> 
> Context: I have had the volumio for a while, so it could definitely be that some of its state is not identical to a newly installed one. I do apply updates regularly though.
> 
> ```
> volumio@volumio:/data/plugins/music_service/volspotconnect2$ cat package.json
> {
>         "name": "volspotconnect2",
>         "version": "1.0.1",
>         "description": "Plugin for Spotify connect in Volumio2. Requires a Premium/Family account",
>         "main": "index.js",
>         "scripts": {
>                 "lint": "semistandard \"./**/*.js\" --fix",
>                 "test": "echo \"Error: no test specified\" && exit 1"
>         },
>         "author": "Balbuze & Ashthespy",
>         "license": "GPL 3.0",
>         "vollibrespot": {
>                 "version": "0.2.0"
>         },
>         "volumio_info": {
>                 "prettyName": "Volumio Spotify Connect2",
>                 "icon": "fa-spotify",
>                 "plugin_type": "music_service"
>         },
>         "bundledDependencies": [
>                 "spotify-web-api-node"
>         ],
>         "dependencies": {
>                 "chalk": "^3.0.0",
>                 "fs-extra": "^8.1.0",
>                 "kew": "^0.7.0",
>                 "spotify-web-api-node": "https://github.com/ashthespy/spotify-web-api-node",
>                 "v-conf": "^1.4.2"
>         },
>         "devDependencies": {
>                 "semistandard": "12.0.1"
>         }
> }
> ```

This looks like it's pulled the right version indeed. I wonder what is going on. I just peeked into  the [`volspotconnect2.zip`](https://github.com/volumio/volumio-plugins/blob/gh-pages/plugins/volumio/armhf/music_service/volspotconnect2/volspotconnect2.zip) file as well, and `startconenct.sh` contains the right lines:

```
#!/usr/bin/env bash
cd /data/plugins/music_service/volspotconnect2
./vollibrespot \
    -c volspotify.toml
    # --verbose
```

Maybe we should open up an issue at https://github.com/volumio/volumio-plugins/ about issues with updating a plugin to figure out what is going on..

**Comment by arjenpdevries** [comment]
Seems indeed an issue with the update procedure, the `package.json` did not hint at a failed update but clearly old settings were still around.
