### ISSUE TITLE
Volspotconnect2 - Player stops when finding an unplayable song

### ISSUE THREAD

**Issue by pachulo** [balbuze/volumio-plugins#266]
I think this was not happening before the update to 1.0.x, but anyway: I just found out that when connected to Volumio, if I “SHUFFLE PLAY“ a playlist that contains unplayable songs some of those might get queued and, as soon as Volumio tries to reproduce one, instead of skipping it, stops playing.

I don't really know where the problem is, because when I'm listening on in my phone I never get unplayable songs queued...I guess because the “Show unplayable songs” setting is disabled, but I thought that it will also apply to Volumio Spotify Connect plugin...

**Comment by ashthespy** [comment]
Could you share such a playlist?

**Comment by pachulo** [comment]
Yeah, sorry; here's one example:
- https://open.spotify.com/playlist/4HrLayxlfZuW8YNwuK1g41?si=6_9XTofvTSW1ry4IY-95eg
- spotify:playlist:4HrLayxlfZuW8YNwuK1g41

**Comment by pachulo** [comment]
were you able to reproduce this @ashthespy ?
Thanks!

**Comment by ashthespy** [comment]
@pachulo sorry, this slipped under my radar, will try looking at it over the weekend!

**Comment by ashthespy** [comment]
@pachulo Fixed in [Vollibrespot v0.2.1](https://github.com/ashthespy/Vollibrespot/blob/master/CHANGELOG.md#021---2020-05-15)

**Comment by pachulo** [comment]
Out of curiosity: when will this show up @ashthespy ?

Thanks!

**Comment by ashthespy** [comment]
You can already [install it via ssh](https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect2#2-download-and-install-the-plugin) from this repository, not sure when it will be made available in the plugin repo..

**Comment by ashthespy** [comment]
Just noticed @balbuze merged v1.0.3 to the official plugin repo as well..

**Comment by pachulo** [comment]
Tested and working! Thanks a lot!
