### ISSUE TITLE
Brutefir3 issue with Allo DigiOne hat

### ISSUE THREAD

**Issue by christophertappin** [balbuze/volumio-plugins#275]
Hi when using the plugin through USB DAC it works fine but when I try to use Allo DigiOne hat Brutefir fails to load.

The steps I have taken are:

- select i2s Allo DigiOne
- check playback works
- install brutefir3 according to GitHub readme instructions
- activate plugin
- reboot as requested

Volumio displays an error on reboot - "Please connect Dsp -> Allo DigiOne to the unit or select a different output device from playback options"

Output of `aplay -l`:

**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 2: sndallodigione [snd_allo_digione], device 0: Allo DigiOne HiFi wm8804-spdif-0 [Allo DigiOne HiFi wm8804-spdif-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 7: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 2/2
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
card 7: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 2/2
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1

Output of `systemctl status brutefir -l`:

● brutefir.service - brutefir Daemon
   Loaded: loaded (/etc/systemd/system/brutefir.service; disabled)
   Active: failed (Result: start-limit) since Thu 2020-07-30 09:43:55 UTC; 8min ago
  Process: 1365 ExecStart=/usr/bin/brutefir /data/configuration/audio_interface/brutefir/volumio-brutefir-config (code=exited, status=1/FAILURE)
 Main PID: 1365 (code=exited, status=1/FAILURE)

Jul 30 09:43:54 volumio systemd[1]: Unit brutefir.service entered failed state.
Jul 30 09:43:55 volumio systemd[1]: brutefir.service holdoff time over, scheduling restart.
Jul 30 09:43:55 volumio systemd[1]: Stopping brutefir Daemon...
Jul 30 09:43:55 volumio systemd[1]: Starting brutefir Daemon...
Jul 30 09:43:55 volumio systemd[1]: brutefir.service start request repeated too quickly, refusing to start.
Jul 30 09:43:55 volumio systemd[1]: Failed to start brutefir Daemon.
Jul 30 09:43:55 volumio systemd[1]: Unit brutefir.service entered failed state.

My knowledge is a bit limited from here. Any ideas how I can get this working?

**Comment by christophertappin** [comment]
I've actually got this working by changing the default output from S24_LE to S24_4LE and rebooting 👍

**Comment by balbuze** [comment]
Good! Just to know, the plugin auto set by the plugin does not work for you then?

**Comment by christophertappin** [comment]
Unfortunately not. I think it selected S24_LE but it was S24_4LE that worked. I just tried a load of different output formats and restarted Brutefir from the command line until I got one that worked. I still didn’t get audio though but after a restart every just suddenly worked :)

**Comment by balbuze** [comment]
Can you check value available for output format HW-Detected xxxx

**Comment by christophertappin** [comment]
Sure.

HW-Detected-S16_LE and HW-Detected-S24_LE
