### ISSUE TITLE
Conflict with IR Remote Controller Plugin: Play command is not seen by volumio

### ISSUE THREAD

**Issue by illtrick** [balbuze/volumio-plugins#276]
I'm going to cross post this on the official IR Remote plugin thread as well right after this [HERE](https://community.volumio.org/t/plugin-ir-remote-controller-feedback-thread/6046/149)

**Setup**:  Fresh volumio install (v2.806), spotify connect plugin (v1.0.4), IR remote controller plugin (v1.2.4), apple A1294 remote (using this [lircd.conf](https://github.com/osmc/osmc/blob/master/package/remote-osmc/files/etc/lirc/apple-silver-A1294-lircd.conf))

**Operating Condition:** Queued song up using mobile device and selected volumio.  All commands issued by mobile device execute as expected.  A song was in the "playing" state before testing.

**Observed Behavior**: Play/Pause/Track controls all operate as expected using volumio web interface.  Using an IR remote control Track and Pause commands execute as expected however the Play command does not.  It plays the last "non spotify" track.  In my case it was a web radio but I'm sure it would be the same if it was a local or network file being played.

**Troubleshooting Steps Performed:**
- Rebooted pi, confirmed behavior is consistent with observed behavior above.
- Turned on debugging and observed NO LOGs generated when the Play button is pressed on the remote but ARE generated when pressing Play in the volumio web ui.
- Confirmed that Play/Pause operates as expected using basic playback of a local mp3.

I'm not sure if it's a problem with the lircrc mapping file or visibility of command execution by the spotify connect plugin.

**Comment by ashthespy** [comment]
This is probably the same issue as https://github.com/balbuze/volumio-plugins/issues/263
Volumio's API isn't consistent when comparing the webUI and other parts of it. I opened up a PR a while back https://github.com/volumio/Volumio2/pull/1938 so should be fixed when that gets merged..

**Comment by illtrick** [comment]
Looks very similar.  I was actually able to get two sources playing at the same time as well.  Is there a different build I could use to validate your hypothesis?

**Comment by ashthespy** [comment]
>  Is there a different build I could use to validate your hypothesis?

https://github.com/balbuze/volumio-plugins/issues/263#issuecomment-626285688

**Comment by illtrick** [comment]
> 
> 
> > Is there a different build I could use to validate your hypothesis?
> 
> [#263 (comment)](https://github.com/balbuze/volumio-plugins/issues/263#issuecomment-626285688)

Thanks.  I tested it and it works! Thanks so much.  Think your PR will get merged in an upcoming build?

**Comment by ashthespy** [comment]
>Think your PR will get merged in an upcoming build?

Anybody's guess ;-) - there are some myvolumio plugins that I can't test with.. But I would suggest you cross post your tests in that PR, so we can track all cases in one place..

**Comment by illtrick** [comment]
@ashthespy Done.  Thank you for your help and all your contributions to this project.  You in particular have gotten me out of a couple of jams that have made the difference between staying with Volumio or abandoning it.   

![Argon One with Apple Remote](https://user-images.githubusercontent.com/49263789/90807191-f3d42e80-e2d2-11ea-9f07-18a0bd2a0304.jpg)
