### ISSUE TITLE
volstereo2mono - can't unzip

### ISSUE THREAD

**Issue by FlorianReiterer** [balbuze/volumio-plugins#277]
Hi Balbuze,
i'd like to use your mono plugin, but cant unzip it.
_End-of-central-directory signature not found. _
could you have a look and maybe zip it again, or have a hint for me?
I did try to copy the unzipped directory but then got stuck at volumio plugin install progress 30 "Downloading plugin from 127.0.0..."
regards,
Florian

**Comment by balbuze** [comment]
hi!
to install :
wget https://github.com/balbuze/volumio-plugins/raw/master/plugins/audio_interface/volstereo2mono/volstereo2mono.zip
mkdir ./volstereo2mono
miniunzip volstereo2mono.zip -d ./volstereo2mono
cd ./volstereo2mono
volumio plugin install
cd ..
rm -Rf volstereo2mono*

Note: I didn't check if it is still working with recent version Volumio....

**Comment by FlorianReiterer** [comment]
Thank you for the detailed instruction.
I am stuck at miniunzipping the downloaded volstereo2mono.zip.
It says:
"End-of-central-directory signature not found."
and does not decompress the github zip file.

I use a allo sparky board written to the emmc card, and the current stable volumio version.

thanks!

**Comment by balbuze** [comment]
It is very weird... I checked and it just download and unzip fine... Do you SSH using Volumio as user? Have changed the default password? Do you get error while downloading with wget?

**Comment by FlorianReiterer** [comment]
I SSH as user volumio, default password, downloading complete.
Thanks for checking that the file is fine! 
Maybe it is the sparky SBC, i will go and do that with a pi.

**Comment by FlorianReiterer** [comment]
Yup. Works like a charm.
Looks like it is one of Sparky's many problems.
Thanks for making this plugin!
