### ISSUE TITLE
Some version working with Volumio 2.619

### ISSUE THREAD

**Issue by McDin** [balbuze/volumio-plugins#280]
Hi,
I own a Audiophonics Rasp dac Mini an newest Volumio for it is 2.619. 
is there an version of the Plugin that works with Volumio 2.619?
Thanks

**Comment by balbuze** [comment]
What version your are talking about?
Audiophonics provides a custom version of Volumio. No idea if 'official' version would work. I suggest you to ask Audiophonics

**Comment by McDin** [comment]
I‘m asking for a version of dsp plugin. Because you mentioned: „Need at least Volumio 2.776 or May not work!“ 
So is there a way to get it work with old Volumio Version 2.6.19? I already asked for update of Volumio, but Audiophonics is not so fast.

**Comment by McDin** [comment]
Official version wouldn’t work with support for Display and spdif

**Comment by balbuze** [comment]
It would work, but : 
- clipping detection will fails (you have to set it by hand)
- UI is not updated correctly in some case such as swapping filters (you have to refresh the page)

**Comment by McDin** [comment]
Thank you very much. Is there maybe a tutorial what has to be done with clipping detection?

**Comment by balbuze** [comment]
Just do a 'journalctl -f' and check while plying error about peak like
````
ep 05 17:44:29 volumio-rpi4 volumio[22198]: peak: 0/0/-0.93 1/4/+0.38
Sep 05 17:44:30 volumio-rpi4 volumio[22198]: peak: 0/0/-0.93 1/5/+0.38
Sep 05 17:44:31 volumio-rpi4 volumio[22198]: peak: 0/0/-0.93 1/7/+0.49
````
if you see that increase value. The best is to use a pink noise at 0 dB. Install tools in the plugin and play it from here.
Let me know if you need more help ;-)
