### ISSUE TITLE
parsing issue with August 2nd 2020 release

### ISSUE THREAD

**Issue by lnu** [balbuze/volumio-plugins#281]
WIth the latest release, VolLibRespot is unable to start because this line `mixer-index = ${mixidx}` is not replaced in the config file(`volspotify.toml`).
It complains with a parsing failed error.
```
Sep 09 05:04:05 volumio-salon volumio[1826]: vollibrespot v0.2.1 1438440 2020-05-15 (librespot 659de68 2020-05-10) -- Built On 2020-05-15
Sep 09 05:04:05 volumio-salon volumio[1826]: Reading Config from "volspotify.toml"
Sep 09 05:04:05 volumio-salon volumio[1826]: Malformed config key: unexpected character found: `$` at line 23 column 15
Sep 09 05:04:05 volumio-salon systemd[1]: volspotconnect2.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by ashthespy** [comment]
Which version of the plugin (and volumio) are you running?

**Comment by lnu** [comment]
volumio 2.806 and latest plugin(did the updated today through the ui)

**Comment by balbuze** [comment]
Do you use an other plugin? What is your mixer?

**Comment by lnu** [comment]
![image](https://user-images.githubusercontent.com/1829553/92597314-8438da00-f2a7-11ea-9787-608267a4119f.png)
![image](https://user-images.githubusercontent.com/1829553/92597343-8d29ab80-f2a7-11ea-9d61-da39c49412d2.png)

**Comment by balbuze** [comment]
Have you tried to disable and enable the plugin? (Probably...)

**Comment by lnu** [comment]
even uninstall/reinstall
