### ISSUE TITLE
Problem with tools (sweeps) provided for measurement

### ISSUE THREAD

**Issue by thegarbz** [balbuze/volumio-plugins#285]
Hi, I'm having some problems taking measurements according to your instructions. The problems seem to be related to playing the included sweep files. I'm setting up REW exactly as per the screenshots in the Wiki (https://volumio.github.io/docs/Plugins_User_Manuals/brutefir/Making_Measurment.html), playing the file from the tools: 512kMeasSweep_30_to_20000_44k_PCM16_L_refL and the resulting sweep is wildly incorrect. 

The results I'm getting show a 35dB increase in treble https://imgur.com/U6Q0CBX throughout the sweep (definitely doesn't sound like this). 

To exclude Volumio or the mixer or the DAC as the source of the problem I transferred the file to a system attached to a Windows PC in my studio. This studio system has been previously EQ'd with the same microphone and REW setup without issue so it should be flat. Again the file showed a massive difference between treble and bass (and unlike my volumio system which has a subwoofer this system should show a drop below 40Hz). 
- The line in blue shows the result of following the instructions on the Wiki and playing the file through Foobar: https://imgur.com/oGuYuAc which clearly is very similar to what I'm getting playing the file through volumio.
- The line in red is a reference loopback sweep from REW. REW generates the timing, the sweep and records it. As you can see this system has a relatively flat response from 40Hz up save for 2 dips due to the room modes. 

Is there something I'm fundamentally missing here? The sweep being played sounds audibly very similar to the sweep REW self-generates, but clearly its being picked up very differently in the measurements.

I also tried V5.19_MeasSweep_44k_L_refL.WAV which generates a similar poor response. 

I'm using REW 5.19, a UMIK-1

Volumio with the latest plugin downloaded 15/Oct/2020
And as a test on a Windows PC using Foobar2000 in WASAPI mode to play back the files with no resampling or other DSPs enabled.

**Comment by balbuze** [comment]
What I suggest, is to copy the sweep file in Rew in the small windows 'from files'. When ready, start, it will wait for the timing signal and then press play in Volumio. Let me know

**Comment by thegarbz** [comment]
Thanks for pointing me in a direction. I still haven't resolved it but I guess it has nothing to do with Volumio or your plugin at this stage. When I figure out what is causing the issue I'll let you know and maybe help update the documentation in case someone in the future has this problem too.

As you can see here: https://imgur.com/a/Gdd3AOV even when I use REW's signal generator to output to WAV files I have a similar response. 

- Red - Rew's own reference signal.
- Blue (dark) - Your included 512k sweep file
- The other two - Various settings of REW Signal Generated WAV files played through both Foobar and and Windows Media Player.

**Comment by balbuze** [comment]
I made a new test with REW 5.20  beta and sweep from the plugin. it works as expected.
![image](https://user-images.githubusercontent.com/12850139/96374006-6006cd80-1170-11eb-9f7a-cce78ee1f1ea.png)

**Comment by thegarbz** [comment]
Hey mate, thanks for pointing me the right way. No idea what is causing my problem with v5.19 but it was consistent across two installs, different sounds sources, and different playback devices. 

v5.20 however has fixed the problem, so the recording process is working as intended. 

Thanks and hopefully tomorrow when I have a play I can get this plugin working :-)
