### ISSUE TITLE
SpotifyConnect "Failed to register IPv6 receiver"

### ISSUE THREAD

**Issue by DevZky** [balbuze/volumio-plugins#289]
Hello,
after reinstall my volumio device I am able to find the volumio in the list of my Spotify-Connect Devices, but it's greyed out and no connection is possible.
Here's the corresponding log data:

```
info: Enabling plugin volspotconnect2
info: Loading plugin "volspotconnect2"...
info: PLUGIN START: volspotconnect2
[SpotifyConnect] Creating VLS config file
info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
[SpotifyConnect] Starting metadata listener
volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl start volspotconnect2.service
pam_unix(sudo:session): session opened for user root by (uid=0)
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.2.2 cd96399 2020-10-07 (librespot 08d8bcc 2020-10-07) -- Built On 2020-10-07
Reading Config from "volspotify.toml"
[Vollibrespot] : Using Alsa backend with device: plughw:1
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
pam_unix(sudo:session): session closed for user root
[SpotifyConnect] Vollibrespot Daemon service started!
[34m [Metrics] [39m SpotifyConnect: [31m 0s 188.02ms [39m
info: Done.
```

Hopefully somebody is facing the same issue and a solution is out there ^^! Changing the option from HW to SW in mixer settings doesn't help.

**Comment by ashthespy** [comment]
`Failed to register IPv6 receiver` is just a warning, as volumio disables IPv6 by default. 
Can you try to turn of multidevice and add your credentials to rule out issues in your network setup?

**Comment by DevZky** [comment]
Thank you very much for the quick answer. I could swear I have already tried MultiUser-Device on/off, anyway. 
After turn MultiUser-Device off and typing in my user data it's working, even after I turned MultiUser-Device back on again!

I cleared the link to "Vollibrespot" in "spotify.com > Spotify-Account > Apps". It seems a reinitialisation of "Vollibrespot" was necessary?! Maybe, maybe not. :)

**Comment by genmeblog** [comment]
Wow, after an hour I found this issue. Seems that reinitialisation is necessary (I changed HifiberryOS to Volumio)
