### ISSUE TITLE
[Feature Request] Gapless playback

### ISSUE THREAD

**Issue by leafy7382** [balbuze/volumio-plugins#29]
First, thank you for your work, it has brought my RPi3 playback system to a new level for home stereo, 320kbps works so well now!

It would be great if there is gapless playback feature for classical music, sometimes track are split in the middle of a note and it sounds a bit weird to be stopped and restarted again within a split second.

**Comment by balbuze** [comment]
this feature, if one day exists, would probably comes from librespot itself
