### ISSUE TITLE
USB DAC not reconnecting after restart

### ISSUE THREAD

**Issue by wbinek** [balbuze/volumio-plugins#291]
Hi, 
I use Volumio with DRC on RaspberryPi with USB DAC. The DAC is being shutdown when it is not in use. The problem is that after the DAC is started again the Volumio with DRC doesn't connect with it. When I change anything in the DRC plugin settings and click apply or reboot the Pi it is working again. Is it possible to detect the usb device reconnecting and force the plugin refresh/reconnect?
Any help appreciated :)

**Comment by balbuze** [comment]
And without the plugin it works?

**Comment by wbinek** [comment]
Without the DSP, it works. After the DAC is disconnected it shows a banner saying that it must be reconnected or other output must be selected. After turning on the DAC the message disappears and after about 15-20 seconds second message appears saying that the configuration was updated and the player is restarted and afterwards it works fine.

With the DSP, the disconnected banner appears but it doesn't disappear after DAC is connected. 

I attach logs created when I shut down wait and start DAC with and without DRC. There is also a log taken after I press apply in the DRC settings when the DAC is not detected (basically what happens right after the log_with_DRC).

[log_with_DRC_after_apply.txt](https://github.com/balbuze/volumio-plugins/files/5631998/log_with_DRC_after_apply.txt)
[log_without_DRC.txt](https://github.com/balbuze/volumio-plugins/files/5631999/log_without_DRC.txt)
[log_with_DRC.txt](https://github.com/balbuze/volumio-plugins/files/5632000/log_with_DRC.txt)

**Comment by wbinek** [comment]
Hi,
I have found a workaround. The problem is that when the device is not connected the brutefir service fails, so I modified the brutefir.service config to infinitely restart every 60 secnonds. Probably some watchdog for device connection would be a better solution but restarting brutefir seems easier.

**Comment by wbinek** [comment]
Hi, I have just tested beta build of Volumio 3 (buster) with Dsp4Volumio and there is no reconnecting problem anymore, so I think it closes the issue.
