### ISSUE TITLE
Regression on 286: Sample rate not selectable

### ISSUE THREAD

**Issue by thegarbz** [balbuze/volumio-plugins#293]
I took the opportunity to update the plugin and Volumio today and it seems there is a regression on issue #286 
All symptoms are identical: Sample rate not selectable, output format defaults to one not detected. 

Reboot and hardware detection did not solve the issue. 

DSP For Volumio 1.9.3
Volumio 2.861 (22 Nov)

**Comment by thegarbz** [comment]
Update:
Looks like it could be an issue with ALSA itself in Volumio 2.8.6.1. I reverted to DSP For Volumio 1.9.0 and I still have no functionality, however the symptoms are not identical. I cannot get audio at all. Seems like soft volume mixer isn't working properly. 

I'll play around a bit more. 

```
Jan 10 12:31:55 volumio volumio[1260]: BruteFIR v1.0m (November 2013)                                (c) Anders Torger
Jan 10 12:31:55 volumio volumio[1260]: Internal resolution is 64 bit floating point.
Jan 10 12:31:55 volumio volumio[1260]: Creating 4 FFTW plans of size 16384...finished.
Jan 10 12:31:56 volumio volumio[1260]: Loading 16 coefficient sets...finished.
Jan 10 12:31:56 volumio volumio[1260]: Realtime priorities are min = 2, usermax = 1, mid = 3 and max = 4.
Jan 10 12:31:56 volumio volumio[1260]: Warning: no support for clock cycle counter on this platform.
Jan 10 12:31:56 volumio volumio[1260]: Timers for benchmarking may be unreliable.
Jan 10 12:31:56 volumio volumio[1260]: Filters in process 0: 0 2
Jan 10 12:31:56 volumio volumio[1260]: Filters in process 1: 1 3
Jan 10 12:31:56 volumio volumio[1260]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM softvolume
Jan 10 12:31:56 volumio volumio[1260]: ALSA I/O: Could not open audio output "softvolume": No such file or directory.
Jan 10 12:31:56 volumio volumio[1260]: Failed to init output device.
Jan 10 12:31:56 volumio volumio[1260]: Failed to initialise digital audio interfaces.
Jan 10 12:31:56 volumio systemd[1]: brutefir.service: main process exited, code=exited, status=1/FAILURE
Jan 10 12:31:56 volumio systemd[1]: Unit brutefir.service entered failed state.
Jan 10 12:31:56 volumio systemd[1]: brutefir.service holdoff time over, scheduling restart.
Jan 10 12:31:56 volumio systemd[1]: Stopping brutefir Daemon...
```

**Comment by balbuze** [comment]
It seems to use a software volume mixer. Is that correct?

**Comment by thegarbz** [comment]
Yes, as I understand it the software mixer is automatically activated by the Brutefir plugin? It seems Volumio is having a problem with it. Let me have a bit more of a play. I'll do a factory reset tonight and see if I can get the software mixer working first. This may have nothing to do with the Brutefir plugin. .

**Comment by balbuze** [comment]
No. The plugin does not activate the software mixer. It use settings from Volumio. I suggest you to reset the plugin and disable it. Reboot and select your Dac and mixer. Check if ok. If yes reboot. Check again. Then enable the plugin.

**Comment by thegarbz** [comment]
Curious. I've always had the mixer set to None, and installing the plugin always set it to Software Mixer. Even after I disabled it and set it back to None after a reboot the Software Mixer came up again. Unless there's something I don't understand? I've only ever had Software and None as the mixer options. 

Anyway a factory reset solved the issue completely. It appears something went wrong with the Volumio update.
