### ISSUE TITLE
Google Home doesn't recognize Spotify Connect Volumio on RPi0

### ISSUE THREAD

**Issue by CtrlAltDel64** [balbuze/volumio-plugins#295]
Hello,
I didn't know where to ask, so I decided opening an issue may be the next best thing.

Situation: I have a Raspberry Pi 0 (rpi0) connected to my AVR over HDMI and am streaming music to it with the plugin Spotify Connect in Volumio. I am able to see this device in spotify connect on my Android device and Windows 10 PC through their respective apps.

Dilemma: I use my google home (mini) in my room to play music on my Sonos speakers sometimes. Something along the lines of "Hey Google, play my music in [name of sonos room]". I tried doing the same with my Volumio setup and my google home tells me "Volumio is not available or cannot be played right now".

Question: My question is if there is any way allow my google home to see this device and be able to play music on my Volumio rpi0 like it would on my Sonos speakers? I tried looking into GassistPi, but it focuses more on converting the whole device into a microphone and speaker, which I am unable to do without a microphone on the rpi0 (and I didn't plan on adding a microphone to it anyway).

Any pointers would be greatly appreciated!

**Comment by ashthespy** [comment]
I might be wrong, but I think Sonos comes with the Google home integration, and that is why it gets picked up.  Or does Google Home link to your Spotify account somehow to find available devices?

**Comment by CtrlAltDel64** [comment]
Sonos may come with Google home integration, but I do have to add my Sonos account under Google home in order for the two to connect. Do you know if there could be anything equivalent for Volumio and Spotify Connect?

**Comment by ashthespy** [comment]
No idea sorry.. 
Have you looked at https://support.spotify.com/us/article/spotify-on-google-home/

**Comment by CtrlAltDel64** [comment]
I will try to find a solution elsewhere, as this doesn't fall within the scope of your plugin. Thank you anyway!

**Comment by Snapple49** [comment]
Sorry to dig this up, but I'm looking for the exact same solution, did you ever find anything @CtrlAltDel64 ? I wish to add a Volumio RPi3 player to my google home setup, have not found anything so far.
