### ISSUE TITLE
rp3, brutefir and Digi-Amp+, no [None] mixer

### ISSUE THREAD

**Issue by git47** [balbuze/volumio-plugins#3]
Hi,
I have a rp3 with Digi-Amp+ and a fresh installation of Volumio 2.001.
The [plugin](https://github.com/balbuze/volumio-plugins/blob/master/plugins/miscellanea/brutefir/brutefir.zip) installs as expected.

This plays until I set output to loopback. I read #1 and learnt that I have to set the mixer to None.
But as soon as I set output device to loopback, the only mixer option I have is Hardware, even if it was set to None before.
aplay -l returns [this](https://github.com/balbuze/volumio-plugins/files/587670/aplay_minus_l.txt).

Do you have any idea how repair this (I don't mind editing config files or js)?

Thanks and regards

Joe

**Comment by balbuze** [comment]
hi!
It is not easy to configure output with volumio 2.001... You can try to update to last dev version. To do that enter in your web browser IP/dev and click on dev "true" and come back to volumio and check for update. But as this is dev version it may not work at all....
You can also remove : rm /data/configuration/audio_interface/alsa_controller/config.json and restart volumio : killall node . Do you use the last version of plugin with output selector ?
