### ISSUE TITLE
Plugin crashed with RUST error

### ISSUE THREAD

**Issue by leafy7382** [balbuze/volumio-plugins#30]
WARN:librespot::player: Track "24 Caprices, Op. 1: XXIV. Tema con Variazione" is not available
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837

**Comment by balbuze** [comment]
does it occur only with this track ?

**Comment by leafy7382** [comment]
Nop, it happens a lot from the "new releases" playlist

**Comment by leafy7382** [comment]
INFO:librespot::player: Track "How Deep Is Your Love - Chris Lake Remix" loaded
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
DEBUG:librespot::player: drop Player[0]

**Comment by leafy7382** [comment]
One more right after

DEBUG:librespot::spirc: kMessageTypePause "jAZJ0750" effbaae9e10113fd195321034dba6b3aa6962580 41 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:837
DEBUG:librespot::spirc: drop Spirc[0]

**Comment by leafy7382** [comment]
I think this is just how the underlying librespot handles network issues right now.

https://github.com/plietar/librespot/issues/127

**Comment by balbuze** [comment]
ok thanks anyway for your investigation
