### ISSUE TITLE
Systeminfo reporting wrong CPU speed

### ISSUE THREAD

**Issue by kaysap** [balbuze/volumio-plugins#300]
Hi,
I think that the CPU speed is reported incorrectly.

The Raspberry Pi Zero W has a 1000 MHz (1GHz) CPU, but is reported at 1.00 MHz (see screenshot).

Maybe just some formatting issue?

Best regards

![2021-02-26 07_48_21-systeminfo](https://user-images.githubusercontent.com/11522893/109266140-e9599b00-7807-11eb-86c1-f46ba91ba802.png)

**Comment by balbuze** [comment]
this corrected in the new version 0.1.6
Thanks
