### ISSUE TITLE
Volspotconnect2 armv6 trial

### ISSUE THREAD

**Issue by chsims1** [balbuze/volumio-plugins#31]
Tried to install volspotconnect2 on RPi0, but installation failed.

Journal output:

`Feb 27 08:01:18 volumio volumio[737]: info: Cpu is armv6l, downloading required package.
Feb 27 08:01:19 volumio sudo[1098]: pam_unix(sudo:session): session closed for user root
Feb 27 08:01:19 volumio volumio[737]: [sudo] password for volumio: converted 'https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/arch/arm/librespot-arm.xz' (ANSI_X3.4-1968) -> 'https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/arch/arm/librespot-arm.xz' (UTF-8)
Feb 27 08:01:19 volumio volumio[737]: --2017-02-27 08:01:17--  https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/arch/arm/librespot-arm.xz
Feb 27 08:01:19 volumio volumio[737]: Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Feb 27 08:01:19 volumio volumio[737]: Connecting to github.com (github.com)|192.30.253.113|:443... connected.
Feb 27 08:01:19 volumio volumio[737]: HTTP request sent, awaiting response... 404 Not Found
Feb 27 08:01:19 volumio volumio[737]: 2017-02-27 08:01:19 ERROR 404: Not Found.
Feb 27 08:01:19 volumio volumio[737]: /data/plugins//music_service/volspotconnect2/install.sh: 21: exit: Illegal number: -1
Feb 27 08:01:19 volumio volumio[737]: info: Install script return the error Error: Command failed: echo volumio | sudo -S sh /data/plugins//music_service/volspotconnect2/install.sh > /tmp/installog
Feb 27 08:01:19 volumio volumio[737]: [sudo] password for volumio: converted 'https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/arch/arm/librespot-arm.xz' (ANSI_X3.4-1968) -> 'https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/arch/arm/librespot-arm.xz' (UTF-8)
Feb 27 08:01:19 volumio volumio[737]: --2017-02-27 08:01:17--  https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/arch/arm/librespot-arm.xz
Feb 27 08:01:19 volumio volumio[737]: Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Feb 27 08:01:19 volumio volumio[737]: Connecting to github.com (github.com)|192.30.253.113|:443... connected.
Feb 27 08:01:19 volumio volumio[737]: HTTP request sent, awaiting response... 404 Not Found
Feb 27 08:01:19 volumio volumio[737]: 2017-02-27 08:01:19 ERROR 404: Not Found.
Feb 27 08:01:19 volumio volumio[737]: /data/plugins//music_service/volspotconnect2/install.sh: 21: exit: Illegal number: -1
Feb 27 08:01:19 volumio volumio[737]: info: An error occurred installing the plugin. Rolling back config
Feb 27 08:01:19 volumio volumio[737]: info: Plugin folders cleanup
Feb 27 08:01:19 volumio volumio[737]: info: Scanning into folder /volumio/app/plugins/
Feb 27 08:01:19 volumio volumio[737]: info: Scanning category audio_interface
Feb 27 08:01:19 volumio volumio[737]: info: Scanning category miscellanea
Feb 27 08:01:19 volumio volumio[737]: info: Scanning category music_service
Feb 27 08:01:19 volumio volumio[737]: info: Scanning category plugins.json
Feb 27 08:01:19 volumio volumio[737]: info: Scanning category system_controller
Feb 27 08:01:19 volumio volumio[737]: info: Scanning category user_interface
Feb 27 08:01:19 volumio volumio[737]: info: Scanning into folder /data/plugins/
Feb 27 08:01:19 volumio volumio[737]: info: Scanning category music_service
Feb 27 08:01:19 volumio volumio[737]: info: Plugin volspotconnect2 found in folder but missing in configuration. Removing folder.
Feb 27 08:01:19 volumio volumio[737]: info: Plugin folders cleanup completed
Feb 27 08:01:19 volumio volumio[737]: info: Error: Error
Feb 27 08:01:19 volumio volumio[737]: info: Failed to download. Stopping installation now
`

**Comment by balbuze** [comment]
humm... It seems this is network problem : Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112 Feb 27 08:01:19 volumio volumio[737]: Connecting to github.com (github.com)|192.30.253.113|:443... connected. Feb 27 08:01:19 volumio volumio[737]: HTTP request sent, awaiting response... 404 Not Found Feb 27 08:01:19 volumio volumio[737]: 2017-02-27 08:01:19 ERROR 404: Not Found. Feb 27 08:01:19 volumio volumio[737]:
Maybe retest it.

I tested on a rpi b, same cpu. Installation is fine. But it doesn't work due to librespot problem I 'm struggling to solve. What is version of volumio do you use?

**Comment by chsims1** [comment]
Yes, you're quite correct.  Apologies, I should have looked more closely at the output.

Volumio 2.041 on this particular device.  Installed OK, but not visible as device in Spotify

**Comment by chsims1** [comment]
Don't know if it's of use to you, but your latest version of librespot (Latest commit f9a49af  ) works on my RPi0 when run from the command line. Well done :)

**Comment by balbuze** [comment]
Yes, I compiled a working armv6l version yesterday. Just one thing why do said when I run from command line ? For me it work when enabling in webUI.

**Comment by chsims1** [comment]
Your script called by the systemd service file is empty

**Comment by balbuze** [comment]
have saved the setting in plugin ? even if you let the default setting ?

**Comment by balbuze** [comment]
I have to add an auto save when the plugin is enabled

**Comment by chsims1** [comment]
Hang on ..let me double check

**Comment by chsims1** [comment]
Yep, you're right again ... I did save the settings originally, but they can't have been written.

**Comment by balbuze** [comment]
Do you know why? Is it working now. When you enable /disable plugin ? As I said I'm going to add auto save when enabling the plugin. Because a other user report it as not working until he saved...

**Comment by chsims1** [comment]
No idea for originally not writing to script ... perhaps I was at fault, but I did think I had pressed 'save'  after setting 'shared device' to 'on'.

Anyway, I uninstalled and reinstalled.  Not working (says 'active') at default state.  As soon as I save it from settings, then everything is ok.

Disabling and enabling works fine without having to resave settings.

**Comment by balbuze** [comment]
I uploaded a new version that should solve the previous "problem" . Now when you enable the plugin, it generates a working startconnect.sh without the need of saving. Let me know if you still have other problem ;-)
