### ISSUE TITLE
Install hangs on downloading

### ISSUE THREAD

**Issue by quanticus** [balbuze/volumio-plugins#310]
Hi there, I'm a new volumio user and I've installed the latest version and everything is working good.
I have it setup with Tidal and Spotify on my Raspberry pi 4 with a Boss Allo 2 hat.

Time for a bit of equalizing and trying to install it via SSH.
The first part is working fine till the point that I have to install it using "sudo volumio plugin install"
If I'm not using "sudo" then I receive another error message:
~/fusion$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
/bin/mv: cannot stat '*.zip': No such file or directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/fusiondsp.zip
/bin/mv: cannot stat '*.zip': No such file or directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:689:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:751:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

The message I receive when using the command with sudo is the same as other users encountered:

Compressing the plugin
Plugin succesfully compressed
Progress: 10
Status :Plug-in downloaden
Downloading plugin at http://127.0.0.1:3000/plugin-serve/fusiondsp.zip

It sticks to this line without any progress.
Can I provide you with more details to grasp the issue?

Cheers, Amancio

**Comment by balbuze** [comment]
Please give what version of Volumio you use. Latest means nothing...
You need a 3.1x version to use Fusiondsp.
Don't use sudo to install a plugin.
Don't change the default password for SSH.
Let me know

**Comment by quanticus** [comment]
Hi, version is 2.907 and I didn't change the default password

**Comment by quanticus** [comment]
If a start over again without using sudo, ill recieve a permission denied:
volumio@volumio:~/fusion$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
/bin/mv: inter-device move failed: 'fusiondsp.zip' to '/tmp/plugins/fusiondsp.zip'; unable to remove target: Permission denied
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/fusiondsp.zip
/bin/mv: inter-device move failed: 'fusiondsp.zip' to '/tmp/plugins/fusiondsp.zip'; unable to remove target: Permission denied

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:689:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:751:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by balbuze** [comment]
Sorry but you can't install it on Volumio 2.x.
It requires Volumio 3.1x in order to install and work.

**Comment by quanticus** [comment]
How can I get version 3.1x?

**Comment by balbuze** [comment]
Have a look here https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/1
And once installed, enable test mode and update to v3.101

**Comment by quanticus** [comment]
Cheers! thanks for your help...

**Comment by balbuze** [comment]
Just one more thing. With Volumio 3 you need to install a specific version for Spotify or Spotify connect.
See :
Spotify https://github.com/balbuze/volumio-plugins/blob/57e96fc9fe1f4ebf57cfa822f96da8391bbe437c/plugins/music_service/spop.zip
Spotify connect
https://github.com/balbuze/volumio-plugins/blob/57e96fc9fe1f4ebf57cfa822f96da8391bbe437c/plugins/music_service/volspotconnect2/volspotconnect2.zip

**Comment by ashthespy** [comment]
@balbuze `volspotconnect2` from your `master` branch should work with either Buster or Jessie as it tests for `MODULAR_ALSA_PIPELINE` variable and sets things accordingly. 
Maybe it's an idea to merge it into the official repo as it's backwards compatible?

**Comment by balbuze** [comment]
Ok. I'll have a look tonight. Btw, not sure it works with Buster x86_amd64 as I remember. To be checked.

**Comment by ashthespy** [comment]
> Btw, not sure it works with Buster x86_amd64 as I remember. To be checked.

I tested just for a few songs long ago, but it should work fine based on Lalashok's tests from the [forum](https://community.volumio.org/t/not-recomended-plugin-and-tweaks-adventures-on-buster-betas/45552/330).
