### ISSUE TITLE
Can't enable

### ISSUE THREAD

**Issue by erangilboa** [balbuze/volumio-plugins#314]
Hi,
Just installed FusionDSP on a Volumio 3.175 running on an x86 machine.
When enabling, I can't play any tracks.
I get errors related to FusionDSP in the log file.
When disabling, everything is working fine.
Log file is attached.
[4fusionDSP.txt](https://github.com/balbuze/volumio-plugins/files/7740542/4fusionDSP.txt)

Thank you for your help!

**Comment by balbuze** [comment]
hello. Yes, currently there is a problem on x86 machine.

We are on it.
Please, post your feedback on community forum and use the official way to generate log https://volumio.github.io/docs/User_Manual/Sending_logs_for_troubleshooting.html
Thanks

**Comment by erangilboa** [comment]
Hi,
will there be a working x86 version anytime soon?
Thanks,
Eran
