### ISSUE TITLE
no spotify account settings

### ISSUE THREAD

**Issue by kliko22** [balbuze/volumio-plugins#32]
There is no way to fill in the spotify username en password. The only thing I see in settings is "Set for high bitrate".
The spotify version I use is Volumio Audiophile Music Player for PC (X86/X64) (2.030)

**Comment by balbuze** [comment]
In this version you don't need to feel credentials...

**Comment by kliko22** [comment]
But where does it gets it's credentials from? Do I need to install the spotify plugin also? Because I don't see it in spotify.
The spotify plugin id is "plop" instead of "spotify"

**Comment by balbuze** [comment]
If it works as expected : enable plugin, save bitrate and that it... Try to disable and re-enable it. If still nothing, ssh to your device and systemctl status volspotconnect2 . paste the result

**Comment by kliko22** [comment]
I tried everything but no succes

here is the result:
● volspotconnect2.service - Volspotconnect2 Daemon
   Loaded: loaded (/etc/systemd/system/volspotconnect2.service; disabled)
   Active: failed (Result: exit-code) since Mon 2017-02-27 11:28:43 UTC; 1min 17                                               s ago
  Process: 1448 ExecStart=/bin/bash /data/plugins/music_service/volspotconnect2/                                               startconnect.sh (code=exited, status=101)
 Main PID: 1448 (code=exited, status=101)

Feb 27 11:28:43 volumio-laptop systemd[1]: Started Volspotconnect2 Daemon.
Feb 27 11:28:43 volumio-laptop volumio[1448]: INFO:librespot: librespot 6a06....
Feb 27 11:28:43 volumio-laptop volumio[1448]: thread 'main' panicked at 'Inv...7
Feb 27 11:28:43 volumio-laptop volumio[1448]: note: Run with `RUST_BACKTRACE....
Feb 27 11:28:43 volumio-laptop systemd[1]: volspotconnect2.service: main pro...a
Feb 27 11:28:43 volumio-laptop systemd[1]: Unit volspotconnect2.service ente....
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by balbuze** [comment]
please set bitrate to 320 and save. let me know
if not better, what happens if you launch "by hand" ./data/plugins/music_service/volspotconnect2/startconnect.sh

**Comment by kliko22** [comment]
I tried it launch by hand and I got this error:

volumio@volumio-laptop:~$ /data/plugins/music_service/volspotconnect2/startconnect.sh
INFO:librespot: librespot 6a0657f (2017-02-22). Built on 2017-02-22.
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }

**Comment by kliko22** [comment]
but it works by the way

**Comment by kliko22** [comment]
do you know what the problem is?

**Comment by balbuze** [comment]
this error should be not really problematic. But can you confirm that the plugin works for you ? In the last version I have added the possibility to disable share. In that case you have to enter your credentials to be the only user allowed.

**Comment by kliko22** [comment]
It only works if I start it manualy in ssh. But I added the line to "/etc/rc.local" and now it's starts when I reboot.
What is the best way to update this pugin?

**Comment by balbuze** [comment]
I really don't understand...
To sum up:
you use a x86 with volumio 2.030
you use volspotconnect2. To install it, you have downloaded https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/volspotconnect2.zip and install it  using the section plugin in the webUI. Refreshed the page to see the installed plugin enabled the plugin, in setting click on save and that should be enough.
There is no need for adding something in rc.local .  Systemd is used in volumio, and the plugin install three services located in /etc/sysemd/sysytem : volspotconnect2.service volspotconnect2purgecache.service volspotconnect2purgecache.timer
Could you confirm you do that and services are in the place ? Have you made other mod on your system ? changing password ? or other thing ?

**Comment by kliko22** [comment]
Yes I use a x86 with volumio 2.030
Yes I use volspotconnect2
And the services are in place. 

The only thing I did was installing LXDE and Lightdm for using a screen.

I updated to the new version and now it works

**Comment by FredBLKYN** [comment]
Hello Guys,
I have the same issue running Volumio (last version) on ARM v7 Synology. By default the only option I see is "Shared" ON. If I turn it off I can specify a login/password (but it is empty)
Question : I didn't provide any credential and it is working... I guess my credentials were saved somewhere as I was using previous version that stopped working (Inactive red state) for whatever reason that's why I re-installed. So I'm pleased now as It is working again :-) but would be nice to have the option to change bitrate and credentials.
Very good work by the way balbuze

**Comment by FredBLKYN** [comment]
balbuze,
I did some tests and I have a question. For me (I'm maybe wrong) using the older version I was able to start playing a song on the Raspberry and then kill Spotify app on my iPhone or enable airplane mode : music was still playing. Now if I kill the app or stop the wifi on my iPhone the music stops immediately... Is it normal ? It looks like it is streaming from my iPhone (which shouldn't be the case with Connect right ?)
thank you !

**Comment by balbuze** [comment]
@FredBLKYN As I already explain, the default mode is "shared device" or in other word discovery. It means that the device is exposed to any user on the same network with premium account. 
In this mode, when you connect to the device, your credentials are sent from your spotify app to the device and store in ram in /tmp/credentials. When a other user connect, its credentials are sent and so on. Nothing is saved on the sd card. When reboot, nothing is kept. If you want to be the only user, disable shared device and add your credentials. In that case you'll be the only one able to use it. But in that case, user and password are saved in /data/configuration/music_service/volspotconnect2/config.json. It is written on the sd card.
I removed bitrate setting. Now the default value is 320kbps.
And no difference with volspotconnect 1, once you started playing, you can even power off your smartphone. Or maybe it behaves in other way with an Iphone ?

**Comment by FredBLKYN** [comment]
Thank you balbuze for your reply.
You were right : I rebooted everything and Spotify connect appeared on my iPhone. I guess it is the same with Android (?) but I can see 2 connections available to my HIFI system, One is Connect and the other "the old way" (streaming from the phone). After the initial setup of the Plugin only the second option was available and it didn't figure it out that it was not Connect.
Thanks and bonne journée ;-)

**Comment by balbuze** [comment]
Ah ok I see ! Volumio provides a "airplay" device. You can send sound from your Istuff to volumio, and it appears in any app with sound (youtube, spotify etc), but this is not Spotify connect ! If you stop your smartphone, the stream stops! With spotify connect provides by the plugin you can stop your phone, it continues to play. I just uploaded a new version in which you don't need to save to get a functionnal plugin. Just activate it in the webUI after installation, that it !

**Comment by balbuze** [comment]
et bonne journée aussi !
