### ISSUE TITLE
Volspotconnect2: librespot backend compile options

### ISSUE THREAD

**Issue by chsims1** [balbuze/volumio-plugins#33]
Hi,

I was just having a look at snapcast use of librespot, and I wondered what 'backend' options you had compiled librespot with?  It is mentioned elsewhere [https://github.com/badaix/snapcast/issues/189](url) that it needs "pipe" to stream correctly with snapcast.

**Comment by balbuze** [comment]
It was just compiled with alsa-backend (default settings). Not sure pipe is included. But as I think that scapcast should be configured to use alsa output in volumio in order that any source can be used (mpd, radio, and future music services)

**Comment by balbuze** [comment]
It was just compiled with alsa-backend (default settings). Not sure pipe is included. But as I think that scapcast should be configured to use alsa output in volumio in order that any source can be used (mpd, radio, and future music services)

**Comment by chsims1** [comment]
Snapcast client does indeed output to ALSA ... it's the getting Snapcast server to use the Spotify stream that I was looking at. 'Stdout' backend to librespot was renamed to 'pipe' according to the above post.

Anyway, as I say, I was just checking what options you had included.  I'll try compiling myself at some point.  Thanks for the reply.

**Comment by balbuze** [comment]
To be honest, I never used snapcast as you want. So I'll be interested in including some options if it helps. Just to know, have you tested the last version, and on which devices?

**Comment by balbuze** [comment]
I test and pipe is compiled in librespot. 
librespot --backend ? -c /tmp -n toto
INFO:librespot: librespot 6a0657f (2017-02-22). Built on 2017-02-25.
Available Backends : 
- alsa (default)
- pipe

**Comment by balbuze** [comment]
So it seems you'll be able to test with snapcast

**Comment by chsims1** [comment]
v0.25 works ok on RPi3.  I could also try RPi0 and RPi2 if that would be of help.

P.S. re. compiling librespot, what was the problem you had with armv6?  Did you cross-compile?  Any pitfalls to look out for?

**Comment by balbuze** [comment]
No needs to test on other boards. It works for me. 
The cross compiled version for arm produce a non working librespot. 
If you compile on a x86_64 using docker it will produce a librespot that won't work on volumio because 32 bits.
