### ISSUE TITLE
Some songs do not play

### ISSUE THREAD

**Issue by borez** [balbuze/volumio-plugins#34]
Can't get some of the newly released songs to play. For example Ed Sheeran's new "%" album: https://open.spotify.com/album/3T4tUhGYeRNVUGevb0wThu

Seems to be more of a librespot problem.

Tried 0.25. and the latest version, but no dice. Any idea?

**Comment by psychophil** [comment]
Songs seem to play fine a day later. Had same issue with new releases that played ok on the phone but not on volumio. Assumed it's a Spotify issue.

**Comment by leafy7382** [comment]
I ran into the same issue a few days before. Starting the plugin with traceback indicates that the problem is in librespot, it would be nice to get a trace and report to them to fix upstream. I don't think the plugin itself can fix the issue.

**Comment by balbuze** [comment]
plays without problem...
