### ISSUE TITLE
Question: Scrobbling with mpdscribble

### ISSUE THREAD

**Issue by dittodhole** [balbuze/volumio-plugins#35]
I've installed `mpdscribble` (https://volumio.org/forum/last-scrobbling-t31.html) on my box, and I am curious whether scrobbling should work or not (fyi, it's not working for me atm, but that could be a different issue ...).

**Comment by Saiyato** [comment]
mpdscribble can't read the librespot state, so that won't work I'm affraid. We'll have to wait for Balbuze to find a way (in accordance with plietar) to push the state to Volumio. That way we can look into building a LastFM scrobbler.
