### ISSUE TITLE
Main thread panic after some songs played

### ISSUE THREAD

**Issue by timlod** [balbuze/volumio-plugins#36]
Hi, I am using volspotconnect2 with volumio 2.118 on an RPIB+. 
When it works, it works quite smoothly (much snappier than before when I used vsc1 on volumio 2.03)

After about 5 songs, the service randomly crashes with the following error:
```
INFO:librespot::player: Track "Studio 20" loaded
thread 'main' panicked at 'connection closed', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/option.rs:715
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I started the service with via startconnect.sh to get this, from ssh. I don't know rust, I did run it like this:
/data/plugins/music_service/volspotconnect2/startconnect.sh RUST_BACKTRACE=1
But don't know how to actually get the backtrace.

Also, two smaller issues:
- playback has a lot of background noise. 
- At startup, I get this warning:
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }

**Comment by balbuze** [comment]
hi,
don't worry with the warning...
what is your dac? 
What do you mean by background noise ? between track?
RUST_BACKTRACE=1 refers to librespot, to startconnect.sh

**Comment by balbuze** [comment]
you rather enter /data/plugins/music_service/volspotconnect2/librespot --verbose -n test
and see what happens when it hangs

**Comment by timlod** [comment]
I don't use a DAC. Standard pi audio out.
I can't seem to start volspotconnect2 right now via that command - but actually right now I'm unable to start it via any means. I'll reinstall and tell you later how it went.
The noise is not background noise - in fact when I stop playback, there is no noise. As soon as I start playing a track, a background noise is introduced to the playback.

**Comment by balbuze** [comment]
The standard RPI output is very crappy... Even a cheap Dac would be a great improvement in term of quality.

**Comment by timlod** [comment]
After updating Volumio and reinstalling both the Spotify and the volspotconnect2 plugins it works again - without the panic!
The noise is still there. I didn't have that noise when I used the old Volumio and volspotconnect2, but that ran very unstably for me. I just checked using the Volumio and not connect for spotify playback - the noise is there also, so it's not a problem you have with volspotconnect.
I think the B+ output generally is acceptable. Not great, but good enough for my purposes.

**Comment by timlod** [comment]
I was being a bit quick there - it crashed again, albeit after a longer runtime and no malfunctions yesterday. Now it crashes really soon again.
I am unable to get it to start using /data/plugins/music_service/volspotconnect2/librespot --verbose -n test, I need to use startconnect.sh.
However, there I did get a better error this time:
`thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', /home/volumio/librespot/librespot/target/release/build/librespot-a5ecfbec8f45cf76/out/lib.rs:672
`

**Comment by balbuze** [comment]
@timlod,
thank you for your feedback. As the problem seems to come from librespot itself, I invite you to have a look here and if necessary, open an issue : https://github.com/plietar/librespot/issues
