### ISSUE TITLE
Premium Family Account - 2nd Account does not show Volumio connect possibility

### ISSUE THREAD

**Issue by GetMike** [balbuze/volumio-plugins#37]
Hi balbuze!
First of all thanks to this great plugin! :)
It works perfectly with my Premium Account. Now I upgraded spotify to a Family Premium Account and added a family member with premium access to spotify. I tried it several times for 2 days, but I cannot get my volumio player shown in the connect options of the spotify-app on the smartphone of this family member. It's no problem with my own phone.
Is there any kown issue concerning spotify connect problems with family accounts?
Installed: Volumio 2 on raspberry pi 3 / volspotconnect2
Cheers, Mike

**Comment by balbuze** [comment]
Hi,
I he plugin must be set to shared device activated. In that case no need to enter credentials. Let me know

**Comment by smalahove** [comment]
Not directly related, perhaps, but it does work fine with family account here. Sometimes  a reboot of Volumio is needed for Spotify Connect to appear. Once it appears, though, it works flawlessly on both my own premium account and our various family accounts.

Playing through mpdroid or similar works as expected.

**Comment by GetMike** [comment]
Thanks for the advice with the shared device activated - that's it! :)
I have running to different raspberries with volumio and forgot to acitvate the option in one of them. Now it works's perfectly - thanks for your great work!

**Comment by GetMike** [comment]
Works as expected :)
