### ISSUE TITLE
Change spotify connect device name?

### ISSUE THREAD

**Issue by miskor-bgd** [balbuze/volumio-plugins#38]
Hello,

Thank you very much for your work, much appreciated!

Is there a way to change spotify connect device name using plugin settings UI so it would survive changes ("-name 'Volumio' command line parameter")?

Thanks!

**Comment by balbuze** [comment]
Hi,
It use the name set in volumio. So go in volumio settings / system and change the name. Save. That should do it!

**Comment by balbuze** [comment]
Don't forget to disable enable the plugin so that change is take in account
