### ISSUE TITLE
No issue, just wanted to thank you for your work!

### ISSUE THREAD

**Issue by gavinhewitt** [balbuze/volumio-plugins#4]
Raspberry Pi 3B + Volumio 2.001 + Hifiberry DAC Plus, just installed volspotconnect. Works like a charm!

**Comment by balbuze** [comment]
Thanks!

**Comment by coqui** [comment]
I absolutely second that. Great work, you deserve a huge thank you. I've just downloaded and installed your last build with Volumio 2.031 + RPi 2 and it's working fantastic, took me just a few minutes to get it up and running. Using the last Spotify app on Android phone to control all is working (incl. volume). Yes, the UI is not showing the currently playing, but that's ok with my usage. Now I can put a hifiberry on order as well :)

**Comment by balbuze** [comment]
Thank you very much! It is always pleasant to read that. Most of the time, users write to complain... But it is necessary to improve the software.
