### ISSUE TITLE
volspotconnect2: indication in Volumio UI when Spotify Connect is active

### ISSUE THREAD

**Issue by MrIncredible007** [balbuze/volumio-plugins#41]
Would it be possible to give an indication of some sort in the Volumio UI to show that someone is streaming with Spotify Connect? Possibly even with current artist + song title.

**Comment by balbuze** [comment]
Librespot used in the plugin is still in dev and some features are missing. I already had a look to see how to get such metadata. But it is really not ready...
If you use volspotconnect and connect to port 4000 (IPadressofvolumio:4000) you'll see a web interface but is not integrated in volumio.

**Comment by ashthespy** [comment]
Wouldn't it be an option to use the Spotify Web API for the meta data, and use Librespot only for the playback? That way you could utilise most of the current Volumio Spop plugin framework?

**Comment by rbott** [comment]
I think @ashthespy is right, this would probably work:
https://developer.spotify.com/web-api/console/get-user-player/

It returns something like this:
`  "device" : {
    "id" : "some_random_id_here",
    "is_active" : true,
    "is_restricted" : false,
    "name" : "Volumio",
    "type" : "TV",
    "volume_percent" : 31
  },`

However, comparing the "name" field is probably not specific enough and might lead to some unwanted behaviour (e.g. if multiple connected clients share the same name). Pausing the playbook could also be implemented with the id from the output above and this request: https://developer.spotify.com/web-api/console/put-pause/ (well, with a slight chance of stopping the playback on another client with the same name). Or is it possible to somewhere get ahold of librespot's client-id?

My javascript skills are rather limited and I only started using Volumio last week, but hey - let's give it a try ;-) If someone comes up with a better approach I would also be happy to invest some time on that as well!

**Comment by balbuze** [comment]
I think the best way would be to write a plugin using https://developer.spotify.com/web-api/ to remote librespot. I made some test in console a it works to play, pause etc...

**Comment by balbuze** [comment]
this is now done in volspotconnect. Maybe one day for volspotconnect2...
