### ISSUE TITLE
volspotconnect2: support for volume changes through hardware mixer

### ISSUE THREAD

**Issue by MrIncredible007** [balbuze/volumio-plugins#42]
I'm using Volumio + volspotconnect2 plugin on a Raspberry Pi 3 with Hifiberry AMP. When changing the volume through Spotify Connect, it's limited to the current volume set in Volumio. Is it possible to change the Volumio master volume through Spotify Connect?

**Comment by balbuze** [comment]
At this point, librespot used in the plugin, does not allow using a other mixer.... A work is in progress  and will be of course integrated as soon as it will be ready.
If you really need this now, you can use volspotconnect
