### ISSUE TITLE
volspotconnect: plugin activation issues

### ISSUE THREAD

**Issue by macmpi** [balbuze/volumio-plugins#43]
It seems volspotconnect activation (red/green light) is conflicting with other plugins, such as @volumio [503 hta tube amp](https://github.com/volumio/volumio-plugins/tree/master/plugins/accessory/503_hta_tube_amp) for instance.

if 503 hta tube amp is `OFF`, setting volspotconnect to `ON` starts normally and green/active light comes after a while: that is fine.

However, if 503 hta tube amp is `ON` first, and then starting volspotconnect, its light stays red/inactive.
Switching 503 hta tube amp then `OFF`  (with volspotconnect still `ON`) does not get volspotconnect green/active light, but then-flipping volspotconnect to `OFF` would  produce green/active light for volspotconnect, while it staying `ON`!...

Same conflict happens between volspotconnect and some other plugins.
It's likely that some voodoo libQ/promise is at play here: no clue how to help, but you may want to look at it.
(did not test with volspotconnect2 is similar issue is there too)

**Comment by balbuze** [comment]
Humm... I used volspotconnect with other plugin (kodi, brutefir, wifireconnect) and never noticed that...
And now I just use volspotconnect2 with the same other plugin, with no issue.
Volspotconnect code is maybe not very "clean". It was one of my first plugin. I'll try to have a look one of this day, but to be honest, most of my effort is not here. Anyway thank you for the hint
