### ISSUE TITLE
Shows up as a device but can't connect

### ISSUE THREAD

**Issue by dirtbiker1824** [balbuze/volumio-plugins#45]
Really appreciate the work you've put into this and the level of response you have with your user base! I have volspotconnect2 ver0.2.9 installed on a RP2. I'm able to see Volumio as a device under the spotify device menu, but I'm not able to connect to it, it just tires for about 30 seconds then times out. Is there anything I'm doing wrong?
Thanks!

**Comment by tbcbigd** [comment]
I have the same problem.
I have used different builds of volumio (2.129 and 2.141) and i tried volspotconnect and volspotconnect2

**Comment by dirtbiker1824** [comment]
I was able to fix this by performing a factory reset on volumio 2.141 then installing Volumio Sopotify connect ver1.6.0.

**Comment by balbuze** [comment]
Hi,
I noticed it very rarely. I can't determine what cause that, and the fact that switching from a device to an other unlock this situation. What is the Spotify client you use ? I mean on android, ios, windows, linux ?
 I now use volspotconnect2, and I don't think volspotconnect will be improved unless a very good and easy to implement feature is added...

**Comment by tbcbigd** [comment]
Thanks for your reply
I have tried spotify on windows and on android. I have tried with volspotconnect 1.6.0 and the latest volspotconnect2. I get the same result every time.
I will try the factory reset dirtbiker did.

**Comment by balbuze** [comment]
let me know because there is something weird.... Volspotconnect is used for month and this is the first time this problem is reported... Could it be due to a Spotify update ?

**Comment by tbcbigd** [comment]
The factory reset didn't solve my problem.
On my android device i use spotify  version 8.4.0.539 armV7.
I hope you can find out what couses the problem

**Comment by tbcbigd** [comment]
I have tried it with an iphone and that worked.
I saw by the iphone two devices stConnect and Volumio. On the android phone there is only stConnect.

**Comment by balbuze** [comment]
Can you use Spotify from a other device ? (computer, ios, linux ) to test.
Are you sure to no other connection to your account ?

**Comment by balbuze** [comment]
oups we posted on the same time

**Comment by tbcbigd** [comment]
I have tried from windows pc. There is also the stconnect device but not connecting

**Comment by balbuze** [comment]
Yes on ios you spotify connect and volumio airplay. This is not the same thing. With airplay, your phone send the stream, and thus  use your battery. With Spotify connect, your phone is just a remote. You can even switche it off, music will continue. In which country do you live ?

**Comment by tbcbigd** [comment]
In the Netherlands

**Comment by balbuze** [comment]
can you use ssh ?

**Comment by tbcbigd** [comment]
Yes i can trie but i'm a noob with raspberry

**Comment by balbuze** [comment]
so connect to your rpi from a console or putty and enter ssh volumio@IPadressofvolumio and password volumio

**Comment by balbuze** [comment]
of course replace IPadressofvolumio by your ip

**Comment by tbcbigd** [comment]
i did

**Comment by balbuze** [comment]
now sudo journalctl -f
wait a bit and try to connect from your smartphone or computer.
Copy if some error message and paste here

**Comment by tbcbigd** [comment]
i only see this text:
Apr 25 19:03:34 volumio volumio[1522]: 192.168.2.9 - - [2017-04-25 19:03:34] "GET /login/_zeroconf?action=getInfo HTTP/1.1" 200 587 0.072340
Apr 25 19:03:36 volumio volumio[1522]: 192.168.2.9 - - [2017-04-25 19:03:36] "GET /login/_zeroconf?action=getInfo HTTP/1.1" 200 587 0.072016

Constant repeating and i can't not connect and i see no error

**Comment by balbuze** [comment]
Have you a premium account ?
Have you tested volspotconnect2 ?

**Comment by tbcbigd** [comment]
Yes i have premium. 
I had tested volspotconnect2 earlier. 
I did several clean installs.
The ip number 192.168.2.9 in the test above is from my phone by the way but i was not constant connecting

**Comment by balbuze** [comment]
I'm sorry,I don't see what is wrong... All your device are on the same network ? Have try to disable "shared device" in plugin settings ? I have to go now. Just to said, when writing I'm listening spotify connect on a pine64, a rpi b and a sparky sbc... It also works on my rpi2...
If you have new info, let me know, but I won't answers tonight I had a hard day today...

**Comment by tbcbigd** [comment]
oke thank you for your help
Yes al my  devices are on the same network.
I will try different settings.
I let you know when it worked
Thank you so far

**Comment by tbcbigd** [comment]
I have figured it out. I have a symbol in my spotify username it's "|" That give the error.
I changed my username and now it's working.
Thank you for your help

**Comment by balbuze** [comment]
ok... I should have think of a password problem...

**Comment by balbuze** [comment]
solved....

**Comment by gustafekeberg** [comment]
Hello!

I have this issue too.

In my username there is a `-`. It used to work until maybe around when this thread started (can't remember the exact date). Now I can't connect to Volumio from Spotify via volspotconnect2 anymore. If I try with another account that has only a-z in the username it's fine.

From the log (these lines repeats until I restart volumio):

```
May 25 14:15:13 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
May 25 14:15:13 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
May 25 14:15:13 volumio systemd[1]: Starting Volspotconnect2 Daemon...
May 25 14:15:13 volumio systemd[1]: Started Volspotconnect2 Daemon.
May 25 14:15:13 volumio volumio[3227]: INFO:librespot: librespot d95c0b3 (2017-04-13). Built on 2017-04-15.
May 25 14:15:13 volumio volumio[3227]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
May 25 14:15:14 volumio volumio[3227]: INFO:librespot::session: Connecting to AP "gew1-accesspoint-a-zpx3.ap.spotify.com:4070"
May 25 14:15:15 volumio volumio[3227]: INFO:librespot::session: Authenticated as "gustaf-ekeberg" !
May 25 14:15:15 volumio volumio[3227]: INFO:librespot::audio_backend::alsa: Using alsa sink
May 25 14:15:16 volumio volumio[3227]: thread 'main' panicked at 'subscription terminated', /home/volumio/librespot/target/release/build/librespot-47570c3f9defd0f4/out/lib.rs:615
May 25 14:15:16 volumio volumio[3227]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
May 25 14:15:16 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
May 25 14:15:16 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
```

**Comment by balbuze** [comment]
@gustafekeberg please try with the last version available of the plugin : https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/volspotconnect2.zip

**Comment by balbuze** [comment]
what is your device ?

**Comment by gustafekeberg** [comment]
That's the version I'm already running. My device is a Raspberry Model B Rev 2.

**Comment by balbuze** [comment]
I see.... I haven't compiled the new librespot for that version of arm... I try to do that ASAP. A quick solution would be to use a previous compiled version of librespot

**Comment by balbuze** [comment]
@gustafekeberg I uploaded a new version for arm . Try if it solve your problem.

**Comment by gustafekeberg** [comment]
Yes! This version seems to work ok. I haven't tested the audio because my kids are using the TV at the moment, but the log looks fine.
Thank you very much, I really appreciate this your work with this plugin!
