### ISSUE TITLE
Reconnect script (wifireconnect.sh)

### ISSUE THREAD

**Issue by djalmaoliveira** [balbuze/volumio-plugins#47]
My case:
1. Start volumio/rpi1b with hotspot disabled (in gui configuration) and with router turned off.
2. Wait the system to start until you see "Volumio 2 system startup" in logs (using journalctl -f).
3. Turn on wifi router, and the system get wifi connection as expected.
4. Now, reboot wifi router and wait, wait, wait until you see in logs "Hotspot is disabled, not starting it".
5. At this time you can see in the logs "Starting/started Wifireconnect", but not works, no reconnection.
6. So, I figured out that "`ip link set ...`" not work in this situation.

Solution: 
Replace "if" statement with this:

```
if [ "$?" != "0" ]; then
    ifdown --force ${NINTERFACE}
    systemctl restart wireless
fi
```

> (I know that this code should be into template file .tmpl)

#### Environment test

Volumio 2163
Raspberry pi 1 Model B
USB Wifi TLWN-721N
8GB microsd card + adapter

**Comment by balbuze** [comment]
Hi!
Thanks for the hint. I can't test now but next week...

**Comment by biva** [comment]
Hello @balbuze 
Were you able to look at this issue. Could it be related to https://github.com/balbuze/volumio-plugins/issues/64 ?
Thank you!
