### ISSUE TITLE
volspotconnect2 dependency install error?

### ISSUE THREAD

**Issue by shawaj** [balbuze/volumio-plugins#48]
Getting the following error when trying to install Spotify Connect via volspotconnect2.zip

![image](https://cloud.githubusercontent.com/assets/3359418/26132555/0ba38de8-3a99-11e7-87e1-d458918259e5.png)

Any idea what is wrong?

**Comment by balbuze** [comment]
The required files cannot be downloaded. Your device can't reach the repo(github). Is your connection to internet ok ? Retry later if so. And in some cases, the DNS of your ISP are in cause. Try to use a custom DNS (network settings of volumio). With last version of volumio it should be ok... Let me know

**Comment by shawaj** [comment]
Yes internet connection is fine, and the normal Spotify plugin connects fine?

**Comment by andrewj15** [comment]
I'm having the same issue, I can install an older version of volspotconnect2 0.15 but have tried to install later versions and non work with the same error as above. It seems that when the file size changed from ~2.8mb to ~200kb that I am no longer able to install the volspotconnect2 plugin. Im using the latest volumio 2.175 with and RPI 3. The internet works fine but am unable to play music via the older 0.15 version of volspotconnect2.

**Comment by andrewj15** [comment]
Fixed it by following this thread seems was an issue with virgin media

https://github.com/balbuze/volumio-plugins/issues/40

**Comment by balbuze** [comment]
Good!

**Comment by jhreid** [comment]
Having the same issue
Raspberry Pi 3, Justboom DAC

I am on BT Infinity and it doesn't allow DNS changes. Is there a way to install dependencies manually?

**Comment by balbuze** [comment]
Hi! Have you tried to change the dns settings in volumio ?

**Comment by jhreid** [comment]
I have - but my ISP doesn't allow that.
I SSHed in to the Pi and ran install.sh directly - I am getting 

Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|213.120.234.138|:443... connected.
GnuTLS: A TLS fatal alert has been received.
GnuTLS: received alert [0]: Close notify
Unable to establish SSL connection.

**Comment by balbuze** [comment]
What is your device? You can download the required librespot by hand and install it with a special version. But I need to know your device to tell you how to do

**Comment by jhreid** [comment]
It is a raspberry pi 3

**Comment by balbuze** [comment]
please have a look here (near the end) I uploaded a special version for local install... But I didn't test it 
https://github.com/volumio/Volumio2/issues/1123

**Comment by jhreid** [comment]
Plugin installed - many thanks

**Comment by balbuze** [comment]
:+1:
