### ISSUE TITLE
Spotify connect plugin does not start

### ISSUE THREAD

**Issue by ENSen** [balbuze/volumio-plugins#5]
Installed the spotify connect plugin but it does not start.
![image](https://cloud.githubusercontent.com/assets/1507248/20409527/45d12262-ad1a-11e6-8a39-460e8603fe71.png)

I found this in /var/log/volumio.log

`2016-11-17T21:39:10.368Z`` - info: Volspotcoonect status error:
2016-11-17T21:39:10.371Z - info:  Error: connect ECONNREFUSED 127.0.0.1:4000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
2016-11-17T21:39:10.374Z - info: Volspotconnect status error:
2016-11-17T21:39:10.375Z - info:  Error: connect ECONNREFUSED 127.0.0.1:4000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

**Comment by ENSen** [comment]
I have a RPI 3B and volumio 2.001, also tried 2.027 with the same result.

**Comment by balbuze** [comment]
Sorry but I can't see what is wrong with that. Could you please tell what is your DAC, mixer setting, and give the content of /data/pluugins/music-service/voslpotconnect/spotify-connect-web/startconnect.sh ( change credentials with xxx). what retruns aplay -l ?

**Comment by ENSen** [comment]
I am using a USB dac with an xmos based USB receiver (WaveIO). I found one problem in startconnect.sh. As you can see below the mixer name contains blanks.

`cd` /data/plugins/music_service/volspotconnect/spotify-connect-web
./spotify-connect-web  --username 'xxxxx' --password 'xxxxx' --bitrate 320 --name 'Volumio' --playback_device hw:5 --mixer Luckit Audio 2.0 Output  --mixer_device_index 5 --dbrange 45 # &
avahi-publish-service 'Volumio' _spotify-connect._tcp 4000 VERSION=1.0 `CPath=/login/_zeroconf`

To get around that I manually updated it to look like this;

'
cd /data/plugins/music_service/volspotconnect/spotify-connect-web
./spotify-connect-web  --username 'xxxxx' --password 'xxxxx' --bitrate 320 --name 'Volumio' --playback_device hw:5 --mixer 'Luckit Audio 2.0 Output'  --mixer_device_index 5 --dbrange 45 # &
avahi-publish-service 'Volumio' _spotify-connect._tcp 4000 VERSION=1.0 CPath=/login/_zeroconf'

Then the plugin became active and "Volumio" showed up in my spotify app on my phone. I could select to play Spotify to Volumio but I did not get any sound. I ran startconnect.sh to be able to see the output from it and when pressing play in my spotify app I got this message from startconnect.sh

Ups! Some badness happened:  Data size must be a multiple of framesize

**Comment by balbuze** [comment]
I'm going to change some things to support mixer with space in name ! (It's the first time I meet that). By waiting, you can change in volspotconnect.tmpl . With that you can change and save config. I keep you in touch with that. For last point I don't know... I have to investigate.

**Comment by ENSen** [comment]
Thank you for the response! I have some faint memory of having problems a couple of years ago with WaveIO. The problem was, I think,  that WaveIO only will accept 32 bit LE. Could that have something to do with this issue?

**Comment by balbuze** [comment]
In fact changing volspotconnect.tmpl won't work.... I'm changing it it index.js. I really don't know for what you see about 32 LE. And there is no option in spotify connect web. Maybe using resampling ....

**Comment by ENSen** [comment]
I have no idea if 32LE have something to do with it. I just remember having to to resample in ALSA config a couple of years ago using Ubuntu. Using Volumio to play music from my NAS works without problems and I have not changed any ALSA configuration.

**Comment by balbuze** [comment]
I just uploaded a new version that supports space in mixer name...

**Comment by ENSen** [comment]
Thanks

**Comment by balbuze** [comment]
I haven't found teh source of your problem but I think there is something to do with that : https://larsimmisch.github.io/pyalsaaudio/libalsaaudio.html

**Comment by ENSen** [comment]
I agree. I am still thining about the format. In this thread for example there was a format problem with airplay. But maybe the problem in that case lies with spotify web connect and not your plugin? I will create a .asoundrc file and change format to S32_LE and see if that helps.

**Comment by ENSen** [comment]
It seems to work if I change playback_device from hw:5,0 to plughw:5,0 in startconnect.sh

**Comment by balbuze** [comment]
Good ! The problem is that I had problem with some dac with plughw.... I have to make some test... 
Anyway thank you for investigating ! Does your mixer work as expected ?

**Comment by balbuze** [comment]
If you want something more convenient, you can change in index.js following line
var hwdev = 'hw:' + outdev; 
in
var hwdev = 'plughw:' + outdev;
save and killall node to apply

**Comment by balbuze** [comment]
And a very important point for me is that I can't get sound with software mixer... Everthing seems ok, the plugin is activated and I can see the device from Spotify app, but no sound.... I really struggle with that !

**Comment by ENSen** [comment]
Sorry for the late feedback. I changed index.js according to your instruction and that worked fine! The mixer works but I have not tried sw mixer.

Thanks for your work, it is very much appreciated. The next step is to try brutefir.

**Comment by balbuze** [comment]
Just to say that it is now included in the plugin. So if you reinstall, nothing to do !

**Comment by twirre** [comment]
thanks!! it is working for me. Had trouble with a RPI and and hifiberry DAC.
