### ISSUE TITLE
No settings 

### ISSUE THREAD

**Issue by Johetan** [balbuze/volumio-plugins#50]
Hej guys! 
I just installed the plugin and have no UI in the brutefir settings tab.

**Comment by balbuze** [comment]
Please, what is your device, volumio version, plugin version ?

**Comment by Johetan** [comment]
Thanks for the fast reply!

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
VOLUMIO_BUILD_VERSION="d590cd4ebba5344530e741a2fc1fa2e5a104f82e"
VOLUMIO_FE_VERSION="6d07d79c9f0950e4863b18b80778e5f7f9892798"
VOLUMIO_BE_VERSION="73e606d24d1ae63b71c508d3b528a9af0fcfe467"
VOLUMIO_ARCH="arm"
VOLUMIO_VARIANT="volumio"
VOLUMIO_TEST="FALSE"
VOLUMIO_BUILD_DATE="Fri May  5 09:07:01 CEST 2017"

VOLUMIO_VERSION="2.163"
VOLUMIO_HARDWARE="pi"

I Also Installed the waveshare 5 inch hdmi display (b)
via display plugin 
and the config.txt 
added 

hdmi_group=2
hdmi_mode=87
hdmi_cvt 800 480 60 6 0 0 0
hdmi_drive=1

spotify plugin
youtube plugin
xinput-configurator 
changed the 99-calibration.conf

raspberry pi 3 
hifiberry dac+

I used yesterdays zipfile of brutefir

**Comment by balbuze** [comment]
I have to do some test. I never tried with touch plugin

**Comment by Johetan** [comment]
Nice, thank you! btw thanks for all your work

**Comment by balbuze** [comment]
I made a test with the last version available on github, and with youtube plugin and everthing is fine... We need to investigate a bit more... Can you use "sudo journalctl -f" in a ssh console and see if something is dispalyed when you go to settings ?

**Comment by balbuze** [comment]
I met the problem even if I don't understand where it comes from...as sometimes it works, sometimes it doesn't... Sorry for that, but I'll try to have a look tomorrow...

**Comment by balbuze** [comment]
let's try the new version !

**Comment by Johetan** [comment]
Sorry, couldn't answer the last days, I'll try it in the evening and give you feedback, cheers mate!

**Comment by Johetan** [comment]
That did it. Thanks mate!
