### ISSUE TITLE
brutefir 2 breaks volumio 2.175

### ISSUE THREAD

**Issue by tomaszrondio** [balbuze/volumio-plugins#51]
I have (had) clean volumio install. Installed brutefir2 from zip file. I got a message that installation failed because brutefir is already installed (seems to be common bug). Anyway it was visible on plugins list. Once activated it breaks volumio web UI. Ssh works fine. Restarting volumio does not help. I managed to get web UI working by running uninstall.sh and deleting /data/plugins/miscellanea/brutefir folder. Although there is no sound. 
in /data/configuration/miscellanea/brutefir there is only config.json

volumio@volumio:~$ systemctl status brutefir
● brutefir.service - brutefir Daemon
   Loaded: loaded (/etc/systemd/system/brutefir.service; disabled)
   Active: failed (Result: start-limit) since Fri 2017-05-19 22:17:05 UTC; 11s ago
  Process: 2889 ExecStart=/usr/bin/brutefir /data/configuration/miscellanea/brutefir/volumio-brutefir-config (code=exited, status=1/FAILURE)
 Main PID: 2889 (code=exited, status=1/FAILURE)

May 19 22:17:05 volumio systemd[1]: brutefir.service: main process exited, code=exite...URE
May 19 22:17:05 volumio systemd[1]: Unit brutefir.service entered failed state.
May 19 22:17:05 volumio systemd[1]: brutefir.service holdoff time over, scheduling restart.
May 19 22:17:05 volumio systemd[1]: Stopping brutefir Daemon...
May 19 22:17:05 volumio systemd[1]: Starting brutefir Daemon...
May 19 22:17:05 volumio systemd[1]: brutefir.service start request repeated too quick...rt.
May 19 22:17:05 volumio systemd[1]: Failed to start brutefir Daemon.
May 19 22:17:05 volumio systemd[1]: Unit brutefir.service entered failed state.

volumio@volumio:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by balbuze** [comment]
Hi,
I know this problem... It's because when you first start the plugin, brutefir is not correctly configured, and cannot be reached and prevent volumio to start. But you can't configure it because volumio can't start... I have to handle this error. Sorry for that. I try to find a fix.

**Comment by tomaszrondio** [comment]
thanks a lot. Let me know and I will try again

**Comment by balbuze** [comment]
should be better now... but sometimes, UI for setting does not come... Don't forget to configure the right ouptut in advanced settings

**Comment by tomaszrondio** [comment]
way better. I am getting something. Plugin settings page is empty now. Rest seems to work perfectly fine. I can't find a way to debug it or see any kind of errors log. It would help I guess.

**Comment by balbuze** [comment]
Thanks for testing. There something very problematic in the Ui I can't figure. In fact, changing a specific line in the code make it appears, and then if back to the previous code, it works... It is like it needs to to be first initialized. The more strange is that persist through plugin install / remove. But on a fresh install... I can send you a version that includes this, but the problem is that value displayed by equaliser are not restored (just in the Ui). They appear to be 0. But the good value is used for the sound.

**Comment by tomaszrondio** [comment]
tell me which line has to be changed and I will try :)

**Comment by balbuze** [comment]
I made the changes in a new version. Now it should work... Don't forget to set and save the good output in advanced settings. If you use a RPI 2or 3 you can set filter length to the max if you experience some cut in the sound. And due to the last modification settings seems to be not restored in the Ui, but values are...

**Comment by tomaszrondio** [comment]
it is alive! Thank you very much!
Will learn how to use it, apply custom presets and let you know.

**Comment by balbuze** [comment]
I uploaded a new version that should fix the UI...

**Comment by tomaszrondio** [comment]
It does not affect my life but values are not restored in my case. I uninstalled old version and installed new. Want me to try with clean volumio install?

**Comment by balbuze** [comment]
Weird... I will do a test with a fresh install. But do you use the very last plugin? Or I missed something when uploading.. apart that, can you use it, the equaliser, test sample filters ? Don't hesitate, I need user feedback to improve and debug

**Comment by tomaszrondio** [comment]
cancel! abort! I restarted volumio and everything works fine. Sorry for that...
I will test sample filters as soon as possible = tomorrow or day after tomorrow and let you know.

**Comment by balbuze** [comment]
No problem! Have you tested the equaliser? It needs some cosmetic improvement... and what is your device, dac? Thanks

**Comment by tomaszrondio** [comment]
I did and it works fine as well as presets. I wouldn't be concerned about equalizer cosmetics. BruteFIR is usable in DRC and hopefully will be used that way. My dac is hifiberry dac+.

**Comment by tomaszrondio** [comment]
how do you create these filter .wav files? I just tried to generate some with DRC Designer and it killed volumio :)

**Comment by tomaszrondio** [comment]
ok. Filters haven't killed volumio but somehow configuration was saved with input and output format as S24_LE and sample rate 192000

**Comment by balbuze** [comment]
I uploaded yesterday a version that handles errors and avoid Ui crash when brutefir fails to start due to a wrong config. And you are right settings must match with the filters format. Let me know.

**Comment by tomaszrondio** [comment]
yep. I managed to break brutefir and got proper error message. Very nice!

**Comment by balbuze** [comment]
I struggle a bit to add a filter selector in the UI : instead of typing the name of the filter, the idea is having a dynamic  list (list of file in the folder) and just select the one you want to use. Nearly ok ...
And the big last improvement is to auto configure input/output and use i2s dac and volume control...
If you manage to create filter, I'll be interested for testing or adding it as demo filters.

**Comment by tomaszrondio** [comment]
I just created first filter in my life using room eq wizard. It should flatten Visaton BG20 speaker (only driver, not room response). I hear difference but I can't tell if that is correct. Its 11pm so I can't do loud measurements.
[rew.wav.zip](https://github.com/balbuze/volumio-plugins/files/1030234/rew.wav.zip)

**Comment by tomaszrondio** [comment]
this is what I did manually and it sounds way better. What i learned so far is that it is super important to set proper filter format. Otherwise it sounds wrong. Attached filter response will work correctly only with my set of speakers. Sometimes I get audio gaps. Increasing filter size solves it. What is filter size? :)
[rewmanual.wav.zip](https://github.com/balbuze/volumio-plugins/files/1031834/rewmanual.wav.zip)

**Comment by balbuze** [comment]
Increasing the filter size avoid a "buffer underflow" in alsa that hang brutefir. The systemd service restart it immediatly, but it is what you ear. If you are interrested, have a look here : https://www.ludd.ltu.se/~torger/brutefir.html the explaination would much better than mine.... Let me know if you need more or other settings...

**Comment by balbuze** [comment]
Thanks for sharing your filters. If you agree I will add them in demo filters as they sound much better than mine...

**Comment by tomaszrondio** [comment]
will read that and try to understand as much as possible :) 
You can do anything you want with these filters. Although I don't think it makes any sense with different speakers. But as I said - it is yours, do whatever you want. 
I can prepare some filters for you. Just tell me what kind you need.

**Comment by balbuze** [comment]
I know it each filter is specific to one system. I just want to provide 2 ou 3 samples for user that want to test the plugin... even if the result is no better or even bad, but you can hear the effect ;-)
( I spend a lot of time reading and trying to understand brutefir and all options... The plugin is the result of what I understood, maybe not very well! )

**Comment by tomaszrondio** [comment]
this filter sucks. I thought it will apply only small equalization but it does more. It feels/sounds that it compresses sound as well (makes it louder). I have to investigate more what is going on and why.

**Comment by balbuze** [comment]
Yep it is not easy to create a good filter... Don't know if you can read french, but if yes there is a nice tutorial here : http://forum-hifi.fr/thread-2003.html
and a translation here  : https://www.dropbox.com/s/10xdhh83jokzbxv/REW_rePhase_tuto.pdf?dl=0

**Comment by tomaszrondio** [comment]
I can't read French but this translation is very good. I will learn, practice, fail, get crazy, try again and get back to you when succeed

**Comment by balbuze** [comment]
To avoid underflow in brutefir I set the systemd service to run as root : in this case brutefir runs with realtime priority that should avoid the problem you met.

**Comment by balbuze** [comment]
new version uploaded... No more manual config for output/input... But Volumio must be configured with the correct output Before enabling the plugin, and only after Loopback must be selected (it will be done automatically when finished). brutefir service run as root in this version. not fully tested...

**Comment by tomaszrondio** [comment]
problem I met is that my filter is probably wrong. It changes volume in full frequency range but should not. I don't get what underflow in brutefir is :)

**Comment by tomaszrondio** [comment]
hmm. I did a little yet simple test. I generated pink noise. Inserted it in Reaper DAW and put through measurement impulse response (via reaverb plugin). And that gave me pretty much what Room EQ Wizard measured:
![screenshot 2017-05-28 00 08 02](https://cloud.githubusercontent.com/assets/4939724/26524641/313b2404-433a-11e7-8a19-4b293c2f11b4.png)
Then on master bus I added reaverb plugin and put filters impulse response. In theory it should flatten frequency. And it did!
![screenshot 2017-05-28 00 08 27](https://cloud.githubusercontent.com/assets/4939724/26524657/97e05e0e-433a-11e7-87b1-fd69954e074d.png)

Conclusion is that I messed something up with brutefir configuration since impulses seem to be fine.

**Comment by tomaszrondio** [comment]
I just installed newest version over clean volumio install. There is no option to select Output device and I can't hear sound. Config looks similar (it was hw:2 before)
but I get:
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
ALSA I/O: Could not open audio output "hw:2": No such file or directory.
Failed to init output device.
Failed to initialise digital audio interfaces.

**Comment by balbuze** [comment]
Ok. .. In fact the plugin use volumio configuration to be configured. It's​because there's no more settings for input output. I'm working to fully automatically​configure it just by enabling the plugin... Do you output to hifiberry ?. Do you use volume control ?

**Comment by tomaszrondio** [comment]
Yeah I output to hifiberry dac+. I don't use volume control. 
Actually this filter I uploaded before started to work properly. I have to double check and do some measurements.

In newest readme.md it says: "Set Loopback as output device in volumio playback options." which seems to be not recommended anymore.

**Comment by tomaszrondio** [comment]
My filters still don't work as they should. I am playing with text filters and brutefir configuration at the moment. How can I restart brutefir properly?
`brutefir volumio-brutefir-config` says that device is busy so I guess that there is some other way.

**Comment by tomaszrondio** [comment]
ha! I think I nailed it! Don't know why yet but it works. 
Remedy is a little console app called sox. Trick is to convert impulse response wav to raw. It cuts wav headers from file and probably something else I don't know about.
`sox filter.wav --bits 16 --encoding signed-integer --endian little filter.raw`
http://sox.sourceforge.net/

this filter cuts high frequencies by 3db.
[rephase.raw.zip](https://github.com/balbuze/volumio-plugins/files/1039440/rephase.raw.zip)

**Comment by balbuze** [comment]
good ! I'll try tomorow. I'm nearly done with the plugin autoconf, but I struggle to finish...

**Comment by tomaszrondio** [comment]
write me how to restart brutefir. I want to try doing custom configurations. eq on each driver + eq of room and phase response.

**Comment by balbuze** [comment]
To restart brutefir you can do "systemctl restart brutefir". But I think the problem is different for you. The plugin takes its configuration from volumio. The first time it is ok. But once you have set Loopback, if restart, the config becomes wrong.. in this version the only way is to disable plugin, set the right output in volumio, enable the plugin, and set Loopback in volumio. Sorry for that. It is solved in the version I have but due to other problem I can't publish it yet

**Comment by tomaszrondio** [comment]
If I put some custom values in config I have to restart. Saving advanced plugin configuration does restart but overwrites my changes. I only need some way to restart brutefir without overwriting my custom coeffs etc.

**Comment by balbuze** [comment]
If you have change something in brutefir config, the best is to do that in brutefir.tmpl this file is the template used by the plugin to create the volumio brutefir config. With that, when you save, it should be ok

**Comment by tomaszrondio** [comment]
great!

**Comment by balbuze** [comment]
If your tests bring to add new parameter let me know. I'll add it in the template file.

**Comment by tomaszrondio** [comment]
sure but it probably won't :) I want to try active crossover that is why I need editing config file.

**Comment by balbuze** [comment]
Hi. This something that might interest me... In which case do you use it? It is near Bauer binaural filter?

**Comment by tomaszrondio** [comment]
I build speakers on my own and need something for testing. 
Next step is multichannel soundcard and amp for each speaker driver to build real active system. 
Good read: https://www.computeraudiophile.com/ca/ca-academy/Advanced-Acourate-Digital-XO-Time-Alignment-Driver-Linearization-Walkthrough/

**Comment by balbuze** [comment]
I made more test with the filter you sent, and I realize that the result really depends of the filter_format setting. When changing this value, 2 cases : brutefir hangs or the sound is very distorded. The setting should match with the filter generated

**Comment by tomaszrondio** [comment]
Absolutely. The one I sent is 16 bits little endian.

**Comment by balbuze** [comment]
I (quickly) read the article you sent. Very interessant

**Comment by balbuze** [comment]
The version I upload today work very well with my usb dac. Now when you disable the plugin, the configuration of volumio is restored. I'm really happy of that, now it is dead easy to us : just enable and it's done. Remains the (big) problem with i2s... It works but after a reboot it's dead...(not really but no more sound)

**Comment by tomaszrondio** [comment]
super cool! What is the problem with i2s? I have hifiberry that works over i2s and everything is fine. Can I somehow help you? I can code pretty well in js (if U tell me how to start). I can test whatever you need.

**Comment by balbuze** [comment]
The only i2s DAC I have to test works when I enable the plugin. But after a reboot no. It seems that when the plugin set the output of volumio to Loopback ( that appears now as "brutefir plugin") it disable i2s. And when you reboot the dac is not available. I'm not sure of that. But I am sure it does not work flawlessy. Do you use the last version of plugin 0.28. have you made a change in volumio ? ( Comment some lines in a file) as I wrote somewhere. Or this is really a base install of volumio and plugin that works out of the box (the case with my USB DAC)?

**Comment by tomaszrondio** [comment]
I have 0.2.4 installed and never had issue you described. Volumio is totally fresh install, no changes.
Will try 0.2.8 + rebooting and let you know.

**Comment by tomaszrondio** [comment]
Just wanted to let you know that I had to reboot bcs volumio updated. Still have 0.2.4. Everything works after rebooting.

**Comment by balbuze** [comment]
Ok . And what about last version?. Thanks for testing

**Comment by tomaszrondio** [comment]
Uninstalled old version. Installed 0.2.8. Restarted and indeed I get no sound. Changing playback preferences back to i2s hifiberry, saving plugin settings. Nothing helps.

**Comment by balbuze** [comment]
Ok sorry for that... If you need to reinstall a previous version 
Search my  github repo.. I need to rework ..

**Comment by balbuze** [comment]
0,2.4 https://raw.githubusercontent.com/balbuze/volumio-plugins/522bdbeb63c5f51aff8ef9e9c6ca33d3ce2f7af9/plugins/miscellanea/brutefir2/brutefir.zip

**Comment by tomaszrondio** [comment]
I am not in hurry. Maybe There is something that would Help you with debugging. Any logs/commands I could check?

**Comment by balbuze** [comment]
Hi!
new version that seems to work with i2s dac... even after a reboot ! when enabling / disabling wait few second before playing as I add some delay to write miscellaneous config file. Hope it will ok! I have to work to understand why a user get no sound with a usb dac. I have small idea...

**Comment by tomaszrondio** [comment]
when you made last comment 2 days ago I removed old plugin and installed new. No sound -> restart -> volumio bricked. I thought that ok I should try on clean install. I did just now. Clean volumio -> install plugin -> enable plugin -> plugin advanced settings save -> can't see plugin on list, can't open playback preferences. I though that maybe restart is a good idea. It was not. Bricked again.

**Comment by balbuze** [comment]
humm there is something else wrong in your settings... I'm using the last version with three different device (rpi b, rpi2, pine64) and it works. You don't need to save advanced setting, just enable the plugin. But now there is a problem in volumio. In very last version 2.191 (and maybe before), when i2s dac is enabled it sends a wrong value in the config (I'm not talking about the plugin) to test look the device number of your dac with aplay -l . And check  /data/configuration/audio_interface/alsa_controller/config.json if value is different for outputdevice, it's because there is no sound. The trick is enabling i2s, selecting the good dac, reboot if required, then disabling i2s, selecteing the right output and save.... But as i2s is disabled, next reboot will be problematic unless if you save /boot/config.txt before disabling, then disabling, and restore the file. After that you should be able to use the plugin. Please what returns 'sudo journalctl -f' ?

**Comment by balbuze** [comment]
And use the very last version.

**Comment by balbuze** [comment]
@tomaszrondio how are you ? I think I may need your help for some node problem.... Just let me know if you want.
I found why the plugin doesn't always works to autoconfigure, sometimes ok, sometimes not. It seems because I need to run some function in the right order or the result is wrong. I made a index.js using promises but it still doesn't work and I must admit I'm not very good in node....

**Comment by tomaszrondio** [comment]
I am back "in business" :) 
How can I help you? I am pretty lucky when debugging. Just tell me how the workflow looks like when developing plugin. I mean: once I change something how to restart etc.

**Comment by tomaszrondio** [comment]
btw I installed latest plugin and bricked volumio. Couldn't even connet via ssh. Restart helped with ssh but volumio is still down. That is the reason :
`Jun 16 22:17:04 volumio volumio[1866]: info: -------------------------------------------
Jun 16 22:17:04 volumio volumio[1866]: in fo: -----            Volumio2              ----
Jun 16 22:17:04 volumio volumio[1866]: info: -------------------------------------------
Jun 16 22:17:04 volumio volumio[1866]: info: -----          System startup          ----
Jun 16 22:17:04 volumio volumio[1866]: info: -------------------------------------------
Jun 16 22:17:05 volumio volumio[1866]: info: Plugin folders cleanup
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning into folder /volumio/app/plugins/
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning category audio_interface
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning category miscellanea
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning category music_service
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning category plugins.json
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning category system_controller
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning category user_interface
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning into folder /data/plugins/
Jun 16 22:17:05 volumio volumio[1866]: info: Scanning category miscellanea
Jun 16 22:17:05 volumio volumio[1866]: info: Plugin folders cleanup completed
Jun 16 22:17:05 volumio volumio[1866]: info: Loading plugins from folder /volumio/app/plugins/
Jun 16 22:17:05 volumio volumio[1866]: info: Loading plugins from folder /data/plugins/
Jun 16 22:17:05 volumio volumio[1866]: info: Loading plugin "system"...
Jun 16 22:17:05 volumio volumio[1866]: info: Loading plugin "appearance"...
Jun 16 22:17:05 volumio volumio[1866]: info: Loading plugin "network"...
Jun 16 22:17:05 volumio volumio[1866]: info: Loading plugin "services"...
Jun 16 22:17:05 volumio volumio[1866]: info: Loading plugin "alsa_controller"...
Jun 16 22:17:06 volumio volumio[1866]: info: Loading plugin "volumio_command_line_client"...
Jun 16 22:17:06 volumio volumio[1866]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 16 22:17:06 volumio volumio[1866]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 16 22:17:06 volumio volumio[1866]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Jun 16 22:17:06 volumio volumio[1866]: info: Loading plugin "upnp"...
Jun 16 22:17:06 volumio volumio[1866]: info: [1497651426216] Starting Upmpd Daemon
Jun 16 22:17:06 volumio volumio[1866]: info: CoreCommandRouter::executeOnPlugin: system , registerCallback
Jun 16 22:17:06 volumio volumio[1866]: info: Loading plugin "mpd"...
Jun 16 22:17:06 volumio volumio[1866]: info: Plugin upnp_browser is not enabled
Jun 16 22:17:06 volumio volumio[1866]: info: Loading plugin "networkfs"...
Jun 16 22:17:06 volumio volumio[1866]: info: Loading plugin "alarm-clock"...
Jun 16 22:17:06 volumio volumio[1866]: info: Loading plugin "airplay_emulation"...
Jun 16 22:17:06 volumio volumio[1866]: info: [1497651426620] Starting Shairport Sync
Jun 16 22:17:06 volumio volumio[1866]: info: Loading plugin "last_100"...
Jun 16 22:17:06 volumio volumio[1866]: info: Loading plugin "webradio"...
Jun 16 22:17:08 volumio volumio[1866]: info: Loading plugin "i2s_dacs"...
Jun 16 22:17:08 volumio volumio[1866]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Jun 16 22:17:08 volumio volumio[1866]: info: Loading plugin "my_volumio"...
Jun 16 22:17:08 volumio volumio[1866]: info: Loading plugin "volumiodiscovery"...
Jun 16 22:17:08 volumio volumio[1866]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Jun 16 22:17:08 volumio node[1866]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Jun 16 22:17:08 volumio node[1866]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jun 16 22:17:08 volumio node[1866]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Jun 16 22:17:08 volumio node[1866]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jun 16 22:17:08 volumio node[1866]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jun 16 22:17:08 volumio node[1866]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Jun 16 22:17:08 volumio volumio[1866]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jun 16 22:17:08 volumio volumio[1866]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Jun 16 22:17:08 volumio volumio[1866]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jun 16 22:17:08 volumio volumio[1866]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jun 16 22:17:08 volumio volumio[1866]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Jun 16 22:17:08 volumio volumio[1866]: info: Applying required configuration parameters for plugin volumiodiscovery
Jun 16 22:17:08 volumio volumio[1866]: fs.js:640
Jun 16 22:17:08 volumio volumio[1866]: return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Jun 16 22:17:08 volumio volumio[1866]: ^
Jun 16 22:17:08 volumio volumio[1866]: Error: EROFS: read-only file system, open '/data/configuration/system_controller/volumiodiscovery/config.json'
Jun 16 22:17:08 volumio volumio[1866]: at Error (native)
Jun 16 22:17:08 volumio volumio[1866]: at Object.fs.openSync (fs.js:640:18)
Jun 16 22:17:08 volumio volumio[1866]: at Object.fs.writeFileSync (fs.js:1333:33)
Jun 16 22:17:08 volumio volumio[1866]: at Object.writeFileSync (/volumio/node_modules/jsonfile/index.js:115:13)
Jun 16 22:17:08 volumio volumio[1866]: at Config.save (/volumio/node_modules/v-conf/index.js:199:16)
Jun 16 22:17:08 volumio volumio[1866]: at PluginManager.checkRequiredConfigurationParameters (/volumio/app/pluginmanager.js:432:13)
Jun 16 22:17:08 volumio volumio[1866]: at PluginManager.initializeConfiguration (/volumio/app/pluginmanager.js:86:11)
Jun 16 22:17:08 volumio volumio[1866]: at PluginManager.loadPlugin (/volumio/app/pluginmanager.js:118:8)
Jun 16 22:17:08 volumio volumio[1866]: at PluginManager.loadPlugins (/volumio/app/pluginmanager.js:192:10)
Jun 16 22:17:08 volumio volumio[1866]: at new CoreCommandRouter (/volumio/app/index.js:58:24)
Jun 16 22:17:08 volumio systemd[1]: volumio.service: main process exited, code=exited, status=1/FAILURE
Jun 16 22:17:08 volumio systemd[1]: Unit volumio.service entered failed state.
Jun 16 22:17:08 volumio systemd[1]: Starting dynamicswap.service...
Jun 16 22:17:08 volumio systemd[1]: Started dynamicswap.service.
Jun 16 22:17:08 volumio systemd[1]: volumio.service holdoff time over, scheduling restart.
Jun 16 22:17:08 volumio systemd[1]: Starting dynamicswap.service...
Jun 16 22:17:08 volumio systemd[1]: Started dynamicswap.service.
Jun 16 22:17:08 volumio systemd[1]: Stopping Volumio Backend Module...
Jun 16 22:17:08 volumio systemd[1]: Starting Volumio Backend Module...
Jun 16 22:17:08 volumio systemd[1]: Started Volumio Backend Module.`

**Comment by tomaszrondio** [comment]
btw 2: I see what is your problem with promises in index.js. I think I can help. Write me proper order of functions you want to fire.

**Comment by balbuze** [comment]
Thanks ! I'm preparing you something. But the problem you have doesn't seems to come from my plugin... Just notice that if you install last version of volumio, ssh is disable by default. You have to enable it https://volumio.github.io/docs/User_Manual/SSH.html (I prefer second method but choose...)

**Comment by balbuze** [comment]
[index.js.zip](https://github.com/balbuze/volumio-plugins/files/1082427/index.js.zip)
The overall plugin help may be useful to understand how it works : https://volumio.github.io/docs/User_Manual/SSH.html
For the plugin, in the section  ControllerBrutefir.prototype.autoconfig = function() { several functions are called and Must be execute in that order, and the first must be finished before executing the second and so on. But the problem (I think) it that function such as setLoopbackoutput call other function from volumio that need time to be executed such as setting loopback device and restart player. And it seems the promise is returned before as I don't always get the same result each time I use it. I added a lot of comments in index.js. When enabling the plugin, you should see  Updating Volume Controller Parameters: Device: 1 Name: IQaudIO DAC Mixer: Analogue Max Vol: 100 Vol Curve; logarithmic Vol Steps: 10
of course with your dac. /etc/mpd.conf should be set with Loopback...
The need to be cleaned...

**Comment by tomaszrondio** [comment]
I have a 4 month dog that is a little absorbing monster. I will try to check if it works tomorrow when get back home but it may be undoable :)
Anyway so far I see one problem:
'''
// saveVolumioconfig() returns a promise - ok
 self.saveVolumioconfig()
.then(function(resolve){
// in this function you return a promise already resolved by saveVolumioconfig function. So saveHardwareAudioParameters() is running "in background" 
  self.saveHardwareAudioParameters()
return resolve;
})
'''
saveHardwareAudioParameters returns promise as well as other functions in chain so it should work like this:
'''
self.saveVolumioconfig()
.then( self.saveHardwareAudioParameters )
.then( self.setLoopbackoutput )
.then( self.restoreVolumioconfig )
.then( self.setVolumeParameters )
.catch(function(err){
     console.log(err);
 });
'''

btw this will throw an error. defer is commented out:
'''
.then(function(resolve){
	defer.resolve();
})
'''

**Comment by tomaszrondio** [comment]
regarding setLoopbackOutput.
Alsa_controller saveAlsaOptions seems to return promise as well with libQ. So in theory it should be enough to do:

```
 ControllerBrutefir.prototype.setLoopbackoutput = function() {
  var self = this;
  var str = {
   "output_device": {
    "value": "Loopback",
    "label": "Brutefir plugin"
   }
  }
  return self.commandRouter.executeOnPlugin('audio_interface', 'alsa_controller', 'saveAlsaOptions', str);
 };
```

**Comment by balbuze** [comment]
Thanks. I'll have a look tonight. Stupid question: is it possible to delayed the return of a promise with something like timeout?

**Comment by tomaszrondio** [comment]
You can delay resolve 
```
new Promise(function(resolve, reject) {
  setTimeout(function() {
    resolve();
  }, 3000); // Wait 3s then resolve.
});
```

Which one you want to delay? There must be some nasty way to make it possible :)

**Comment by balbuze** [comment]
I'm thinking of functions that copy or move file. I wonder if the promise is resolved just after the function is called, or when the action (moving a file) is finished. But not sure it is required... I just see it behaves in different ways depending devices, or when reboot is done compared to enabling/ disabling plugin. It is supposed to do the same thing.

**Comment by balbuze** [comment]
After a fight, I give up for tonight... I get new error on savehardwareaudioparameters and now nothing is saved or restored. I probably missed something. Maybe I should restart from the last version I uploaded on gihtub, where I made something different for promises... But not functionnal.

what is your dog's name ?

**Comment by tomaszrondio** [comment]
well it would be stupid if promise is resolved before real action is finished. But it is just an untested theory.
Dog's name is "dude" although he may think his name is "don't!" :) 
He behaves better now so maybe I will be able to put back my audio gear and test with you. I had to remove it bcs I was afraid that it will be eaten.

**Comment by balbuze** [comment]
so the problem does ot come from savehardwareaudioparameters as if I comment it in autoconfig section, I get a similar error with the following function Jun 20 15:51:11 volumio-rpi2 volumio[13968]: TypeError: Cannot read property 'then' of undefined

**Comment by balbuze** [comment]
I have added a gitter room for a more convenient way of talking... https://gitter.im/balbuze/volumio-plugins

**Comment by balbuze** [comment]
No more error by adding () for each function. . then ( saveVolimioconfig()) But it still not work as expected....

**Comment by balbuze** [comment]
Loopback is not always set, nor restorevolumioconfig

**Comment by balbuze** [comment]
we can close now ?
