### ISSUE TITLE
Question - enabled backends

### ISSUE THREAD

**Issue by Saiyato** [balbuze/volumio-plugins#52]
Hey,

What backends are enabled in your builds? I've been reading into snapcast and librespot should have a pipe backend. But it needs to be enabled during compile, are you enabling this backend? :)

https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#spotify

**Comment by balbuze** [comment]
hi,
I saw you are working on a new plugin...
librespot is compiled with alsa and pipe as backend. You can see it with the command "/data/plugins/music_service/volspotconnect2/librespot --backend ? -n test"

**Comment by Saiyato** [comment]
Awesome, thanks, will continue development ;)

Will also close the issue, since the question is answered
