### ISSUE TITLE
Can't connect on Raspberry Model B Rev 2

### ISSUE THREAD

**Issue by gustafekeberg** [balbuze/volumio-plugins#54]
Hi.

With the last version (temporary librespot for arm") Spotify on Volumio worked until yesterday. I've tried to install older versions of the plugin with no luck.

I'm getting this error when trying to connect on a Raspberry Model B Rev 2:

```
Jun 04 19:54:57 volumio volumio[1217]: INFO:librespot::session: Connecting to AP "gew1-accesspoint-a-91hf.ap.spotify.com:4070"
Jun 04 19:54:58 volumio volumio[1217]: thread 'main' panicked at 'Authentication failed', /home/travis/build/herrernst/librespot/target/arm-unknown-linux-gnueabihf/release/build/librespot-cbf31f11fa905ab0/out/lib.rs:365
Jun 04 19:54:58 volumio volumio[1217]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jun 04 19:54:58 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Jun 04 19:54:58 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
Jun 04 19:55:00 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Jun 04 19:55:00 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Jun 04 19:55:00 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Jun 04 19:55:00 volumio systemd[1]: Started Volspotconnect2 Daemon.
Jun 04 19:55:00 volumio volumio[1225]: INFO:librespot: librespot 1d7f448 (2017-03-26). Built on 2017-05-16.
Jun 04 19:55:00 volumio volumio[1225]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
```

**Comment by dzschille** [comment]
Perhaps it is related to this librespot issue: https://github.com/plietar/librespot/issues/190

**Comment by gustafekeberg** [comment]
Yes, that's likely.

**Comment by gereccius** [comment]
Same here... stop working around 2 days ago :(

**Comment by balbuze** [comment]
Yep this is a Spotify problem. It seems they block librespot ( used in the plugin). It need a new version of this library to work again, but this is surely not a permanent fix...

**Comment by gereccius** [comment]
TKS Balbuze ,
Working great again!!!!

**Comment by dzschille** [comment]
@gereccius it's not working here. How are your settings? Do you use "Shared Device"?

**Comment by gereccius** [comment]
Yes, shared service on 0.3.4 fixed versión ;)

**Comment by gereccius** [comment]
Sorry, shared device!

**Comment by mundodisco8** [comment]
Working on my side, using shared service too, haven't tried the other mode.

On 9 Jun 2017 17:43, "gereccius" <notifications@github.com> wrote:

Sorry, shared device!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/balbuze/volumio-plugins/issues/54#issuecomment-307439654>,
or mute the thread

**Comment by dzschille** [comment]
Oh, haven't seen the new version. 0.3.4 works! Great, thanks!!

**Comment by balbuze** [comment]
Good! :-)
