### ISSUE TITLE
Connexion stops during a song

### ISSUE THREAD

**Issue by Guillaumeraym** [balbuze/volumio-plugins#55]
Hi Balbuze, Thanks for your plugin, i love it! 
Sadly when I play a song, spotify stops and the plugin too. I have to connect again to volumio and press play again. I can't play a whole song without cutting. Can you help me?

hardware:
raspberry pi3B
JustBoom DAC HAT

software:
volumio 2.185
volumio spotify connect 2 v0.3.4

**Comment by Guillaumeraym** [comment]
What is the linux command to see the error. I would like to show it to you but I don't know how to...

**Comment by balbuze** [comment]
hi,
you can try  a sudo journalctl -f to see what happens. Was it working before ?

**Comment by Guillaumeraym** [comment]
There is the log ive got. I can't read read it, I dont know how to read linux language. I have the impression that spotify lose connexion with volumio, Sometimes during a song, often at the end of the song and I have to connect volumio again on spotify to continue with next song. Thanks for your help and your time.
   
-- Logs begin at Thu 2017-06-08 23:00:36 UTC. --
Jun 09 23:34:10 volumio systemd[8357]: Starting Basic System.
Jun 09 23:34:10 volumio systemd[8357]: Reached target Basic System.
Jun 09 23:34:10 volumio systemd[8357]: Starting Default.
Jun 09 23:34:10 volumio systemd[8357]: Reached target Default.
Jun 09 23:34:10 volumio systemd[8357]: Startup finished in 52ms.
Jun 09 23:34:10 volumio systemd[1]: Started User Manager for UID 1000.
Jun 09 23:34:10 volumio sshd[8351]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
Jun 09 23:34:10 volumio sshd[8351]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
Jun 09 23:35:39 volumio sudo[8376]: volumio : TTY=pts/0 ; PWD=/home/volumio ; USER=root ; COMMAND=/bin/journalctl -f
Jun 09 23:35:39 volumio sudo[8376]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)
Jun 09 23:36:06 volumio volumio[8333]: thread 'main' panicked at 'Box<Any>', src/session.rs:129
Jun 09 23:36:06 volumio volumio[8333]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jun 09 23:36:06 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Jun 09 23:36:06 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
Jun 09 23:36:08 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Jun 09 23:36:08 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Jun 09 23:36:08 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Jun 09 23:36:08 volumio systemd[1]: Started Volspotconnect2 Daemon.
Jun 09 23:36:08 volumio volumio[8384]: INFO:librespot: librespot 29d5f79 (2017-06-04). Built on 2017-06-05.
Jun 09 23:36:08 volumio volumio[8384]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
Jun 09 23:36:09 volumio volumio[8384]: INFO:librespot::session: Connecting to AP "ash2-accesspoint-a100.ap.spotify.com:4070"
Jun 09 23:36:10 volumio volumio[8384]: INFO:librespot::session: Authenticated as "g*****" !
Jun 09 23:36:10 volumio volumio[8384]: INFO:librespot::audio_backend::alsa: Using alsa sink
Jun 09 23:36:10 volumio volumio[8384]: INFO:librespot::session: Country: "CA"

**Comment by Guillaumeraym** [comment]
Anybody have a idea of what my problem could be?
