### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by leafy7382** [balbuze/volumio-plugins#60]
Are we able to make default volume a configurable parameter?

**Comment by balbuze** [comment]
What plugin are you talking about? If volspotconnect 2 it is not possible as the value is hard coded before the compilation. The default for librespot is 100% but I set it to about 30% for volspotconnect2.

**Comment by leafy7382** [comment]
Yes, it's volspotconnet 2. I find that By lowering volume in Spotify, it loses more dynamic than when I push to 100% and lower the volume by turning down the volume pot on my preamp.

**Comment by balbuze** [comment]
I understand. In that case try volspotconnect that output directly, and if you use no mixer it will be 100%
