### ISSUE TITLE
brutefir2 fails to install

### ISSUE THREAD

**Issue by DirkLaurenz** [balbuze/volumio-plugins#61]
Downloading plugin at http://127.0.0.1:3000/plugin-serve/d8ce2857-9760-44d9-a46f-449c757768f2.zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/d8ce2857-9760-44d9-a46f-449c757768f2.zip
Creating folder on disk
Unpacking plugin
Checking for duplicate plugin
Copying Plugin into location
Installing dependencies
The following error occurred when installing the plugin: Error

**Comment by balbuze** [comment]
And there is a problem with plugin install (not only brutefir) if you have changed your password

**Comment by DirkLaurenz** [comment]
I will Check this 

Von meinem iPhone gesendet

**Comment by DirkLaurenz** [comment]
And i Downloaded the file... May u send it Directly to me via Email just to make sure it is the correct file

Von meinem iPhone gesendet

**Comment by balbuze** [comment]
use that : https://github.com/balbuze/volumio-plugins/raw/master/plugins/miscellanea/brutefir2/brutefir.zip

**Comment by DirkLaurenz** [comment]
Reseting to factory setiings helped – it worked

 

Von: balbuze [mailto:notifications@github.com] 
Gesendet: Montag, 26. Juni 2017 21:24
An: balbuze/volumio-plugins <volumio-plugins@noreply.github.com>
Cc: DirkLaurenz <dirk@laurenz.ws>; Author <author@noreply.github.com>
Betreff: Re: [balbuze/volumio-plugins] brutefir2 fails to install (#61)

 

use that : https://github.com/balbuze/volumio-plugins/raw/master/plugins/miscellanea/brutefir2/brutefir.zip
