### ISSUE TITLE
When switching tracks, volspotconnect2 plugin pauses digital out

### ISSUE THREAD

**Issue by leafy7382** [balbuze/volumio-plugins#62]
I have successfully used Hifiberry Digi+ Pro using the experimental Volumio2. Also I have successfully installed volspotconnect2. The problem I have now is that if I am using the Digi+ Pro, whether it's optical or coaxial, it pauses the digital out inbetween tracks. This causes my DAC (Schiit Yggdrasil) relay to click. Are we able to maintain the digital out as long as the plugin is connected by a Spotify instance?

**Comment by balbuze** [comment]
maybe by using volspotconnect... But currently I don't see how to do that with volspotconnect2
