### ISSUE TITLE
Volspotconnect2: Can't connect

### ISSUE THREAD

**Issue by BLX-S** [balbuze/volumio-plugins#63]
<img width="286" alt="screen shot 2017-06-28 at 17 17 02" src="https://user-images.githubusercontent.com/7920208/27645115-a3b0e9e8-5c25-11e7-80fd-347a3a308c10.png">

I added the volspotconnect2 zip from this repo and it appears across all my devices, I just can't connect to it... I get the error as seen in the screenshot above. What can I do to fix it? Is it a Spotify thing with the WebAPI switch? 

EDIT: I'm trying to play music on the blackpi device...

**Comment by BLX-S** [comment]
It sort of works now. I had to disable the shared device function and then it worked but only for devices linked to my spotify account. Is there a way to make it work on everyone's account (that is to say everyone in my lan?)

**Comment by balbuze** [comment]
Humm weird. It's the first this is reported with volspotconnect2... Need to check..

**Comment by balbuze** [comment]
Tested...
It works for me

**Comment by BLX-S** [comment]
It works now, miraculously... I don't know what sorcery you worked but it works perfectly
