### ISSUE TITLE
asound.conf overwrites existing one

### ISSUE THREAD

**Issue by Saiyato** [balbuze/volumio-plugins#67]
Selecting a profile overwrites any existing asound.conf already on the system. Can you add/replace your configs instead?

**Comment by balbuze** [comment]
Hi. I don't know what plugin your are talking about. But this a general problem for brutefir 2, volsimpleequal that prevent it to be used with soft vol and with any other plugin that use asound.conf. It need to be rework...

**Comment by Saiyato** [comment]
Oh sorry yes, in my head it all made sense. I was talking about the equalizer plugin. I just reworked my snapcast plugin to modify asound, as opposed to overwrite it. I use it to redirect output to pipe for volspotconnect1.

I wanted to try the equalizer, but my asound.conf was gone afterwards ;)

**Comment by Saiyato** [comment]
Just checked the SnapCast documentation, I believe audio playback is over alsa:

> Every received chunk is first decoded and added to the client's chunk-buffer. Knowing the server's time, the chunk is played out using alsa at the appropriate time. Time deviations are corrected by

source; https://libraries.io/github/badaix/snapcast

And since I use asound.conf to route the audio for volspotconnect1 (because it supports shuffle and repeat), it is desirable to keep the asound.conf. :)

**Comment by balbuze** [comment]
I just had a quick look at your code ( I'm at work;-)). I think one  of the problem is that you configure a sound at install time. What happens if a user wants to add a plugin after yours ? And if the user change something in volumio settings? (But I didn't tested it yet). In equalizer and brutefir, the plugin configure "on the fly" Volumio to use the new output, keeping hardware mixer if any. But I need to make some changes to not overwrite astound.conf.

**Comment by balbuze** [comment]
But what I have done is far from being perfect... needs some improvement

**Comment by Saiyato** [comment]
Yes I do create it install-time, I will add functionality to rewrite the asound section. If you want I can create a pull to add it to yours too.

I'm at work too, so I can't develop it now, but will look at it tonight. :)

**Comment by balbuze** [comment]
we have to consider when softvol is used... I really wonder how to do that properly. I plan to write some other plugins that needs a specific asound.conf (such as a stereo to mono plugin). Even if doing that when installing works, it is problematic when adding a new plugin, or changing settings

**Comment by balbuze** [comment]
Other thing. If you want to test volsimpleequal , just add your settings in asound.tmpl found in the plugin folder...
