### ISSUE TITLE
Device shows up, but can't connect

### ISSUE THREAD

**Issue by Techassi** [balbuze/volumio-plugins#68]
The plugin worked for some time but randomly stopped working.
Im using:

- Volumio v2.185
- Your plugin v0.3.7

I hope you can help me.

**Comment by balbuze** [comment]
Yes.. I met some problem tonight to connect to Spotify... Hope it is just a small network / spotify problem...

**Comment by marcvangend** [comment]
I'm seeing the same thing. Just did a clean install of Volumio 2.201 on a Rpi 2.

    volumio@volumio:~$ uname -a
    Linux volumio 4.4.9-v7+ #884 SMP Fri May 6 17:28:59 BST 2016 armv7l GNU/Linux

Please let me know if I can assist with logs or additional data.

**Comment by cortegedusage** [comment]
Seems to be a problem with Spotify againand.
See https://github.com/plietar/librespot/issues/216

**Comment by Techassi** [comment]
Ok @balbuze ! I hope it will get fixed soon. 
I will investigate the problem a little bit further.

**Comment by balbuze** [comment]
Hi!
should be ok for armv6 and armv7.
compiling x86 now !
let me know...
next step is to disable cache to avoid using a service to remove it and mix armv6 and armv7 librespot (easier to maintain)

**Comment by balbuze** [comment]
done !

**Comment by marcvangend** [comment]
Nice! I didn't quite understand what you said about disabling cache, but that's okay. I'll try to test asap.

**Comment by balbuze** [comment]
Up to now librespot write some files on a cache. The problem is that this cache grow and can fill all the memory. To avoid this, the plugin check and limit the size of the cache using a special service and a timer to check periodically the cache. Now librespot supports a option to not use the cache. This what I have done... But for user it is not important...

**Comment by marcvangend** [comment]
Thanks for the explanation. I've only listened to half a song yet, but it works so far! Thanks.

**Comment by Techassi** [comment]
So i can close this thread the next day I think, if it stays like that.

**Comment by balbuze** [comment]
Yes and we'll reopen it if needed....

**Comment by marcvangend** [comment]
Yes. It's been playing for 1h20 now, without any connection problems :-D

**Comment by paansamari** [comment]
I also suffered this connect issue. Suddenly it stopped working a few days ago. The latest update (0.4.0) seems to resolve the problem. Thanks for now @balbuze.

**Comment by nbonamy** [comment]
Just downloaded latest build but I seem to get an error with the purge cache thing :

```
2017-07-17T16:10:50.417Z - info: Enabling plugin volspotconnect2
2017-07-17T16:10:50.454Z - info: Loading plugin "volspotconnect2"...
2017-07-17T16:10:50.879Z - info: The following error occurred while starting VOLSPOTCONNECT: Error: Command failed: /usr/bin/sudo /bin/systemctl start volspotconnect2.service volspotconnect2purgecache.timer
Failed to start volspotconnect2purgecache.timer: Unit volspotconnect2purgecache.timer failed to load: No such file or directory.
```

Any idea?

Thanks

**Comment by balbuze** [comment]
Oh I think a reboot should solve it.It seems some parts of the previous version remains in memory. Let me know

**Comment by balbuze** [comment]
Because this command doesn't exist anymore on the New version
