### ISSUE TITLE
volspotconnect2 not installing in RPi0 2.201

### ISSUE THREAD

**Issue by tiagoefreitas** [balbuze/volumio-plugins#69]
Can't install any of the spotify plugins.

Downloading plugin at http://127.0.0.1:3000/plugin-serve/5b740ee2-ee21-46db-95f8-4588e6edbdb0.zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/5b740ee2-ee21-46db-95f8-4588e6edbdb0.zip
Creating folder on disk
Unpacking plugin
Checking for duplicate plugin
Copying Plugin into location
Installing dependencies
The following error occurred when installing the plugin: Error

**Comment by balbuze** [comment]
You need a valid internet connection.
You shouldn't have changed your password
You may have to change DNS in volumio depending on your ISP.

**Comment by tiagoefreitas** [comment]
Changing the default user password is a security must have. Doesn't make sense to require a default password for it to function correctly.

**Comment by balbuze** [comment]
This something that should change in a next version of volumio. But waiting the patch this like this...
