### ISSUE TITLE
Spotify app key

### ISSUE THREAD

**Issue by awiouy** [balbuze/volumio-plugins#7]
Hi balbuze,

I am the maintainer of the spotify-connect-web addon for LibreELEC, and I am wondering what app key your are using (the same for all users?). Is this a key that I could use in my addon, or should I get one (and how could I get one)?

Thank you in advance for your help

**Comment by balbuze** [comment]
Hi awiouy,
I use a app key provided for volumio by the founder Michelangelo. This is now included in the plugin and user don't need to get one.  I don't think you can use it... But you can get one on the spotify website. This is what I have done before using the volumio one. You just have to ask here : https://developer.spotify.com/technologies/libspotify/application-keys/
I should have a look at your work, my plugin is rather basic. Just a easy installation and user account setting in the webUI . Works for RPI1 2 3 ZERO sparky etc... (I detect the cpu and install required files) . Main problem no sound with software volume.... Next step getting album art and working button in webUI.

**Comment by awiouy** [comment]
Thank you for your answers.

My addon is [here](https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/addons/service/spotify-connect-web). It is merely a wrapper to the packaged release, with bindings to the Kodi UI. I will try to implement the chroot or docker option before Spotify drops support of libspotify.

As for the keys, I believed that they were bound to an account. It is however difficult to verify now, since the key generation and retrieval service is offline, and there is no sign it will be brought online again.

By the way, users often refer me to your work. Keep up the good job!
