### ISSUE TITLE
FYI: please update librespot

### ISSUE THREAD

**Issue by bramoosterhuis** [balbuze/volumio-plugins#70]
I was facing a strange authentication issue, after rebuilding and updating librespot to the version below everything was fine again. You also might want to update the binaries. 

https://github.com/plietar/librespot/commit/910974e5e2cc1d98b9c3c08b57e33132987cef5d

**Comment by balbuze** [comment]
Thanks, but it is already included in the build I made in the last version... 5 days ago about https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect2

**Comment by balbuze** [comment]
let me know if you are still facing problem
