### ISSUE TITLE
"Name" error on Volumio 2.201

### ISSUE THREAD

**Issue by notshy** [balbuze/volumio-plugins#71]
Hi all,

I'm getting the following error when installing on Volumio 2.201

Any idea what I can do to fix it?

Thanks,
NotShy

```

Downloading plugin at http://127.0.0.1:3000/plugin-serve/f2227195-b1cd-446a-b1b3-841eb204f666.zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/f2227195-b1cd-446a-b1b3-841eb204f666.zip
Creating folder on disk
Unpacking plugin
The following error occurred when installing the plugin: TypeError: Cannot read property 'name' of undefined

```

**Comment by balbuze** [comment]
Please give the plugin you want to install...
What is your device? (RPI ? Model? Other)
Are you really in 2.201 or have you updated with a dev version ?

**Comment by notshy** [comment]
Apologies - Raspberry Pi 2 Model B

I'm not on the Dev version of Volumio - just the normal version.

**Comment by notshy** [comment]
This is now fixed through a fresh install of Volumio and a fresh install of Volspot.

Can close and/or delete the thread.
