### ISSUE TITLE
Switching songs does not work / always stops after the first song

### ISSUE THREAD

**Issue by jenswet** [balbuze/volumio-plugins#72]
Hello,

I have some problem with the latest (0.4.0) Connect2 version.
It worked fine some weeks, than suddenly I couldn't switch songs anymore.
After one song ended, the next one didn't start anymore. Skipping a song manually doesn't work either. Changing the current play position in a song causes the audio to stop too.

To fix this I tried to update the old version I had before to the new version. This caused an error (probably because I changed the password of volumio). Then I removed the plugin manually (like you described in some old issue of connect1) and reinstalled the new version. This caused again an error, so I used the default password and could install it without any problems.

But the problems I had before are still persistent.
Do you have any idea why? Can I provide you any log, that you can fix that or help me what to change?
The plugin is great, I really like to use it.

Thanks in advance,
Jens

**Comment by jenswet** [comment]
Somehow it works again now. Didn't change anything. Don't ask me why.

**Comment by balbuze** [comment]
Just to explain : when you install the plugin, it downloads librespot from the repo. It means that even if you use a previous version, the librespot on the repo will be use.
And to finish, I'm compiling a new version. But not sure it will solve your problem
