### ISSUE TITLE
librespot x86 missing alsa-backend flag

### ISSUE THREAD

**Issue by anders3408** [balbuze/volumio-plugins#73]
Hi

Before i can use this in my system, i need the alsa flag.
Your version seems to not have that enabled, so i recompiled with that flag, and it works.

My cpu is i686 and it would be nice to be able to use your plugin without needed to recreate librespot :)

Nice work.

**Comment by balbuze** [comment]
Hi,
I don't understand... The version I compiled is used in volumio with alsa... 
What error do you get?

_Sent from my Motorola XT1039 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by balbuze** [comment]
I see now! I'm recompiling an up to date version !
thanks for pointing it

**Comment by anders3408** [comment]
Yes i forgot to say it was X86 at my first post.
When manually running the command to start librespot with ./librespot ,.,,,,, as the stated in the startup script (with alsa as backend) it says invalid backend :)

**Comment by balbuze** [comment]
I uploaded a new version that should be ok now...

**Comment by anders3408** [comment]
Good job. Thanks.
