### ISSUE TITLE
Spotify Track timer does not work with plugin

### ISSUE THREAD

**Issue by moonprancer** [balbuze/volumio-plugins#74]
Hi,

Running Volumio 2.246 and have noticed on this version and also older versions that the connect plugin will force the track timer to show like it is at the end of the very song. The song/playlist or album will play as normal but every new song that plays the timer will just show stuck at the end of the very song.

My screenshot shows exactly what I mean.

![timer wrong volumio](https://user-images.githubusercontent.com/29468683/29200312-682738a0-7ea8-11e7-80fe-d7b2add260ad.PNG)

**Comment by balbuze** [comment]
Hi,
I never noticed that. I just checked and it behaves correctly from android and Ubuntu... What is your system?

**Comment by moonprancer** [comment]
> Hi,
I never noticed that. I just checked and it behaves correctly from android and Ubuntu... What is your system?> 

Windows 10 Version 1703. I have also had this on other Windows machines including ones before the latest creators update.

**Comment by kayue** [comment]
I have a similar problem with Mac's Spotify. 
The Spotify client' time track shows it is 7 - 12 seconds ahead.

**Comment by balbuze** [comment]
ok it is a librespot limitiation
