### ISSUE TITLE
Not working on Volumio X86

### ISSUE THREAD

**Issue by codewarriorFX** [balbuze/volumio-plugins#75]
Hello,

I installed the volspotconnect2 on a Udoo x86 with volumio. It shows that is enabled on Volumio UI but its not working, It doesn't show as an available device on Spotify. Is there any additional step that needs to be done on X86 devices?

Thanks

**Comment by balbuze** [comment]
hi,
I must admit I never tested it on that device.
Just to check : 
- you have a premium account or family
- you try to connect devices on the same network
If yes, through ssh you can check with "systemctl status volspotconnect2" and past the result

**Comment by codewarriorFX** [comment]
Hi!

- I have family account
- Is on the same network, I will get you the results as soon as I get home.

By the way, I see that 5 days ago new librespot has been added and alsa backend for x86 has been corrected on the branch. Could it be that the problem? I can update and give the results If still doesn't work.

**Comment by balbuze** [comment]
Oh yes, I correct a mistake I have done when compiling for x86 with alsa  backend.... So use the last version and let me know !

**Comment by codewarriorFX** [comment]
Hey, it seems the volspotconnect2.zip is not updated with the new changes.

**Comment by codewarriorFX** [comment]
Nevermind my last comment, its working now with the new alsa backend :)

**Comment by balbuze** [comment]
good !
