### ISSUE TITLE
Album playback repeats after last song 

### ISSUE THREAD

**Issue by sorin-pop** [balbuze/volumio-plugins#77]
When playing a saved album from Spotify through Volumio via the Spotify Connect 2 plugin, after the last song the album starts playing again from the beginning, instead of playback being stopped.

Environment:
Latest volspotconnect2.zip installed on Volumio 2.224, on Raspberry Pi 3 model B.
Spotify Premium account, Spotify Android App, or Spotify desktop application on Windows 10.

Steps to reproduce:
1. In the Spotify application, search for an artist you like, look at his/her albums.
2. Choose an album and save it to your your library. (for testing purposes you can choose some short album, like an EP or single, so you don't have to wait so long for the whole album to be played untill you see the problem at the end)
3. Go to your library /Albums, and start the playback of that album.
4. Check the playback queue: it looks normal, the album's songs are listed, and are not duplicated or anything like that.
However, note that after the last song is over, **the album automatically starts playing again**, from the first song. If you leave it, it will do this indefinitely, in an infinite loop.
**Expected behaviour:** The playback should stop after the album has been played.

The expected behaviour can not be experienced when you are playing the album through another device than volumio with spotify connect plugin, e.g. through your laptop or smartphone. That's why I suspect that this is actually an issue with this plugin. (Or Volumio itself perhaps?)

I look forward to your tests and thoughts on this matter.

Thank you.

**Comment by rmvanhees** [comment]
I have the same problem on the same hardware.
Greetings, Richard

**Comment by balbuze** [comment]
The "problem" comes from librespot itself. I just compiled it with a small modification to set the default volume. Hope a improvement for a next version....

**Comment by rmvanhees** [comment]
Great, I had already looked for a way to set the default volume to 100%

Thanks, Richard

**Comment by balbuze** [comment]
Hummm, my mod is to not having 100% but about 30%...
Some work (fork) seems to disable software mixer in librespot. But not implemented (yet ?) In the plugin. I'll have a deeper look.

**Comment by sorin-pop** [comment]
Thanks a lot Balbuze. By the way, for now I worked around the problem by installing the old version of your plugin, volspotconnect.zip. It works fine with that one. But I guess it would be better to eventually be able to use the latest version of the plugin. Looking forward to your updates. All the best!

**Comment by balbuze** [comment]
Ok good!. Just to precise, volspotconnect is not exactly an old version. Both plugins provide a Spotify connect device, but are based on two different library. Volspotconnect use a Spotify lib, and it's because it provides more features. Volspotconnect 2 is based on librespot, a free and open source library from reverse engineering.... It is still in heavy development, but some features are missing...

**Comment by orderoftheflame** [comment]
This is interesting to know.

Do you recommend using Volspotconnect over vsc2 because of this?

**Comment by sorin-pop** [comment]
Yes, that's really interesting to know then! Well, even though I know the question is not addressed to me, based on what Balbuze said, and the fact that I don't get the issue reported on this ticket with Volspotconnect, I would say it is rather recommended over Volspotconnect2.

**Comment by balbuze** [comment]
Hi!
for info : https://github.com/plietar/librespot/issues/237
expect an update soon ;-)
