### ISSUE TITLE
Shuffle does not work on Spotify connect

### ISSUE THREAD

**Issue by GraysonAdams** [balbuze/volumio-plugins#78]
Spotify Connect works, but if I try to enable Shuffle on my phone or desktop via Spotify Connect, it will disable shuffle when I go to the next track and won't play a random track, but instead the next consecutive song on the playlist.

**Comment by kayue** [comment]
Duplicated with https://github.com/balbuze/volumio-plugins/issues/59

Use volspotconnect instead.
