### ISSUE TITLE
Gives error when installing to new volumio

### ISSUE THREAD

**Issue by dacool** [balbuze/volumio-plugins#8]
When trying to install plugin to brand new Volumio install on raspberry pi 2 b, it gives only the following error. I try'd new and 2 older volspotconnect.zip, all gives same error.

- Hide details
Downloading plugin at http://127.0.0.1:3000/plugin-serve/volspotconnect.zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/volspotconnect.zip
Creating folder on disk
Unpacking plugin
Checking for duplicate plugin
Copying Plugin into location
Installing dependencies
The following error occurred when installing the plugin: Error

**Comment by balbuze** [comment]
I saw there is something wrong when downloading the file. A way that works is to see the code of volspoconnect.zip and then click on download. Anyway I'm going to upload a new file in about 8 hours.

**Comment by balbuze** [comment]
To download from github, DON'T right click on on brutfeir.zip and save ! CLICK LEFT, and in the following page select download.
;)
If you right click and save, it will save html code of the page....inside the file, and of course it failed to install

**Comment by szelek** [comment]
I've had the same problem when I've changed volumio user password.
Changing it back to volumio solved issue.
