### ISSUE TITLE
wifireconnect: impossible to remove the plugin

### ISSUE THREAD

**Issue by biva** [balbuze/volumio-plugins#81]
Hello,
I'm unable to uninstall wifireconnect, in order to be able to install the new version. Logs are:
```
Sep 11 15:03:44 volumio volumio[1270]: info: Starting Uninstall of plugin system_controller - wifireconnect
Sep 11 15:03:44 volumio volumio[1270]: info: Uninstalling plugin wifireconnect
Sep 11 15:03:44 volumio volumio[1270]: info: PLUGIN STOP: wifireconnect
Sep 11 15:03:44 volumio volumio[1270]: info: Killing wifireconnect
Sep 11 15:03:44 volumio volumio[1270]: info: Disabling plugin wifireconnect
Sep 11 15:03:44 volumio volumio[1270]: info: Checking if uninstall.sh is present
Sep 11 15:03:44 volumio volumio[1270]: info: Check return the error Error: ENOENT: no such file or directory, stat '/data/plugins/system_controller/wifireconnect/uninstall.sh'
Sep 11 15:03:44 volumio sudo[6141]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl stop wifireconnect.timer
Sep 11 15:03:44 volumio sudo[6141]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 11 15:03:44 volumio systemd[1]: Stopped Runs wifireconnect every 5min.
Sep 11 15:03:44 volumio sudo[6141]: pam_unix(sudo:session): session closed for user root
```
Any idea how to remove it?

**Comment by balbuze** [comment]
If it is removed in volumio, just install last version, it should remove the service. If not try "sudo rm /etc/systemd/system/wifireconnect*"

**Comment by biva** [comment]
Thank you for your quick reply, but if I try to install the last version, I get this message: " Error: Plugin wifireconnect already exists"
I tried your command, but still the same issue :(

**Comment by balbuze** [comment]
Ah ok. Try this "rm /data/plugins/system_controller/wifireconnect" and "killall node" to restart volumio.

**Comment by biva** [comment]
Great, it worked, thanks. Am I the only one with this issue? What was wrong? Removing 0.0.9 is working.
For the record, the full command is ```sudo rm -r /data/plugins/system_controller/wifireconnect```

**Comment by balbuze** [comment]
Yes of course...
