### ISSUE TITLE
Fresh install - No such device

### ISSUE THREAD

**Issue by vkolotov** [balbuze/volumio-plugins#82]
Hello, I've installed a fresh copy volumio and the spotify connect plugin. Activated the plugin in volumio, I can see the Volumio Spotify connect option in the native spotify client. When I click it, nothing happens. I see the following in the volumio logs:

Sep 12 02:14:19 volumio volumio[1963]: INFO:librespot: librespot ddfc28f (2017-08-04). Built on 2017-08-10. Build ID: Z3qO6N4b
Sep 12 02:14:19 volumio volumio[1963]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }

**Comment by vkolotov** [comment]
Looks like this is something to do with the librespot library: https://github.com/plietar/librespot/issues/217

**Comment by balbuze** [comment]
This problem should not avoid it working. What happens when you try to connect ? (Use sudo journalctl -f)

**Comment by vkolotov** [comment]
> What happens when you try to connect ? (Use sudo journalctl -f)

That's the only what I can see there:

>Sep 12 02:14:19 volumio volumio[1963]: INFO:librespot: librespot ddfc28f (2017-08-04). Built on 2017-08-10. Build ID: Z3qO6N4b
Sep 12 02:14:19 volumio volumio[1963]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }

Please let me know what I can do else to get more info?

Thanks

**Comment by balbuze** [comment]
humm If you use sudo journalctl -f and after use the official spotify app to connect the device you should see other things related to volumio and librespot

**Comment by vkolotov** [comment]
Here we go. This is a full output when I push "connect" button in a native spotify client:

>Sep 12 19:41:26 volumio volumio[2480]: INFO:librespot_core::session: Connecting to AP "gae2-accesspoint-b-mzf1.ap.spotify.com:4070"
Sep 12 19:41:27 volumio volumio[2480]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 111, message: "Connection refused" } }', /checkout/src/libcore/result.rs:859
Sep 12 19:41:27 volumio volumio[2480]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Sep 12 19:41:27 volumio systemd[1]: volspotconnect2.service: main process exited, code=exited, status=101/n/a
Sep 12 19:41:27 volumio systemd[1]: Unit volspotconnect2.service entered failed state.
Sep 12 19:41:29 volumio systemd[1]: volspotconnect2.service holdoff time over, scheduling restart.
Sep 12 19:41:29 volumio systemd[1]: Stopping Volspotconnect2 Daemon...
Sep 12 19:41:29 volumio systemd[1]: Starting Volspotconnect2 Daemon...
Sep 12 19:41:29 volumio systemd[1]: Started Volspotconnect2 Daemon.
Sep 12 19:41:29 volumio volumio[2654]: INFO:librespot: librespot ddfc28f (2017-08-04). Built on 2017-08-10. Build ID: Z3qO6N4b
Sep 12 19:41:29 volumio volumio[2654]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }

**Comment by vkolotov** [comment]
Right... I see now. Connection is refused from my RPi, but I can access it through my laptop!

>volumio@volumio:~$ telnet gae2-accesspoint-b-mzf1.ap.spotify.com 4070
Trying 104.199.241.161...
telnet: Unable to connect to remote host: Connection refused

**Comment by balbuze** [comment]
Have you a premium or family account?

**Comment by vkolotov** [comment]
I've got family account, does it matter? Cheers

**Comment by balbuze** [comment]
No it should work... Do you use the shared device or you entered your credentials? Does your username or password use special characters? (?!;*@#£)?
