### ISSUE TITLE
volspotconnect: adding metadata

### ISSUE THREAD

**Issue by markubiak** [balbuze/volumio-plugins#84]
Thought you would find this useful.  Spotify-connect-web has a, well, web-based architecture to get metadata and perform playback commands.  You can see this clearly in the [main.py](https://github.com/Fornoth/spotify-connect-web/blob/7b1c426bf4830eaeb33ccb056eb77475d5a83418/main.py) for the program.

For example:
localhost:4000/api/info/metadata - returns metadata in json format, including artist, track, album art link, and more
localhost:4000/api/info/image_url/<id> - returns the album art provided the album art spotify id from the metadata path
localhost:4000/api/playback/play - starts playback

There are a ton of routes.  I don't know if you are still actively working on v1 but librespot has been significantly buggier for me than spotify-connect-web.  This could be used to send album art and metadata back to Volumio and have the program merge quite well with the existing interface.

**Comment by balbuze** [comment]
hi,
I often though to add it in volumio, but as the libspotify was supposed to be shut down by spotify I never spent time on it... But this is still in project to do something, maybe using librespot...

**Comment by markubiak** [comment]
I agree, I just wish librespot would stop stuttering on my pi.... It's a pi3 so I don't believe it to be an issue with the horsepower of the thing.  We'd also have to get the author to expose the metadata in a file or some sort; although the metadata is clearly displayed on the command line AFAIK there's no way to get it into any actual kind of file.  You could use spawn() and have callbacks for stdout that check for the Artist and Song but you'd still be missing the rest of the metadata.

**Comment by balbuze** [comment]
How I see the future... Writing a plugin using spotify API to remote librespot. I made some test in command line and I can play/stop. But there is a gap between that and the plugin...

**Comment by kayue** [comment]
`librespot` is currently missing some core features like shuffle. Will using Spotify API to remote librespot fix these issues?

**Comment by markubiak** [comment]
I'm closing this issue because I agree that development focus should shift to librespot.

On that note, the original author has been very slow to add features. I'm sure there is a good reason for this, but I believe it's time to start using your own fork of librespot for volspotconnect2. The "pause after the last song" branch should have been merged, and shuffle/repeat are, in my eyes, high enough priority that they should have been fixed long ago.  It would also open a path to add metadata and thus state messages by implementing a pipe much like shairplay does; I see no reason to do it differently.

**Comment by balbuze** [comment]
I will compile a "merge" of different fork in next days... Maybe before the end of the week.
