### ISSUE TITLE
volspotconnect2 not working

### ISSUE THREAD

**Issue by rez0n** [balbuze/volumio-plugins#85]
Hello!
volspotconnect2 not working in Volumio 2.246 on Raspberry Pi.
volspotconnect are working perfect, but I want to use volspotconnect2 for auto stop playing local music when i use Spotify.

In /var/log/volumio.log nothing about volspotconnect2. How to debug this?
(FYI - I using Hifiberry DAC+. If this are important)

**Comment by balbuze** [comment]
What do you see? Does a Spotify device appears? If yes no sound? Please give more details.

**Comment by rez0n** [comment]
Oh, sorry, forgot that :)
Yes, on my phone in Spotify app I see device, selecting my volumio but no sound, sometimes playing are stuck (not pause, just stuck), when i selecting "Play on this phone" track resume playing.

**Comment by mathinus** [comment]
Unfortunately I can second that. After installing the latest volspotconnect2 ver0.4.2 it stopped working. Shows up in Spotify as a connect device, linking is possible, also playing songs, but no sound.
Sound output does work with volume playing radio streams.

Volumio ver 2.279, using external USB Soundcard

**Comment by balbuze** [comment]
please could you post aplay -l, and "cat /data/plugins/music_service/volspotconnect2/startconnect.sh 
"

**Comment by rez0n** [comment]
`**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0`
and
`#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'Volumio' --backend alsa --device plughw:1 --disable-audio-cache --onstart ./onstart1.sh`

**Comment by zayamatias** [comment]
Hi, 

Just had a similar issue with the plugin. When I ran it from the command line:

./librespot -b 320  -c /tmp  --name 'Volumio' --backend alsa --device plughw:1 --disable-audio-cache --onstart ./onstart1.sh

I got a "permission error"

I removed the "onstart parameter" (you know just in case):

./librespot -b 320  -c /tmp  --name 'Volumio' --backend alsa --device plughw:1 --disable-audio-cache

and then it worked.... so probably permission issue as with the script execution...

So I simply "chmod 755 onstart1.sh" under /data/plugins/music_service/volspotconnect2 and guess what?

It works!

Hope this helps you.

**Comment by mathinus** [comment]
```
volumio@volumio:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 5: STU [Xonar Essence STU], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

and


`volumio@volumio:~$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --disable-discovery -u XXXXXXXXXX -p XXXXXXXXXX --name 'Volumio' --backend alsa --device plughw:5 --disable-audio-cache --onstart ./onstart1.sh`

Thank you so much for your hard work!

**Comment by balbuze** [comment]
Oh shame on me! I had this problem when I added onstart1.sh script on my system and I forgot to update it in the plugin....I will correct it asap!  Thank anyway for your work!

**Comment by zayamatias** [comment]
Thank you for the plugin! it rocks!
