### ISSUE TITLE
Brutefir doesn't work volspotconnect 1

### ISSUE THREAD

**Issue by kayue** [balbuze/volumio-plugins#88]
When Brutefir is activated, volspotconnect 1 cannot be detected.

volspotconnect 2 still works tho.

**Comment by balbuze** [comment]
yes probably... I wrote brutefir plugin after volspotconnect and I never made the required change to use it with brutefir... Maybe if thousand of user ask for it...

**Comment by balbuze** [comment]
I'm working on that point and it should be solved soon

**Comment by kayue** [comment]
@balbuze Will try it out tonight! Thanks!
