### ISSUE TITLE
error during downloading of armv6l package

### ISSUE THREAD

**Issue by ccccc382** [balbuze/volumio-plugins#9]
i tried installing volspotconnect on a fresh install of volumio 2.
however when it gives the following log which ends with a error.
the download bar is stuck at 70%

Downloading` plugin at http://127.0.0.1:3000/plugin-serve/volspotconnect[1].zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/volspotconnect[1].zip
Creating folder on disk
Unpacking plugin
Checking for duplicate plugin
Copying Plugin into location
Installing dependencies
Installing spotify-connect-web dependencies
Err http://archive.raspbian.org jessie InRelease

Err http://archive.raspbian.org jessie Release.gpg
Temporary failure resolving 'archive.raspbian.org'
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Detecting cpu
Cpu is Armv6l, downloading required package. Be very patient, it could take up to 15min...
The following error occurred when installing the plugin: Error 
Failed to download. Stopping installation `now

is it possible to maybe manually install the packages?

**Comment by ccccc382** [comment]
after restarting the pi the downloading works

**Comment by balbuze** [comment]
Maybe the server was down... Is everything ok now?
