### ISSUE TITLE
volsimpleequal doesnt work with hifiberry DAC plus

### ISSUE THREAD

**Issue by mrpurplenz** [balbuze/volumio-plugins#90]
I've got the Hifiberry DAC plus and it doesnt work. Specifically:
When the plugin is enabled the DAC model in settings is defaulted back to the first in the list and changing it to the correct model only causes it to immediately jump back to the first model in the drop down.

When enabled there is no sound

When installed but "off" in its settings there is sound but volume cannot be changed from the web ui

Weirdly it worked  (I think) for about a second when I first enabled it. I heard the sound change just for it when silent. Then it stopped.

PS: If you get it working with this DAC it would be nice to be able to manually send command to ALSA EQUAL in bash (like I do normally) without killing the plugin. I can't test this though until Hifiberry DAC is working.

**Comment by balbuze** [comment]
Before enabling the plugin, make sure you have a correct and working config., With the correct volume control if any, but not software. Once it is ok, enable the plugin, wait 10 sec, and try to play something. Don't change the setting in volumio playback settings . ( Something like " hifiberryvdac trough brutefir" should be displayed as output. But don't charge it nor the volume control. If no sound, reboot and retry. Let me know

**Comment by mrpurplenz** [comment]
OK that worked. Which is weird because I cant think how I did it differently before. FYI the output device is listed as "HiFiBerry DAC Plus through equalizer plugin" and I2S DAC "off"
This specific issue can be [solved] (I'll deal with the PS elsewhere)

**Comment by balbuze** [comment]
ok good! Yes once the plugin is activated, I2s dac appears to be off, but this is not the case. This is due to the way volumio handle output. But don't worry about that.
