### ISSUE TITLE
volsimpleequal access to alsa-equal from BASH

### ISSUE THREAD

**Issue by mrpurplenz** [balbuze/volumio-plugins#91]
With alsa-equal manually installed I can make changes to the settings from a simple bash (run as the mpd user) with the following for example
amixer -D equal set 01. 31 Hz 20%
Which resulted in near real time tone control for my project.
Unfortunately not with volsimpleequal plugin installed though.
Any idea how I might reinstate that or some other control from BASH/python? (perhaps over the custom set)
Maybe link in to the volumio controls that can be used to control it from bash like one can already for volume. For example to change the volume to 25 one can execute the following in bash:
volumio volume 25
I see that the slider controls are recorded in  /data/configuration/miscellanea/volsimpleequal/config.json but editing the file doesn't apply the changes, which are rewritten on the next "apply". My js foo is too weak to figure out how to hack into the process. Plus to do so would bring shame on my house.

**Comment by balbuze** [comment]
When the plugin is enabled, you should be able to acces amixer -D equal via a console. But there will be no feedback in the webUI. The plugin is designed only to be controlled by the webUI.

**Comment by mrpurplenz** [comment]
Thanks that's fine. It wasn’t working for be because I was still trying to run via the mpd user but I see that after installation of the plugin, the normal user is the correct one. So the CLI command as above works fine. This is closed too I guess. Thanks so much for this. Just what I needed.
