### ISSUE TITLE
no sound with softvol/doesn't start with no mixer

### ISSUE THREAD

**Issue by cortegedusage** [balbuze/volumio-plugins#93]
it seems volspotconnect1 doesn't start when no mixer is selected
and does start when software mixer is selected but no sound.

I have a rpi 3 with audiophonics raspdac v3 using generic i2s driver
running latest volumio release 2.285

like the info in the volumio screen, now my lcd-display actually displays something when playing 
spotify..

**Comment by balbuze** [comment]
Humm, weird. I just made a test with softvol and none and it works for me. But this is with a pine 64 with a "old" volumio 2.166. I have to test on a rpi with last update.

**Comment by cortegedusage** [comment]
I believe something changed between some releases in the way softvolume was
handled. Have to check with a fresh image maybe.

Thnx


Op 9 okt. 2017 8:33 p.m. schreef "balbuze" <notifications@github.com>:
