### ISSUE TITLE
Authorization alternative, multiple users

### ISSUE THREAD

**Issue by whatsnewsisyphus** [balbuze/volumio-plugins#94]
Hello,
The squeezebox plugin allows you to authorize using your phone/spotify app, oauth without entering passwords, also allowing multiple users. Do you think this would be possible?

**Comment by balbuze** [comment]
This is the case with volspotconnect2

**Comment by whatsnewsisyphus** [comment]
Hello @balbuze the librespot one or the older one? I think I installed the librespot one. By multiple users you don't mean the everyone on the network option right? I was thinking about authorizing multiple spotify connect endpoints.
