### ISSUE TITLE
dependency 'Spotify' plugin necessary

### ISSUE THREAD

**Issue by OliverGruenberg** [balbuze/volumio-plugins#95]
... works great, but requires the standard plugin 'Spotify' to be installed and running.
Once this requirement is met, spotify connect (especially Spotify Family and multiple users) runs great!
Thank you, btw!

**Comment by balbuze** [comment]
There is No dependencies with other plugin... Maybe something went wrong when installing and downloading avahi. But really nothing with others plugins.

**Comment by OliverGruenberg** [comment]
you're correct, the problem was not reproduceable.
