### ISSUE TITLE
switching between remote users crashes functionality

### ISSUE THREAD

**Issue by OliverGruenberg** [balbuze/volumio-plugins#96]
Spotify Connect user A plays a song on Volumio,
then
Spotify Connect user B clicks 'play' on another device in order to play a different song on Volumio (without stopping user A's song)
then
Volumio loses its Spotify Connect functionality, denial on service.
Volumio then doesn't occur as a device anymore in Spotify's list of possible Connect devices.

A hard restart on Volumio doesn't help.

Only re-installing the plugin and a restart solves the problem.

**Comment by paulohoppe** [comment]
I have seen the same behavior on my Raspberry.
The difference is that a hard reset solves the problem.

**Comment by balbuze** [comment]
which plugin do you use ? volspotconnect or volspotconnect2 ?

**Comment by OliverGruenberg** [comment]
hmmm... hard to tell :) the downloaded archive's name is 'volspotconnect 14.48.33.zip'

**Comment by balbuze** [comment]
Don't know where your archive name comes from.... On the repo it's just volspotconnect.zip or volspotconnect2 zip.... Nevermind, in volumio Ui go in plugin and you'll see the list of installed plugins. You can try to disable and enable it instead of rebooting the system.

**Comment by OliverGruenberg** [comment]
Thanks,
disabling/enabling is a workaround.

But since I have to do this two times an hour, wouldn't it be nice to spend this behaviour to the plugin itself? Something like recognizing once it is going wrong and then dis-/enabling it automatically?

Keep up with the great work! :)

**Comment by balbuze** [comment]
I don't know what is wrong in your setting. I never had this issue. Can you please check if sudo journalctl -f shows something when it hangs?

**Comment by OliverGruenberg** [comment]
here we go:

-- Logs begin at Wed 2017-10-18 21:03:18 UTC. --
Oct 18 21:14:07 stereo volumio[1180]: kSpPlaybackNotifyPause
Oct 18 21:14:07 stereo volumio[1113]: info: Pushing Favourites {"service":"volspotconnect","uri":"spotify:track:7KdbM0arRfhnblMXj94f0l","favourite":false}
Oct 18 21:14:07 stereo volumio[1113]: info: Pushing Favourites {"service":"volspotconnect","uri":"spotify:track:7KdbM0arRfhnblMXj94f0l","favourite":false}
Oct 18 21:14:07 stereo volumio[1180]: Traceback (most recent call last):
Oct 18 21:14:07 stereo volumio[1180]: File "/data/plugins/music_service/volspotconnect/spotify-connect-web/console_callbacks.py", line 183, in inner
Oct 18 21:14:07 stereo volumio[1180]: return f(self, *args[:-1])
Oct 18 21:14:07 stereo volumio[1180]: File "/data/plugins/music_service/volspotconnect/spotify-connect-web/console_callbacks.py", line 200, in connection_notify
Oct 18 21:14:07 stereo volumio[1180]: print "kSpConnectionNotifyLoggedOut"
Oct 18 21:14:36 stereo sudo[5539]: volumio : TTY=pts/0 ; PWD=/home/volumio ; USER=root ; COMMAND=/bin/journalctl -f
Oct 18 21:14:37 stereo sudo[5539]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)

**Comment by OliverGruenberg** [comment]
and after dis-/en-abling the plugin:

Oct 18 21:18:31 stereo systemd[1]: Starting Cleanup of Temporary Directories...
Oct 18 21:18:31 stereo systemd[1]: Started Cleanup of Temporary Directories.
Oct 18 21:18:47 stereo volumio[1113]: info: CoreCommandRouter::volumioGetState
Oct 18 21:18:47 stereo volumio[1113]: info: [1508361527251] CoreStateMachine::getState
Oct 18 21:18:47 stereo volumio[1113]: info:
Oct 18 21:18:47 stereo volumio[1113]: [1508361527252] ---------------------------- Client requests Volumio state
Oct 18 21:18:47 stereo volumio[1113]: info: [1508361527253] InterfaceWebUI::pushState
Oct 18 21:18:47 stereo volumio[1113]: info: [1508361527284] ------------------------------ 34ms
Oct 18 21:18:47 stereo volumio[1113]: info:
Oct 18 21:18:47 stereo volumio[1113]: [1508361527297] ---------------------------- Client requests Menu Items
Oct 18 21:18:47 stereo volumio[1113]: info: CoreCommandRouter::executeOnPlugin: appearance , getUiSettings
Oct 18 21:18:47 stereo volumio[1113]: info: CoreCommandRouter::executeOnPlugin: wizard , getShowWizard
Oct 18 21:18:47 stereo volumio[1113]: info: CoreCommandRouter::executeOnPlugin: system , getShowWizard
Oct 18 21:18:47 stereo volumio[1113]: info: CoreCommandRouter::executeOnPlugin: multiroom , getMultiroom
Oct 18 21:18:47 stereo volumio[1113]: Plugin multiroom or method getMultiroom not found
Oct 18 21:18:47 stereo volumio[1113]: info: [1508361527335] Listing playlists
Oct 18 21:18:47 stereo volumio[1113]: info: [1508361527412] ------------------------------ 115ms
Oct 18 21:18:55 stereo volumio[1113]: info: [{"prettyName":"Spotify","name":"spop","category":"music_service","version":"1.3.3","icon":"fa-spotify","enabled":false,"active":false},{"prettyName":"Volumio Spotify Connect ver1.6.4","name":"volspotconnect","category":"music_service","version":"1.6.4","icon":"fa-spotify","enabled":true,"active":true}]
Oct 18 21:18:57 stereo volumio[1113]: info: PLUGIN STOP: volspotconnect
Oct 18 21:18:57 stereo volumio[1113]: info: Killing Spotify-connect-web daemon
Oct 18 21:18:57 stereo volumio[1113]: info: Disabling plugin volspotconnect
...

**Comment by balbuze** [comment]
ok I met the problem... But still unsolved. A workaround would be to restart automatically the plugin. I'll have a look

**Comment by balbuze** [comment]
seems to be solved now...
