### ISSUE TITLE
Integration with volumio interface

### ISSUE THREAD

**Issue by rosaldanha** [balbuze/volumio-plugins#97]
I can´t see what is playing on volumio interface, and can´t stop or play on that interface either. Via spotify connect works. 
The other functions worked out of the box ! Thank you for this great work.

**Comment by balbuze** [comment]
you'll see album art, artist, tarck name only if you use volspotconnect, not volspotconnect2. But buttons (play, previous, next) are still not usable.

**Comment by cortegedusage** [comment]
@balbuze are you going to develop further the volspotconnect2 plugin with integration with the interface.
I've got a feeling that Librespot sounds a bit better than spotify-connect-web (but this might be psychological)
thanks in advance.

**Comment by balbuze** [comment]
The main Dev of librespot stop the development. But it doesn't mean librespot is dead! A main fork will probably appears, with new features... To answer, I still following librespot and the fork. Asap it will possible to integrate in the webUi, it will be done..  but don't know when

**Comment by cortegedusage** [comment]
@balbuze did you see:
https://github.com/frafall/librespot
for metadata.

and also did you see:
https://github.com/fossedihelm/librespot
so one could choose the volume at which librespot starts.
(would be awesome to set this from volumio interface)

would love to see this in volspotconnect2.

**Comment by balbuze** [comment]
Yep,
even if nothing seems to move for volspotconnect2, I'm following miscellaneous fork. For the volume setting, it shouldn't be to difficult to add it in the plugin setting... For metadata, it requires more work!
But of course the main idea is to do that. Of course, help welcome !

**Comment by balbuze** [comment]
I'll try to compile a version (armv6) tomorow, if it works as expected, I'll add a volume setting. :-)

**Comment by cortegedusage** [comment]
yeah, I can imagine the metadata part would be more work.

wish I could be more usefull than to only point at things.

your plugin is very usefull for me, everyday even without metadata.
Thank you for that!

**Comment by cortegedusage** [comment]
wow that'd be great!

thanks in advance

**Comment by balbuze** [comment]
Pointing things is good!  I can't follow all what is done eveywhere ;-) and I could miss some info.. So thanks! Don't hesitate if you find interesting things or feedback.

**Comment by balbuze** [comment]
Do you know volspotconnnect supports metatada, with album art ?

**Comment by cortegedusage** [comment]
yes I did notice, and tried it, I thought SQ was a bit less, 
this might be just a psychological thing rather than a technical thing
but nevertheless I preffered librespot.
Also I liked the initial thought with librespot about not being dependent of spotify on which architecture one uses to listen on.

cheers!

**Comment by balbuze** [comment]
Hi!
have a look and a try here : https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect-futurdev/volspotconnect2.zip
Initial volume setting in webUI!
Metadata not in use but integrated in librespot
shuffle and repeat should work
let me know
Just for arm (x86 later if it works)

**Comment by cortegedusage** [comment]
Looks good. But when I change the volume and save it. It doesn't save it.
Maybe something to do with writing rights... Will investigate later this
evening.
But hell, this is really good! Thank you.

Op 10 dec. 2017 4:58 p.m. schreef "balbuze" <notifications@github.com>:

**Comment by cortegedusage** [comment]
hmm can't seem to find why it won't save the correct values

did notice something else you use wget in onstart1.sh
is this by any particular reason as it creates an
index.html?cmd=stop in the plugin folder everytime it is run.

why not use curl?

anyway. need to get some sleep now.

thank you for now hardcoding 100 percent in the tmpl file did do the trick
for me now..



2017-12-10 21:46 GMT+01:00 Dennis van Paassen <dvpaassen@gmail.com>:
