### ISSUE TITLE
volspotconnect doesn't work with volumio 2.285

### ISSUE THREAD

**Issue by ayhlai** [balbuze/volumio-plugins#98]
Volumio Spotify Connect ver1.6.4 used to work with volumio 2.246.

After upgrade to 2.285, it's not working. The symptoms as follow:

In Spotify PC version, I can see volumio in "listening on".
- PC shows that it's playing in volumio
- However, there is no sound from Volumio

Status show that it's playing

{
  "active": true, 
  "logged_in": true, 
  "playing": true, 
  "repeat": false, 
  "shuffle": true
}

Metadata also showing correctly

{
  "album_name": "Is That For Me", 
  "album_uri": "spotify:album:1LtTYrAjvMjXTAo8U70eWL", 
  "artist_name": "Alesso", 
  "artist_uri": "spotify:artist:4AVFqumd2ogHFlRbKIjp1t", 
  "context_uri": "spotify:user:spotify:playlist:37i9dQZF1DXbVmhQBDSKS7", 
  "cover_uri": "spotify:image:21d3c06fe84e08f0f14f16243d2c1e76a08c86b1", 
  "data0": "\u65b0\u6b4c\u71b1\u64ad", 
  "duration": 169269, 
  "track_name": "Is That For Me", 
  "track_uri": "spotify:track:2KwojFDebQV4J2b0JMRR5Q", 
  "volume": 52428
}

But there is just no sound

**Comment by balbuze** [comment]
Yes I know that... Last version of volumio keep active the output device and thus prevent other sources to access it. We are working on it.

**Comment by nanomesher** [comment]
Look forward to the fix. thanks a lot!

**Comment by volumio** [comment]
I tried it a bit, in fact I think this is a problem of when the plugin actually starts: 
if you restart the plugin it just works, but for some reasons it can't start when volumio starts.

**Comment by balbuze** [comment]
@volumio what is the device you use for your test ?

**Comment by keab** [comment]
I have the same problem with my RPi1 + HifiBerry DAC. I found a temporary workaround: When using the "Audio jack" instead of HifiBerry as output, Volspotconnect works fine. That might give some clues towards the root cause.

**Comment by ayhlai** [comment]
Latest version of volspotconnect is working with volumio 2.310 (latest as of now).  Great news and thanks for nice job!

**Comment by MateEke** [comment]
It still doesn't works for me - Volumio 2.310, volspotconnect 1.6.9/1.6.7. volspotconnect2 works fine.

**Comment by balbuze** [comment]
Try to reboot right after the installation as /etc/asound.conf needs to be reloaded

**Comment by MateEke** [comment]
I have tried multiple times, still no sound.

**Comment by balbuze** [comment]
what is your device and dac ?
can you past the content of /etc/asound.conf and cat /data/plugins/music_service/volspotconnect/spotify-connect-web/startconnect.sh PLEASE REMOVE YOUR CREDENTIALS BEFORE POSTING !!!
Do you use a other plugin or softvolume ?

**Comment by MateEke** [comment]
I have an RPI3 and now I'm using the audio jack (still waiting for my Allo Boss).

`cat /etc/asound.conf`:
```
pcm.spotout
{
type dmix
slave {
pcm hw:0
rate 44100
        }
ipc_key 1024
}
defaults.pcm.rate_converter "speexrate_high"
```
`cat /data/plugins/music_service/volspotconnect/spotify-connect-web/startconnect.sh`:
```
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect/spotify-connect-web
./spotify-connect-web  --username '***' --password '***' --bitrate 320 --name 'Volumio' --playback_device spotout --mixer 'PCM'  --mixer_device_index 0 --dbrange 45  &
avahi-publish-service -s 'Volumio' _spotify-connect._tcp 4000 VERSION=1.0 CPath=/login/_zeroconf
```

Only the official Spotify plugin is installed.

**Comment by balbuze** [comment]
you have to disable officiial plugin
and to be honnest I never tested with jack output....
I have between other a Allo Boss and it's a very nice DAC! I really like how it sounds. I'm not talking about spotify...

**Comment by MateEke** [comment]
I have removed the official plugin, but still no sound.

My Allo Boss is on it's way for a month now, there was a problem with the postal service...

**Comment by ayhlai** [comment]
Using volumio latest v2.310, I have both Spotify and volspotconnect working very nicely using all latest version.

I have [NanoSound DAC](https://volumio.org/product/nanosound-dac/)  and have display showing the song title as well.

Let me know if you need help with debugging.

**Comment by keab** [comment]
I upgraded my RPi0 to Volumio 2.310 and volspotconnect 1.6.9. Got sound with Audio jack output but not with HIfiBerry DAC. But thereafter I can't get sound with _any_ output, even after removing and reinstalling volspotconnect.
Another problem is that volspotconnect seems to loose its connection to the spotify server - it disappears from the list of "available units". Thsi didn't happen before.
My files look the same as those from MateEke above, and I don't have any other spotify plugin installed.

**Comment by MateEke** [comment]
I just received my Allo Boss, now everything works fine.

**Comment by balbuze** [comment]
Good! Are you happy with it?

**Comment by MateEke** [comment]
Yes, it has very powerful bass, and the sound doesn't get tiring after several hours.

Another question: is there any way to update the plugin, or it's always needs full reinstall?

**Comment by balbuze** [comment]
I agree bass are powerful!
There is no way to update a plugin... You have to reinstall it.
